### ISSUE TITLE
LR finder returns None

### ISSUE THREAD

**Issue by Borda** [Lightning-AI/lightning#10557]
## 🐛 Bug: LR finder returns None

Could be come model or LR finder range which yield in returning LR as None which crashes the consecutive 

### To Reproduce

https://www.kaggle.com/jirkaborovec/titanic-crash-with-lightning-flash
```py
from pytorch_lightning.loggers import CSVLogger
from pytorch_lightning.callbacks import StochasticWeightAveraging
from pytorch_lightning import seed_everything

seed_everything(7)
swa = StochasticWeightAveraging(swa_epoch_start=0.6)
logger = CSVLogger(save_dir='logs/')
trainer = flash.Trainer(
    max_epochs=150,
    gpus=torch.cuda.device_count(),
    logger=logger,
    accumulate_grad_batches=12,
    gradient_clip_val=0.01,
    auto_lr_find=True,
)

# ==============================

trainer.tune(model, datamodule=datamodule, lr_find_kwargs=dict(min_lr=1e-4, max_lr=0.1, num_training=65),)
print(f"Learning Rate: {model.learning_rate}")

# ==============================

trainer.fit(model, datamodule=datamodule)
```

### Expected behavior

I see several options:
- raise an error on the LR finder `tune` so it does not interfere with consecutive `fit`
- raise just warning and continue with the model's initial LR value
- find why the LR is failing

### Additional context

include in Tune redesign #9103

cc @akihironitta @borda @rohitgr7

**Comment by rohitgr7** [comment]
not stale

**Comment by tchaton** [comment]
not stale.

**Comment by asicoderOfficial** [comment]
It still persists, but happens arbitrarily. 
In my case, the error looked like this:
`Finding best initial lr:  12%|████████████▌                                                                                            | 12/100 [00:00<00:02, 42.37it/s]
LR finder stopped early after 12 steps due to diverging loss.
Restoring states from the checkpoint path at /home/asicoder/gitrepos/TradingBot/src/.lr_find_b2260f3a-5905-49d8-bf1d-cb594137bded.ckpt
Failed to compute suggesting for `lr`. There might not be enough points.
Traceback (most recent call last):
  File "/home/asicoder/miniconda3/envs/timeseries_env/lib/python3.9/site-packages/pytorch_lightning/tuner/lr_finder.py", line 177, in suggestion
    min_grad = np.gradient(loss).argmin()
  File "<__array_function__ internals>", line 180, in gradient
  File "/home/asicoder/miniconda3/envs/timeseries_env/lib/python3.9/site-packages/numpy/lib/function_base.py", line 1195, in gradient
    raise ValueError(
ValueError: Shape of array too small to calculate a numerical gradient, at least (edge_order + 1) elements are required.
suggested learning rate: None
Failed to compute suggesting for `lr`. There might not be enough points.
Traceback (most recent call last):
  File "/home/asicoder/miniconda3/envs/timeseries_env/lib/python3.9/site-packages/pytorch_lightning/tuner/lr_finder.py", line 177, in suggestion
    min_grad = np.gradient(loss).argmin()
  File "<__array_function__ internals>", line 180, in gradient
  File "/home/asicoder/miniconda3/envs/timeseries_env/lib/python3.9/site-packages/numpy/lib/function_base.py", line 1195, in gradient
    raise ValueError(
ValueError: Shape of array too small to calculate a numerical gradient, at least (edge_order + 1) elements are required.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
Traceback (most recent call last):
  File "/home/asicoder/gitrepos/TradingBot/src/experiments2.py", line 204, in <module>
    mlpipeline()
  File "/home/asicoder/gitrepos/TradingBot/src/experiments2.py", line 171, in mlpipeline
    trainer.fit(
  File "/home/asicoder/miniconda3/envs/timeseries_env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 771, in fit
    self._call_and_handle_interrupt(
  File "/home/asicoder/miniconda3/envs/timeseries_env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 724, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/asicoder/miniconda3/envs/timeseries_env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 812, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/asicoder/miniconda3/envs/timeseries_env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1218, in _run
    self.strategy.setup(self)
  File "/home/asicoder/miniconda3/envs/timeseries_env/lib/python3.9/site-packages/pytorch_lightning/strategies/single_device.py", line 72, in setup
    super().setup(trainer)
  File "/home/asicoder/miniconda3/envs/timeseries_env/lib/python3.9/site-packages/pytorch_lightning/strategies/strategy.py", line 139, in setup
    self.setup_optimizers(trainer)
  File "/home/asicoder/miniconda3/envs/timeseries_env/lib/python3.9/site-packages/pytorch_lightning/tuner/lr_finder.py", line 109, in func
    optimizers, _, _ = _init_optimizers_and_lr_schedulers(trainer.lightning_module)
  File "/home/asicoder/miniconda3/envs/timeseries_env/lib/python3.9/site-packages/pytorch_lightning/core/optimizer.py", line 180, in _init_optimizers_and_lr_schedulers
    optim_conf = model.trainer._call_lightning_module_hook("configure_optimizers", pl_module=model)
  File "/home/asicoder/miniconda3/envs/timeseries_env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1596, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/home/asicoder/miniconda3/envs/timeseries_env/lib/python3.9/site-packages/pytorch_forecasting/models/base_model.py", line 929, in configure_optimizers
    optimizer = Ranger(self.parameters(), lr=lr, weight_decay=self.hparams.weight_decay, **optimizer_params)
  File "/home/asicoder/miniconda3/envs/timeseries_env/lib/python3.9/site-packages/pytorch_forecasting/optim.py", line 68, in __init__
    if not lr > 0:
TypeError: '>' not supported between instances of 'NoneType' and 'int'`

**Comment by asicoderOfficial** [comment]
It still persists :(
