### ISSUE TITLE
How to pass str to a batch?

### ISSUE THREAD

**Issue by nonstopfor** [Lightning-AI/lightning#12586]
## 🐛 Bug

I try to pass str values to a batch (list of str). But there is a problem when transferring the batch to the targeted gpu device. 

### Expected behavior

```
Traceback (most recent call last):
  File "bert_main.py", line 574, in <module>
    train(args)
  File "bert_main.py", line 360, in train
    trainer.fit(model, train_dataloader, dev_dataloader)
  File "/home/zhangzhexin/anaconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 741, in fit
    self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
  File "/home/zhangzhexin/anaconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 685, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/zhangzhexin/anaconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 777, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/zhangzhexin/anaconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1199, in _run
    self._dispatch()
  File "/home/zhangzhexin/anaconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1279, in _dispatch
    self.training_type_plugin.start_training(self)
  File "/home/zhangzhexin/anaconda3/lib/python3.7/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 202, in start_training
    self._results = trainer.run_stage()
  File "/home/zhangzhexin/anaconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1289, in run_stage
    return self._run_train()
  File "/home/zhangzhexin/anaconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1311, in _run_train
    self._run_sanity_check(self.lightning_module)
  File "/home/zhangzhexin/anaconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1375, in _run_sanity_check
    self._evaluation_loop.run()
  File "/home/zhangzhexin/anaconda3/lib/python3.7/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/home/zhangzhexin/anaconda3/lib/python3.7/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 110, in advance
    dl_outputs = self.epoch_loop.run(dataloader, dataloader_idx, dl_max_batches, self.num_dataloaders)
  File "/home/zhangzhexin/anaconda3/lib/python3.7/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/home/zhangzhexin/anaconda3/lib/python3.7/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 111, in advance
    batch = self.trainer.accelerator.batch_to_device(batch, dataloader_idx=dataloader_idx)
  File "/home/zhangzhexin/anaconda3/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 209, in batch_to_device
    return model._apply_batch_transfer_handler(batch, device=device, dataloader_idx=dataloader_idx)
  File "/home/zhangzhexin/anaconda3/lib/python3.7/site-packages/pytorch_lightning/core/lightning.py", line 291, in _apply_batch_transfer_handler
    batch = self.transfer_batch_to_device(batch, device, dataloader_idx)
  File "/home/zhangzhexin/anaconda3/lib/python3.7/site-packages/pytorch_lightning/core/hooks.py", line 707, in transfer_batch_to_device
    return move_data_to_device(batch, device)
  File "/home/zhangzhexin/anaconda3/lib/python3.7/site-packages/pytorch_lightning/utilities/apply_func.py", line 291, in move_data_to_device
    return apply_to_collection(batch, dtype=dtype, function=batch_to)
  File "/home/zhangzhexin/anaconda3/lib/python3.7/site-packages/pytorch_lightning/utilities/apply_func.py", line 96, in apply_to_collection
    return function(data, *args, **kwargs)
  File "/home/zhangzhexin/anaconda3/lib/python3.7/site-packages/pytorch_lightning/utilities/apply_func.py", line 284, in batch_to
    data_output = data.to(device, **kwargs)
  File "/home/zhangzhexin/anaconda3/lib/python3.7/site-packages/transformers/file_utils.py", line 2477, in wrapper
    return func(*args, **kwargs)
  File "/home/zhangzhexin/anaconda3/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 747, in to
    self.data = {k: v.to(device=device) for k, v in self.data.items()}
  File "/home/zhangzhexin/anaconda3/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 747, in <dictcomp>
    self.data = {k: v.to(device=device) for k, v in self.data.items()}
AttributeError: 'list' object has no attribute 'to'
```

### Environment

- PyTorch Lightning Version 1.5.10
- PyTorch Version 1.11.0
- Python version 3.7
- transformers version 4.17.0
- OS Linux

cc @justusschock @awaelchli @ninginthecloud @rohitgr7 @otaj

**Comment by twsl** [comment]
The batch is expected to consists of Tensors, which do have the `.to` method to transfer the data to the device of choice. You need to tokenize your strings first, check e.g. [here](https://pytorch-lightning.readthedocs.io/en/stable/notebooks/lightning_examples/text-transformers.html).

**Comment by rohitgr7** [comment]
in PyTorch, strings are are accumulated in form of a list.
if you want to avoid this error, you can override [transfer_batch_to_device](https://pytorch-lightning.readthedocs.io/en/latest/extensions/datamodules.html#transfer-batch-to-device) hook to disable moving the list of strings to the device.
