### ISSUE TITLE
CUDA error when running predictions in DeepSpeed

### ISSUE THREAD

**Issue by ShaneTian** [Lightning-AI/lightning#12815]
## 🐛 Bug

I run predictions after model training, but in DeepSpeed, which raises CUDA error.
However, the program still finished the prediction process and saved the output, but some processes did not exit correctly (such as 0th exited but others dit not exit).

Related code:

```py
predict_outputs = trainer.predict(datamodule=model.datamodule, ckpt_path="best")
predict_outputs = [item for batchs in predict_outputs for item in batchs]
predict_output_file = os.path.join(trainer.log_dir, "predict_outputs.txt")
with open(predict_output_file, "w") as fout:
    fout.write("\n".join(predict_outputs))
    logger.info(f"save prediction outputs to `{predict_output_file}`.")
```

error:

```
Restoring states from the checkpoint path at output/dataset1/T5/version_1/checkpoints/T5-monitor-epoch=12-micro=0.7291.ckpt
Loaded model weights from checkpoint at output/dataset1/T5/version_1/checkpoints/T5-monitor-epoch=12-micro=0.7291.ckpt
/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/connectors/data_connector.py:245: PossibleUserWarning: The dataloader, predict_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 160 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  category=PossibleUserWarning,
Predicting: 200it [00:00, ?it/s]/usr/local/lib/python3.7/dist-packages/pytorch_lightning/loops/epoch/prediction_epoch_loop.py:175: UserWarning: Lightning couldn't infer the indices fetched for your dataloader.
  warning_cache.warn("Lightning couldn't infer the indices fetched for your dataloader.")
Predicting DataLoader 0: : 34it [05:05, -0.54it/s]
2022-04-20 14:53:56,267 INFO __main__ train.py[171]: save prediction outputs to `output/dataset1/T5/version_1/predict_outputs.txt`.
+ exit_code=0
+ exit 0
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/workspace/env_run/train.py", line 176, in <module>
    train(args)
  File "/root/workspace/env_run/train.py", line 168, in train
    predict_output_file = os.path.join(trainer.log_dir, "predict_outputs.txt")
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py", line 2243, in log_dir
    dirpath = self.strategy.broadcast(dirpath)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/strategies/ddp.py", line 314, in broadcast
    torch.distributed.broadcast_object_list(obj, src, group=_group.WORLD)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/distributed_c10d.py", line 1824, in broadcast_object_list
    torch.sum(object_sizes_tensor).int().item(),  # type: ignore[arg-type]
RuntimeError: CUDA error: uncorrectable NVLink error detected during the execution
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
terminate called after throwing an instance of 'c10::CUDAError'
  what():  CUDA error: uncorrectable NVLink error detected during the execution
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Exception raised from create_event_internal at ../c10/cuda/CUDACachingAllocator.cpp:1211 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7fcba767fd62 in /usr/local/lib/python3.7/dist-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x1c5f3 (0x7fcbead2c5f3 in /usr/local/lib/python3.7/dist-packages/torch/lib/libc10_cuda.so)
frame #2: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0x1a2 (0x7fcbead2d002 in /usr/local/lib/python3.7/dist-packages/torch/lib/libc10_cuda.so)
frame #3: c10::TensorImpl::release_resources() + 0xa4 (0x7fcba7669314 in /usr/local/lib/python3.7/dist-packages/torch/lib/libc10.so)
frame #4: <unknown function> + 0x29e5f9 (0x7fcc6e0535f9 in /usr/local/lib/python3.7/dist-packages/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0xae7829 (0x7fcc6e89c829 in /usr/local/lib/python3.7/dist-packages/torch/lib/libtorch_python.so)
frame #6: THPVariable_subclass_dealloc(_object*) + 0x2b9 (0x7fcc6e89cb49 in /usr/local/lib/python3.7/dist-packages/torch/lib/libtorch_python.so)
frame #7: <unknown function> + 0x139328 (0x55827d522328 in /usr/bin/python3)
frame #8: <unknown function> + 0x1cead7 (0x55827d5b7ad7 in /usr/bin/python3)
frame #9: <unknown function> + 0x1ceaed (0x55827d5b7aed in /usr/bin/python3)
frame #10: <unknown function> + 0x1ceaed (0x55827d5b7aed in /usr/bin/python3)
frame #11: <unknown function> + 0x1ceaed (0x55827d5b7aed in /usr/bin/python3)
frame #12: <unknown function> + 0x1ceaed (0x55827d5b7aed in /usr/bin/python3)
frame #13: <unknown function> + 0x1ceaed (0x55827d5b7aed in /usr/bin/python3)
frame #14: <unknown function> + 0x1ceaed (0x55827d5b7aed in /usr/bin/python3)
frame #15: <unknown function> + 0x24d571 (0x55827d636571 in /usr/bin/python3)
frame #16: PyDict_SetItemString + 0x74 (0x55827d53cbd4 in /usr/bin/python3)
frame #17: PyImport_Cleanup + 0x9d (0x55827d5a6bad in /usr/bin/python3)
frame #18: Py_FinalizeEx + 0x64 (0x55827d64fdc4 in /usr/bin/python3)
frame #19: <unknown function> + 0x240f37 (0x55827d629f37 in /usr/bin/python3)
frame #20: _Py_UnixMain + 0x3c (0x55827d629dac in /usr/bin/python3)
frame #21: __libc_start_main + 0xe7 (0x7fcc72650b97 in /lib/x86_64-linux-gnu/libc.so.6)
frame #22: _start + 0x2a (0x55827d629c8a in /usr/bin/python3)
```

### Environment

* CUDA:
        - GPU:
                - A100-SXM4-40GB
                - A100-SXM4-40GB
                - A100-SXM4-40GB
                - A100-SXM4-40GB
                - A100-SXM4-40GB
                - A100-SXM4-40GB
                - A100-SXM4-40GB
                - A100-SXM4-40GB
        - available:         True
        - version:           11.3
* Packages:
        - numpy:             1.20.1
        - pyTorch_debug:     False
        - pyTorch_version:   1.10.2+cu113
        - pytorch-lightning: 1.6.0
        - tqdm:              4.63.1
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - 
        - processor:         x86_64
        - python:            3.7.10
        - version:           #1 SMP Fri Mar 19 10:07:22 CST 2021

### Additional context

cc @SeanNaren @awaelchli @rohitgr7 @akihironitta

**Comment by ShaneTian** [comment]
Any news? I meet it everyday :(

**Comment by zejunchen-zejun** [comment]
I met the same issue for now.

**Comment by deependujha** [comment]
Hi @zejunchen-zejun , can you please share a minimal reproducible code?

**Comment by zejunchen-zejun** [comment]
Hi, @deependujha 
For now I have no reproducer but I met the issue when running the sglang + deepseek-r1 on B200*8 machine.
When I got the machine, I will reproduce it again to obtain the NCCL log.
