### ISSUE TITLE
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:31, unhandled cuda error, NCCL version 2.7.8

### ISSUE THREAD

**Issue by WYHbxer** [Lightning-AI/lightning#13109]
## 🐛 Bug

I'm trying to train a model. The project comes from [https://github.com/PRBonn/segcontrast](https://github.com/PRBonn/segcontrast)
An error occurred while executing here

    if torch.cuda.device_count() > 1:
        model_sem_kitti = SemanticKITTIContrastiveTrainer(model, criterion, train_loader, args)
        trainer = Trainer(gpus=-1, accelerator='ddp', max_epochs=args.epochs, accumulate_grad_batches=args.accum_steps)
        trainer.fit(model_sem_kitti)

python3 contrastive_train.py --use-cuda --use-intensity --segment-contrast --checkpoint segcontrast
                 
```
Traceback (most recent call last):
  File "/home/WuYanhao/WorkSpace/segcontrast-main/contrastive_train.py", line 73, in <module>
    trainer.fit(model_sem_kitti)
  File "/home/WuYanhao/anaconda3/envs/segcontrast/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 510, in fit
    results = self.accelerator_backend.train()
  File "/home/WuYanhao/anaconda3/envs/segcontrast/lib/python3.7/site-packages/pytorch_lightning/accelerators/ddp_accelerator.py", line 158, in train
    trainer.fit(model_sem_kitti)
  File "/home/WuYanhao/anaconda3/envs/segcontrast/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 510, in fit
    results = self.ddp_train(process_idx=self.task_idx, model=model)
  File "/home/WuYanhao/anaconda3/envs/segcontrast/lib/python3.7/site-packages/pytorch_lightning/accelerators/ddp_accelerator.py", line 261, in ddp_train
    self.trainer.is_slurm_managing_tasks
  File "/home/WuYanhao/anaconda3/envs/segcontrast/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 163, in init_ddp_connection
    results = self.accelerator_backend.train()
  File "/home/WuYanhao/anaconda3/envs/segcontrast/lib/python3.7/site-packages/pytorch_lightning/accelerators/ddp_accelerator.py", line 158, in train
    is_slurm_managing_tasks,
  File "/home/WuYanhao/anaconda3/envs/segcontrast/lib/python3.7/site-packages/pytorch_lightning/plugins/ddp_plugin.py", line 94, in init_ddp_connection
    results = self.ddp_train(process_idx=self.task_idx, model=model)
  File "/home/WuYanhao/anaconda3/envs/segcontrast/lib/python3.7/site-packages/pytorch_lightning/accelerators/ddp_accelerator.py", line 261, in ddp_train
    torch_backend, rank=global_rank, world_size=world_size
  File "/home/WuYanhao/anaconda3/envs/segcontrast/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 455, in init_process_group
    self.trainer.is_slurm_managing_tasks
  File "/home/WuYanhao/anaconda3/envs/segcontrast/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 163, in init_ddp_connection
    barrier()
  File "/home/WuYanhao/anaconda3/envs/segcontrast/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1960, in barrier
    is_slurm_managing_tasks,
  File "/home/WuYanhao/anaconda3/envs/segcontrast/lib/python3.7/site-packages/pytorch_lightning/plugins/ddp_plugin.py", line 94, in init_ddp_connection
    torch_backend, rank=global_rank, world_size=world_size
  File "/home/WuYanhao/anaconda3/envs/segcontrast/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 455, in init_process_group
    barrier()
  File "/home/WuYanhao/anaconda3/envs/segcontrast/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1960, in barrier
    work = _default_pg.barrier()
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:31, unhandled cuda error, NCCL version 2.7.8
```

and this is my env

- PyTorch Lightning Version: 1.1.8
- PyTorch Version: 1.7.1
- Python version: 3.7
- OS: ubuntu 18.04
- CUDA/cuDNN version: 11.1
- GPU models and configuration: RTX 3090
- How you installed PyTorch: pip3

matplotlib==3.3.4
numpy==1.20.1
open3d==0.12.0
plyfile==0.7.3
pytorch-lightning==1.1.8
tensorboard==2.4.1
tensorboard-plugin-wit==1.8.0
torch==1.7.1
torchvision==0.8.2
tqdm==4.56.2
h5py==3.6.0
ninja==1.10.2.3
MinkowskiEngine==0.5.4

cc @justusschock @kaushikb11 @awaelchli @akihironitta @rohitgr7

**Comment by akihironitta** [comment]
@WYHbxer I would set `NCCL_DEBUG=INFO` and run it again to see information for its possible cause.
https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/env.html#nccl-debug

I'd also try updating the PL version to one of the recent releases as `pytorch-lightning==1.1.8` is very old and a number of issues have been resolved since then. Please note that the current stable release `pytorch-lightning>=1.6.0` dropped support for PyTorch 1.7 and thus is not tested in our CI.

**Comment by awaelchli** [comment]
If I remember correctly, around that time we had a bug with setting `gpus=-1` and `ddp`. Please avoid that and select the number directly or upgrade Lightning.

**Comment by WYHbxer** [comment]
> @WYHbxer I would set `NCCL_DEBUG=INFO` and run it again to see information for its possible cause. https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/env.html#nccl-debug
> 
> I'd also try updating the PL version to one of the recent releases as `pytorch-lightning==1.1.8` is very old and a number of issues have been resolved since then. Please note that the current stable release `pytorch-lightning>=1.6.0` dropped support for PyTorch 1.7 and thus is not tested in our CI.

Thank you!
after I update my PL and pytorch. I successfully run the program

**Comment by WYHbxer** [comment]
> If I remember correctly, around that time we had a bug with setting `gpus=-1` and `ddp`. Please avoid that and select the number directly or upgrade Lightning.

Thank you !

**Comment by flyingwaters** [comment]
when use deepspeed_stage_3 as strtategy , this bug also emerge, the same error as this...???? why  
torch>=1.7.1
transformers==4.16.2
pytorch-lightning==1.5.10
