### ISSUE TITLE
Unable to load trained checkpoint in Pytorch Lightning

### ISSUE THREAD

**Issue by Yxs-160** [Lightning-AI/lightning#13288]
Hello folks,

I made some changes in a model, and I can train the changed model from scratch. However when I evaluate the trained model, it reported a bug:

Traceback (most recent call last):
  File "eval.py", line 108, in <module>
    **transformer_config
  File "/home/ubuntu/anaconda3/envs/3d-retr/lib/python3.6/site-packages/pytorch_lightning/core/saving.py", line 157, in load_from_checkpoint
    model = cls._load_model_state(checkpoint, strict=strict, **kwargs)
  File "/home/ubuntu/anaconda3/envs/3d-retr/lib/python3.6/site-packages/pytorch_lightning/core/saving.py", line 205, in _load_model_state
    model.load_state_dict(checkpoint['state_dict'], strict=strict)
KeyError: 'state_dict'

and the eval.py is:
model = Image2Voxel.load_from_checkpoint(
        threshold=args.threshold,
        checkpoint_path=args.resume_from_checkpoint,
        **transformer_config
    )

    trainer = pl.Trainer.from_argparse_args(args, logger=False)

    if args.predict:
        if args.save_path is None:
            raise ValueError('save_path is not specified')

        prediction = trainer.predict(model, loader)
        for pred_dict in tqdm(prediction):
            for i in range(len(pred_dict['generation'])):
                tax_path = os.path.join(args.save_path, pred_dict['taxonomy_id'][i], pred_dict['model_id'][i])

                if not os.path.isdir(tax_path):
                    os.makedirs(tax_path)

                voxel = pred_dict['generation'][i][0].cpu().numpy()
                save_binvox(
                    voxel.astype(np.bool),
                    os.path.join(tax_path, 'prediction.binvox'),
                    pred_dict['translate'][i].cpu().numpy(),
                    pred_dict['scale'][i].cpu().numpy(),
                )
    else:
        trainer.test(model, loader)

I will appreciate any help. Thank you so much.

cc @awaelchli @ananthsub @ninginthecloud @rohitgr7 @otaj

**Comment by Yxs-160** [comment]
i have solved this problem thx!
