### ISSUE TITLE
AttributeError: 'FeatureExtractorFreezeUnfreeze' object has no attribute '_restarting'

### ISSUE THREAD

**Issue by mfoglio** [Lightning-AI/lightning#13326]
I am fine tuning a model. I'd like to freeze the backbone for the first epochs.
I followed the example in the doc and I created:
```
class FeatureExtractorFreezeUnfreeze(pl.callbacks.BaseFinetuning):

    def __init__(self, unfreeze_at_epoch=5):
        self._unfreeze_at_epoch = unfreeze_at_epoch

    def freeze_before_training(self, pl_module):
        # freeze any module you want
        # Here, we are freezing `features`
        self.freeze(pl_module.features)

    def finetune_function(self, pl_module, current_epoch, optimizer, optimizer_idx):
        # When `current_epoch` is self._unfreeze_at_epoch, features layers will start training.
        if current_epoch == self._unfreeze_at_epoch:
            self.unfreeze_and_add_param_group(
                modules=pl_module.features,
                optimizer=optimizer,
                train_bn=True,
            )
```
I am using it this way:
```
    feature_freeze_unfreeze = FeatureExtractorFreezeUnfreeze()
    # Trainer
    trainer = Trainer(
        accelerator='auto',
        default_root_dir=checkpoint_path,
        strategy='ddp',
        precision=16 if torch.cuda.is_available() else 32,
        logger=logger,
        log_every_n_steps=50,
        val_check_interval=0.5,
        callbacks=[RichProgressBar(), checkpoint_epoch_model, checkpoint_best_model, feature_freeze_unfreeze],
        max_epochs=-1
    )

    # Train
    trainer.fit(
        model=model,
        datamodule=vehicles_datamodule,
        ckpt_path=...
    )
```
But before the training could start, I get the error:
```
Traceback (most recent call last):
  File "/home/ubuntu/pycharm/projects/ai-models/src/vehicles/train/train.py", line 78, in <module>
    trainer.fit(
  File "/home/ubuntu/pycharm/projects/ai-models/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 768, in fit
    self._call_and_handle_interrupt(
  File "/home/ubuntu/pycharm/projects/ai-models/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 719, in _call_and_handle_interrupt
    return self.strategy.launcher.launch(trainer_fn, *args, trainer=self, **kwargs)
  File "/home/ubuntu/pycharm/projects/ai-models/venv/lib/python3.8/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 93, in launch
    return function(*args, **kwargs)
  File "/home/ubuntu/pycharm/projects/ai-models/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 809, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/ubuntu/pycharm/projects/ai-models/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1219, in _run
    self._call_callback_hooks("on_fit_start")
  File "/home/ubuntu/pycharm/projects/ai-models/venv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1634, in _call_callback_hooks
    fn(self, self.lightning_module, *args, **kwargs)
  File "/home/ubuntu/pycharm/projects/ai-models/venv/lib/python3.8/site-packages/pytorch_lightning/callbacks/finetuning.py", line 101, in on_fit_start
    if self._restarting:
AttributeError: 'FeatureExtractorFreezeUnfreeze' object has no attribute '_restarting'
```

**Comment by mfoglio** [comment]
My bad. I forgot to call `super().__init__()`.
