### ISSUE TITLE
TypeError: Unwrapping the module did not yield a `LightningModule`

### ISSUE THREAD

**Issue by ychenZHANG** [Lightning-AI/lightning#13355]
I am following the tutorial of MNIST, and I passed a pretrained model from timm, and I got this error.

I am using default strategy and backend.

```py
`Traceback (most recent call last):
  File "train.py", line 172, in <module>
    train(args)
  File "train.py", line 163, in train
    trainer.fit(model=pl_model, train_dataloaders=train_loader, val_dataloaders=val_loader)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py", line 771, in fit
    self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py", line 721, in _call_and_handle_interrupt
    return self.strategy.launcher.launch(trainer_fn, *args, trainer=self, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/strategies/launchers/spawn.py", line 82, in launch
    start_method=self._start_method,
  File "/usr/local/lib/python3.7/dist-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/usr/local/lib/python3.7/dist-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/usr/local/lib/python3.7/dist-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/strategies/launchers/spawn.py", line 101, in _wrapping_function
    results = function(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py", line 811, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py", line 1217, in _run
    self.strategy.setup(self)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/strategies/ddp_spawn.py", line 141, in setup
    self.configure_ddp()
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/strategies/ddp_spawn.py", line 193, in configure_ddp
    self.setup_optimizers(self.lightning_module.trainer)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/strategies/parallel.py", line 60, in lightning_module
    return unwrap_lightning_module(self.model) if self.model is not None else None
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/overrides/base.py", line 116, in unwrap_lightning_module
    raise TypeError(f"Unwrapping the module did not yield a `LightningModule`, got {type(model)} instead.")
TypeError: Unwrapping the module did not yield a `LightningModule`, got <class 'torch.nn.parallel.distributed.DistributedDataParallel'> instead.`
```

I am passing the model to pl.LightningModule as this:
```py
class PLModelFinetune(pl.LightningModule):
    def __init__(self, model, lr=1e-3):
        super().__init__()
        self.model = model
        self.lr = lr
        self.criterion = nn.CrossEntropyLoss(label_smoothing=0.1)
        # Metrics
        self.train_accuracy = torchmetrics.Accuracy()
        self.val_accuracy = torchmetrics.Accuracy()
        self.train_epoch_metrics = []
        self.val_epoch_metrics = []
```

cc @justusschock @awaelchli @ninginthecloud @rohitgr7 @kaushikb11 @akihironitta

**Comment by justusschock** [comment]
@ychenZHANG thanks for the issue. Could you maybe update your snippet a bit? What I am looking for is the class of the model (e.g which timm model you used) as well as your instantiation of the trainer. This would  make it significantly easier to debug this :)

**Comment by samdona14** [comment]
I am having the same issue:
`model = BartForConditionalGeneration.from_pretrained("facebook/bart-base")`
`trainer = pl.Trainer(accelerator="gpu", devices=1,check_val_every_n_epoch=1, max_epochs=5)`

TypeError: Unwrapping the module did not yield a `LightningModule`, got <class 'transformers.models.bart.modeling_bart.BartForConditionalGeneration'> instead.

**Comment by awaelchli** [comment]
You are not by any chance trying to call Trainer.fit() with something not a LightningModule? Because that's not valid. The BartForConditionalGeneration you have here seems to be directly the model from huggingface transformers but that's not a LightningModule. 

Here is a simple repro that produces the same error:

```py
import torch
from pytorch_lightning import Trainer

model = torch.nn.Linear(2, 2)
trainer = Trainer()
trainer.fit(model) 
```

So the fix here for us is to update the error messaging, so that it is clear to the user only LightningModules can be passed to the Trainer methods.
