### ISSUE TITLE
ModelPruning results in "AttributeError: 'int' object has no attribute 'is_cuda'"

### ISSUE THREAD

**Issue by styler00dollar** [Lightning-AI/lightning#13411]
## 🐛 Bug

I tried to use `ModelPruning("l1_unstructured", amount=0.2)` [like the documention showed as an example](https://pytorch-lightning.readthedocs.io/en/stable/advanced/pruning_quantization.html), but it seems to crash with my code.

I hope a full traceback is enough since my training code is quite big.

```
    trainer = pl.Trainer(
        plugins=pl.plugins.precision.NativeMixedPrecisionPlugin(precision="16", device="cuda"),
        amp_backend="native",
        num_sanity_val_steps=0,
        log_every_n_steps=50,
        resume_from_checkpoint=cfg["path"]["checkpoint_path"],
        check_val_every_n_epoch=None,
        val_check_interval=int(cfg["datasets"]["train"]["save_step_frequency"]),
        logger=None,
        gpus=1,
        precision=16,
        max_epochs=cfg["datasets"]["train"]["max_epochs"],
        default_root_dir=cfg["default_root_dir"],
        callbacks=[
            CheckpointOnInterrupt(
                save_path=cfg["path"]["checkpoint_save_path"],
            )
            , QuantizationAwareTraining(),
            ModelPruning("l1_unstructured", amount=0.2)
        ])
```

```
  | Name    | Type            | Params
--------------------------------------------
0 | netG    | SRVGGNetCompact | 3.1 M 
1 | loss    | AllLoss         | 143 M 
2 | quant   | QuantStub       | 0     
3 | dequant | DeQuantStub     | 0     
--------------------------------------------
10.2 M    Trainable params
136 M     Non-trainable params
146 M     Total params
587.691   Total estimated model params size (MB)
Epoch 0: 100% 275/275 [01:32<00:00,  2.98it/s, loss=0.0401]Traceback (most recent call last):
  File "train.py", line 119, in <module>
    trainer.fit(model, dm)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py", line 703, in fit
    self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py", line 655, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py", line 743, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py", line 1168, in _run
    results = self._run_stage()
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py", line 1255, in _run_stage
    return self._run_train()
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py", line 1285, in _run_train
    self.fit_loop.run()
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/loops/loop.py", line 205, in run
    self.on_advance_end()
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/loops/fit_loop.py", line 297, in on_advance_end
    self.trainer._call_callback_hooks("on_train_epoch_end")
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py", line 1599, in _call_callback_hooks
    fn(self, self.lightning_module, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/callbacks/pruning.py", line 397, in on_train_epoch_end
    self._run_pruning(pl_module.current_epoch)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/callbacks/pruning.py", line 385, in _run_pruning
    self.apply_pruning(amount)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/callbacks/pruning.py", line 334, in apply_pruning
    self._apply_global_pruning(amount)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/callbacks/pruning.py", line 317, in _apply_global_pruning
    self._parameters_to_prune, pruning_method=self.pruning_fn, **self._resolve_global_kwargs(amount)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/utils/prune.py", line 1082, in global_unstructured
    for (module, name) in parameters
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/utils/convert_parameters.py", line 21, in parameters_to_vector
    param_device = _check_param_device(param, param_device)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/utils/convert_parameters.py", line 77, in _check_param_device
    if param.is_cuda:  # Check if in same GPU
AttributeError: 'int' object has no attribute 'is_cuda'
```

### Expected behavior

It should not crash. It crashes after one epoch.

### Environment

```
Google Colab
pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113 --force-reinstall
pip install git+https://github.com/PyTorchLightning/pytorch-lightning.git
```

cc @carmocca

**Comment by carmocca** [comment]
Can you try and reproduce it by adapting this script?: https://github.com/Lightning-AI/lightning/blob/master/examples/pl_bug_report/bug_report_model.py

The cause might be an unwanted interaction between the `QuantizationAwareTraining` and `ModelPruning` callbacks.

**Comment by carmocca** [comment]
A reproducible notebook would definitely help.

**Comment by aminst** [comment]
Hi everyone,
Is there any update on this issue?
