### ISSUE TITLE
translate_boto_error, permission error when using lightning storage Drive put()

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/lightning#13425]
## 🐛 Bug

Uploading a file with `Drive.put()` results in a permission error. The error does not say exactly why this happened. 

### To Reproduce

```py

import lightning as L
from lightning.app.components.python import TracerPythonScript
import shutil
from pathlib import Path
from lightning_app.storage import Drive


class TrainAndSaveModel(TracerPythonScript):

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.checkoint_files = Drive("lit://checkpoints")

    def on_after_run(self, _):
        self.checkoint_files.put(Path.cwd() / "my_trained_model.pt")


class RootFlow(L.LightningFlow):
    def __init__(self):
        super().__init__()

        self.train = TrainAndSaveModel(
            script_path="my_train_script.py",
            script_args=["--num_epochs=1", "--save_name=my_trained_model.pt"],
            cloud_compute=L.CloudCompute("gpu")
        )

    def run(self):
        self.train.run()


app = L.LightningApp(RootFlow())

```

Run as

```bash
lightning run app app.py --cloud
```

Output logs and error:
```

[root.train] 2022-06-28T07:56:30.110Z INFO: Batch: 000/234 |
[root.train] 2022-06-28T07:56:30.111Z INFO: Loss: 2.3222
[root.train] 2022-06-28T07:56:31.148Z INFO: Epoch: 001/001 |
[root.train] 2022-06-28T07:56:31.148Z INFO: Batch: 050/234 |
[root.train] 2022-06-28T07:56:31.148Z INFO: Loss: 0.4334
[root.train] 2022-06-28T07:56:32.209Z INFO: Epoch: 001/001 |
[root.train] 2022-06-28T07:56:32.209Z INFO: Batch: 100/234 |
[root.train] 2022-06-28T07:56:32.209Z INFO: Loss: 0.2531
[root.train] 2022-06-28T07:56:33.317Z INFO: Epoch: 001/001 |
[root.train] 2022-06-28T07:56:33.317Z INFO: Batch: 150/234 |
[root.train] 2022-06-28T07:56:33.317Z INFO: Loss: 0.2577
[root.train] 2022-06-28T07:56:34.417Z INFO: Epoch: 001/001 |
[root.train] 2022-06-28T07:56:34.417Z INFO: Batch: 200/234 |
[root.train] 2022-06-28T07:56:34.417Z INFO: Loss: 0.1782
[root.train] 2022-06-28T07:56:35.223Z INFO: Total Training Time: 0.09 min
[root.train] 2022-06-28T07:56:41.190Z INFO: Training accuracy: 94.33%
[root.train] 2022-06-28T07:56:41.190Z INFO: Test accuracy: 94.07%
[root.train] 2022-06-28T07:56:41.299Z Traceback (most recent call last):
[root.train] 2022-06-28T07:56:41.299Z   File "/content/venv/lib/python3.8/site-packages/s3fs/core.py", line 593, in _lsdir
[root.train] 2022-06-28T07:56:41.299Z     async for i in it:
[root.train] 2022-06-28T07:56:41.299Z   File "/content/venv/lib/python3.8/site-packages/aiobotocore/paginate.py", line 32, in __anext__
[root.train] 2022-06-28T07:56:41.299Z     response = await self._make_request(current_kwargs)
[root.train] 2022-06-28T07:56:41.299Z   File "/content/venv/lib/python3.8/site-packages/aiobotocore/client.py", line 225, in _make_api_call
[root.train] 2022-06-28T07:56:41.299Z     raise error_class(parsed_response, operation_name)
[root.train] 2022-06-28T07:56:41.299Z botocore.exceptions.ClientError: An error occurred (403) when calling the ListObjectsV2 operation: Forbidden
[root.train] 2022-06-28T07:56:41.299Z The above exception was the direct cause of the following exception:
[root.train] 2022-06-28T07:56:41.299Z Traceback (most recent call last):
[root.train] 2022-06-28T07:56:41.299Z   File "/content/venv/bin/lightning-cloud-launcher", line 8, in <module>
[root.train] 2022-06-28T07:56:41.299Z     sys.exit(main())
[root.train] 2022-06-28T07:56:41.299Z   File "/content/venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
[root.train] 2022-06-28T07:56:41.299Z     return self.main(*args, **kwargs)
[root.train] 2022-06-28T07:56:41.299Z   File "/content/venv/lib/python3.8/site-packages/click/core.py", line 1055, in main
[root.train] 2022-06-28T07:56:41.299Z     rv = self.invoke(ctx)
[root.train] 2022-06-28T07:56:41.299Z   File "/content/venv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
[root.train] 2022-06-28T07:56:41.299Z     return _process_result(sub_ctx.command.invoke(sub_ctx))
[root.train] 2022-06-28T07:56:41.299Z   File "/content/venv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
[root.train] 2022-06-28T07:56:41.299Z     return _process_result(sub_ctx.command.invoke(sub_ctx))
[root.train] 2022-06-28T07:56:41.299Z   File "/content/venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
[root.train] 2022-06-28T07:56:41.299Z     return ctx.invoke(self.callback, **ctx.params)
[root.train] 2022-06-28T07:56:41.299Z   File "/content/venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
[root.train] 2022-06-28T07:56:41.299Z     return __callback(*args, **kwargs)
[root.train] 2022-06-28T07:56:41.299Z   File "/content/venv/lib/python3.8/site-packages/lightning_launcher/cli/__main__.py", line 86, in run_work
[root.train] 2022-06-28T07:56:41.299Z     run_lightning_work(
[root.train] 2022-06-28T07:56:41.299Z   File "/content/venv/lib/python3.8/site-packages/lightning_launcher/utils.py", line 49, in wrapper
[root.train] 2022-06-28T07:56:41.299Z     res = func(*args, **kwargs)
[root.train] 2022-06-28T07:56:41.299Z   File "/content/venv/lib/python3.8/site-packages/lightning_launcher/utils.py", line 73, in wrapper
[root.train] 2022-06-28T07:56:41.299Z     res = func(*args, **kwargs)
[root.train] 2022-06-28T07:56:41.299Z   File "/content/venv/lib/python3.8/site-packages/lightning_launcher/launcher.py", line 109, in run_lightning_work
[root.train] 2022-06-28T07:56:41.299Z     WorkRunner(
[root.train] 2022-06-28T07:56:41.299Z   File "/content/venv/lib/python3.8/site-packages/lightning_app/utilities/proxies.py", line 308, in __call__
[root.train] 2022-06-28T07:56:41.299Z     raise e
[root.train] 2022-06-28T07:56:41.299Z   File "/content/venv/lib/python3.8/site-packages/lightning_app/utilities/proxies.py", line 291, in __call__
[root.train] 2022-06-28T07:56:41.299Z     self.run_once()
[root.train] 2022-06-28T07:56:41.299Z   File "/content/venv/lib/python3.8/site-packages/lightning_app/utilities/proxies.py", line 400, in run_once
[root.train] 2022-06-28T07:56:41.299Z     self.work.on_exception(e)
[root.train] 2022-06-28T07:56:41.299Z   File "/content/venv/lib/python3.8/site-packages/lightning_app/core/work.py", line 471, in on_exception
[root.train] 2022-06-28T07:56:41.299Z     raise exception
[root.train] 2022-06-28T07:56:41.299Z   File "/content/venv/lib/python3.8/site-packages/lightning_app/utilities/proxies.py", line 391, in run_once
[root.train] 2022-06-28T07:56:41.299Z     ret = work_run(*args, **kwargs)
[root.train] 2022-06-28T07:56:41.299Z   File "/content/venv/lib/python3.8/site-packages/lightning_app/components/python/tracer.py", line 117, in run
[root.train] 2022-06-28T07:56:41.299Z     return self.on_after_run(res)
[root.train] 2022-06-28T07:56:41.299Z   File "app4.py", line 16, in on_after_run
[root.train] 2022-06-28T07:56:41.299Z   File "/content/venv/lib/python3.8/site-packages/lightning_app/storage/drive.py", line 89, in put
[root.train] 2022-06-28T07:56:41.299Z     fs.put(str(source_path), str(destination_path))
[root.train] 2022-06-28T07:56:41.299Z   File "/content/venv/lib/python3.8/site-packages/fsspec/asyn.py", line 91, in wrapper
[root.train] 2022-06-28T07:56:41.299Z     return sync(self.loop, func, *args, **kwargs)
[root.train] 2022-06-28T07:56:41.299Z   File "/content/venv/lib/python3.8/site-packages/fsspec/asyn.py", line 71, in sync
[root.train] 2022-06-28T07:56:41.299Z     raise return_result
[root.train] 2022-06-28T07:56:41.299Z   File "/content/venv/lib/python3.8/site-packages/fsspec/asyn.py", line 25, in _runner
[root.train] 2022-06-28T07:56:41.299Z     result[0] = await coro
[root.train] 2022-06-28T07:56:41.299Z   File "/content/venv/lib/python3.8/site-packages/fsspec/asyn.py", line 474, in _put
[root.train] 2022-06-28T07:56:41.299Z     lpaths, rpath, exists=isinstance(rpath, str) and await self._isdir(rpath)
[root.train] 2022-06-28T07:56:41.299Z   File "/content/venv/lib/python3.8/site-packages/s3fs/core.py", line 1142, in _isdir
[root.train] 2022-06-28T07:56:41.299Z     return bool(await self._lsdir(path))
[root.train] 2022-06-28T07:56:41.299Z   File "/content/venv/lib/python3.8/site-packages/s3fs/core.py", line 616, in _lsdir
[root.train] 2022-06-28T07:56:41.299Z     raise translate_boto_error(e)
[root.train] 2022-06-28T07:56:41.299Z PermissionError: Forbidden
[flow] 2022-06-28T07:56:42.048Z INFO: Waiting for works to stop...
[flow] 2022-06-28T07:56:43.084Z INFO: Waiting for works to stop...
[flow] 2022-06-28T07:56:44.135Z INFO: Waiting for works to stop...
[flow] 2022-06-28T07:56:45.172Z INFO: Waiting for works to stop...
[flow] 2022-06-28T07:56:46.209Z INFO: Waiting for works to stop...
```

### Expected behavior

Files get uploaded. The same code works if we switch to lightning.storage.Path:

```py
class TrainAndSaveModel(TracerPythonScript):

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.model_path = "lit://my_trained_model.pt"

    def on_after_run(self, _):
        shutil.copy(Path.cwd() / "my_trained_model.pt", self.model_path)

```

### Environment

- PyTorch Lightning Version (e.g., 1.5.0): Lightning apps master (lightning_app) June 28
- PyTorch Version (e.g., 1.10): -
- Python version (e.g., 3.9): whatever it is in the cloud
- OS (e.g., Linux): Linux
- CUDA/cuDNN version: -
- GPU models and configuration: -
- How you installed PyTorch (`conda`, `pip`, source): -
- If compiling from source, the output of `torch.__config__.show()`: -
- Any other relevant information: -

**Comment by awaelchli** [comment]
@tchaton have you seen this error before?

**Comment by rasbt** [comment]
Can confirm, I encounter this issue, too!

**Comment by tchaton** [comment]
Hey @awaelchli Can you try without Path.cwd(), everything should be relative.
