### ISSUE TITLE
Local rank conflict when training on multi-node multi-gpu cluster using deepspeed

### ISSUE THREAD

**Issue by jessecambon** [Lightning-AI/lightning#13567]
## 🐛 Bug

When training using deepspeed stage 3 in a multi-node environment with multiple GPUs on each node, an error regarding the LOCAL_RANK environment variable appears. AzureML with an MPIConfiguration is used to submit the job to an Azure cluster.

```sh
Traceback (most recent call last):
  File "/mnt/batch/tasks/shared/LS_root/jobs/abcinc-stg-amls/azureml/lightning_logs_1657208514_7d53279f/wd/azureml/lightning_logs_1657208514_7d53279f/deepspeed_reprex.py", line 126, in <module>
    trainer1.fit(model, datamodule=dm)
  File "/azureml-envs/azureml_d27e5eec175d09c4fb60e106b8da1c72/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 701, in fit
    self._call_and_handle_interrupt(
  File "/azureml-envs/azureml_d27e5eec175d09c4fb60e106b8da1c72/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 655, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/azureml-envs/azureml_d27e5eec175d09c4fb60e106b8da1c72/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 742, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/azureml-envs/azureml_d27e5eec175d09c4fb60e106b8da1c72/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1148, in _run
    self.strategy.setup(self)
  File "/azureml-envs/azureml_d27e5eec175d09c4fb60e106b8da1c72/lib/python3.8/site-packages/pytorch_lightning/strategies/deepspeed.py", line 366, in setup
    self.init_deepspeed()
  File "/azureml-envs/azureml_d27e5eec175d09c4fb60e106b8da1c72/lib/python3.8/site-packages/pytorch_lightning/strategies/deepspeed.py", line 470, in init_deepspeed
    self._initialize_deepspeed_train(model)
  File "/azureml-envs/azureml_d27e5eec175d09c4fb60e106b8da1c72/lib/python3.8/site-packages/pytorch_lightning/strategies/deepspeed.py", line 503, in _initialize_deepspeed_train
    model, deepspeed_optimizer = self._setup_model_and_optimizer(model, optimizer, scheduler)
  File "/azureml-envs/azureml_d27e5eec175d09c4fb60e106b8da1c72/lib/python3.8/site-packages/pytorch_lightning/strategies/deepspeed.py", line 430, in _setup_model_and_optimizer
    deepspeed_engine, deepspeed_optimizer, _, _ = deepspeed.initialize(
  File "/azureml-envs/azureml_d27e5eec175d09c4fb60e106b8da1c72/lib/python3.8/site-packages/deepspeed/__init__.py", line 120, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/azureml-envs/azureml_d27e5eec175d09c4fb60e106b8da1c72/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 239, in __init__
    self._configure_with_arguments(args, mpu)
  File "/azureml-envs/azureml_d27e5eec175d09c4fb60e106b8da1c72/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 860, in _configure_with_arguments
    assert ompi_local_rank == local_rank, f"LOCAL_RANK ({local_rank}) != OMPI_COMM_WORLD_LOCAL_RANK ({ompi_local_rank}), " \
AssertionError: LOCAL_RANK (1) != OMPI_COMM_WORLD_LOCAL_RANK (0), not sure how to proceed as we're seeing conflicting local rank info.
```

I was able to fix this error (and get training to run successfully) by adding the following line to the setup() function of the LightningModule:

```python
os.environ['OMPI_COMM_WORLD_LOCAL_RANK'] = os.environ.get('LOCAL_RANK')
```

### To Reproduce

Download the two python scripts below (edit as needed to run on a multinode multi-gpu environment) and then run `python submit_job.py`. To fix the error (shown above), uncomment the following line in `deepspeed_reprex.py`):

```python
os.environ['OMPI_COMM_WORLD_LOCAL_RANK'] = os.environ.get('LOCAL_RANK')
```

**submit_job.py**:
```python
import os
from azureml.core.runconfig import PyTorchConfiguration, MpiConfiguration
from azureml.core import Environment, Workspace, ScriptRunConfig, Experiment
from azureml.core.authentication import ServicePrincipalAuthentication

experiment_name = "XXXXXXXXX"
environment_name = "XXXXXXXX"
cluster_name="XXXXXXX"
node_count=2
environment_version="XXXXXXX"

command="; ".join([
    "python -m pip freeze",
    "wget https://raw.githubusercontent.com/Lightning-AI/lightning/master/requirements/collect_env_details.py",
    "python collect_env_details.py",
    "python deepspeed_reprex.py"
])

print(command)

ws = Workspace.get(
    name="XXXXXXXXX",
    resource_group="XXXXXXXXXX",
    subscription_id=os.environ["AZURE_SUBSCRIPTION_ID"],
    auth= ServicePrincipalAuthentication(
            tenant_id=os.environ.get("AZURE_TENANT_ID"),
            service_principal_id=os.environ.get("AZURE_CLIENT_ID"),
            service_principal_password=os.environ.get("AZURE_CLIENT_SECRET")
        )
    )

compute_target=ws.compute_targets[cluster_name]

env = Environment.get(
    workspace = ws,
    name = environment_name,
    version = environment_version
    )

print(env)
print(env.get_image_details(ws))

job_config = MpiConfiguration(node_count=node_count, process_count_per_node=1)

src = ScriptRunConfig(
    source_directory = ".",
    command=command,
    compute_target = compute_target,
    environment = env,
    distributed_job_config = job_config
)

# Submit job
run = Experiment(ws, experiment_name).submit(src)
```

**deepspeed_reprex.py**:

```python
import torch, os, logging, sys
from torch.utils.data import DataLoader, Dataset
from pytorch_lightning import LightningModule, Trainer, LightningDataModule
from deepspeed.ops.adam import FusedAdam

os.environ["MKL_THREADING_LAYER"] = "GNU" # fixes https://github.com/pytorch/pytorch/issues/37377?

divider_str="-"*40

def get_env_display_text(var_name):
    var_value = os.environ.get(var_name, "")
    return f"{var_name} = {var_value}"

def display_environment():
    """
    Print a few environment variables of note
    """
    variable_names = [
        "MASTER_ADDR",
        "MASTER_PORT",
        "NODE_RANK",
        "LOCAL_RANK",
        "GLOBAL_RANK",
        "WORLD_SIZE",
        "NCCL_SOCKET_IFNAME",
        "OMPI_COMM_WORLD_RANK",
        "OMPI_COMM_WORLD_LOCAL_RANK",
        "OMPI_COMM_WORLD_SIZE",
        "OMPI_COMM_WORLD_LOCAL_SIZE"
    ]
    var_text = "\n".join([get_env_display_text(var) for var in variable_names])
    print(f"\nEnvironmental variables:\n{divider_str}\n{var_text}\n{divider_str}\n")

class RandomDataset(Dataset):
    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len

class BoringModel(LightningModule):
    def __init__(self):
        super().__init__()
        self.save_hyperparameters()
        self.layer = torch.nn.Linear(32, 2)

    def forward(self, x):
        return self.layer(x)

    def training_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("train_loss", loss)
        return {"loss": loss}

    def validation_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("valid_loss", loss)

    def test_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("test_loss", loss)

    def configure_optimizers(self):
        return FusedAdam(self.layer.parameters())
    
    def setup(self, stage=None) -> None:
        print(f"\n LightningModule: setup(stage={stage})\n")

        # prevents hanging
        if stage != "fit":
            return
        
        # UNCOMMENT FOLLOWING LINE TO FIX BUG
        #os.environ['OMPI_COMM_WORLD_LOCAL_RANK'] = os.environ.get('LOCAL_RANK')
        display_environment()


class DataModule(LightningDataModule):
    def __init__(self):
        super().__init__()
        self.num_workers = os.cpu_count()
        print(f"num_workers set to {self.num_workers}")

    def setup(self, stage=None) -> None:
        self._dataloader = DataLoader(
            RandomDataset(32, 64),
             num_workers=self.num_workers,
             batch_size=1,
             pin_memory=True
             )

    def train_dataloader(self):
        return self._dataloader
    
    def test_dataloader(self):
        return self._dataloader

    def val_dataloader(self):
        return self._dataloader

if __name__ == "__main__":
    model = BoringModel()
    dm = DataModule()
    trainer1 = Trainer(
        accelerator='gpu',
        auto_select_gpus=True,
        limit_train_batches=1,
        limit_val_batches=1,
        logger=False,
        enable_checkpointing=False,
        num_sanity_val_steps=0,
        max_epochs=1,
        enable_model_summary=False,
        strategy="deepspeed_stage_3",
        precision=16
    )

    trainer1.fit(model, datamodule=dm)
```

### Expected behavior

Training should run successfully without requiring an environmental variable adjustment.

### Environment

2 Nodes on Azure Machine Learning Services with the following specs:

```
* CUDA:
	- GPU:
		- Tesla V100-PCIE-16GB
		- Tesla V100-PCIE-16GB
	- available:         True
	- version:           10.2
* Packages:
	- numpy:             1.23.0
	- pyTorch_debug:     False
	- pyTorch_version:   1.11.0+cu102
	- pytorch-lightning: 1.7.0dev
	- tqdm:              4.64.0
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- ELF
	- processor:         x86_64
	- python:            3.8.13
	- version:           #38-Ubuntu SMP Sun Mar 22 21:27:21 UTC 2020
```

- Deepspeed is version 0.6.5
- The base docker image for the cluster is `mcr.microsoft.com/azureml/openmpi3.1.2-cuda10.2-cudnn8-ubuntu18.04`

cc @SeanNaren @awaelchli @rohitgr7 @akihironitta

**Comment by thongonary** [comment]
I'm having the exact same issue with `deepspeed_stage_2` strategy on AzureML with 1 node / 4 GPUs.

**Comment by thongonary** [comment]
Looks like the suggested fix is what we're supposed to do in the first place.

Per Azure documentation https://docs.microsoft.com/en-us/azure/machine-learning/how-to-train-distributed-gpu
```
import os

def set_environment_variables_for_nccl_backend(single_node=False, master_port=6105):
     if not single_node:
         master_node_params = os.environ["AZ_BATCH_MASTER_NODE"].split(":")
         os.environ["MASTER_ADDR"] = master_node_params[0]

         # Do not overwrite master port with that defined in AZ_BATCH_MASTER_NODE
         if "MASTER_PORT" not in os.environ:
             os.environ["MASTER_PORT"] = str(master_port)
     else:
         os.environ["MASTER_ADDR"] = os.environ["AZ_BATCHAI_MPI_MASTER_NODE"]
         os.environ["MASTER_PORT"] = "54965"

     os.environ["NCCL_SOCKET_IFNAME"] = "^docker0,lo"
     try:
         os.environ["NODE_RANK"] = os.environ["OMPI_COMM_WORLD_RANK"]
         # additional variables
         os.environ["MASTER_ADDRESS"] = os.environ["MASTER_ADDR"]
         os.environ["LOCAL_RANK"] = os.environ["OMPI_COMM_WORLD_LOCAL_RANK"]
         os.environ["WORLD_SIZE"] = os.environ["OMPI_COMM_WORLD_SIZE"]
     except:
         # fails when used with pytorch configuration instead of mpi
         pass
```

**Comment by jessecambon** [comment]
@thongonary were you able to get this fix to work? When I try to insert it into `LightningModule.setup()` it hangs. I then tried calling this function in the main script body before the trainer is created and it caused this error on my 2nd node (in a 3 node setup):

```
Auto select gpus: [0, 1]
Global seed set to 42
initializing deepspeed distributed: GLOBAL_RANK: 2, MEMBER: 3/2
e26f1f7c0b3e461f994bc6a9bca5374e000004:146:146 [0] NCCL INFO Bootstrap : Using eth0:10.0.0.8<0>
e26f1f7c0b3e461f994bc6a9bca5374e000004:146:146 [0] NCCL INFO NET/Plugin: Failed to find ncclCollNetPlugin_v4 symbol.
e26f1f7c0b3e461f994bc6a9bca5374e000004:146:146 [0] NCCL INFO Plugin Path : /usr/local/nccl-rdma-sharp-plugins/lib/libnccl-net.so
e26f1f7c0b3e461f994bc6a9bca5374e000004:146:146 [0] NCCL INFO P2P plugin IBext
e26f1f7c0b3e461f994bc6a9bca5374e000004:146:146 [0] NCCL INFO NET/IB : No device found.
e26f1f7c0b3e461f994bc6a9bca5374e000004:146:146 [0] NCCL INFO NCCL_IB_DISABLE set by environment to 1.
e26f1f7c0b3e461f994bc6a9bca5374e000004:146:146 [0] NCCL INFO NET/Socket : Using [0]eth0:10.0.0.8<0>
e26f1f7c0b3e461f994bc6a9bca5374e000004:146:146 [0] NCCL INFO Using network Socket

e26f1f7c0b3e461f994bc6a9bca5374e000004:146:146 [0] init.cc:932 NCCL WARN Invalid rank requested : 2/2
e26f1f7c0b3e461f994bc6a9bca5374e000004:146:146 [0] NCCL INFO init.cc:953 -> 4
Traceback (most recent call last):
  File "logging_reprex.py", line 189, in <module>
    trainer.fit(model, datamodule=dm)
  File "/azureml-envs/azureml_6f92577c1b6d4ac994abfeb03f256212/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 770, in fit
    self._call_and_handle_interrupt(
  File "/azureml-envs/azureml_6f92577c1b6d4ac994abfeb03f256212/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 723, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/azureml-envs/azureml_6f92577c1b6d4ac994abfeb03f256212/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 811, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/azureml-envs/azureml_6f92577c1b6d4ac994abfeb03f256212/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1172, in _run
    self.__setup_profiler()
  File "/azureml-envs/azureml_6f92577c1b6d4ac994abfeb03f256212/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1797, in __setup_profiler
    self.profiler.setup(stage=self.state.fn._setup_fn, local_rank=local_rank, log_dir=self.log_dir)
  File "/azureml-envs/azureml_6f92577c1b6d4ac994abfeb03f256212/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 2249, in log_dir
    dirpath = self.strategy.broadcast(dirpath)
  File "/azureml-envs/azureml_6f92577c1b6d4ac994abfeb03f256212/lib/python3.8/site-packages/pytorch_lightning/strategies/ddp.py", line 319, in broadcast
    torch.distributed.broadcast_object_list(obj, src, group=_group.WORLD)
  File "/azureml-envs/azureml_6f92577c1b6d4ac994abfeb03f256212/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1869, in broadcast_object_list
    broadcast(object_sizes_tensor, src=src, group=group)
  File "/azureml-envs/azureml_6f92577c1b6d4ac994abfeb03f256212/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1187, in broadcast
    work = default_pg.broadcast([tensor], opts)
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1646755903507/work/torch/csrc/distributed/c10d/NCCLUtils.hpp:125, invalid argument, NCCL version 21.0.3
ncclInvalidArgument: Invalid value for an argument (such as invalid pointer, device count, ip:host pair, etc).
[2022-07-12T16:22:52.823286] Command finished with exit code 256 interpreted as return code 1
```

**Comment by thongonary** [comment]
Yeah sorry @jessecambon I did not test it properly before posting. Indeed `OMPI_COMM_WORLD_LOCAL_RANK` is blank in AML PyTorch environment so it does not make sense to set `os.environ["LOCAL_RANK"] = os.environ["OMPI_COMM_WORLD_LOCAL_RANK"]` as in the Azure doc.

**Comment by jessecambon** [comment]
@thongonary This is a more comprehensive solution which I initially used for `strategy='ddp'`, but it works with deepspeed as well:

https://github.com/Lightning-AI/lightning/issues/13639#issuecomment-1184719803

**Comment by thongonary** [comment]
Thanks @jessecambon, this is awesome! I confirm it works for me.

**Comment by awaelchli** [comment]
The MPI environment is now supported through #16570 which handles these environment variables. Converting the local rank manually should no longer be necessary. If mpi4py is installed, Lightning will auto-detect the MPI cluster and set itself up.

**Comment by pengyanai** [comment]
related issue: https://github.com/iqiancheng/llms-cookbook/issues/2
