### ISSUE TITLE
Upload sdist to PyPI to enable building conda-forge package

### ISSUE THREAD

**Issue by weiji14** [Lightning-AI/lightning#13583]
### Motivation

Hiya, I've been trying to get `lightning` onto conda-forge using [`grayskull`](https://github.com/conda-incubator/grayskull) but it seems like the source distribution (sdist) for `lightning` is missing on PyPI at https://pypi.org/project/lightning/2022.6.15.post2/#files. So running `grayskull pypi lightning` (to generate the conda-forge recipe) fails:

```python-traceback
#### Initializing recipe for lightning (pypi) ####

Recovering metadata from pypi...
Traceback (most recent call last):
  File "/home/username/mambaforge/envs/condalock/bin/grayskull", line 8, in <module>
    sys.exit(main())
  File "/home/username/mambaforge/envs/condalock/lib/python3.10/site-packages/grayskull/__main__.py", line 155, in main
    generate_recipes_from_list(args.pypi_packages, args)
  File "/home/username/mambaforge/envs/condalock/lib/python3.10/site-packages/grayskull/__main__.py", line 177, in generate_recipes_from_list
    recipe, config = create_python_recipe(
  File "/home/username/mambaforge/envs/condalock/lib/python3.10/site-packages/grayskull/__main__.py", line 206, in create_python_recipe
    GrayskullFactory.create_recipe(
  File "/home/username/mambaforge/envs/condalock/lib/python3.10/site-packages/grayskull/base/factory.py", line 31, in create_recipe
    GrayskullFactory.REGISTERED_STRATEGY[repo_type.lower()].fetch_data(
  File "/home/username/mambaforge/envs/condalock/lib/python3.10/site-packages/grayskull/strategy/pypi.py", line 61, in fetch_data
    update_recipe(recipe, config, sections or ALL_SECTIONS)
  File "/home/username/mambaforge/envs/condalock/lib/python3.10/site-packages/grayskull/strategy/pypi.py", line 426, in update_recipe
    metadata = get_metadata(recipe, config)
  File "/home/username/mambaforge/envs/condalock/lib/python3.10/site-packages/grayskull/strategy/pypi.py", line 344, in get_metadata
    sdist_metadata, pypi_metadata = get_origin_wise_metadata(config)
  File "/home/username/mambaforge/envs/condalock/lib/python3.10/site-packages/grayskull/strategy/pypi.py", line 228, in get_origin_wise_metadata
    pypi_metadata = get_pypi_metadata(config)
  File "/home/username/mambaforge/envs/condalock/lib/python3.10/site-packages/grayskull/strategy/pypi.py", line 283, in get_pypi_metadata
    "sha256": get_sha256_from_pypi_metadata(metadata),
  File "/home/username/mambaforge/envs/condalock/lib/python3.10/site-packages/grayskull/strategy/pypi.py", line 149, in get_sha256_from_pypi_metadata
    raise AttributeError("Hash information for sdist was not found on PyPi metadata.")
AttributeError: Hash information for sdist was not found on PyPi metadata.
```

Would it be possible to upload the sdist (tar.gz file) to PyPI too? A quick search through the codebase showed this workflow which should make the sdist:

https://github.com/Lightning-AI/lightning/blob/b59f80224843886459d54c828325683d770da746/.github/workflows/release-pypi.yml#L35

However, it doesn't seem like that GitHub Actions workflow was used in recent releases. Has the release workflow changed recently?

### Pitch

Allow users to do `conda install lightning` eventually.

### Alternatives

Let users continue to use `pip install lightning` only.

### Additional context

______________________________________________________________________

#### If you enjoy Lightning, check out our other projects! ⚡

- [**Metrics**](https://github.com/Lightning-AI/metrics): Machine learning metrics for distributed, scalable PyTorch applications.

- [**Lite**](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html): enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.

- [**Flash**](https://github.com/Lightning-AI/lightning-flash): The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.

- [**Bolts**](https://github.com/Lightning-AI/lightning-bolts): Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.

- [**Lightning Transformers**](https://github.com/Lightning-AI/lightning-transformers): Flexible interface for high-performance research using SOTA Transformers leveraging Pytorch Lightning, Transformers, and Hydra.

cc @carmocca @akihironitta @borda

**Comment by weiji14** [comment]
Looks like sdist is available now since https://pypi.org/project/lightning/2022.7.18/#files, and there's a working PR at https://github.com/conda-forge/staged-recipes/pull/19715 to add `lightning` to conda-forge. WIll close this then.
