### ISSUE TITLE
WANDB integration causes failures to import on an unsupporting venv 

### ISSUE THREAD

**Issue by erezinman** [Lightning-AI/lightning#13659]
## 🐛 Bug

I get the following exception when importing  `pytorch_lightning` (python 3.9, latest version of PL):

```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/razor/anaconda3/envs/dev/lib/python3.9/site-packages/pytorch_lightning/__init__.py", line 30, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/home/razor/anaconda3/envs/dev/lib/python3.9/site-packages/pytorch_lightning/callbacks/__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.base import Callback
  File "/home/razor/anaconda3/envs/dev/lib/python3.9/site-packages/pytorch_lightning/callbacks/base.py", line 25, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "/home/razor/anaconda3/envs/dev/lib/python3.9/site-packages/pytorch_lightning/utilities/__init__.py", line 18, in <module>
    from pytorch_lightning.utilities.apply_func import move_data_to_device  # noqa: F401
  File "/home/razor/anaconda3/envs/dev/lib/python3.9/site-packages/pytorch_lightning/utilities/apply_func.py", line 29, in <module>
    from pytorch_lightning.utilities.imports import _compare_version, _TORCHTEXT_LEGACY
  File "/home/razor/anaconda3/envs/dev/lib/python3.9/site-packages/pytorch_lightning/utilities/imports.py", line 121, in <module>
    _WANDB_GREATER_EQUAL_0_10_22 = _WANDB_AVAILABLE and _compare_version("wandb", operator.ge, "0.10.22")
  File "/home/razor/anaconda3/envs/dev/lib/python3.9/site-packages/pytorch_lightning/utilities/imports.py", line 79, in _compare_version
    pkg_version = Version(pkg_resources.get_distribution(package).version)
  File "/home/razor/anaconda3/envs/dev/lib/python3.9/site-packages/pkg_resources/__init__.py", line 477, in get_distribution
    dist = get_provider(dist)
  File "/home/razor/anaconda3/envs/dev/lib/python3.9/site-packages/pkg_resources/__init__.py", line 353, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/home/razor/anaconda3/envs/dev/lib/python3.9/site-packages/pkg_resources/__init__.py", line 897, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/razor/anaconda3/envs/dev/lib/python3.9/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wandb' distribution was not found and is required by the application
```

I can not tell you how to reproduce this error, but I can describe it however I'll manage. What happens is that both `importlib.util.find_spec` and `importlib.import_module` return a not none spec/module. When I try to load `wandb` in the console, it succeeds but the module is empty (has no attributes other than the most basic dunder ones). I don't have the package installed in my conda environment, or even on the python distribution I'm using. I did use it once in some projects with python 3.6 (I currently use a venv of 3.9). When I use `importlib.util.find_spec` it points to an auto-generated empty folder named `wandb` somewhere in the old project I mentioned. When I erased that folder the problem ceased. 

To make a long story short, PLEASE, in the `imports` module, either catch 
`pkg_resources.DistributionNotFound` to return `False` in the `_compare_versions`, or - better yet - group these availability and version checks in `try: .. except: ...` blocks according to the checked import. For example:

```python
try:
     _WANDB_AVAILABLE = _package_available("wandb")
     _WANDB_GREATER_EQUAL_0_10_22 = _WANDB_AVAILABLE and _compare_version("wandb", operator.ge, "0.10.22")
     _WANDB_GREATER_EQUAL_0_12_10 = _WANDB_AVAILABLE and _compare_version("wandb", operator.ge, "0.12.10")
except:
     _WANDB_AVAILABLE = _WANDB_GREATER_EQUAL_0_10_22 = _WANDB_GREATER_EQUAL_0_12_10 = False
```

### Environment

* CUDA:
        - GPU:
                - NVIDIA GeForce GTX 1080 Ti
                - NVIDIA GeForce GTX 1080 Ti
                - NVIDIA GeForce GTX 1080 Ti
        - available:         True
        - version:           10.2
* Packages:
        - numpy:             1.23.1
        - pyTorch_debug:     False
        - pyTorch_version:   1.12.0+cu102
        - pytorch-lightning: 1.6.5
        - tqdm:              4.64.0
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.9.12
        - version:           #136~18.04.1-Ubuntu SMP Fri Jun 10 18:00:44 UTC 2022

cc @awaelchli @morganmcg1 @AyushExel @borisdayma @scottire @manangoel99

**Comment by awaelchli** [comment]
Hello @erezinman 
We are currently refactoring these imports to become lazy so that wandb and other optional dependencies only get imported when actually needed (#12786).
For wandb, we recently applied this in #13474. Could you try to install from master and try again?

**Comment by erezinman** [comment]
@awaelchli Alas, I cannot because I deleted and reinstalled a bunch of stuff. However, that sounds like the right way to go, so you can surely close this issue. Kudos!

**Comment by awaelchli** [comment]
Alright, that's great. Ping us again if this problem surfaces again.
