### ISSUE TITLE
Rich version check fails

### ISSUE THREAD

**Issue by senarvi** [Lightning-AI/lightning#13714]
## 🐛 Bug

`RichProgressBar` uses the [rich](https://github.com/Textualize/rich) library for text formatting. The module checks that the rich package is available and recent enough: https://github.com/Lightning-AI/lightning/blob/master/src/pytorch_lightning/callbacks/progress/rich_progress.py#L26

It uses `torchmetrics.utilities.imports._compare_version` for checking the version, which relies on [`pkg.__version__`](https://github.com/Lightning-AI/metrics/blob/master/src/torchmetrics/utilities/imports.py#L83).

However, rich package doesn't provide the `__version__` attribute. I'm not sure if it ever has provided. Based on some issues, it seems like there's no intention to provide it: https://github.com/Textualize/rich/issues/15

If rich is installed, Lightning cannot be imported.

### To Reproduce

Install the latest PyTorch Lightning and rich. Open Python interpreter and type `import pytorch_lightning`. The following error appears:

```
>>> import pytorch_lightning
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../pytorch-lightning/src/pytorch_lightning/__init__.py", line 34, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File ".../pytorch-lightning/src/pytorch_lightning/callbacks/__init__.py", line 25, in <module>
    from pytorch_lightning.callbacks.progress import ProgressBarBase, RichProgressBar, TQDMProgressBar
  File ".../pytorch-lightning/src/pytorch_lightning/callbacks/progress/__init__.py", line 22, in <module>
    from pytorch_lightning.callbacks.progress.rich_progress import RichProgressBar  # noqa: F401
  File ".../pytorch-lightning/src/pytorch_lightning/callbacks/progress/rich_progress.py", line 26, in <module>
    _RICH_AVAILABLE: bool = _package_available("rich") and _compare_version("rich", operator.ge, "10.2.2")
  File ".../lib/python3.9/site-packages/torchmetrics/utilities/imports.py", line 54, in _compare_version
    pkg_version = pkg.__version__  # type: ignore
AttributeError: module 'rich' has no attribute '__version__'
```

### Environment

- PyTorch Lightning Version (e.g., 1.5.0): 1.6.5
- PyTorch Version (e.g., 1.10): 1.12.0
- Python version (e.g., 3.9): 3.9.12
- rich version  12.5.1
- OS (e.g., Linux): Linux
- CUDA/cuDNN version: 11.3
- How you installed PyTorch (`conda`, `pip`, source): Using pip in a Conda environment

**Comment by senarvi** [comment]
Sorry, this bug only appears with an old version of torchmetrics. I was intentionally using an old version of torchmetrics (0.6.0) because of a performance issue. So the solution to this bug is to update torchmetrics. I'm closing this issue.
