### ISSUE TITLE
lightning run app app.py --cloud results in FileNotFoundError: [Errno 2] No such file or directory: '/content/venv/lib/python3.8/dist'

### ISSUE THREAD

**Issue by robert-s-lee** [Lightning-AI/lightning#13913]
## 🐛 Bug

`lightning run app app.py --cloud` results in 

```
FileNotFoundError: [Errno 2] No such file or directory: '/content/venv/lib/python3.8/dist'
```

### To Reproduce

- clone and run [ScratchPad, Notebook Manager for Teams](https://lightning.ai/app/hvUwbEG70B-ScratchPad%2C%20Notebook%20Manager%20for%20Teams)
- 
- go to Jupyter notebooks and open a terminal and run

```
lightning install app lightning/quick-start
```

- copy $HOME/.lightning/credentials.json from laptop

- run 
```
lightning run app app.py --cloud 
```

```
File "/content/venv/lib/python3.8/site-packages/lightning_app/utilities/packaging/lightning_utils.py", line 107, in _prepare_lightning_wheels_and_requirements
    tar_name = _copy_tar(_PROJECT_ROOT, root)
  File "/content/venv/lib/python3.8/site-packages/lightning_app/utilities/packaging/lightning_utils.py", line 73, in _copy_tar
    tar_files = os.listdir(dist_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/content/venv/lib/python3.8/dist'
```

that’s odd and looks like a regression on the packaging function (could you create another ticket please?). As a work around, can you set the env variable PACKAGE_LIGHTNING to 0 and try?

[Robert Lee](https://app.slack.com/team/U023VDYPB0Q)
  [< 1 minute ago](https://pytorch-lightning.slack.com/archives/CRBLFHY79/p1659031933279509?thread_ts=1658770802.365889&cid=CRBLFHY79)
the same with lightning run app app.py --cloud --env PACKAGE_LIGHTNING=0 and export PACKAGE_LIGHTNING=0
```
zeus@lightningwork-01g8v3jstyeh3xeb4a8p5kc5wz:/content/lightning-quick-start$ lightning run app app.py --cloud
Your Lightning App is starting. This won't take long.
The Lightning UI has successfully been downloaded!
INFO: Packaged Lightning with your application.
Traceback (most recent call last):
  File "/content/venv/bin/lightning", line 8, in <module>
    sys.exit(main())
  File "/content/venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/content/venv/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/content/venv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/content/venv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/content/venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/content/venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/content/venv/lib/python3.8/site-packages/lightning_app/cli/lightning_cli.py", line 125, in run_app
    _run_app(file, cloud, without_server, no_cache, name, blocking, open_ui, env)
  File "/content/venv/lib/python3.8/site-packages/lightning_app/cli/lightning_cli.py", line 82, in _run_app
    dispatch(
  File "/content/venv/lib/python3.8/site-packages/lightning_app/runners/runtime.py", line 63, in dispatch
    return runtime.dispatch(on_before_run=on_before_run, name=name, no_cache=no_cache)
  File "/content/venv/lib/python3.8/site-packages/lightning_app/runners/cloud.py", line 73, in dispatch
    cleanup_handle = _prepare_lightning_wheels_and_requirements(root)
  File "/content/venv/lib/python3.8/site-packages/lightning_app/utilities/packaging/lightning_utils.py", line 107, in _prepare_lightning_wheels_and_requirements
    tar_name = _copy_tar(_PROJECT_ROOT, root)
  File "/content/venv/lib/python3.8/site-packages/lightning_app/utilities/packaging/lightning_utils.py", line 73, in _copy_tar
    tar_files = os.listdir(dist_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/content/venv/lib/python3.8/dist'
zeus@lightningwork-01g8v3jstyeh3xeb4a8p5kc5wz:/content/lightning-quick-start$ echo $PACKAGE_LIGHTNING
0
```
 
```
lightning run app app.py --cloud --env PACKAGE_LIGHTNING=0
Your Lightning App is starting. This won't take long.
The Lightning UI has successfully been downloaded!
INFO: Packaged Lightning with your application.
Traceback (most recent call last):
  File "/content/venv/bin/lightning", line 8, in <module>
    sys.exit(main())
  File "/content/venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/content/venv/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/content/venv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/content/venv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/content/venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/content/venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/content/venv/lib/python3.8/site-packages/lightning_app/cli/lightning_cli.py", line 125, in run_app
    _run_app(file, cloud, without_server, no_cache, name, blocking, open_ui, env)
  File "/content/venv/lib/python3.8/site-packages/lightning_app/cli/lightning_cli.py", line 82, in _run_app
    dispatch(
  File "/content/venv/lib/python3.8/site-packages/lightning_app/runners/runtime.py", line 63, in dispatch
    return runtime.dispatch(on_before_run=on_before_run, name=name, no_cache=no_cache)
  File "/content/venv/lib/python3.8/site-packages/lightning_app/runners/cloud.py", line 73, in dispatch
    cleanup_handle = _prepare_lightning_wheels_and_requirements(root)
  File "/content/venv/lib/python3.8/site-packages/lightning_app/utilities/packaging/lightning_utils.py", line 107, in _prepare_lightning_wheels_and_requirements
    tar_name = _copy_tar(_PROJECT_ROOT, root)
  File "/content/venv/lib/python3.8/site-packages/lightning_app/utilities/packaging/lightning_utils.py", line 73, in _copy_tar
    tar_files = os.listdir(dist_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/content/venv/lib/python3.8/dist'
### Expected behavior
```

### Environment

```
zeus@lightningwork-01g8v3jstyeh3xeb4a8p5kc5wz:~$ python collect_env_details.py* CUDA:
        - GPU:
        - available:         False
        - version:           10.2
* Packages:
        - lightning:         2022.7.18
        - lightning_app:     0.5.2
        - numpy:             1.23.1
        - pyTorch_debug:     False
        - pyTorch_version:   1.9.0+cu102
        - pytorch-lightning: 1.6.3
        - tqdm:              4.64.0
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.8.10
        - version:           #1 SMP Thu May 26 12:49:47 UTC 2022
```

**Comment by rhjohnstone** [comment]
I'm also facing the same issue, but I'm running from my local machine
```lightning run app app.py --cloud```
gives the error
```FileNotFoundError: [Errno 2] No such file or directory: '/opt/miniconda3/envs/lightning/lib/python3.8/dist'```

My whole `app.py` is
```
import lightning as L
from lightning_app.frontend import StreamlitFrontend
from lit_slack import SlackMessenger
import streamlit as st


def streamlit_app(lightning_app_state):
    message = st.text_input("Message")
    if st.button("Send Slack message to #bot_lightning"):
        lightning_app_state.message = message
        lightning_app_state.send_message = True


class LitStreamlit(L.LightningFlow):
    def __init__(self):
        super().__init__()
        self.send_message = False
        self.message = "Starting app..."

    def configure_layout(self):
        return StreamlitFrontend(render_fn=streamlit_app)


class SlackApp(L.LightningFlow):
    def __init__(self):
        super().__init__()
        self.lit_streamlit = LitStreamlit()
        self.slack_messenger = SlackMessenger(
            token=LONG_TOKEN, 
            channel_id=SHORTER_TOKEN,
        )

    def run(self):
        self.lit_streamlit.run()
        if self.lit_streamlit.send_message:
            self.slack_messenger.send_message(self.lit_streamlit.message)
            self.lit_streamlit.send_message = False

    def configure_layout(self):
        tab1 = {"name": "Message", "content": self.lit_streamlit}
        return tab1
        
app = L.LightningApp(SlackApp())
```
and I've installed the Slack component.

This was working earlier this week.

On a Mac in a clean Miniconda environment with Python 3.8.

**Comment by robert-s-lee** [comment]
@rhjohnstone tried running in the cloud on a new `conda` environment with success today.  Can you try again when you get a chance?

```
import lightning as L
class Work(L.LightningWork):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
    def run(self):
        print("Hello world from work")
class Flow(L.LightningFlow):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.work = Work()
    def run(self):
        self.work.run()
if __name__ == "__main__":
    app = L.LightningApp(Flow())
```

```
(obscure-data) base> lightning run app 02_app.py --cloud
Your Lightning App is starting. This won't take long.
The name of the app is: beautiful-hamilton-8529
upload ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.0%
Application is ready in the cloud
(obscure-data) base>
```

**Comment by rlizzo** [comment]
Hi @robert-s-lee I've got a PR up which addresses this (see #14025). It will be scheduled as part of the next release

**Comment by rhjohnstone** [comment]
Hi @robert-s-lee and @rlizzo, the temporary solution of removing `.git` did indeed work. Surprising though, as my structure is
```
lightning-apps
├── .git
├── hpo
│   ├── app.py
├── slack
│   ├── app.py
```
so I assumed the `.git` would be safe when running the app from inside the child directories.

Anyway thanks for the help and looking forward to the next release!
