### ISSUE TITLE
Cannot start lightning app at cloud on macOS

### ISSUE THREAD

**Issue by tshu-w** [Lightning-AI/lightning#13942]
## 🐛 Bug

Following the [LIGHTNING APPS IN 15 MINUTES](https://lightning.ai/lightning-docs/get_started/lightning_apps_intro.html) and run the app in the cloud command got FileNotFoundError on macOS:
```
FileNotFoundError: [Errno 2] No such file or directory: '/opt/homebrew/Caskroom/miniconda/base/envs/lightning/lib/python3.9/dist'
```

### To Reproduce

Following the [LIGHTNING APPS IN 15 MINUTES](https://lightning.ai/lightning-docs/get_started/lightning_apps_intro.html) on ARM macOS with conda env.

```console
λ conda create -n lightning python=3.9
λ conda activate lightning
λ pip install lightning
λ lightning install app lightning/quick-start
λ cd lightning-quick-start
λ lightning run app app.py
~/Developer/lightning-app/lightning-quick-start HEAD (716e903) via 🐍 v3.9.12 took 4m13s
lightning λ lightning run app app.py --cloud
Your Lightning App is starting. This won't take long.
The Lightning UI has successfully been downloaded!
INFO: Packaged Lightning with your application.
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/lightning/bin/lightning", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/Caskroom/miniconda/base/envs/lightning/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/lightning/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/lightning/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/Caskroom/miniconda/base/envs/lightning/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/Caskroom/miniconda/base/envs/lightning/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/lightning/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/lightning/lib/python3.9/site-packages/lightning_app/cli/lightning_cli.py", line 125, in run_app
    _run_app(file, cloud, without_server, no_cache, name, blocking, open_ui, env)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/lightning/lib/python3.9/site-packages/lightning_app/cli/lightning_cli.py", line 82, in _run_app
    dispatch(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/lightning/lib/python3.9/site-packages/lightning_app/runners/runtime.py", line 63, in dispatch
    return runtime.dispatch(on_before_run=on_before_run, name=name, no_cache=no_cache)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/lightning/lib/python3.9/site-packages/lightning_app/runners/cloud.py", line 73, in dispatch
    cleanup_handle = _prepare_lightning_wheels_and_requirements(root)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/lightning/lib/python3.9/site-packages/lightning_app/utilities/packaging/lightning_utils.py", line 107, in _prepare_lightning_wheels_and_requirements
    tar_name = _copy_tar(_PROJECT_ROOT, root)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/lightning/lib/python3.9/site-packages/lightning_app/utilities/packaging/lightning_utils.py", line 73, in _copy_tar
    tar_files = os.listdir(dist_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/homebrew/Caskroom/miniconda/base/envs/lightning/lib/python3.9/dist'
```

### Expected behavior

lightning run the app in the cloud correctly.

### Environment

* CUDA:
	- GPU:
	- available:         False
	- version:           None
* Packages:
	- lightning:         2022.7.18
	- lightning_app:     0.5.3
	- numpy:             1.23.1
	- pyTorch_debug:     False
	- pyTorch_version:   1.12.0
	- pytorch-lightning: 1.6.5
	- tqdm:              4.64.0
* System:
	- OS:                Darwin
	- architecture:
		- 64bit
		-
	- processor:         arm
	- python:            3.9.12
	- version:           Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:22 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T6000

**Comment by lantiga** [comment]
Hi @tshu-w apologies.
We are going to issue a fix with the upcoming release, the issue the repo name starting with `lightning` (as checked from `.git`).
As an immediate workaround, can you try removing the .git directory from within `lightning-quick-start` and trying again?

/cc @hhsecond

**Comment by rlizzo** [comment]
Thanks for the report @tshu-w! I'll be making a fix for this in the next day or two :)

**Comment by tshu-w** [comment]
> As an immediate workaround, can you try removing the .git directory from within `lightning-quick-start` and trying again?

Yes, this workaround works.

**Comment by rlizzo** [comment]
Hi @tshu-w I've got a PR up which addresses this (see #14025). It will be scheduled as part of the next release.
