### ISSUE TITLE
cannot generate component from template

### ISSUE THREAD

**Issue by tshu-w** [Lightning-AI/lightning#13943]
## 🐛 Bug

When I generate a component from template with `lightning init component your-component-name`, I got `FileNotFoundError`

### To Reproduce

```console
λ conda create -n lightning python=3.9
λ conda activate lightning
λ pip install lightning
lightning λ lightning init component your-component-name
INFO: laying out component template at /Users/wangtianshu/Developer/lightning-app/your-component-name
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/lightning/bin/lightning", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/Caskroom/miniconda/base/envs/lightning/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/lightning/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/lightning/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/Caskroom/miniconda/base/envs/lightning/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/Caskroom/miniconda/base/envs/lightning/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/lightning/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/lightning/lib/python3.9/site-packages/lightning_app/cli/lightning_cli.py", line 260, in init_component
    cmd_init.component(name)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/lightning/lib/python3.9/site-packages/lightning_app/cli/cmd_init.py", line 113, in component
    new_resource_name, name_for_files = _make_resource(resource_dir="component-template", resource_name=component_name)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/lightning/lib/python3.9/site-packages/lightning_app/cli/cmd_init.py", line 42, in _make_resource
    os.rename(os.path.join(new_resource_name, "placeholdername"), os.path.join(new_resource_name, name_for_files))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/wangtianshu/Developer/lightning-app/your-component-name/placeholdername' -> '/Users/wangtianshu/Developer/lightning-app/your-component-name/your_component_name'
```

### Expected behavior

the command runs correctly.

### Environment

* CUDA:
	- GPU:
	- available:         False
	- version:           None
* Packages:
	- lightning:         2022.7.18
	- lightning_app:     0.5.3
	- numpy:             1.22.4
	- pyTorch_debug:     False
	- pyTorch_version:   1.11.0
	- pytorch-lightning: 1.6.5
	- tqdm:              4.64.0
* System:
	- OS:                Darwin
	- architecture:
		- 64bit
		-
	- processor:         arm
	- python:            3.9.12
	- version:           Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:22 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T6000

### Additional context

I am participating in Storm Chaser Task, but the experience is not very good. I've experienced three issues so far https://github.com/Lightning-AI/lightning/issues/13943 https://github.com/Lightning-AI/lightning/issues/13942 and 
> the link to [Lightning Sweeper](https://lightning.ai/app/8FOWcOVsdf-Lightning%20Sweeper) seems wrong and I got error when trying to run https://lightning.ai/app/vIDPvY3YAA-Unsplash%20Image%20Search

**Comment by tshu-w** [comment]
@manskx Yes, it solved.
