### ISSUE TITLE
DDP Notebook/Fork not working with PyTorch 1.12.0

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/lightning#14043]
## 🐛 Bug

`strategy="ddp_notebook"` works with PyTorch 1.12.1 but NOT with PyTorch 1.12.0. 
This issue exists solely for visibility and possible regressions in the future. 

TLDR: Use the latest PyTorch when setting `strategy="ddp_notebook"` 

### To Reproduce

```py
import os

import torch
from torch.utils.data import DataLoader, Dataset

from pytorch_lightning import LightningModule, Trainer
from pytorch_lightning import seed_everything
from pytorch_lightning.strategies import DDPSpawnStrategy

seed_everything(1)

print(torch.__version__)


class RandomDataset(Dataset):
    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len


class BoringModel(LightningModule):
    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)

    def forward(self, x):
        return self.layer(x)

    def training_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("train_loss", loss)
        return {"loss": loss}

    def validation_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("valid_loss", loss)

    def test_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("test_loss", loss)

    def configure_optimizers(self):
        return torch.optim.SGD(self.layer.parameters(), lr=0.1)


def run():
    train_data = DataLoader(RandomDataset(32, 64), batch_size=2, num_workers=2)
    val_data = DataLoader(RandomDataset(32, 64), batch_size=2, num_workers=2)
    

    model = BoringModel()
    trainer = Trainer(
        default_root_dir=os.getcwd(),
        limit_train_batches=1,
        limit_val_batches=1,
        limit_test_batches=1,
        num_sanity_val_steps=0,
        max_epochs=1,
        enable_model_summary=False,
        strategy="ddp_notebook_find_unused_parameters_false",
        devices="auto",
        accelerator="auto",
        
    )
    print(trainer.strategy._launcher._start_method)
    print(trainer.strategy)
    print(trainer.accelerator)
    trainer.fit(model, train_dataloaders=train_data, val_dataloaders=val_data)


run()
```

Error:

```
ProcessRaisedException                    Traceback (most recent call last)
Input In [2], in <cell line: 1>()
----> 1 run()

Input In [1], in run()
     72 print(trainer.strategy)
     73 print(trainer.accelerator)
---> 74 trainer.fit(model, train_dataloaders=train_data, val_dataloaders=val_data)

File ~/repositories/lightning/src/pytorch_lightning/trainer/trainer.py:702, in Trainer.fit(self, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path)
    700     raise TypeError(f"`Trainer.fit()` requires a `LightningModule`, got: {model.__class__.__qualname__}")
    701 self.strategy.model = model
--> 702 self._call_and_handle_interrupt(
    703     self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
    704 )

File ~/repositories/lightning/src/pytorch_lightning/trainer/trainer.py:652, in Trainer._call_and_handle_interrupt(self, trainer_fn, *args, **kwargs)
    650 try:
    651     if self.strategy.launcher is not None:
--> 652         return self.strategy.launcher.launch(trainer_fn, *args, trainer=self, **kwargs)
    653     else:
    654         return trainer_fn(*args, **kwargs)

File ~/repositories/lightning/src/pytorch_lightning/strategies/launchers/multiprocessing.py:103, in _MultiProcessingLauncher.launch(self, function, trainer, *args, **kwargs)
    100 else:
    101     process_args = [trainer, function, args, kwargs, return_queue]
--> 103 mp.start_processes(
    104     self._wrapping_function,
    105     args=process_args,
    106     nprocs=self._strategy.num_processes,
    107     start_method=self._start_method,
    108 )
    109 worker_output = return_queue.get()
    110 if trainer is None:

File ~/anaconda3/envs/lightning/lib/python3.9/site-packages/torch/multiprocessing/spawn.py:198, in start_processes(fn, args, nprocs, join, daemon, start_method)
    195     return context
    197 # Loop on join until it returns True or raises an exception.
--> 198 while not context.join():
    199     pass

File ~/anaconda3/envs/lightning/lib/python3.9/site-packages/torch/multiprocessing/spawn.py:160, in ProcessContext.join(self, timeout)
    158 msg = "\n\n-- Process %d terminated with the following error:\n" % error_index
    159 msg += original_trace
--> 160 raise ProcessRaisedException(msg, error_index, failed_process.pid)

ProcessRaisedException: 

-- Process 4 terminated with the following error:
Traceback (most recent call last):
  File "/home/adrian/anaconda3/envs/lightning/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/adrian/repositories/lightning/src/pytorch_lightning/strategies/launchers/multiprocessing.py", line 129, in _wrapping_function
    results = function(*args, **kwargs)
  File "/home/adrian/repositories/lightning/src/pytorch_lightning/trainer/trainer.py", line 743, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/adrian/repositories/lightning/src/pytorch_lightning/trainer/trainer.py", line 1119, in _run
    self.strategy.setup_environment()
  File "/home/adrian/repositories/lightning/src/pytorch_lightning/strategies/strategy.py", line 130, in setup_environment
    self.accelerator.setup_environment(self.root_device)
  File "/home/adrian/repositories/lightning/src/pytorch_lightning/accelerators/cuda.py", line 43, in setup_environment
    torch.cuda.set_device(root_device)
  File "/home/adrian/anaconda3/envs/lightning/lib/python3.9/site-packages/torch/cuda/__init__.py", line 314, in set_device
    torch._C._cuda_setDevice(device)
  File "/home/adrian/anaconda3/envs/lightning/lib/python3.9/site-packages/torch/cuda/__init__.py", line 207, in _lazy_init
    raise RuntimeError(
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method

```

This error occurs when a CUDA context is opened before launching processes, i.e. before entering trainer.fit().

### Expected behavior

No error. 

### Environment

- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
- PyTorch Lightning Version (e.g., 1.5.0): 1.8.0dev
- Lightning App Version (e.g., 0.5.2): -
- PyTorch Version (e.g., 1.10): 1.12.0 
- Python version (e.g., 3.9): 3.10
- OS (e.g., Linux): Linux, MaxOS
- CUDA/cuDNN version: cuda11.3
- GPU models and configuration: -
- How you installed PyTorch (`conda`, `pip`, source): conda
- If compiling from source, the output of `torch.__config__.show()`: -
- Running environment of LightningApp (e.g. local, cloud): -
- Any other relevant information: -

**Comment by awaelchli** [comment]
As written in the description, the issue is solved with PyTorch 1.12.1, and I'm only posting for visibility of this observation. If the issue occurs again in a future PyTorch version, we can reopen.

**Comment by awaelchli** [comment]
cc @Borda @carmocca
