### ISSUE TITLE
Training on N>1 GPUs throws AttributeError: Can't pickle local object 'Settings._validator_factory.<locals>.helper'

### ISSUE THREAD

**Issue by RylanSchaeffer** [Lightning-AI/lightning#14120]
## 🐛 Bug

When training on 1 CPU or 1 GPU, my code has no problem. When I try using 2 GPUs, my Trainer throws the following error: `AttributeError: Can't pickle local object 'Settings._validator_factory.<locals>.helper'`

### To Reproduce

I have a custom dataset, so I unfortunately can't share the dataset code. The Lightning code is very straightforward:

```
trainer = pl.Trainer(
    max_epochs=wandb_config.n_epochs,
    default_root_dir=checkpoint_dir,
    accelerator='gpu' if torch.cuda.is_available() else None,
    devices=torch.cuda.device_count() if torch.cuda.is_available() else None,
)

trainer.fit(
    model=system,
    train_dataloaders=train_trajectory_dataloader,
    val_dataloaders=val_trajectory_dataloader,
)
```

I receive the following stack trace:

```
Traceback (most recent call last):
  File "train.py", line 261, in <module>
    val_dataloaders=val_trajectory_dataloader,
  File "python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 701, in fit
    self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
  File "python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 652, in _call_and_handle_interrupt
    return self.strategy.launcher.launch(trainer_fn, *args, trainer=self, **kwargs)
  File "python3.7/site-packages/pytorch_lightning/strategies/launchers/multiprocessing.py", line 107, in launch
    start_method=self._start_method,
  File "python3.7/site-packages/torch/multiprocessing/spawn.py", line 189, in start_processes
    process.start()
  File "python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "lib/python3.7/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "python3.7/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "python3.7/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "python3.7/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'Settings._validator_factory.<locals>.helper'
```

### Expected behavior

I expect my trainer to run without errors, as it does on 1 CPU or 1 GPU.

### Environment

```
$ python collect_env_details.py
* CUDA:
        - GPU:
                - GeForce GTX TITAN X
                - GeForce GTX TITAN X
        - available:         True
        - version:           10.2
* Packages:
        - lightning:         None
        - lightning_app:     None
        - numpy:             1.21.6
        - pyTorch_debug:     False
        - pyTorch_version:   1.12.1+cu102
        - tqdm:              4.64.0
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - 
        - processor:         x86_64
        - python:            3.7.4
        - version:           #1 SMP Wed Aug 7 18:08:02 UTC 2019
```

**Comment by RylanSchaeffer** [comment]
If it matters, I'm trying to do this on a SLURM cluster.

**Comment by RylanSchaeffer** [comment]
When I try pickling the system, I get the same error:

```
with open('tmp.pkl', 'rw') as fp:
    pickle.dump(system, fp)
```

**Comment by RylanSchaeffer** [comment]
I can share the system class, in case that helps identify the problem:

```
class SSLGridCellSystem(pl.LightningModule):

    def __init__(self,
                 wandb_config: wandb_sdk.wandb_config.Config,
                 ):
        super().__init__()
        self.wandb_config = wandb_config

        if self.wandb_config.main_loss == 'similarity_matching':
            self.main_loss_fn = compute_similarity_matching_loss
        elif wandb_config.main_loss == 'will_dorrell_like':
            self.main_loss_fn = compute_will_dorrell_like_loss
        else:
            raise NotImplementedError

        if self.wandb_config.rnn_type == 'RNN':
            self.rnn = torch.nn.RNN(
                nonlinearity=wandb_config.activation,
                input_size=2,
                hidden_size=wandb_config.n_hidden_units,
                num_layers=1,
                batch_first=True)
        else:
            raise NotImplementedError
        self.initial_position_layer = torch.nn.Linear(
            in_features=2,
            out_features=wandb_config.n_hidden_units)

        # TODO: Check that height and width are in the correct order.
        self.ratemaps_coords_range = (
            (-self.wandb_config.box_height_in_m / 2., self.wandb_config.box_height_in_m / 2.),
            (-self.wandb_config.box_width_in_m / 2., self.wandb_config.box_width_in_m / 2.))

        self.log_step = 1

    def forward(self,
                initial_positions: torch.Tensor,
                velocities: torch.Tensor,
                ) -> torch.Tensor:

        # Initial positions has shape: (batch size, 1, 2)
        # Remove the 1st axis to work with the network.
        # initial_positions = torch.squeeze(initial_positions)

        # Shape: (batch size, number of layers i.e. 1, n_hidden_units)
        # activations_per_step = self.initial_position_layer(initial_positions)

        activations = []
        activations_per_step = None
        for step_idx in range(velocities.shape[1]):

            # Shape: (batch size, 1, n_hidden_units)
            activations_per_step, hx = self.rnn(
                velocities[:, step_idx, np.newaxis, :],
                activations_per_step)

            if self.wandb_config.normalize_activations:
                # Shape: (batch size, 1, n_hidden_units)
                activations_per_step = activations_per_step / torch.linalg.norm(
                    activations_per_step,
                    dim=2,
                    keepdim=True)

            activations.append(activations_per_step)

            # Even though the RNN takes inputs with batch dimension first,
            # for some reason, if h0 is provided, h0 needs to have shape
            # (number of layers, batch, n_hidden units), so we need to transpose.
            # Shape: (number of layers, batch size, n_hidden_units)
            activations_per_step = torch.transpose(activations_per_step, 0, 1)

        # Exclude the first trajectory element since that was the initial position.
        # Shape: (batch size, trajectory length, n_hidden_units)
        activations = torch.cat(activations, dim=1)
        return activations

    def training_step(self, batch, batch_idx):
        # Shape: (batch size, 1, 2)
        initial_positions = batch['initial_positions']
        # Shape: (batch size, trajectory length, 2)
        positions = batch['positions']
        # Shape: (batch size, trajectory length, 2)
        velocities = batch['velocities']

        rnn_activations = self.forward(
            initial_positions=initial_positions,
            velocities=velocities)

        main_loss = self.main_loss_fn(
            positions=positions,
            velocities=velocities,
            activations=rnn_activations,
            code_kernel_type=self.wandb_config.code_kernel_type,
            code_kernel_scale=self.wandb_config.code_kernel_scale,
            space_kernel_type=self.wandb_config.space_kernel_type,
            space_kernel_scale=self.wandb_config.space_kernel_scale,
            compare_across_batch_dim=self.wandb_config.compare_across_batch_dim)

        unit_norm_over_population_loss = compute_unit_norm_over_population_loss(
            activations=rnn_activations)

        unit_norm_over_time_loss = compute_unit_norm_over_time_loss(
            activations=rnn_activations)

        loss = main_loss \
               + self.wandb_config.unit_norm_over_population_loss_prefactor * unit_norm_over_population_loss \
               + self.wandb_config.unit_norm_over_time_loss_prefactor * unit_norm_over_time_loss

        if (batch_idx % 50) == 0:
            wandb.log({
                'total_loss': loss.item(),
                f'{self.wandb_config.main_loss}_loss': main_loss.item(),
                'unit_norm_over_population_loss': unit_norm_over_population_loss.item(),
                'unit_norm_over_time_loss': unit_norm_over_time_loss.item(),
            }, step=self.log_step)
            self.log_step += 1

        return loss

    def validation_step(self, batch, batch_idx):

        # Shape: (batch size, 1, 2)
        initial_positions = batch['initial_positions']
        # Shape: (batch size, trajectory length, 2)
        positions = batch['positions']
        # Shape: (batch size, trajectory length, 2)
        velocities = batch['velocities']

        rnn_activations = self.forward(
            initial_positions=initial_positions,
            velocities=velocities)

        ratemaps = compute_ratemaps(
            positions=positions.cpu().detach().numpy(),
            activations=rnn_activations.cpu().detach().numpy(),
            coords_range=self.ratemaps_coords_range)

        plot_ratemaps(ratemaps=ratemaps,
                      log_step=self.log_step)

    def configure_optimizers(self):
        if self.wandb_config.optimizer == 'adam':
            optimizer = torch.optim.Adam(
                self.parameters(),
                lr=self.wandb_config.learning_rate,
                weight_decay=self.wandb_config.weight_decay)
        # elif self.wandb_config.optimizer == 'shampoo':
        #     optimizer = torch_optimizer.Shampoo(
        #         self.parameters(),
        #         lr=self.wandb_config.learning_rate,
        #         weight_decay=self.wandb_config.weight_decay)
        else:
            raise NotImplementedError
        return optimizer
```

**Comment by RylanSchaeffer** [comment]
Ha! The problem is with the W&B config, not PyTorch lightning! Closing this issue.

**Comment by akihironitta** [comment]
> ```
> AttributeError: Can't pickle local object 'Settings._validator_factory.<locals>.helper'
> ```

@RylanSchaeffer Yes, as the error suggests (and you've noticed already), everything needs to be picklable when using ddp spawn. Please also note that this picklability limitation won't apply if you use ddp. See the documentation here: https://pytorch-lightning.readthedocs.io/en/stable/accelerators/gpu_intermediate.html?highlight=picklable#comparison-of-ddp-variants-and-tradeoffs

**Comment by robust1997** [comment]
Hi, I met the same bug. Can you tell me how to fix the problem with w&b config? thanks:)
