### ISSUE TITLE
Distributed TPU Trainer breaks on Google Cloud Platform

### ISSUE THREAD

**Issue by adamcatto** [Lightning-AI/lightning#14391]
## 🐛 Bug

I am training an image self-supervised model on the GCP TPU v3-8. The trainer makes it through 13 batches of the first epoch (each batch has 128 96x96 grayscale images per TPU core and takes ~70 seconds to compute) and proceeds to break. I ran the same code on Colab single TPU and it worked without a problem – I also implemented my model using native torch_xla distributed training and it worked without a hitch on the same GCP environment. This makes me wonder if the issue is with how PyTorch-Lightning does multiprocess spawning on TPU?

### Environment

- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow): Trainer
- PyTorch Lightning Version (e.g., 1.5.0): 1.7.0
- Lightning App Version (e.g., 0.5.2):
- PyTorch Version (e.g., 1.10): 1.11
- Python version (e.g., 3.9): 3.8.5
- OS (e.g., Linux): Linux
- CUDA/cuDNN version:
- GPU models and configuration:
- How you installed PyTorch (`conda`, `pip`, source):
- If compiling from source, the output of `torch.__config__.show()`:
- Running environment of LightningApp (e.g. local, cloud):
- Any other relevant information:

### Additional context

I am posting the full traceback for better reference:

```py
> 2022-08-19 18:50:36.070503: E tensorflow/core/framework/op_kernel.cc:1676] OpKernel ('op: "TPURoundRobin" device_type: "CPU"') for unknown op: TPURoundRobin
2022-08-19 18:50:36.071270: E tensorflow/core/framework/op_kernel.cc:1676] OpKernel ('op: "TpuHandleToProtoKey" device_type: "CPU"') for unknown op: TpuHandleToProtoKey
/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py:122: PkgResourcesDeprecationWarning: 0.23ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py:122: PkgResourcesDeprecationWarning: 0.1.36ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
/home/adam_catto_mssm_edu/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py:450: LightningDeprecationWarning: Setting `Trainer(tpu_cores=8)` is deprecated in v1.7 and will be removed in v2.0. Please use `Trainer(accelerator='tpu', devices=8)` instead.
  rank_zero_deprecation(
GPU available: False, used: False
TPU available: True, using: 8 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
https://symbolize.stripped_domain/r/?trace=7f3e760aaa10,7f3e75cd90bf&map= 
*** SIGTERM received by PID 5410 (TID 5410) on cpu 46 from PID 3828; stack trace: ***
PC: @     0x7f3e760aaa10  (unknown)  (unknown)
    @     0x7f3d6bb7bcda        992  (unknown)
    @     0x7f3e75cd90c0  (unknown)  (unknown)
https://symbolize.stripped_domain/r/?trace=7f3e760aaa10,7f3d6bb7bcd9,7f3e75cd90bf&map=50c831e765011c7eb7163b7f3cb5c4b6:7f3d5d3d1000-7f3d6bee9f00 
E0819 18:51:06.336371    5410 coredump_hook.cc:320] RAW: Remote crash gathering disabled for SIGTERM.
E0819 18:51:06.341113    5410 process_state.cc:771] RAW: Raising signal 15 with default behavior
2022-08-19 18:51:06.443264: E tensorflow/core/framework/op_kernel.cc:1676] OpKernel ('op: "TPURoundRobin" device_type: "CPU"') for unknown op: TPURoundRobin
2022-08-19 18:51:06.443345: E tensorflow/core/framework/op_kernel.cc:1676] OpKernel ('op: "TpuHandleToProtoKey" device_type: "CPU"') for unknown op: TpuHandleToProtoKey
2022-08-19 18:51:24.066424: E tensorflow/core/framework/op_kernel.cc:1676] OpKernel ('op: "TPURoundRobin" device_type: "CPU"') for unknown op: TPURoundRobin
2022-08-19 18:51:24.066488: E tensorflow/core/framework/op_kernel.cc:1676] OpKernel ('op: "TpuHandleToProtoKey" device_type: "CPU"') for unknown op: TpuHandleToProtoKey
2022-08-19 18:51:25.003574: E tensorflow/core/framework/op_kernel.cc:1676] OpKernel ('op: "TPURoundRobin" device_type: "CPU"') for unknown op: TPURoundRobin
2022-08-19 18:51:25.003640: E tensorflow/core/framework/op_kernel.cc:1676] OpKernel ('op: "TpuHandleToProtoKey" device_type: "CPU"') for unknown op: TpuHandleToProtoKey
2022-08-19 18:51:29.867407: E tensorflow/core/framework/op_kernel.cc:1676] OpKernel ('op: "TPURoundRobin" device_type: "CPU"') for unknown op: TPURoundRobin
2022-08-19 18:51:29.867473: E tensorflow/core/framework/op_kernel.cc:1676] OpKernel ('op: "TpuHandleToProtoKey" device_type: "CPU"') for unknown op: TpuHandleToProtoKey
2022-08-19 18:51:31.852158: E tensorflow/core/framework/op_kernel.cc:1676] OpKernel ('op: "TPURoundRobin" device_type: "CPU"') for unknown op: TPURoundRobin
2022-08-19 18:51:31.852220: E tensorflow/core/framework/op_kernel.cc:1676] OpKernel ('op: "TpuHandleToProtoKey" device_type: "CPU"') for unknown op: TpuHandleToProtoKey
2022-08-19 18:51:31.983662: E tensorflow/core/framework/op_kernel.cc:1676] OpKernel ('op: "TPURoundRobin" device_type: "CPU"') for unknown op: TPURoundRobin
2022-08-19 18:51:31.983726: E tensorflow/core/framework/op_kernel.cc:1676] OpKernel ('op: "TpuHandleToProtoKey" device_type: "CPU"') for unknown op: TpuHandleToProtoKey
2022-08-19 18:51:32.151776: E tensorflow/core/framework/op_kernel.cc:1676] OpKernel ('op: "TPURoundRobin" device_type: "CPU"') for unknown op: TPURoundRobin
2022-08-19 18:51:32.151841: E tensorflow/core/framework/op_kernel.cc:1676] OpKernel ('op: "TpuHandleToProtoKey" device_type: "CPU"') for unknown op: TpuHandleToProtoKey
2022-08-19 18:51:32.671996: E tensorflow/core/framework/op_kernel.cc:1676] OpKernel ('op: "TPURoundRobin" device_type: "CPU"') for unknown op: TPURoundRobin
2022-08-19 18:51:32.672059: E tensorflow/core/framework/op_kernel.cc:1676] OpKernel ('op: "TpuHandleToProtoKey" device_type: "CPU"') for unknown op: TpuHandleToProtoKey

  | Name             | Type       | Params
------------------------------------------------
0 | backbone         | ResNet     | 23.5 M
1 | online_encoder   | NetWrapper | 33.0 M
2 | online_predictor | MLP        | 2.1 M 
3 | target_encoder   | NetWrapper | 33.0 M
------------------------------------------------
21.0 M    Trainable params
23.5 M    Non-trainable params
44.5 M    Total params
178.069   Total estimated model params size (MB)
Sanity Checking DataLoader 0: 100%|███████████████| 2/2 [00:34<00:00, 17.31s/it]/home/adam_catto_mssm_edu/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/logger_connector/result.py:536: PossibleUserWarning: It is recommended to use `self.log('val_loss', ..., sync_dist=True)` when logging on epoch level in distributed setting to accumulate the metric across devices.
  warning_cache.warn(
Epoch 0:   2%|▏        | 13/591 [15:07<11:12:49, 69.84s/it, loss=1.87, v_num=13]2022-08-19 19:12:17.857636: E tensorflow/core/tpu/kernels/tpu_compilation_cache_external.cc:113] Computation requires more parameters (3496) than supported (limit 3305).
2022-08-19 19:12:17.857731: F tensorflow/core/tpu/kernels/tpu_program_group.cc:86] Check failed: xla_tpu_programs.size() > 0 (0 vs. 0)
https://symbolize.stripped_domain/r/?trace=7f3e75cd903b,7f3e75cd90bf,7f3d7ab78bcf,7f3d751ed922,7f3d751abebd,7f3d751fbdb0,7f3d751fb8ae,7f3d7105ded3,7f3d7669f1b8,7f3d7a62a8a0,7f3d7a62c633,7f3d7ab41cb1,7f3d7ab414e0,7f3d7ab298cb,7f3e75c7b608&map=b5462df73b9bb298b2bca5d2f02176eed80a2e90:7f3d6c719000-7f3d7da0ee30 
*** SIGABRT received by PID 5414 (TID 6198) on cpu 24 from PID 5414; stack trace: ***
PC: @     0x7f3e75cd903b  (unknown)  raise
    @     0x7f3d6bb7bcda        992  (unknown)
    @     0x7f3e75cd90c0       3968  (unknown)
    @     0x7f3d7ab78bd0         16  tensorflow::internal::LogMessageFatal::~LogMessageFatal()
    @     0x7f3d751ed923        592  tensorflow::tpu::TpuProgramGroup::Initialize()
    @     0x7f3d751abebe       1488  tensorflow::tpu::TpuCompilationCacheExternal::InitializeEntry()
    @     0x7f3d751fbdb1        800  tensorflow::tpu::TpuCompilationCacheInterface::CompileIfKeyAbsentHelper()
    @     0x7f3d751fb8af        496  tensorflow::tpu::TpuCompilationCacheInterface::CompileIfKeyAbsent()
    @     0x7f3d7105ded4        912  tensorflow::XRTCompileOp::Compute()
    @     0x7f3d7669f1b9        432  tensorflow::XlaDevice::Compute()
    @     0x7f3d7a62a8a1       2128  tensorflow::(anonymous namespace)::ExecutorState<>::Process()
    @     0x7f3d7a62c634         48  std::_Function_handler<>::_M_invoke()
    @     0x7f3d7ab41cb2        128  Eigen::ThreadPoolTempl<>::WorkerLoop()
    @     0x7f3d7ab414e1         48  tensorflow::thread::EigenEnvironment::CreateThread()::{lambda()#1}::operator()()
    @     0x7f3d7ab298cc         80  tensorflow::(anonymous namespace)::PThread::ThreadFn()
    @     0x7f3e75c7b609  (unknown)  start_thread
https://symbolize.stripped_domain/r/?trace=7f3e75cd903b,7f3d6bb7bcd9,7f3e75cd90bf,7f3d7ab78bcf,7f3d751ed922,7f3d751abebd,7f3d751fbdb0,7f3d751fb8ae,7f3d7105ded3,7f3d7669f1b8,7f3d7a62a8a0,7f3d7a62c633,7f3d7ab41cb1,7f3d7ab414e0,7f3d7ab298cb,7f3e75c7b608&map=b5462df73b9bb298b2bca5d2f02176eed80a2e90:7f3d6c719000-7f3d7da0ee30,50c831e765011c7eb7163b7f3cb5c4b6:7f3d5d3d1000-7f3d6bee9f00 
E0819 19:12:25.499816    6198 coredump_hook.cc:365] RAW: Remote crash data gathering hook invoked.
E0819 19:12:25.499836    6198 coredump_hook.cc:411] RAW: Skipping coredump since rlimit was 0 at process start.
E0819 19:12:25.499860    6198 client.cc:222] RAW: Coroner client retries enabled (b/136286901), will retry for up to 30 sec.
E0819 19:12:25.499874    6198 coredump_hook.cc:473] RAW: Sending fingerprint to remote end.
E0819 19:12:25.499892    6198 coredump_socket.cc:124] RAW: Stat failed errno=2 on socket /var/google/services/logmanagerd/remote_coredump.socket
E0819 19:12:25.499896    6198 coredump_hook.cc:477] RAW: Cannot send fingerprint to Coroner: [NOT_FOUND] Missing crash reporting socket. Is the listener running?
E0819 19:12:25.499902    6198 coredump_hook.cc:550] RAW: Discarding core.
E0819 19:12:26.381038    6198 process_state.cc:771] RAW: Raising signal 6 with default behavior
2022-08-19 19:16:08.118354: W tensorflow/core/distributed_runtime/rpc/grpc_remote_master.cc:157] RPC failed with status = "UNAVAILABLE: Connection reset by peer" and grpc_error_string = "{"created":"@1660936568.118086051","description":"Error received from peer ipv4:127.0.0.1:51011","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Connection reset by peer","grpc_status":14}", maybe retrying the RPC
2022-08-19 19:16:08.121698: W tensorflow/core/distributed_runtime/rpc/grpc_remote_master.cc:157] RPC failed with status = "UNAVAILABLE: Connection reset by peer" and grpc_error_string = "{"created":"@1660936568.121551341","description":"Error received from peer ipv4:127.0.0.1:51011","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Connection reset by peer","grpc_status":14}", maybe retrying the RPC
2022-08-19 19:16:08.121850: W tensorflow/core/distributed_runtime/rpc/grpc_remote_master.cc:157] RPC failed with status = "UNAVAILABLE: Connection reset by peer" and grpc_error_string = "{"created":"@1660936568.121673841","description":"Error received from peer ipv4:127.0.0.1:51011","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Connection reset by peer","grpc_status":14}", maybe retrying the RPC
2022-08-19 19:16:08.122091: W tensorflow/core/distributed_runtime/rpc/grpc_remote_master.cc:157] RPC failed with status = "UNAVAILABLE: Socket closed" and grpc_error_string = "{"created":"@1660936568.121976147","description":"Error received from peer ipv4:127.0.0.1:51011","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Socket closed","grpc_status":14}", maybe retrying the RPC
2022-08-19 19:16:08.122420: W tensorflow/core/distributed_runtime/rpc/grpc_remote_master.cc:157] RPC failed with status = "UNAVAILABLE: Connection reset by peer" and grpc_error_string = "{"created":"@1660936568.122250817","description":"Error received from peer ipv4:127.0.0.1:51011","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Connection reset by peer","grpc_status":14}", maybe retrying the RPC
2022-08-19 19:16:08.122566: W tensorflow/core/distributed_runtime/rpc/grpc_remote_master.cc:157] RPC failed with status = "UNAVAILABLE: Connection reset by peer" and grpc_error_string = "{"created":"@1660936568.122414562","description":"Error received from peer ipv4:127.0.0.1:51011","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Connection reset by peer","grpc_status":14}", maybe retrying the RPC
2022-08-19 19:16:08.122676: W tensorflow/core/distributed_runtime/rpc/grpc_remote_master.cc:157] RPC failed with status = "UNAVAILABLE: Connection reset by peer" and grpc_error_string = "{"created":"@1660936568.122580450","description":"Error received from peer ipv4:127.0.0.1:51011","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Connection reset by peer","grpc_status":14}", maybe retrying the RPC
https://symbolize.stripped_domain/r/?trace=7f3e75c853f4,7f3e75cd90bf&map= 
*** SIGTERM received by PID 5421 (TID 5421) on cpu 49 from PID 3828; stack trace: ***
PC: @     0x7f3e75c853f4  (unknown)  do_futex_wait.constprop.0
    @     0x7f3d6bb7bcda        992  (unknown)
    @     0x7f3e75cd90c0  (unknown)  (unknown)
    @ ... and at least 1 more frames
https://symbolize.stripped_domain/r/?trace=7f3e75c853f4,7f3d6bb7bcd9,7f3e75cd90bf&map=50c831e765011c7eb7163b7f3cb5c4b6:7f3d5d3d1000-7f3d6bee9f00 
E0819 19:16:10.582266    5421 coredump_hook.cc:320] RAW: Remote crash gathering disabled for SIGTERM.
E0819 19:16:10.611582    5421 process_state.cc:771] RAW: Raising signal 15 with default behavior
https://symbolize.stripped_domain/r/?trace=7f3e75c853f4,7f3e75cd90bf&map= 
*** SIGTERM received by PID 5515 (TID 5515) on cpu 31 from PID 3828; stack trace: ***
PC: @     0x7f3e75c853f4  (unknown)  do_futex_wait.constprop.0
    @     0x7f3d6bb7bcda        992  (unknown)
    @     0x7f3e75cd90c0  (unknown)  (unknown)
    @ ... and at least 1 more frames
https://symbolize.stripped_domain/r/?trace=7f3e75c853f4,7f3d6bb7bcd9,7f3e75cd90bf&map=50c831e765011c7eb7163b7f3cb5c4b6:7f3d5d3d1000-7f3d6bee9f00 
E0819 19:16:10.685134    5515 coredump_hook.cc:320] RAW: Remote crash gathering disabled for SIGTERM.
E0819 19:16:10.710575    5515 process_state.cc:771] RAW: Raising signal 15 with default behavior
https://symbolize.stripped_domain/r/?trace=7f3e75c853f4,7f3e75cd90bf&map= 
*** SIGTERM received by PID 5519 (TID 5519) on cpu 79 from PID 3828; stack trace: ***
PC: @     0x7f3e75c853f4  (unknown)  do_futex_wait.constprop.0
    @     0x7f3d6bb7bcda        992  (unknown)
    @     0x7f3e75cd90c0  (unknown)  (unknown)
    @ ... and at least 1 more frames
https://symbolize.stripped_domain/r/?trace=7f3e75c853f4,7f3d6bb7bcd9,7f3e75cd90bf&map=50c831e765011c7eb7163b7f3cb5c4b6:7f3d5d3d1000-7f3d6bee9f00 
E0819 19:16:10.788056    5519 coredump_hook.cc:320] RAW: Remote crash gathering disabled for SIGTERM.
E0819 19:16:10.813398    5519 process_state.cc:771] RAW: Raising signal 15 with default behavior
https://symbolize.stripped_domain/r/?trace=7f3e75c853f4,7f3e75cd90bf&map= 
*** SIGTERM received by PID 5523 (TID 5523) on cpu 5 from PID 3828; stack trace: ***
PC: @     0x7f3e75c853f4  (unknown)  do_futex_wait.constprop.0
    @     0x7f3d6bb7bcda        992  (unknown)
    @     0x7f3e75cd90c0  (unknown)  (unknown)
    @ ... and at least 1 more frames
https://symbolize.stripped_domain/r/?trace=7f3e75c853f4,7f3d6bb7bcd9,7f3e75cd90bf&map=50c831e765011c7eb7163b7f3cb5c4b6:7f3d5d3d1000-7f3d6bee9f00 
E0819 19:16:10.888321    5523 coredump_hook.cc:320] RAW: Remote crash gathering disabled for SIGTERM.
E0819 19:16:10.913426    5523 process_state.cc:771] RAW: Raising signal 15 with default behavior
https://symbolize.stripped_domain/r/?trace=7f3e75c853f4,7f3e75cd90bf&map= 
*** SIGTERM received by PID 5527 (TID 5527) on cpu 26 from PID 3828; stack trace: ***
PC: @     0x7f3e75c853f4  (unknown)  do_futex_wait.constprop.0
    @     0x7f3d6bb7bcda        992  (unknown)
    @     0x7f3e75cd90c0  (unknown)  (unknown)
    @ ... and at least 1 more frames
https://symbolize.stripped_domain/r/?trace=7f3e75c853f4,7f3d6bb7bcd9,7f3e75cd90bf&map=50c831e765011c7eb7163b7f3cb5c4b6:7f3d5d3d1000-7f3d6bee9f00 
E0819 19:16:10.988339    5527 coredump_hook.cc:320] RAW: Remote crash gathering disabled for SIGTERM.
E0819 19:16:11.013561    5527 process_state.cc:771] RAW: Raising signal 15 with default behavior
https://symbolize.stripped_domain/r/?trace=7f3e75c853f4,7f3e75cd90bf&map= 
*** SIGTERM received by PID 5531 (TID 5531) on cpu 56 from PID 3828; stack trace: ***
PC: @     0x7f3e75c853f4  (unknown)  do_futex_wait.constprop.0
    @     0x7f3d6bb7bcda        992  (unknown)
    @     0x7f3e75cd90c0  (unknown)  (unknown)
    @ ... and at least 1 more frames
https://symbolize.stripped_domain/r/?trace=7f3e75c853f4,7f3d6bb7bcd9,7f3e75cd90bf&map=50c831e765011c7eb7163b7f3cb5c4b6:7f3d5d3d1000-7f3d6bee9f00 
E0819 19:16:11.083357    5531 coredump_hook.cc:320] RAW: Remote crash gathering disabled for SIGTERM.
E0819 19:16:11.108967    5531 process_state.cc:771] RAW: Raising signal 15 with default behavior
https://symbolize.stripped_domain/r/?trace=7f3e75c853f4,7f3e75cd90bf&map= 
*** SIGTERM received by PID 5535 (TID 5535) on cpu 69 from PID 3828; stack trace: ***
PC: @     0x7f3e75c853f4  (unknown)  do_futex_wait.constprop.0
    @     0x7f3d6bb7bcda        992  (unknown)
    @     0x7f3e75cd90c0  (unknown)  (unknown)
    @ ... and at least 1 more frames
https://symbolize.stripped_domain/r/?trace=7f3e75c853f4,7f3d6bb7bcd9,7f3e75cd90bf&map=50c831e765011c7eb7163b7f3cb5c4b6:7f3d5d3d1000-7f3d6bee9f00 
E0819 19:16:11.186153    5535 coredump_hook.cc:320] RAW: Remote crash gathering disabled for SIGTERM.
E0819 19:16:11.212888    5535 process_state.cc:771] RAW: Raising signal 15 with default behavior
Traceback (most recent call last):
  File "run_gcp.py", line 137, in <module>
    pretrainer.fit(model=ssl_model, datamodule=pretraining_data)
  File "/home/adam_catto_mssm_edu/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 700, in fit
    self._call_and_handle_interrupt(
  File "/home/adam_catto_mssm_edu/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 652, in _call_and_handle_interrupt
    return self.strategy.launcher.launch(trainer_fn, *args, trainer=self, **kwargs)
  File "/home/adam_catto_mssm_edu/.local/lib/python3.8/site-packages/pytorch_lightning/strategies/launchers/xla.py", line 83, in launch
    _save_spawn(
  File "/home/adam_catto_mssm_edu/.local/lib/python3.8/site-packages/pytorch_lightning/strategies/launchers/xla.py", line 168, in _save_spawn
    return xmp.spawn(wrapped, args=args, nprocs=nprocs, join=join, daemon=daemon, start_method=start_method)
  File "/usr/local/lib/python3.8/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 389, in spawn
    return torch.multiprocessing.start_processes(
  File "/usr/local/lib/python3.8/dist-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/usr/local/lib/python3.8/dist-packages/torch/multiprocessing/spawn.py", line 140, in join
    raise ProcessExitedException(
torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with signal SIGABRT
```

cc @JackCaoG @steventk-g @Liyang90 @tchaton @rohitgr7 @kaushikb11

**Comment by CYHSM** [comment]
I encounter the same problem using both pytorch 1.12 and pytorch 1.10. For me it happens sometimes in the first 10 steps while once it finished an epoch and then crashed.

**Comment by ssusie** [comment]
Have you tried 
```
import torch_xla.core.xla_model as xm
print(xm.xla_device())
```
after this error. I am having similar error

**Comment by jnyjxn** [comment]
For anyone else waiting for this fix, I found the following command-line instruction fixes the problem when using Vertex AI Workbench:
`pip uninstall torch_xla`

**Comment by carmocca** [comment]
We run tests on gcloud and don't see any issues related to the top post. Closing

Happy to discuss if this is still a problem
