### ISSUE TITLE
Different versions of PyTorch Lightning provide different results while training on ImageNet

### ISSUE THREAD

**Issue by AlonNT** [Lightning-AI/lightning#14445]
## 🐛 Bug

While training a ResNet18-like CNN on ImageNet, different versions of PyTorch Lightning reach very different accuracies.
Minimal code is in this [GitHub repository](https://github.com/AlonNT/pl-reproduce), experiments logged in this [wandb project](https://wandb.ai/alonnt/pl-reproduce).

### To Reproduce

Create 3 different conda environments, where the only difference between them is PyTorch Lightning version.
Launch the trainings, each one in its own environment.
Details in the README of the [GitHub repository](https://github.com/AlonNT/pl-reproduce) I created for this issue.

### Expected behavior

- Training using version 1.5.4 reaches 67%/70% validation/train accuracy.  
For more details see the [wandb run](https://wandb.ai/alonnt/pl-reproduce/runs/jbpagr83).
- Training using version 1.6.5 reaches 44%/41% validation/train accuracy.  
For more details see the [wandb run](https://wandb.ai/alonnt/pl-reproduce/runs/1evkeupn).
- Training using version 1.7.3 reaches 49%/61% validation/train accuracy.  
For more details see the [wandb run](https://wandb.ai/alonnt/pl-reproduce/runs/xthb4zdx).

![train_accuracy](https://user-images.githubusercontent.com/19415791/187382595-422dc789-9f9d-4a22-a100-730014ef627f.png)

![validation_accuracy](https://user-images.githubusercontent.com/19415791/187382679-8273b2b3-1c77-4cab-9127-e7543fb4cec3.png)

### Environment

There are 3 different environment, I'm adding the output of _collect_env_details.py_ on one of them.
The other two are almost the same - the only different is the PyTorch Lightning version.

```text
* CUDA:
        - GPU:
                - NVIDIA GeForce RTX 2080 Ti
                - NVIDIA GeForce RTX 2080 Ti
                - NVIDIA GeForce RTX 2080 Ti
                - NVIDIA GeForce RTX 2080 Ti
                - NVIDIA GeForce RTX 2080 Ti
                - NVIDIA GeForce RTX 2080 Ti
                - NVIDIA GeForce RTX 2080 Ti
                - NVIDIA GeForce RTX 2080 Ti
        - available:         True
        - version:           11.3
* Lightning:
        - pytorch-lightning: 1.5.4
        - torch:             1.12.1
        - torchmetrics:      0.9.3
        - torchvision:       0.13.1
* Packages:
        - absl-py:           1.2.0
        - aiohttp:           3.8.1
        - aiosignal:         1.2.0
        - async-timeout:     4.0.2
        - attrs:             22.1.0
        - blinker:           1.4
        - brotlipy:          0.7.0
        - cachetools:        5.2.0
        - certifi:           2022.6.15
        - cffi:              1.15.1
        - charset-normalizer: 2.1.1
        - click:             8.1.3
        - colorama:          0.4.5
        - cryptography:      37.0.4
        - cycler:            0.11.0
        - docker-pycreds:    0.4.0
        - flatten-dict:      0.4.2
        - fonttools:         4.37.1
        - frozenlist:        1.3.1
        - fsspec:            2022.7.1
        - future:            0.18.2
        - gitdb:             4.0.9
        - gitpython:         3.1.27
        - google-auth:       2.11.0
        - google-auth-oauthlib: 0.4.6
        - grpcio:            1.48.0
        - idna:              3.3
        - importlib-metadata: 4.11.4
        - joblib:            1.1.0
        - kiwisolver:        1.4.4
        - loguru:            0.6.0
        - markdown:          3.4.1
        - markupsafe:        2.1.1
        - matplotlib:        3.5.3
        - multidict:         6.0.2
        - munkres:           1.1.4
        - numpy:             1.23.2
        - oauthlib:          3.2.0
        - packaging:         21.3
        - pandas:            1.4.3
        - pathlib2:          2.3.7.post1
        - pathtools:         0.1.2
        - pillow:            9.2.0
        - pip:               22.2.2
        - plotly:            5.10.0
        - ply:               3.11
        - promise:           2.3
        - protobuf:          4.21.5
        - psutil:            5.9.1
        - pyasn1:            0.4.8
        - pyasn1-modules:    0.2.7
        - pycparser:         2.21
        - pydantic:          1.9.2
        - pydeprecate:       0.3.1
        - pyjwt:             2.4.0
        - pyopenssl:         22.0.0
        - pyparsing:         3.0.9
        - pyqt5:             5.15.7
        - pyqt5-sip:         12.11.0
        - pysocks:           1.7.1
        - python-dateutil:   2.8.2
        - pytorch-lightning: 1.5.4
        - pytz:              2022.2.1
        - pyu2f:             0.1.5
        - pyyaml:            6.0
        - requests:          2.28.1
        - requests-oauthlib: 1.3.1
        - rsa:               4.9
        - scikit-learn:      1.1.2
        - scipy:             1.9.0
        - sentry-sdk:        1.9.5
        - setproctitle:      1.3.2
        - setuptools:        65.3.0
        - shortuuid:         1.0.9
        - sip:               6.6.2
        - six:               1.16.0
        - smmap:             3.0.5
        - tenacity:          8.0.1
        - tensorboard:       2.9.0
        - tensorboard-data-server: 0.6.0
        - tensorboard-plugin-wit: 1.8.1
        - threadpoolctl:     3.1.0
        - tikzplotlib:       0.10.1
        - toml:              0.10.2
        - torch:             1.12.1
        - torchmetrics:      0.9.3
        - torchvision:       0.13.1
        - tornado:           6.2
        - tqdm:              4.64.0
        - typing-extensions: 4.3.0
        - unicodedata2:      14.0.0
        - urllib3:           1.26.11
        - wandb:             0.13.1
        - webcolors:         1.12
        - werkzeug:          2.2.2
        - wheel:             0.37.1
        - yarl:              1.7.2
        - zipp:              3.8.1
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.9.13
        - version:           #30~18.04.1-Ubuntu SMP Fri Jan 17 06:14:09 UTC 2020
```

cc @awaelchli

**Comment by carmocca** [comment]
@AlonNT did you set the same seed for all runs? Do all runs use the same PyTorch version?

I see they were trained with DataParallel enabled, do you see similar behaviour without distributed and/or on CPU?

**Comment by AlonNT** [comment]
@carmocca 
I didn't set a custom seed at all, but these results re-produce over and over again.
I can try to set the same seed for all runs and update here.

The only difference in the environments is the PyTorch Lightning version.
In particular, all the runs use the same PyTorch version.

I didn't try to train on CPU or on a single GPU without distributed training. 
I can try to to that and update here, but it will take some time (it's quite slow already now when using 4 GPUs).

**Comment by carmocca** [comment]
Training for 10 epochs max should be enough to notice the difference, given the graphs in the top post

**Comment by awaelchli** [comment]
Since we are looking at graphs that plot accuracy, I think it is worth noting that the computation of accuracy here is not correct: https://github.com/AlonNT/pl-reproduce/blob/edcc17603e256ce37e40dc1fb5ef05257becb219/utils.py#L648-L656
For the sake of sanity and evaluation, I recommend using torchmetrics there. I don't expect the numbers to be drastically different, but I think it is important not to overlook in the context of distributed training here. 

Another reason why I mention this is because I looked at the wandb plots you linked and the training loss curves seem to be identical (note, no seed was set which could explain the small differences in the curves). The validation loss is different which leads me to believe that there might be a difference between either 1) self.log behavior 2) distributed sampling between the different versions during validation phase. 

To phase them out, I would do the following. In addition to logging with self.log, log directly using `self.logger.experiment.log(...)` (wandb api). This will log on rank 0 only. This will tell us whether the difference comes from the internal logging code or something else.

**Comment by ruiyan1995** [comment]
I meet the same issue. The same code shows different results with different PL versions...

**Comment by AlonNT** [comment]
@carmocca and @awaelchli 
Thanks for your help and feedback! 

@carmocca 
I launched the runs without DataParallel, using only a single GPU. 
I also trained on CPU for 17 epochs (I killed it after 6.5 days).
You can see all runs for yourself in the [wandb project](https://wandb.ai/alonnt/pl-reproduce).

**The issue occurs only in the distributed training strategy.**

Training on single GPU or on CPU provides the same results in all different PL versions (1.5.4, 1.6.5 & 1.7.3).
Now the only two runs which are below the others are 1.7.3 and 1.6.5 multiGPU.

![W B Chart 9_6_2022, 9_26_47 AM](https://user-images.githubusercontent.com/19415791/188562268-403da50a-c4d5-4b9a-8c42-5f19e305e428.png)

There are still some very small variation in the curves, which are the results of using different seeds.
I launched new runs with [seed_everything](https://pytorch-lightning.readthedocs.io/en/stable/api/pytorch_lightning.utilities.seed.html#pytorch_lightning.utilities.seed.seed_everything) (you can see [here](https://github.com/AlonNT/pl-reproduce/blob/2fd7e7bf4794eb2e4bf974284df9f5c7757712f4/main.py#L19)), they are still running so no results yet.
Anyway, I'm not sure we should wait for these runs, since the results re-produce with different seeds as well.

@awaelchli 
Can you explain what is not correct in the accuracy calculation?
The code is [here](https://github.com/AlonNT/pl-reproduce/blob/edcc17603e256ce37e40dc1fb5ef05257becb219/utils.py#L648-L656), I copy the two relevant lines here for convenience:
```python
predictions = torch.argmax(logits, dim=1)
accuracy = torch.sum(labels == predictions).item() / len(labels)
```
Anyway, you can see that the validation loss also differs, so I'm not sure the problem is in the accuracy computation.

![W B Chart 9_6_2022, 9_43_48 AM](https://user-images.githubusercontent.com/19415791/188564997-d396cc80-d153-48f4-b35d-93578aeb316c.png)

Anyway, following your recommendation I tried to use torchmetrics by initiating two Accuracy instances (for train/val) as class attributes, and replaced the `accuracy = <my_calculation>` with `accuracy = self.accuracy(predictions, labels)`. This raised exception telling me calculations were made using tensors from different devices.
```text
RuntimeError: Encountered different devices in metric calculation (see stacktrace for details).This could be due to the metric class not being on the same device as input.Instead of `metric=Accuracy(...)` try to do `metric=Accuracy(...).to(device)` where device corresponds to the device of the input.
```
I'm attaching the full stack trace below.
What am I doing wrong?

Regarding your suggestion of using `self.logger.experiment.log(...)` in addition to `self.log(...)`, I didn't fully understand your suggestion - if it will log on rank 0 only, shouldn't the result be the accumulated accuracy of the first quarter of every mini-batch? and not the full accuracy across the whole data?

If you think this is still relevant (after the findings that the differences occur only in distributed training) I can launch new runs with this change as well (and using torchmetrics.Accuracy properly).
Waiting to hear what you think.



Stack trace of using _torchmetrics_ Accuracy:
```text
Validation sanity check:   0%|                                                                                                                                           | 0/2 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/mobileye/algo_OBJD/alonnt/repos/pl-reproduce/main.py", line 29, in <module>
    main()
  File "/mobileye/algo_OBJD/alonnt/repos/pl-reproduce/main.py", line 25, in main
    trainer.fit(model, datamodule=datamodule)
  File "/homes/alonnt/.conda/envs/lightning-1-5-4/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 737, in fit
    self._call_and_handle_interrupt(
  File "/homes/alonnt/.conda/envs/lightning-1-5-4/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 682, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/homes/alonnt/.conda/envs/lightning-1-5-4/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 772, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/homes/alonnt/.conda/envs/lightning-1-5-4/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1195, in _run
    self._dispatch()
  File "/homes/alonnt/.conda/envs/lightning-1-5-4/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1274, in _dispatch
    self.training_type_plugin.start_training(self)
  File "/homes/alonnt/.conda/envs/lightning-1-5-4/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 202, in start_training
    self._results = trainer.run_stage()
  File "/homes/alonnt/.conda/envs/lightning-1-5-4/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1284, in run_stage
    return self._run_train()
  File "/homes/alonnt/.conda/envs/lightning-1-5-4/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1306, in _run_train
    self._run_sanity_check(self.lightning_module)
  File "/homes/alonnt/.conda/envs/lightning-1-5-4/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1370, in _run_sanity_check
    self._evaluation_loop.run()
  File "/homes/alonnt/.conda/envs/lightning-1-5-4/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/homes/alonnt/.conda/envs/lightning-1-5-4/lib/python3.9/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 109, in advance
    dl_outputs = self.epoch_loop.run(dataloader, dataloader_idx, dl_max_batches, self.num_dataloaders)
  File "/homes/alonnt/.conda/envs/lightning-1-5-4/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/homes/alonnt/.conda/envs/lightning-1-5-4/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 122, in advance
    output = self._evaluation_step(batch, batch_idx, dataloader_idx)
  File "/homes/alonnt/.conda/envs/lightning-1-5-4/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 217, in _evaluation_step
    output = self.trainer.accelerator.validation_step(step_kwargs)
  File "/homes/alonnt/.conda/envs/lightning-1-5-4/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 236, in validation_step
    return self.training_type_plugin.validation_step(*step_kwargs.values())
  File "/homes/alonnt/.conda/envs/lightning-1-5-4/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/dp.py", line 104, in validation_step
    return self.model(*args, **kwargs)
  File "/homes/alonnt/.conda/envs/lightning-1-5-4/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/homes/alonnt/.conda/envs/lightning-1-5-4/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 168, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/homes/alonnt/.conda/envs/lightning-1-5-4/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 178, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/homes/alonnt/.conda/envs/lightning-1-5-4/lib/python3.9/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/homes/alonnt/.conda/envs/lightning-1-5-4/lib/python3.9/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/homes/alonnt/.conda/envs/lightning-1-5-4/lib/python3.9/site-packages/torchmetrics/metric.py", line 391, in wrapped_func
    update(*args, **kwargs)
  File "/homes/alonnt/.conda/envs/lightning-1-5-4/lib/python3.9/site-packages/torchmetrics/classification/accuracy.py", line 253, in update
    self.tp += tp
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/homes/alonnt/.conda/envs/lightning-1-5-4/lib/python3.9/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/homes/alonnt/.conda/envs/lightning-1-5-4/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/homes/alonnt/.conda/envs/lightning-1-5-4/lib/python3.9/site-packages/pytorch_lightning/overrides/data_parallel.py", line 63, in forward
    output = super().forward(*inputs, **kwargs)
  File "/homes/alonnt/.conda/envs/lightning-1-5-4/lib/python3.9/site-packages/pytorch_lightning/overrides/base.py", line 92, in forward
    output = self.module.validation_step(*inputs, **kwargs)
  File "/mobileye/algo_OBJD/alonnt/repos/pl-reproduce/utils.py", line 649, in validation_step
    self.shared_step(batch, batch_idx, RunningStage.VALIDATING)
  File "/mobileye/algo_OBJD/alonnt/repos/pl-reproduce/utils.py", line 674, in shared_step
    loss = self.get_classification_loss(logits, labels, stage)
  File "/mobileye/algo_OBJD/alonnt/repos/pl-reproduce/utils.py", line 654, in get_classification_loss
    self.accuracy[stage](predictions, labels)
  File "/homes/alonnt/.conda/envs/lightning-1-5-4/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/homes/alonnt/.conda/envs/lightning-1-5-4/lib/python3.9/site-packages/torchmetrics/metric.py", line 245, in forward
    self._forward_cache = self._forward_reduce_state_update(*args, **kwargs)
  File "/homes/alonnt/.conda/envs/lightning-1-5-4/lib/python3.9/site-packages/torchmetrics/metric.py", line 309, in _forward_reduce_state_update
    self.update(*args, **kwargs)
  File "/homes/alonnt/.conda/envs/lightning-1-5-4/lib/python3.9/site-packages/torchmetrics/metric.py", line 394, in wrapped_func
    raise RuntimeError(
RuntimeError: Encountered different devices in metric calculation (see stacktrace for details).This could be due to the metric class not being on the same device as input.Instead of `metric=Accuracy(...)` try to do `metric=Accuracy(...).to(device)` where device corresponds to the device of the input.
```

**Comment by carmocca** [comment]
@AlonNT Did you ever continue exploring what could be the issue? Is it still a problem in current master?

If a bug was introduced on multi-GPU, that would be a high priority. However, if you cannot `git bisect` what introduced the regression, we would need some sort of reproducible script.

**Comment by brandnewx** [comment]
I have investigated this further and it appears different **torchmetrics** versions contribute to drastically different training results. torchmetrics behavior of the same version differs too when trained on a T4 and on a A100.

**Comment by carmocca** [comment]
cc @SkafteNicki @Borda. @brandnewx It's probably worth that you open a separate issue in the [torchmetrics](https://github.com/Lightning-AI/metrics) repository

**Comment by AlonNT** [comment]
@brandnewx @carmocca @awaelchli 

Note that this issue will be automatically closed in a week, are you dropping this issue on purpose or was it fixed in recent versions?

**Comment by awaelchli** [comment]
@AlonNT This is just a bot that is triggered based on activity. 
Is your problem also caused by the torchmetrics version affecting the metrics/plots?
