### ISSUE TITLE
Using FP16 with apex backend at optimization level O2 results in runtime error

### ISSUE THREAD

**Issue by SM1991CODES** [Lightning-AI/lightning#14868]
### First check

- [X] I'm sure this is a bug.
- [X] I've added a descriptive title to this bug.
- [X] I've provided clear instructions on how to reproduce the bug.
- [X] I've added a code sample.
- [X] I've provided any other important info that is required.

### Bug description

I am trying to save my model weights as FP16 while using mixed precision training.
As I understand from the documents, the only way to do this is to use the apex backend with optimization level O2.

However, I get this error when I try this:
![image](https://user-images.githubusercontent.com/69435296/191948462-1af1cfe0-57fd-4663-b6c8-d479f23bb5c7.png)

Please help fix this or suggest if there is a better way to get FP16 weights.
Also, I would like to know if there is a way to train a network in INT8 directly - end result should be a model with INT8 weights.

### How to reproduce the bug

```python
trainer = pl.Trainer(default_root_dir=settings.argoverse_workspace_root_path + 'logs/argologs',
                        max_epochs=2, accelerator='gpu', devices=[0], amp_backend='apex', amp_level="O2", 
                        precision=16, log_every_n_steps=10,
                        check_val_every_n_epoch=1, accumulate_grad_batches={10: 2, 20: 3},
                        callbacks=[ RichModelSummary(max_depth=5), 
                                    RichProgressBar(),
                                    ModelPruning("l1_unstructured", amount=0.2),
                                    lr_monitor])
```

### Error messages and logs

```




Epoch 0/1  ━━━━━━━━━━━━━━━━ 0/1027 0:00:02 •       0.00it/s loss: nan v_num: 
                                   -:--:--                  0                
Traceback (most recent call last):
  File "/home/sambit/Documents/codeworks/valeo/velo_train_py/radarworks/argoverse_2/root/train/train_lightning_detector.py", line 137, in <module>
    train_lightning_model()
  File "/home/sambit/Documents/codeworks/valeo/velo_train_py/radarworks/argoverse_2/root/train/train_lightning_detector.py", line 112, in train_lightning_model
    trainer.fit(model=light_net)
  File "/home/sambit/.pyenv/versions/3.8.10/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "/home/sambit/.pyenv/versions/3.8.10/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/sambit/.pyenv/versions/3.8.10/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 735, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/sambit/.pyenv/versions/3.8.10/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1166, in _run
    results = self._run_stage()
  File "/home/sambit/.pyenv/versions/3.8.10/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1252, in _run_stage
    return self._run_train()
  File "/home/sambit/.pyenv/versions/3.8.10/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1283, in _run_train
    self.fit_loop.run()
  File "/home/sambit/.pyenv/versions/3.8.10/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/home/sambit/.pyenv/versions/3.8.10/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 271, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "/home/sambit/.pyenv/versions/3.8.10/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/home/sambit/.pyenv/versions/3.8.10/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 203, in advance
    batch_output = self.batch_loop.run(kwargs)
  File "/home/sambit/.pyenv/versions/3.8.10/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/home/sambit/.pyenv/versions/3.8.10/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 87, in advance
    outputs = self.optimizer_loop.run(optimizers, kwargs)
  File "/home/sambit/.pyenv/versions/3.8.10/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/home/sambit/.pyenv/versions/3.8.10/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 201, in advance
    result = self._run_optimization(kwargs, self._optimizers[self.optim_progress.optimizer_position])
  File "/home/sambit/.pyenv/versions/3.8.10/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 248, in _run_optimization
    self._optimizer_step(optimizer, opt_idx, kwargs.get("batch_idx", 0), closure)
  File "/home/sambit/.pyenv/versions/3.8.10/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 358, in _optimizer_step
    self.trainer._call_lightning_module_hook(
  File "/home/sambit/.pyenv/versions/3.8.10/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1550, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/home/sambit/.pyenv/versions/3.8.10/lib/python3.8/site-packages/pytorch_lightning/core/module.py", line 1705, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/home/sambit/.pyenv/versions/3.8.10/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py", line 168, in step
    step_output = self._strategy.optimizer_step(self._optimizer, self._optimizer_idx, closure, **kwargs)
  File "/home/sambit/.pyenv/versions/3.8.10/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 216, in optimizer_step
    return self.precision_plugin.optimizer_step(model, optimizer, opt_idx, closure, **kwargs)
  File "/home/sambit/.pyenv/versions/3.8.10/lib/python3.8/site-packages/pytorch_lightning/plugins/precision/apex_amp.py", line 89, in optimizer_step
    closure_result = closure()
  File "/home/sambit/.pyenv/versions/3.8.10/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 146, in __call__
    self._result = self.closure(*args, **kwargs)
  File "/home/sambit/.pyenv/versions/3.8.10/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 141, in closure
    self._backward_fn(step_output.closure_loss)
  File "/home/sambit/.pyenv/versions/3.8.10/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 304, in backward_fn
    self.trainer._call_strategy_hook("backward", loss, optimizer, opt_idx)
  File "/home/sambit/.pyenv/versions/3.8.10/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1704, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/sambit/.pyenv/versions/3.8.10/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 191, in backward
    self.precision_plugin.backward(self.lightning_module, closure_loss, optimizer, optimizer_idx, *args, **kwargs)
  File "/home/sambit/.pyenv/versions/3.8.10/lib/python3.8/site-packages/pytorch_lightning/plugins/precision/apex_amp.py", line 75, in backward
    super().backward(model, closure_loss, optimizer, optimizer_idx, *args, **kwargs)
  File "/home/sambit/.pyenv/versions/3.8.10/lib/python3.8/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 80, in backward
    model.backward(closure_loss, optimizer, optimizer_idx, *args, **kwargs)
  File "/home/sambit/.pyenv/versions/3.8.10/lib/python3.8/site-packages/pytorch_lightning/core/module.py", line 1450, in backward
    loss.backward(*args, **kwargs)
  File "/home/sambit/.pyenv/versions/3.8.10/lib/python3.8/site-packages/torch/_tensor.py", line 363, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/sambit/.pyenv/versions/3.8.10/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.HalfTensor [12, 4, 384, 384]] is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

```

### Important info

```

#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow): Trainer
#- PyTorch Lightning Version (e.g., 1.5.0): 1.12.1
#- Lightning App Version (e.g., 0.5.2): 
#- PyTorch Version (e.g., 1.10):
#- Python version (e.g., 3.9): 3.8.10
#- OS (e.g., Linux): Linux
#- CUDA/cuDNN version: 11.3
#- GPU models and configuration: RTX2080 MaxQ
#- How you installed Lightning(`conda`, `pip`, source): pip
#- Running environment of LightningApp (e.g. local, cloud): local

```

**Comment by awaelchli** [comment]
Hello @SM1991CODES 

> I am trying to save my model weights as FP16 while using mixed precision training.

Could you explain a bit more the motivation behind why you are choosing apex O2 over native amp? Are you trying to save more memory? We generally don't recommend doing that, because computations in forward and backward pass become numerically unstable. In most cases, native amp (mixed precision) is the better choice. 

Also, related issue: #14416 

Regarding this error:
```
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.HalfTensor [12, 4, 384, 384]] is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
```

You get it because, as the message says (from torch), because one operation in your forward pass (or loss function) was performing an inplace operation. For example, `ReLU(inplace=True)` or `some_tensor[x] = y`. You need to find this and fix it by avoiding inplace. You can set `Trainer(detect_anomaly=True)` to get more information from torch in which layer this happens.


> Also, I would like to know if there is a way to train a network in INT8 directly - end result should be a model with INT8 weights.

PyTorch as well as Lightning doesn't have direct support for it. But you can use other libraries like https://github.com/TimDettmers/bitsandbytes that have special optimizers for it. It should work together with Lightning if you want to try it. 

I hope this helps.
