### ISSUE TITLE
lightning CLI argument fails

### ISSUE THREAD

**Issue by JatheenA** [Lightning-AI/lightning#14875]
### First check

- [X] I'm sure this is a bug.
- [X] I've added a descriptive title to this bug.
- [X] I've provided clear instructions on how to reproduce the bug.
- [X] I've added a code sample.
- [X] I've provided any other important info that is required.

### Bug description
```
% python -m lightning          
NOTE: Redirects are currently not supported in Windows or MacOs.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/lightning/__main__.py", line 4, in <module>
    main()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/lightning_app/cli/lightning_cli.py", line 52, in main
    if sys.argv[1] in ("connect", "disconnect"):
IndexError: list index out of range
```
-- with args it works ---
```
% python -m lightning --version
NOTE: Redirects are currently not supported in Windows or MacOs.
python -m lightning, version 0.6.2
```

### How to reproduce the bug

```python
run %python -m lightning  <without args>
```

### Important info

```
% pip list | grep lightning

lightning                     2022.9.22
lightning-app                 0.6.2
lightning-cloud               0.5.7
lightning-utilities           0.3.0
pytorch-lightning             1.7.7
```

### More info

```
if sys.argv[1] in ("connect", "disconnect"):
IndexError: list index out of range
```

**Comment by nicolai86** [comment]
looks like something introduced in https://github.com/Lightning-AI/lightning/pull/14183 - [link](https://github.com/Lightning-AI/lightning/pull/14183/files#diff-33b1761b903630ec4114a48eb8e6f93a3324731780f6d52c8eef0582cc69954bR50)
https://github.com/Lightning-AI/lightning/pull/14877 will fix that.
