### ISSUE TITLE
IndexError on multi-node multi-gpu SLURM script with DDP.

### ISSUE THREAD

**Issue by tsikup** [Lightning-AI/lightning#14949]
Hi.

I want to submit a SLURM job with 2 nodes, 4 gpus per node and 4 tasks per node (1 task per gpu) as suggested by the lightning docs [here](https://pytorch-lightning.readthedocs.io/en/latest/clouds/cluster_advanced.html). 

```
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=4
#SBATCH --gpus-per-node=A100:4
```

with `devices=4` and `num_nodes=2` in the Trainer with `ddp` strategy.

I get the following error although the first 4 ranks (gpus) have been initialized as follows (the rest haven't)
`Initializing distributed: GLOBAL_RANK: 2, MEMBER: 3/8`
`Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/8`
`Initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/8`
`Initializing distributed: GLOBAL_RANK: 3, MEMBER: 4/8`

Can you help me?

```
Traceback (most recent call last):
  File "/local/tmp.581850/9.train.py", line 156, in <module>
    main(args, config)
  File "/local/tmp.581850/9.train.py", line 138, in main
    trainer.fit(model, datamodule=data, ckpt_path=None)
  File "/envs/pytorch-env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "/envs/pytorch-env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/envs/pytorch-env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 735, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/envs/pytorch-env/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1102, in _run
    self.strategy.setup_environment()
  File "/envs/pytorch-env/lib/python3.9/site-packages/pytorch_lightning/strategies/ddp.py", line 157, in setup_environment
    self.setup_distributed()
  File "/envs/pytorch-env/lib/python3.9/site-packages/pytorch_lightning/strategies/ddp.py", line 209, in setup_distributed
    self._process_group_backend = self._get_process_group_backend()
  File "/envs/pytorch-env/lib/python3.9/site-packages/pytorch_lightning/strategies/ddp.py", line 216, in _get_process_group_backend
    or get_default_process_group_backend_for_device(self.root_device)
  File "/envs/pytorch-env/lib/python3.9/site-packages/pytorch_lightning/strategies/ddp.py", line 123, in root_device
    return self.parallel_devices[self.local_rank]
IndexError: list index out of range
```

_Originally posted by @tsikup in https://github.com/Lightning-AI/lightning/discussions/7275#discussioncomment-3765109_
    

cc @awaelchli

**Comment by awaelchli** [comment]
Hi, please have a look at the troubleshooting guide here: 
https://pytorch-lightning.readthedocs.io/en/latest/clouds/cluster_advanced.html#troubleshooting
Also, make sure that your slurm script has exactly the same variables as shown here:
https://pytorch-lightning.readthedocs.io/en/latest/clouds/cluster_advanced.html#design-your-training-script

**Comment by spirosbax** [comment]
I'm running into to the exact same problem. Any updates on this ?

**Comment by auhcheng** [comment]
I ran into the same issue and was able to resolve this on my cluster. I had noticed a warning:

```
srun: Warning: can't honor --ntasks-per-node set to 4 which doesn't match the requested tasks 8 with the number of requested nodes 1. Ignoring --ntasks-per-node.
```

I then tried passing the number of nodes and tasks specified by the sbatch script to srun as well, which seemed to work. This is my sbatch for 2 nodes, 4 GPUs each (total 8 GPUs):

```
#!/bin/bash

#SBATCH --nodes=2
#SBATCH --gres=gpu:4
#SBATCH --tasks-per-node=4

srun --nodes=2 --tasks-per-node=4 python train.py
```
