### ISSUE TITLE
Single Node distributed training with multiple GPUs works but fails on multi-node

### ISSUE THREAD

**Issue by martinez-zacharya** [Lightning-AI/lightning#14986]
### Bug description

I'm able to train on multiple GPUs on one node, but it fails when trying to do multi-node. I'm using SLURM to submit my jobs. Thank you ahead of time!

### How to reproduce the bug

```python
import os
import torch
from torch.nn import functional as F
from torch.utils.data import DataLoader
from torchvision.datasets import MNIST
import torchvision.transforms as transforms
from pytorch_lightning import Trainer
import pytorch_lightning as pl


class CoolModel(pl.LightningModule):

    def __init__(self):
        super(CoolModel, self).__init__()
        self.l1 = torch.nn.Linear(28 * 28, 10)

    def forward(self, x):
        return torch.relu(self.l1(x.view(x.size(0), -1)))

    def my_loss(self, y_hat, y):
        return F.cross_entropy(y_hat, y)

    def training_step(self, batch, batch_nb):
        x, y = batch
        y_hat = self.forward(x)
        return {'loss': self.my_loss(y_hat, y)}

    def validation_step(self, batch, batch_nb):
        x, y = batch
        y_hat = self.forward(x)
        return {'val_loss': self.my_loss(y_hat, y)}

    def validation_end(self, outputs):
        avg_loss = torch.stack([x['val_loss'] for x in outputs]).mean()
        return {'avg_val_loss': avg_loss}

    def configure_optimizers(self):
        return [torch.optim.Adam(self.parameters(), lr=0.02)]

    def train_dataloader(self):
        return DataLoader(MNIST(os.getcwd(), train=True, download=True, transform=transforms.ToTensor()), batch_size=32)

    def val_dataloader(self):
        return DataLoader(MNIST(os.getcwd(), train=True, download=True, transform=transforms.ToTensor()), batch_size=32)

    def test_dataloader(self):
        return DataLoader(MNIST(os.getcwd(), train=True, download=True, transform=transforms.ToTensor()), batch_size=32)




model = CoolModel()


trainer = Trainer(max_epochs=1, gpus=4, num_nodes=2, accelerator='gpu', strategy='fsdp')

trainer.fit(model)
```

```shellscript
#!/bin/bash
#SBATCH --time=1:00:00   # walltime
#SBATCH --ntasks=2   # number of processor cores (i.e. tasks)
#SBATCH --ntasks-per-node=4
#SBATCH --nodes=2 # number of nodes
#SBATCH --gres=gpu:4 # number of GPUs (max 4 per node)
#SBATCH --mem-per-cpu=32G   # memory per CPU core
#SBATCH -J "test_lightning"   # job name
#SBATCH --mail-user="" # change to your email
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL
#SBATCH --output=%x-%j.out


module purge
master_addr=$(scontrol show hostnames "$SLURM_JOB_NODELIST" | head -n 1)
export MASTER_ADDR=$master_addr
export MASTER_PORT=13579
export NCCL_SOCKET_IFNAME=^docker0,lo
export NCCL_DEBUG=INFO
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/central/groups/mthomson/zam/miniconda3
source ~/.bashrc

srun python3 testing_ddp.py
```
```


### Error messages and logs


/central/groups/mthomson/zam/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py:447: LightningDeprecationWarning: Setting `Trainer(gpus=4)` is deprecated in v1.7 and will be removed in v2.0. Please use `Trainer(accelerator='gpu', devices=4)` instead.
  rank_zero_deprecation(
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/8
Initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/8
Initializing distributed: GLOBAL_RANK: 2, MEMBER: 3/8
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/8
Initializing distributed: GLOBAL_RANK: 3, MEMBER: 4/8
Initializing distributed: GLOBAL_RANK: 2, MEMBER: 3/8
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/8
Initializing distributed: GLOBAL_RANK: 3, MEMBER: 4/8
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 8 processes
----------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 8 processes
----------------------------------------------------------------------------------------------------

hpc-25-14:18569:18569 [0] NCCL INFO Bootstrap : Using em1:172.18.28.81<0>
hpc-25-14:18569:18569 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
hpc-25-14:18569:18569 [0] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB ; OOB em1:172.18.28.81<0>
hpc-25-14:18569:18569 [0] NCCL INFO Using network IB
NCCL version 2.10.3+cuda10.2
hpc-25-14:18627:18627 [2] NCCL INFO Bootstrap : Using em1:172.18.28.81<0>
hpc-25-14:18627:18627 [2] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
hpc-25-14:18627:18627 [2] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB ; OOB em1:172.18.28.81<0>
hpc-25-14:18627:18627 [2] NCCL INFO Using network IB
hpc-25-15:21491:21491 [3] NCCL INFO Bootstrap : Using em1:172.18.28.82<0>
hpc-25-15:21491:21491 [3] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
hpc-25-15:21491:21491 [3] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB ; OOB em1:172.18.28.82<0>
hpc-25-15:21491:21491 [3] NCCL INFO Using network IB
hpc-25-14:18622:18622 [1] NCCL INFO Bootstrap : Using em1:172.18.28.81<0>
hpc-25-14:18622:18622 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
hpc-25-14:18622:18622 [1] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB ; OOB em1:172.18.28.81<0>
hpc-25-14:18622:18622 [1] NCCL INFO Using network IB
hpc-25-15:21476:21476 [2] NCCL INFO Bootstrap : Using em1:172.18.28.82<0>
hpc-25-15:21476:21476 [2] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
hpc-25-15:21476:21476 [2] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB ; OOB em1:172.18.28.82<0>
hpc-25-15:21476:21476 [2] NCCL INFO Using network IB
hpc-25-14:18648:18648 [3] NCCL INFO Bootstrap : Using em1:172.18.28.81<0>
hpc-25-14:18648:18648 [3] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
hpc-25-15:21400:21400 [1] NCCL INFO Bootstrap : Using em1:172.18.28.82<0>
hpc-25-15:21400:21400 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
hpc-25-15:21400:21400 [1] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB ; OOB em1:172.18.28.82<0>
hpc-25-15:21400:21400 [1] NCCL INFO Using network IB
hpc-25-14:18648:18648 [3] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB ; OOB em1:172.18.28.81<0>
hpc-25-14:18648:18648 [3] NCCL INFO Using network IB
hpc-25-15:21312:21312 [0] NCCL INFO Bootstrap : Using em1:172.18.28.82<0>

hpc-25-14:18569:18835 [0] bootstrap.cc:131 NCCL WARN Bootstrap Root : rank 1 of 8 ranks has already checked in
hpc-25-15:21312:21312 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
hpc-25-15:21312:21312 [0] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB ; OOB em1:172.18.28.82<0>
hpc-25-15:21312:21312 [0] NCCL INFO Using network IB
NCCL version 2.10.3+cuda10.2
hpc-25-14:18648:18842 [3] NCCL INFO Call to connect returned Connection refused, retrying
hpc-25-14:18648:18842 [3] NCCL INFO Call to connect returned Connection refused, retrying
hpc-25-14:18648:18842 [3] NCCL INFO Call to connect returned Connection refused, retrying
hpc-25-14:18648:18842 [3] NCCL INFO Call to connect returned Connection refused, retrying
hpc-25-14:18648:18842 [3] NCCL INFO Call to connect returned Connection refused, retrying
hpc-25-14:18648:18842 [3] NCCL INFO Call to connect returned Connection refused, retrying
hpc-25-14:18648:18842 [3] NCCL INFO Call to connect returned Connection refused, retrying
hpc-25-14:18648:18842 [3] NCCL INFO Call to connect returned Connection refused, retrying
hpc-25-14:18648:18842 [3] NCCL INFO Call to connect returned Connection refused, retrying
hpc-25-14:18648:18842 [3] NCCL INFO Call to connect returned Connection refused, retrying
hpc-25-14:18648:18842 [3] NCCL INFO Call to connect returned Connection refused, retrying
hpc-25-14:18648:18842 [3] NCCL INFO Call to connect returned Connection refused, retrying
hpc-25-14:18648:18842 [3] NCCL INFO Call to connect returned Connection refused, retrying
hpc-25-14:18648:18842 [3] NCCL INFO Call to connect returned Connection refused, retrying
hpc-25-14:18648:18842 [3] NCCL INFO Call to connect returned Connection refused, retrying
hpc-25-14:18648:18842 [3] NCCL INFO Call to connect returned Connection refused, retrying
hpc-25-14:18648:18842 [3] NCCL INFO Call to connect returned Connection refused, retrying
hpc-25-14:18648:18842 [3] NCCL INFO Call to connect returned Connection refused, retrying
hpc-25-14:18648:18842 [3] NCCL INFO Call to connect returned Connection refused, retrying

hpc-25-14:18648:18842 [3] include/socket.h:409 NCCL WARN Net : Connect to 172.18.28.81<52012> failed : Connection refused
hpc-25-14:18648:18842 [3] NCCL INFO bootstrap.cc:360 -> 2
hpc-25-14:18648:18842 [3] NCCL INFO init.cc:501 -> 2
hpc-25-14:18648:18842 [3] NCCL INFO init.cc:904 -> 2
hpc-25-14:18648:18842 [3] NCCL INFO group.cc:72 -> 2 [Async thread]
Traceback (most recent call last):
  File "/central/home/zmartine/DistantHomologyDetection/scripts/testing_ddp.py", line 57, in <module>
    trainer.fit(model)
  File "/central/groups/mthomson/zam/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "/central/groups/mthomson/zam/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/central/groups/mthomson/zam/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 735, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/central/groups/mthomson/zam/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1103, in _run
    self.__setup_profiler()
  File "/central/groups/mthomson/zam/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1736, in __setup_profiler
    self.profiler.setup(stage=self.state.fn._setup_fn, local_rank=local_rank, log_dir=self.log_dir)
  File "/central/groups/mthomson/zam/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 2222, in log_dir
    dirpath = self.strategy.broadcast(dirpath)
  File "/central/groups/mthomson/zam/miniconda3/lib/python3.9/site-packages/pytorch_lightning/strategies/ddp.py", line 322, in broadcast
    torch.distributed.broadcast_object_list(obj, src, group=_group.WORLD)
  File "/central/groups/mthomson/zam/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 1877, in broadcast_object_list
    broadcast(object_sizes_tensor, src=src, group=group)
  File "/central/groups/mthomson/zam/miniconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 1193, in broadcast
    work = default_pg.broadcast([tensor], opts)
RuntimeError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1191, unhandled system error, NCCL version 2.10.3
ncclSystemError: System call (e.g. socket, malloc) or external library call failed or device error. It can be also caused by unexpected exit of a remote peer, you can check NCCL warnings for failure reason and see if there is connection closure by a peer.



```

### Environment

```
* CUDA:
	- GPU:
		- NVIDIA Tesla P100-PCIE-16GB
		- NVIDIA Tesla P100-PCIE-16GB
		- NVIDIA Tesla P100-PCIE-16GB
		- NVIDIA Tesla P100-PCIE-16GB
	- available:         True
	- version:           10.2
* Lightning:
	- pytorch-lightning: 1.7.7
	- torch:             1.12.1
	- torchmetrics:      0.9.3
	- torchvision:       0.13.1
* Packages:
	- absl-py:           1.2.0
	- aiohttp:           3.8.3
	- aiosignal:         1.2.0
	- async-timeout:     4.0.2
	- attrs:             22.1.0
	- bottleneck:        1.3.5
	- brotlipy:          0.7.0
	- cachetools:        5.2.0
	- certifi:           2022.9.14
	- cffi:              1.15.0
	- charset-normalizer: 2.0.4
	- colorama:          0.4.4
	- conda:             22.9.0
	- conda-content-trust: 0+unknown
	- conda-package-handling: 1.8.1
	- cryptography:      36.0.0
	- deepspeed:         0.7.3
	- eutils:            0.6.0
	- fair-esm:          1.0.2
	- frozenlist:        1.3.1
	- fsspec:            2022.8.2
	- google-auth:       2.11.1
	- google-auth-oauthlib: 0.4.6
	- grpcio:            1.49.1
	- hjson:             3.1.0
	- idna:              3.3
	- importlib-metadata: 4.12.0
	- lxml:              4.9.1
	- markdown:          3.4.1
	- markupsafe:        2.1.1
	- mkl-fft:           1.3.0
	- mkl-random:        1.0.2
	- mkl-service:       2.3.0
	- multidict:         6.0.2
	- ninja:             1.10.2.3
	- numexpr:           2.7.3
	- numpy:             1.23.3
	- oauthlib:          3.2.1
	- packaging:         21.3
	- pandas:            1.4.4
	- pillow:            9.2.0
	- pip:               22.2.2
	- protobuf:          3.19.5
	- psutil:            5.9.2
	- py-cpuinfo:        8.0.0
	- pyasn1:            0.4.8
	- pyasn1-modules:    0.2.8
	- pycosat:           0.6.3
	- pycparser:         2.21
	- pydantic:          1.10.2
	- pydeprecate:       0.3.2
	- pyopenssl:         22.0.0
	- pyparsing:         3.0.9
	- pysocks:           1.7.1
	- python-dateutil:   2.8.2
	- pytorch-lightning: 1.7.7
	- pytz:              2022.1
	- pyyaml:            6.0
	- requests:          2.27.1
	- requests-oauthlib: 1.3.1
	- rsa:               4.9
	- ruamel-yaml-conda: 0.15.100
	- setuptools:        61.2.0
	- six:               1.16.0
	- tensorboard:       2.10.1
	- tensorboard-data-server: 0.6.1
	- tensorboard-plugin-wit: 1.8.1
	- toolz:             0.11.2
	- torch:             1.12.1
	- torchmetrics:      0.9.3
	- torchvision:       0.13.1
	- tqdm:              4.63.0
	- typing-extensions: 4.3.0
	- urllib3:           1.26.8
	- werkzeug:          2.2.2
	- wheel:             0.37.1
	- yarl:              1.8.1
	- zipp:              3.8.1
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- ELF
	- processor:         x86_64
	- python:            3.9.12
	- version:           #1 SMP Wed Apr 28 21:49:45 UTC 2021



```

**Comment by awaelchli** [comment]
@martinez-zacharya 
Why are you setting both of these:

```
#SBATCH --ntasks=2   # number of processor cores (i.e. tasks)
#SBATCH --ntasks-per-node=4
```

Please delete the first one and keep

```
#SBATCH --ntasks-per-node=4
```
because you have devices=4 in your Trainer.

We have an exact SLURM template [here with required sbatch variables](https://pytorch-lightning.readthedocs.io/en/stable/clouds/cluster_advanced.html#design-your-training-script). 

If you are still seeing the nccl error, make sure nccl is supported over the network. You can set NCCL_DEBUG=info or NCCL_DEBUG=warn to see more details in the logs. Alternatively try gloo as the backend.

**Comment by martinez-zacharya** [comment]
Awesome, this was the problem! Thank you for clearing that up.

**Comment by awaelchli** [comment]
@martinez-zacharya Would a warning in the logs have helped you? Like, if the Trainer would check that for example both are set incorrectly, would that have helped you fix it on your own? I think we should consider adding such a warning, or even an error if that's appropriate. What do you think?

**Comment by martinez-zacharya** [comment]
@awaelchli 100% would have helped! I've spent the last few months trying different versions of pytorch, nccl and then finally migrating completely to lightning to see if that would help. The nccl warnings and errors can be pretty obtuse and hard to decipher, which led me to trying lots of potential fixes.

**Comment by awaelchli** [comment]
Alright! Great, I am working on this #15011 to hopefully minimize the SLURM pain for future Lightning users. Thanks for raising this, and sorry you had a rough time. Please reach out here on GitHub or our slack if you have more questions in this direction.
