### ISSUE TITLE
unable to import/install pytorch_lightning

### ISSUE THREAD

**Issue by kiristern** [Lightning-AI/lightning#15037]
### Bug description

I am working in an Azure Jupyter Notebook and am unable to import `pytorch-lightning` from my environment.

I can clearly see it is in my list of downloaded libraries:
```
pytorch-lightning         1.7.7                    pypi_0    pypi
```
However cannot call the module in my script.

I then tried installing directly in my jupyter notebook: ```!pip install pytorch-lightning``` but get an ```invalid syntax error```:
```
Collecting pytorch-lightning
  Using cached https://files.pythonhosted.org/packages/7b/39/ec22cf5675473b7ea496e5fd64df49dc3122f1cfe3646d72c84f0e7fe74a/pytorch-lightning-0.5.3.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-7oa1Io/pytorch-lightning/setup.py", line 19, in <module>
        import pytorch_lightning  # noqa: E402
      File "pytorch_lightning/__init__.py", line 28, in <module>
        from .trainer.trainer import Trainer
      File "pytorch_lightning/trainer/trainer.py", line 16, in <module>
        from pytorch_lightning.trainer.callback_config_mixin import TrainerCallbackConfigMixin
      File "pytorch_lightning/trainer/callback_config_mixin.py", line 21
        f'version_{self.logger.version}',
                                       ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-7oa1Io/pytorch-lightning/
```

### How to reproduce the bug

```python
import pytorch_lightning as pl
```

### Error messages and logs

```

ImportError: No module named pytorch_lightning

```

### Environment

```

* CUDA:
        - GPU:
                - Tesla V100-PCIE-16GB
        - available:         True
        - version:           11.2
* Lightning:
        - pytorch-lightning: 1.7.7
        - torch:             1.12.1.post201
        - torchaudio:        0.12.1
        - torchmetrics:      0.10.0
        - torchvision:       0.13.0a0+8069656
* Packages:
        - absl-py:           1.2.0
        - aiohttp:           3.8.3
        - aiosignal:         1.2.0
        - asttokens:         2.0.8
        - async-timeout:     4.0.2
        - attrs:             22.1.0
        - backcall:          0.2.0
        - backports.functools-lru-cache: 1.6.4
        - brotlipy:          0.7.0
        - cachetools:        5.2.0
        - certifi:           2022.9.24
        - cffi:              1.15.1
        - charset-normalizer: 2.1.1
        - contourpy:         1.0.5
        - cryptography:      38.0.1
        - cycler:            0.11.0
        - debugpy:           1.6.3
        - decorator:         5.1.1
        - entrypoints:       0.4
        - executing:         1.1.0
        - fonttools:         4.37.4
        - frozenlist:        1.3.1
        - fsspec:            2022.8.2
        - google-auth:       2.12.0
        - google-auth-oauthlib: 0.4.6
        - grpcio:            1.49.1
        - idna:              3.4
        - ipykernel:         6.16.0
        - ipython:           8.5.0
        - jedi:              0.18.1
        - jupyter-client:    7.3.5
        - jupyter-core:      4.11.1
        - kiwisolver:        1.4.4
        - markdown:          3.4.1
        - markupsafe:        2.1.1
        - matplotlib:        3.6.0
        - matplotlib-inline: 0.1.6
        - multidict:         6.0.2
        - munkres:           1.1.4
        - nest-asyncio:      1.5.6
        - numpy:             1.23.3
        - oauthlib:          3.2.1
        - packaging:         21.3
        - pandas:            1.5.0
        - parso:             0.8.3
        - patsy:             0.5.2
        - pexpect:           4.8.0
        - pickleshare:       0.7.5
        - pillow:            9.2.0
        - pip:               22.2.2
        - ply:               3.11
        - prompt-toolkit:    3.0.31
        - protobuf:          3.19.6
        - psutil:            5.9.2
        - ptyprocess:        0.7.0
        - pure-eval:         0.2.2
        - pyasn1:            0.4.8
        - pyasn1-modules:    0.2.8
        - pycparser:         2.21
        - pydeprecate:       0.3.2
        - pygments:          2.13.0
        - pyopenssl:         22.0.0
        - pyparsing:         3.0.9
        - pyqt5:             5.15.7
        - pyqt5-sip:         12.11.0
        - pysocks:           1.7.1
        - python-dateutil:   2.8.2
        - pytorch-lightning: 1.7.7
        - pytz:              2022.4
        - pyyaml:            6.0
        - pyzmq:             24.0.1
        - requests:          2.28.1
        - requests-oauthlib: 1.3.1
        - rsa:               4.9
        - scipy:             1.9.1
        - seaborn:           0.12.0
        - setuptools:        65.4.1
        - sip:               6.6.2
        - six:               1.16.0
        - stack-data:        0.5.1
        - statsmodels:       0.13.2
        - tensorboard:       2.10.1
        - tensorboard-data-server: 0.6.1
        - tensorboard-plugin-wit: 1.8.1
        - toml:              0.10.2
        - torch:             1.12.1.post201
        - torchaudio:        0.12.1
        - torchmetrics:      0.10.0
        - torchvision:       0.13.0a0+8069656
        - tornado:           6.2
        - tqdm:              4.64.1
        - traitlets:         5.4.0
        - typing-extensions: 4.4.0
        - unicodedata2:      14.0.0
        - urllib3:           1.26.11
        - wcwidth:           0.2.5
        - werkzeug:          2.2.2
        - wheel:             0.37.1
        - yarl:              1.8.1
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.10.6
        - version:           #71~18.04.1-Ubuntu SMP Thu Jan 20 08:21:40 UTC 2022

```

**Comment by awaelchli** [comment]
Hi

> `from pytorch_lightning.trainer.callback_config_mixin import TrainerCallbackConfigMixi`

> `Using cached https://files.pythonhosted.org/packages/7b/39/ec22cf5675473b7ea496e5fd64df49dc3122f1cfe3646d72c84f0e7fe74a/pytorch-lightning-0.5.3.1.tar.gz`


From these parts of the error message we can see that somehow a very old version of Lightning got cached and is pulled for installation. Can you try uninstalling it first via

```
pip uninstall pytorch-lightning
```
and then

```
pip install -U pytorch-lightning --no-cache-dir 
```
to force downloading a new version?

**Comment by kiristern** [comment]
Hi @awaelchli thanks for your response. Oddly, when I tried importing just now, without changing anything, it all of a sudden worked. Curious as to why I had so many issues the other day... if I run into trouble again, I'll try your steps, but closing this issue for now. Thanks!
