### ISSUE TITLE
lightning.app.storage.Path tool fails to share a files between works

### ISSUE THREAD

**Issue by DaniDapena** [Lightning-AI/lightning#15039]
### Bug description

The lightning.app.storage.Path tool fails to share a file from work1 to work2 in the cloud

### How to reproduce the bug

```python
import lightning as L
from lightning_app import LightningFlow, LightningWork
from lightning_app.storage.path import Path
import torch
import os


class ModelTraining(LightningWork):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.checkpoint_dir = "lit://outputs/checkpoints"
        self.best_model = None

    def run(self):
        # create a directory
        os.makedirs(self.model_checkpoints_path, exist_ok=True)
        # make fake checkpoints
        checkpoint_1 = torch.tensor([0, 1, 2, 3, 4])
        torch.save(checkpoint_1, os.path.join(self.checkpoint_dir, "checkpoint_1.ckpt"))
        self.best_model =  os.path.join(self.checkpoint_dir, "checkpoint_1.ckpt")

class ModelDeploy(LightningWork):
    def __init__(self, *args, **kwargs):
        super().__init__()

    def run(self, best_model):
        checkpoint_1 = torch.load(best_model)
        print(checkpoint_1)

class Flow(LightningFlow):
    def __init__(self):
        super().__init__()
        self.train = ModelTraining()

        # pass the checkpoint path
        self.deploy = ModelDeploy()

    def run(self):
        self.train.run()
        self.deploy.run(self.train.best_model)


app = L.LightningApp(Flow())


## Requirements.txt:

torchvision==0.13.0
jsonargparse[signatures]
wandb==0.12.16
pyyaml==5.4.0
protobuf<4.21.0 
lightning_hpo
websockets
lightning


## in terminal 
lightning run app app.py --cloud
```

### Error messages and logs

[root.deploy] 2022-10-07T21:57:35.339Z /usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 0.23ubuntu1 is an invalid version and will not be supported in a future release
[root.deploy] 2022-10-07T21:57:35.339Z   warnings.warn(
[root.deploy] 2022-10-07T21:57:35.343Z Traceback (most recent call last):
[root.deploy] 2022-10-07T21:57:35.343Z     sys.exit(main())
[root.deploy] 2022-10-07T21:57:35.343Z   File "/home/zeus/.local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
[root.deploy] 2022-10-07T21:57:35.343Z     return self.main(*args, **kwargs)
[root.deploy] 2022-10-07T21:57:35.343Z   File "/home/zeus/.local/lib/python3.8/site-packages/click/core.py", line 1055, in main
[root.deploy] 2022-10-07T21:57:35.343Z     rv = self.invoke(ctx)
[root.deploy] 2022-10-07T21:57:35.343Z   File "/home/zeus/.local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
[root.deploy] 2022-10-07T21:57:35.343Z     return _process_result(sub_ctx.command.invoke(sub_ctx))
[root.deploy] 2022-10-07T21:57:35.343Z   File "/home/zeus/.local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
[root.deploy] 2022-10-07T21:57:35.343Z     return _process_result(sub_ctx.command.invoke(sub_ctx))
[root.deploy] 2022-10-07T21:57:35.343Z   File "/home/zeus/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
[root.deploy] 2022-10-07T21:57:35.343Z     return ctx.invoke(self.callback, **ctx.params)
[root.deploy] 2022-10-07T21:57:35.343Z   File "/home/zeus/.local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
[root.deploy] 2022-10-07T21:57:35.343Z     return __callback(*args, **kwargs)
[root.deploy] 2022-10-07T21:57:35.343Z   File "/home/zeus/.local/lib/python3.8/site-packages/lightning_launcher/cli/__main__.py", line 86, in run_work
[root.deploy] 2022-10-07T21:57:35.343Z     run_lightning_work(
[root.deploy] 2022-10-07T21:57:35.343Z   File "/home/zeus/.local/lib/python3.8/site-packages/lightning_launcher/utils.py", line 49, in wrapper
[root.deploy] 2022-10-07T21:57:35.343Z     res = func(*args, **kwargs)
[root.deploy] 2022-10-07T21:57:35.343Z   File "/home/zeus/.local/lib/python3.8/site-packages/lightning_launcher/utils.py", line 73, in wrapper
[root.deploy] 2022-10-07T21:57:35.343Z     res = func(*args, **kwargs)
[root.deploy] 2022-10-07T21:57:35.343Z   File "/home/zeus/.local/lib/python3.8/site-packages/lightning_launcher/launcher.py", line 145, in run_lightning_work
[root.deploy] 2022-10-07T21:57:35.343Z     WorkRunner(
[root.deploy] 2022-10-07T21:57:35.343Z   File "/home/zeus/.local/lib/python3.8/site-packages/lightning_app/utilities/proxies.py", line 316, in __call__
[root.deploy] 2022-10-07T21:57:35.343Z     raise e
[root.deploy] 2022-10-07T21:57:35.343Z   File "/home/zeus/.local/lib/python3.8/site-packages/lightning_app/utilities/proxies.py", line 299, in __call__
[root.deploy] 2022-10-07T21:57:35.343Z     self.run_once()
[root.deploy] 2022-10-07T21:57:35.343Z   File "/home/zeus/.local/lib/python3.8/site-packages/lightning_app/utilities/proxies.py", line 437, in run_once
[root.deploy] 2022-10-07T21:57:35.343Z     self.work.on_exception(e)
[root.deploy] 2022-10-07T21:57:35.343Z   File "/home/zeus/.local/lib/python3.8/site-packages/lightning_app/core/work.py", line 537, in on_exception
[root.deploy] 2022-10-07T21:57:35.343Z     raise exception
[root.deploy] 2022-10-07T21:57:35.343Z   File "/home/zeus/.local/lib/python3.8/site-packages/lightning_app/utilities/proxies.py", line 402, in run_once
[root.deploy] 2022-10-07T21:57:35.343Z     ret = work_run(*args, **kwargs)
[root.deploy] 2022-10-07T21:57:35.343Z   File "untitled/app_script_V1.py", line 28, in run
[root.deploy] 2022-10-07T21:57:35.343Z     checkpoint_1 = torch.load(best_model)
[root.deploy] 2022-10-07T21:57:35.343Z   File "/home/zeus/.local/lib/python3.8/site-packages/torch/serialization.py", line 699, in load
[root.deploy] 2022-10-07T21:57:35.343Z     with _open_file_like(f, 'rb') as opened_file:
[root.deploy] 2022-10-07T21:57:35.343Z   File "/home/zeus/.local/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
[root.deploy] 2022-10-07T21:57:35.343Z     return _open_file(name_or_buffer, mode)
[root.deploy] 2022-10-07T21:57:35.343Z   File "/home/zeus/.local/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
[root.deploy] 2022-10-07T21:57:35.343Z     super(_open_file, self).__init__(open(name, mode))
[root.deploy] 2022-10-07T21:57:35.343Z FileNotFoundError: [Errno 2] No such file or directory: '/content/.storage/outputs/checkpoints/checkpoint_1.ckpt'

### Environment

```
# 
#- Lightning Component: LightningFlow, LightningWork, LightningApp, lightning_app.storage.path
#- Lightning App Version: 0.6.3 (cloud)
#- PyTorch Version:  torch-1.12.0 (cloud)
#- Python version: 3.8.3 (Cloud)
#- How you installed Lightning: pip (locally) 
#- Running environment of LightningApp (e.g. local, cloud): cloud

```

### More info

The code works perfect locally

**Comment by DaniDapena** [comment]
@tchaton
