### ISSUE TITLE
module 'distutils' has no attribute 'version'

### ISSUE THREAD

**Issue by yipliu** [Lightning-AI/lightning#15041]
### Bug description

AttributeError: module 'distutils' has no attribute 'version'

### How to reproduce the bug

```python
from pytorch_lightning import LightningDataModule
```

### Error messages and logs

```

Traceback (most recent call last):
  File "/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File ".vscode-server/extensions/ms-python.python-2022.16.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/.vscode-server/extensions/ms-python.python-2022.16.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/.vscode-server/extensions/ms-python.python-2022.16.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/.vscode-server/extensions/ms-python.python-2022.16.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/.vscode-server/extensions/ms-python.python-2022.16.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/.vscode-server/extensions/ms-python.python-2022.16.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "", line 10, in <module>
    from pytorch_lightning import LightningDataModule
  File "/lib/python3.8/site-packages/pytorch_lightning/__init__.py", line 34, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/lib/python3.8/site-packages/pytorch_lightning/callbacks/__init__.py", line 26, in <module>
    from pytorch_lightning.callbacks.pruning import ModelPruning
  File "lib/python3.8/site-packages/pytorch_lightning/callbacks/pruning.py", line 30, in <module>
    from pytorch_lightning.core.module import LightningModule
  File "python3.8/site-packages/pytorch_lightning/core/__init__.py", line 16, in <module>
    from pytorch_lightning.core.module import LightningModule
  File "/lib/python3.8/site-packages/pytorch_lightning/core/module.py", line 41, in <module>
    from pytorch_lightning.loggers import Logger, LoggerCollection
  File "python3.8/site-packages/pytorch_lightning/loggers/__init__.py", line 23, in <module>
    from pytorch_lightning.loggers.tensorboard import TensorBoardLogger
  File "/lib/python3.8/site-packages/pytorch_lightning/loggers/tensorboard.py", line 26, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "lib/python3.8/site-packages/torch/utils/tensorboard/__init__.py", line 4, in <module>
    LooseVersion = distutils.version.LooseVersion
AttributeError: module 'distutils' has no attribute 'version'

```

### Environment

```

#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (1.7.1):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (1.11.0 ):
#- Python version (3.8):
#- OS (Linux):
#- CUDA/cuDNN version: cuda11.3
#- GPU models and configuration: 
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):

```

**Comment by awaelchli** [comment]
@yipliu Could you fill out the full bug report template with the version information. Otherwise it will be unlikely that we can help. See the section "Environment" [here](https://github.com/Lightning-AI/lightning/issues/new?assignees=&labels=needs+triage&template=1_bug_report.yaml).

**Comment by awaelchli** [comment]
Related to this issue #9900

**Comment by ecolss** [comment]
Or try this? https://github.com/pytorch/pytorch/issues/69894#issuecomment-1080635462
