### ISSUE TITLE
Unable to pickle (dump) LightningModule object if RichProgressBar callback is added to Trainer

### ISSUE THREAD

**Issue by krshrimali** [Lightning-AI/lightning#15212]
### Bug description

Adding `RichProgressBar` callback to the `Trainer` initialization, and then attempting to save the `LightningModule` object gives a `TypeError`:

```bash
Traceback (most recent call last):
  File "/home/krshrimali/bug.py", line 12, in <module>
    pickle.dumps(boring_model)
TypeError: cannot pickle '_thread.RLock' object
```

After some debugging with the help of @tchaton, here is where I could find the callback object:

```bash
> /home/krshrimali/anaconda3/envs/cloud_weights/lib/python3.9/pickle.py(607)save()
-> self.save_reduce(obj=obj, *rv)
(Pdb) obj
<pytorch_lightning.callbacks.progress.rich_progress.CustomProgress object at 0x7f7c096e7520>
```

(after disabling fast pickling)

If one tries to save the model before `trainer.fit` is called, `pickle.dumps(model)` works. After suggestion with @rohitgr7 - if `model.trainer = None` is done after `trainer.fit`, the error is gone. Not saying that it's a solution, but can help us improve the teardown method.

We should also write tests to make sure it works? `torch.save` is one of the features that everyone will expect to just work with LightningModules and Trainer.

### How to reproduce the bug

```python
from pytorch_lightning.demos.boring_classes import BoringModel
from pytorch_lightning import Trainer
from pytorch_lightning.callbacks import RichProgressBar

import pickle


boring_model = BoringModel()
trainer = Trainer(callbacks=[RichProgressBar()], max_epochs=1)
trainer.fit(model=boring_model)
# Uncomment the following to get rid of the error (not a solution)
# boring_model.trainer = None
pickle.dumps(boring_model)
```

### Error messages and logs

```bash
Traceback (most recent call last):
  File "/home/krshrimali/bug.py", line 12, in <module>
    pickle.dumps(boring_model)
TypeError: cannot pickle '_thread.RLock' object
```

### Environment

```

#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
- PyTorch Lightning Version (e.g., 1.5.0): 1.7.1
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 1.10):
#- Python version (e.g., 3.9): 3.9.13
#- OS (e.g., Linux): Linux (Pop OS 22.04)
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):

```

**Comment by rohitgr7** [comment]
regarding this, do you think it's worth de-attaching the trainer? since we only need to save the model.
