### ISSUE TITLE
Cannot init `wandb` if `.git/` was pushed to the cloud because `git rev-parse --show-toplevel` crashes in the cloud

### ISSUE THREAD

**Issue by KogaiIrina** [Lightning-AI/lightning#15248]
### Bug description

```
git rev-parse --show-toplevel
```
fails when running the app in the cloud with
```
stderr: 'fatal: detected dubious ownership in repository at '/content
```

This causes `wandb.init` to crash too.

The workaround is to add `.git/` to `.lightningignore`, but this may not always be an option.

### How to reproduce the bug

```python
$ git clone git@github.com:KogayIrina/masterpiece-creator.git
# next, checkout the commit where the error is reproducible
$ git checkout 910567557c679335a3b3a5dd89e3f7ee58d13200
$ pip install -r requirements.txt
$ lightning run app app.py --cloud


Then wait for the app to start (it can take a while 😅), open it, enter the prompt, and observe the crash in the error logs.
```

### Error messages and logs

```
[root.work] 2022-10-22T16:03:32.254Z wandb: ERROR Abnormal program exit
[root.work] 2022-10-22T16:03:32.509Z INFO: Traceback (most recent call last):
[root.work] 2022-10-22T16:03:32.510Z INFO:   File "/home/zeus/.local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1075, in init
[root.work] 2022-10-22T16:03:32.510Z     wi.setup(kwargs)
[root.work] 2022-10-22T16:03:32.510Z INFO:   File "/home/zeus/.local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 165, in setup
[root.work] 2022-10-22T16:03:32.510Z     self._wl = wandb_setup.setup()
[root.work] 2022-10-22T16:03:32.510Z INFO:   File "/home/zeus/.local/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 312, in setup
[root.work] 2022-10-22T16:03:32.510Z     ret = _setup(settings=settings)
[root.work] 2022-10-22T16:03:32.510Z INFO:   File "/home/zeus/.local/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 307, in _setup
[root.work] 2022-10-22T16:03:32.510Z     wl = _WandbSetup(settings=settings)
[root.work] 2022-10-22T16:03:32.510Z INFO:   File "/home/zeus/.local/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 293, in __init__
[root.work] 2022-10-22T16:03:32.510Z     _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
[root.work] 2022-10-22T16:03:32.510Z INFO:   File "/home/zeus/.local/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 100, in __init__
[root.work] 2022-10-22T16:03:32.510Z     self._settings = self._settings_setup(settings, self._early_logger)
[root.work] 2022-10-22T16:03:32.510Z INFO:   File "/home/zeus/.local/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 130, in _settings_setup
[root.work] 2022-10-22T16:03:32.510Z     s._infer_run_settings_from_environment(_logger=early_logger)
[root.work] 2022-10-22T16:03:32.510Z INFO:   File "/home/zeus/.local/lib/python3.8/site-packages/wandb/sdk/wandb_settings.py", line 1428, in _infer_run_settings_from_environment
[root.work] 2022-10-22T16:03:32.510Z     program_relpath = self.program_relpath or _get_program_relpath_from_gitrepo(
[root.work] 2022-10-22T16:03:32.510Z INFO:   File "/home/zeus/.local/lib/python3.8/site-packages/wandb/sdk/wandb_settings.py", line 139, in _get_program_relpath_from_gitrepo
[root.work] 2022-10-22T16:03:32.510Z     root = repo.root
[root.work] 2022-10-22T16:03:32.510Z INFO:   File "/home/zeus/.local/lib/python3.8/site-packages/wandb/sdk/lib/git.py", line 65, in root
[root.work] 2022-10-22T16:03:32.510Z     return self.repo.git.rev_parse("--show-toplevel")
[root.work] 2022-10-22T16:03:32.510Z INFO:   File "/home/zeus/.local/lib/python3.8/site-packages/git/cmd.py", line 696, in <lambda>
[root.work] 2022-10-22T16:03:32.510Z     return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
[root.work] 2022-10-22T16:03:32.510Z INFO:   File "/home/zeus/.local/lib/python3.8/site-packages/git/cmd.py", line 1270, in _call_process
[root.work] 2022-10-22T16:03:32.510Z     return self.execute(call, **exec_kwargs)
[root.work] 2022-10-22T16:03:32.510Z INFO:   File "/home/zeus/.local/lib/python3.8/site-packages/git/cmd.py", line 1064, in execute
[root.work] 2022-10-22T16:03:32.510Z     raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
[root.work] 2022-10-22T16:03:32.510Z INFO: git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
[root.work] 2022-10-22T16:03:32.510Z   cmdline: git rev-parse --show-toplevel
[root.work] 2022-10-22T16:03:32.510Z   stderr: 'fatal: detected dubious ownership in repository at '/content'
[root.work] 2022-10-22T16:03:32.510Z To add an exception for this directory, call:
[root.work] 2022-10-22T16:03:32.510Z    git config --global --add safe.directory /content'
[root.work] 2022-10-22T16:03:32.510Z INFO: 
[root.work] 2022-10-22T16:03:32.510Z The above exception was the direct cause of the following exception:
[root.work] 2022-10-22T16:03:32.510Z INFO: Traceback (most recent call last):
[root.work] 2022-10-22T16:03:32.510Z INFO:   File "/home/zeus/.local/lib/python3.8/site-packages/gradio/routes.py", line 298, in run_predict
[root.work] 2022-10-22T16:03:32.510Z     output = await app.blocks.process_api(
[root.work] 2022-10-22T16:03:32.510Z INFO:   File "/home/zeus/.local/lib/python3.8/site-packages/gradio/blocks.py", line 790, in process_api
[root.work] 2022-10-22T16:03:32.510Z     result = await self.call_function(fn_index, inputs, iterator)
[root.work] 2022-10-22T16:03:32.510Z INFO:   File "/home/zeus/.local/lib/python3.8/site-packages/gradio/blocks.py", line 697, in call_function
[root.work] 2022-10-22T16:03:32.510Z     prediction = await anyio.to_thread.run_sync(
[root.work] 2022-10-22T16:03:32.510Z INFO:   File "/home/zeus/.local/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
[root.work] 2022-10-22T16:03:32.510Z     return await get_asynclib().run_sync_in_worker_thread(
[root.work] 2022-10-22T16:03:32.510Z INFO:   File "/home/zeus/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
[root.work] 2022-10-22T16:03:32.510Z     return await future
[root.work] 2022-10-22T16:03:32.511Z INFO:   File "/home/zeus/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
[root.work] 2022-10-22T16:03:32.511Z     result = context.run(func, *args)
[root.work] 2022-10-22T16:03:32.511Z INFO:   File "app.py", line 14, in predict
[root.work] 2022-10-22T16:03:32.511Z     da = self.model.create(
[root.work] 2022-10-22T16:03:32.511Z INFO:   File "/home/zeus/.local/lib/python3.8/site-packages/discoart/create.py", line 217, in create
[root.work] 2022-10-22T16:03:32.511Z     da = do_run(
[root.work] 2022-10-22T16:03:32.511Z INFO:   File "/home/zeus/.local/lib/python3.8/site-packages/discoart/runner.py", line 407, in do_run
[root.work] 2022-10-22T16:03:32.511Z     with wandb.init(
[root.work] 2022-10-22T16:03:32.511Z INFO:   File "/home/zeus/.local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1116, in init
[root.work] 2022-10-22T16:03:32.511Z     raise Exception("problem") from error_seen
[root.work] 2022-10-22T16:03:32.511Z INFO: Exception: problem
```

### Environment

```

#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow): LightningWork
#- PyTorch Lightning Version (e.g., 1.5.0): N/A
#- Lightning App Version (e.g., 0.5.2): 0.7.0
#- PyTorch Version (e.g., 1.10): N/A
#- Python version (e.g., 3.9): Lightning Cloud
#- OS (e.g., Linux): Linux
#- CUDA/cuDNN version: Lightning Cloud
#- GPU models and configuration: `CloudCompute('gpu-fast')`
#- How you installed Lightning(`conda`, `pip`, source): `pip`
#- Running environment of LightningApp (e.g. local, cloud): cloud

```

**Comment by awaelchli** [comment]
Hi @KogayIrina 

Thanks for reporting this. So the error occurs here in wandb's git utils, when determining the repo root: 
https://github.com/wandb/wandb/blob/50258c1d316108fad85f89e81b349db7eead921b/wandb/sdk/lib/git.py#L62-L65

Pretty sure it is not because of wandb. This is a git error that seems to appear when the user calling the git command is not the same as the one owning the repository. 

@hhsecond @alecmerdler could you comment on how we set the ownership of `/content`? Is there something we potentially need to change there?
