### ISSUE TITLE
StochasticWeightAveraging throws error when using trainer.tune

### ISSUE THREAD

**Issue by julpegor** [Lightning-AI/lightning#15298]
### Bug description

When using `pytorch_lightning.callbacks.StochasticWeightAveraging` as a callback for the `trainer`, in combination with `trainer.tune(model)` an error is thrown. Tested it with `auto_lr_find` and `auto_scale_batch_size`.

When no autotuning is applied the training (and `pytorch_lightning.callbacks.StochasticWeightAveraging`) works just fine.

### How to reproduce the bug

```python
import torch
import pytorch_lightning as pl


class ExampleDataset(torch.utils.data.Dataset):

    def __len__(self):
        return 1000

    def __getitem__(self, index):
        return torch.rand(3), torch.rand(3)


class ExampleModel(pl.LightningModule):

    def __init__(self) -> None:
        super().__init__()
        self.model = torch.nn.Linear(3, 3)
        self.lr = 1e-5
        self.batch_size = 2

    def configure_optimizers(self):
        return torch.optim.Adam(self.model.parameters(), self.lr)

    def training_step(self, batch):
        return ((self.model(batch[0]) - batch[1])**2).sum()

    def train_dataloader(self):
        return torch.utils.data.DataLoader(ExampleDataset(), batch_size=self.batch_size)


trainer = pl.Trainer(
    callbacks=[pl.callbacks.StochasticWeightAveraging(swa_lrs=1e-2)],
    auto_lr_find=True,
    # auto_scale_batch_size="power",
    )
model = ExampleModel()
trainer.tune(model)
trainer.fit(model)
```

### Error messages and logs

```
Traceback (most recent call last):
  File "train2.py", line 38, in <module>
    trainer.tune(model)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/base/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1052, in tune
    result = self.tuner._tune(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/base/lib/python3.8/site-packages/pytorch_lightning/tuner/tuning.py", line 70, in _tune
    result["lr_find"] = lr_find(self.trainer, model, **lr_find_kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/base/lib/python3.8/site-packages/pytorch_lightning/tuner/lr_finder.py", line 227, in lr_find
    trainer.save_checkpoint(ckpt_path)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/base/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 2427, in save_checkpoint
    self._checkpoint_connector.save_checkpoint(filepath, weights_only=weights_only, storage_options=storage_options)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/base/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 458, in save_checkpoint
    _checkpoint = self.dump_checkpoint(weights_only)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/base/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 388, in dump_checkpoint
    checkpoint["callbacks"] = self.trainer._call_callbacks_state_dict()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/base/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1608, in _call_callbacks_state_dict
    state_dict = callback.state_dict()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/base/lib/python3.8/site-packages/pytorch_lightning/callbacks/stochastic_weight_avg.py", line 326, in state_dict
    "average_model_state": None if self._average_model is None else self._average_model.state_dict(),
AttributeError: 'StochasticWeightAveraging' object has no attribute '_average_model'
```

### Environment

- Lightning Component
  - Trainer
  - LightningModule
  - callbacks.StochasticWeightAveraging
- PyTorch Lightning Version: 1.7.7
- PyTorch Version: 1.14.0.dev20221017
- Python version: 3.8.13
- OS: MacOS
- How you installed Lightning: pip

**Comment by rohitgr7** [comment]
This must be fixed on master. Will be released soon

**Comment by julpegor** [comment]
I can confirm that it works with the master.

New minimal code:
```python
import torch
import lightning as lt

class ExampleDataset(torch.utils.data.Dataset):

    def __len__(self):
        return 1000

    def __getitem__(self, index):
        return torch.rand(3), torch.rand(3)


class ExampleModel(lt.LightningModule):

    def __init__(self) -> None:
        super().__init__()
        self.model = torch.nn.Linear(3, 3)
        self.lr = 1e-5
        self.batch_size = 2

    def configure_optimizers(self):
        return torch.optim.Adam(self.model.parameters(), self.lr)

    def training_step(self, batch):
        return ((self.model(batch[0]) - batch[1])**2).sum()

    def train_dataloader(self):
        return torch.utils.data.DataLoader(ExampleDataset(), batch_size=self.batch_size)


trainer = lt.Trainer(
    callbacks=[lt.pytorch.callbacks.StochasticWeightAveraging(swa_lrs=1e-2)],
    auto_lr_find=True,
    auto_scale_batch_size="power",
    )
model = ExampleModel()
trainer.tune(model)
trainer.fit(model)
```
