### ISSUE TITLE
I get an error about 'No module named 'pytorch_lightning.utilities.argparse_utils''

### ISSUE THREAD

**Issue by sherwincn** [Lightning-AI/lightning#15451]
### Bug description

When I load a '.ckpt' model in pytorch model, I get an error 'No module named 'pytorch_lightning.utilities.argparse_utils'. Could you tell me how to load the ckpt model in pytorch or address this issue?

### How to reproduce the bug

```python
load an ckpt model in mmcv.
```

### Error messages and logs

```

2022-11-01 22:39:17,087 - mmseg - INFO - Set random seed to 753555044, deterministic: False
/root/paddlejob/workspace/chensilin/mmsegmentation/mmseg/models/backbones/resnet.py:431: UserWarning: DeprecationWarning: pretrained is a deprecated, please use "init_cfg" instead
  warnings.warn('DeprecationWarning: pretrained is a deprecated, '
/root/paddlejob/workspace/chensilin/mmsegmentation/mmseg/models/backbones/resnet.py:431: UserWarning: DeprecationWarning: pretrained is a deprecated, please use "init_cfg" instead
  warnings.warn('DeprecationWarning: pretrained is a deprecated, '
/root/paddlejob/workspace/chensilin/mmsegmentation/mmseg/models/backbones/resnet.py:431: UserWarning: DeprecationWarning: pretrained is a deprecated, please use "init_cfg" instead
  warnings.warn('DeprecationWarning: pretrained is a deprecated, '
/root/paddlejob/workspace/chensilin/mmsegmentation/mmseg/models/backbones/resnet.py:431: UserWarning: DeprecationWarning: pretrained is a deprecated, please use "init_cfg" instead
  warnings.warn('DeprecationWarning: pretrained is a deprecated, '
/root/paddlejob/workspace/chensilin/mmsegmentation/mmseg/models/losses/cross_entropy_loss.py:235: UserWarning: Default ``avg_non_ignore`` is False, if you would like to ignore the certain label and average loss over non-ignore labels, which is the same with PyTorch official cross_entropy, set ``avg_non_ignore=True``.
  warnings.warn(
/root/paddlejob/workspace/chensilin/mmsegmentation/mmseg/models/losses/cross_entropy_loss.py:235: UserWarning: Default ``avg_non_ignore`` is False, if you would like to ignore the certain label and average loss over non-ignore labels, which is the same with PyTorch official cross_entropy, set ``avg_non_ignore=True``.
  warnings.warn(
/root/paddlejob/workspace/chensilin/mmsegmentation/mmseg/models/losses/cross_entropy_loss.py:235: UserWarning: Default ``avg_non_ignore`` is False, if you would like to ignore the certain label and average loss over non-ignore labels, which is the same with PyTorch official cross_entropy, set ``avg_non_ignore=True``.
  warnings.warn(
/root/paddlejob/workspace/chensilin/mmsegmentation/mmseg/models/losses/cross_entropy_loss.py:235: UserWarning: Default ``avg_non_ignore`` is False, if you would like to ignore the certain label and average loss over non-ignore labels, which is the same with PyTorch official cross_entropy, set ``avg_non_ignore=True``.
  warnings.warn(
2022-11-01 22:39:18,776 - mmseg - INFO - initialize ResNet with init_cfg {'type': 'Pretrained', 'checkpoint': '/root/paddlejob/workspace/chensilin/mmsegmentation/seco_resnet50_1m.ckpt'}
2022-11-01 22:39:18,776 - mmcv - INFO - load model from: /root/paddlejob/workspace/chensilin/mmsegmentation/seco_resnet50_1m.ckpt
2022-11-01 22:39:18,777 - mmcv - INFO - load checkpoint from local path: /root/paddlejob/workspace/chensilin/mmsegmentation/seco_resnet50_1m.ckpt
Traceback (most recent call last):
  File "tools/train.py", line 242, in <module>
    main()
  File "tools/train.py", line 202, in main
    model.init_weights()
  File "/root/paddlejob/workspace/chensilin/openmmlab/lib/python3.8/site-packages/mmcv/runner/base_module.py", line 117, in init_weights
    m.init_weights()
  File "/root/paddlejob/workspace/chensilin/openmmlab/lib/python3.8/site-packages/mmcv/runner/base_module.py", line 106, in init_weights
    initialize(self, self.init_cfg)
  File "/root/paddlejob/workspace/chensilin/openmmlab/lib/python3.8/site-packages/mmcv/cnn/utils/weight_init.py", line 636, in initialize
    _initialize(module, cp_cfg)
  File "/root/paddlejob/workspace/chensilin/openmmlab/lib/python3.8/site-packages/mmcv/cnn/utils/weight_init.py", line 539, in _initialize
    func(module)
  File "/root/paddlejob/workspace/chensilin/openmmlab/lib/python3.8/site-packages/mmcv/cnn/utils/weight_init.py", line 509, in __call__
    load_checkpoint(
  File "/root/paddlejob/workspace/chensilin/openmmlab/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 638, inload_checkpoint
    checkpoint = _load_checkpoint(filename, map_location, logger)
  File "/root/paddlejob/workspace/chensilin/openmmlab/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 572, in_load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "/root/paddlejob/workspace/chensilin/openmmlab/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 314, inload_checkpoint
    return checkpoint_loader(filename, map_location)  # type: ignore
  File "/root/paddlejob/workspace/chensilin/openmmlab/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 334, inload_from_local
    checkpoint = torch.load(filename, map_location=map_location)
  File "/root/paddlejob/workspace/chensilin/openmmlab/lib/python3.8/site-packages/torch/serialization.py", line 607, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/root/paddlejob/workspace/chensilin/openmmlab/lib/python3.8/site-packages/torch/serialization.py", line 882, in _load
    result = unpickler.load()
  File "/root/paddlejob/workspace/chensilin/openmmlab/lib/python3.8/site-packages/torch/serialization.py", line 875, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'pytorch_lightning.utilities.argparse_utils'
Traceback (most recent call last):
  File "tools/train.py", line 242, in <module>
    main()
  File "tools/train.py", line 202, in main
    model.init_weights()
  File "/root/paddlejob/workspace/chensilin/openmmlab/lib/python3.8/site-packages/mmcv/runner/base_module.py", line 117, in init_weights
    m.init_weights()
  File "/root/paddlejob/workspace/chensilin/openmmlab/lib/python3.8/site-packages/mmcv/runner/base_module.py", line 106, in init_weights
    initialize(self, self.init_cfg)
  File "/root/paddlejob/workspace/chensilin/openmmlab/lib/python3.8/site-packages/mmcv/cnn/utils/weight_init.py", line 636, in initialize
    _initialize(module, cp_cfg)
  File "/root/paddlejob/workspace/chensilin/openmmlab/lib/python3.8/site-packages/mmcv/cnn/utils/weight_init.py", line 539, in _initialize
    func(module)
  File "/root/paddlejob/workspace/chensilin/openmmlab/lib/python3.8/site-packages/mmcv/cnn/utils/weight_init.py", line 509, in __call__
    load_checkpoint(
  File "/root/paddlejob/workspace/chensilin/openmmlab/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 638, inload_checkpoint
    checkpoint = _load_checkpoint(filename, map_location, logger)
  File "/root/paddlejob/workspace/chensilin/openmmlab/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 572, in_load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "/root/paddlejob/workspace/chensilin/openmmlab/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 314, inload_checkpoint
    return checkpoint_loader(filename, map_location)  # type: ignore
  File "/root/paddlejob/workspace/chensilin/openmmlab/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 334, inload_from_local
    checkpoint = torch.load(filename, map_location=map_location)
  File "/root/paddlejob/workspace/chensilin/openmmlab/lib/python3.8/site-packages/torch/serialization.py", line 607, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/root/paddlejob/workspace/chensilin/openmmlab/lib/python3.8/site-packages/torch/serialization.py", line 882, in _load
    result = unpickler.load()
  File "/root/paddlejob/workspace/chensilin/openmmlab/lib/python3.8/site-packages/torch/serialization.py", line 875, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'pytorch_lightning.utilities.argparse_utils'
Traceback (most recent call last):
  File "tools/train.py", line 242, in <module>
    main()
  File "tools/train.py", line 202, in main
    model.init_weights()
  File "/root/paddlejob/workspace/chensilin/openmmlab/lib/python3.8/site-packages/mmcv/runner/base_module.py", line 117, in init_weights
    m.init_weights()
  File "/root/paddlejob/workspace/chensilin/openmmlab/lib/python3.8/site-packages/mmcv/runner/base_module.py", line 106, in init_weights
    initialize(self, self.init_cfg)
  File "/root/paddlejob/workspace/chensilin/openmmlab/lib/python3.8/site-packages/mmcv/cnn/utils/weight_init.py", line 636, in initialize
    _initialize(module, cp_cfg)
  File "/root/paddlejob/workspace/chensilin/openmmlab/lib/python3.8/site-packages/mmcv/cnn/utils/weight_init.py", line 539, in _initialize
    func(module)
  File "/root/paddlejob/workspace/chensilin/openmmlab/lib/python3.8/site-packages/mmcv/cnn/utils/weight_init.py", line 509, in __call__
    load_checkpoint(
  File "/root/paddlejob/workspace/chensilin/openmmlab/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 638, inload_checkpoint
    checkpoint = _load_checkpoint(filename, map_location, logger)
  File "/root/paddlejob/workspace/chensilin/openmmlab/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 572, in_load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "/root/paddlejob/workspace/chensilin/openmmlab/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 314, inload_checkpoint
    return checkpoint_loader(filename, map_location)  # type: ignore
  File "/root/paddlejob/workspace/chensilin/openmmlab/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 334, inload_from_local
    checkpoint = torch.load(filename, map_location=map_location)
  File "/root/paddlejob/workspace/chensilin/openmmlab/lib/python3.8/site-packages/torch/serialization.py", line 607, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/root/paddlejob/workspace/chensilin/openmmlab/lib/python3.8/site-packages/torch/serialization.py", line 882, in _load
    result = unpickler.load()
  File "/root/paddlejob/workspace/chensilin/openmmlab/lib/python3.8/site-packages/torch/serialization.py", line 875, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'pytorch_lightning.utilities.argparse_utils'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 217048) of binary: /root/paddlejob/workspace/chensilin/openmmlab/bin/python
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/paddlejob/workspace/chensilin/openmmlab/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/root/paddlejob/workspace/chensilin/openmmlab/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/root/paddlejob/workspace/chensilin/openmmlab/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/root/paddlejob/workspace/chensilin/openmmlab/lib/python3.8/site-packages/torch/distributed/run.py", line 689, in run
    elastic_launch(
  File "/root/paddlejob/workspace/chensilin/openmmlab/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line116, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/paddlejob/workspace/chensilin/openmmlab/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line244, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

```

cc @awaelchli @ananthsub @ninginthecloud @rohitgr7 @otaj

**Comment by awaelchli** [comment]
@sherwincn Could you please fill out the section under "Environment", with the Lightning version being the most important one for us to be able to help.

**Comment by awaelchli** [comment]
> load an ckpt model in mmcv.

I couldn't find any PyTorch Lightning code in this repository. Could you please provide more information?

There was an issue with checkpoints being saved prior to Lightning 1.4, and when loading checkpionts in Lightning we apply a patch in future versions:

https://github.com/Lightning-AI/lightning/blob/f8675ff8bef5d862d1b8d2a7e39a4d880084f87c/src/pytorch_lightning/utilities/migration.py#L26

If you need to load a "broken" checkpoint like this one in your PyTorch code, you can either do

```py
from pytorch_lightning.utilities.migration import pl_legacy_patch

with pl_legacy_patch():
    # load your checkpoint here
```

OR

you can copy the function in the link above and use it in your code without needing to install PyTorch Lightning. If you see any further issues, feel free to share your checkpoint file here and we can take a closer look.

**Comment by awaelchli** [comment]
@sherwincn if you could take a look at my previous answer, which should unblock you. Please let me know if it helps.

**Comment by sherwincn** [comment]
My code is based on pytorch but the params file (.ckpt) is based on lightning. I wannna load the params in pytorch frame. What should I do?

**Comment by awaelchli** [comment]
See my answer above. 

> If you need to load a "broken" checkpoint like this one in your PyTorch code, you can either do
...

**Comment by awaelchli** [comment]
@sherwincn did you eventually manage to resolve this issue?
