### ISSUE TITLE
`BuildConfig` not working

### ISSUE THREAD

**Issue by aniketmaurya** [Lightning-AI/lightning#15495]
### Bug description

I want to install `flask` from `BuildConfig` rather than having a requirements.txt file that will install `flask` in all the components. But it doesn't work!

### How to reproduce the bug

```python
import lightning as L

class SampleWork(L.LightningWork):
    def __init__(self):
        cloud_build_config = L.BuildConfig(requirements=["flask"]
        )
        super().__init__(cloud_build_config=cloud_build_config)
    
    def run(self):
        import flask
        print("flask imported succesfully")


class Root(L.LightningFlow):
    def __init__(self):
        super().__init__()
        self.server = SampleWork()
    
    def run(self, *args, **kwargs) -> None:
        self.server.run()

app = L.LightningApp(Root())
```

### Error messages and logs

```

[root.server] 2022-11-03T05:48:30.916Z Traceback (most recent call last):
[root.server] 2022-11-03T05:48:30.916Z     sys.exit(main())
[root.server] 2022-11-03T05:48:30.916Z   File "/content/venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
[root.server] 2022-11-03T05:48:30.916Z     return self.main(*args, **kwargs)
[root.server] 2022-11-03T05:48:30.916Z   File "/content/venv/lib/python3.8/site-packages/click/core.py", line 1055, in main
[root.server] 2022-11-03T05:48:30.916Z     rv = self.invoke(ctx)
[root.server] 2022-11-03T05:48:30.916Z   File "/content/venv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
[root.server] 2022-11-03T05:48:30.916Z     return _process_result(sub_ctx.command.invoke(sub_ctx))
[root.server] 2022-11-03T05:48:30.916Z   File "/content/venv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
[root.server] 2022-11-03T05:48:30.916Z     return _process_result(sub_ctx.command.invoke(sub_ctx))
[root.server] 2022-11-03T05:48:30.916Z   File "/content/venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
[root.server] 2022-11-03T05:48:30.916Z     return ctx.invoke(self.callback, **ctx.params)
[root.server] 2022-11-03T05:48:30.916Z   File "/content/venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
[root.server] 2022-11-03T05:48:30.916Z     return __callback(*args, **kwargs)
[root.server] 2022-11-03T05:48:30.916Z   File "/content/venv/lib/python3.8/site-packages/lightning_launcher/cli/__main__.py", line 87, in run_work
[root.server] 2022-11-03T05:48:30.916Z     run_lightning_work(
[root.server] 2022-11-03T05:48:30.916Z   File "/content/venv/lib/python3.8/site-packages/lightning_launcher/utils.py", line 50, in wrapper
[root.server] 2022-11-03T05:48:30.916Z     res = func(*args, **kwargs)
[root.server] 2022-11-03T05:48:30.916Z   File "/content/venv/lib/python3.8/site-packages/lightning_launcher/utils.py", line 75, in wrapper
[root.server] 2022-11-03T05:48:30.916Z     res = func(*args, **kwargs)
[root.server] 2022-11-03T05:48:30.916Z   File "/content/venv/lib/python3.8/site-packages/lightning_launcher/launcher.py", line 161, in run_lightning_work
[root.server] 2022-11-03T05:48:30.916Z     WorkRunner(
[root.server] 2022-11-03T05:48:30.916Z   File "/content/venv/lib/python3.8/site-packages/lightning/app/utilities/proxies.py", line 336, in __call__
[root.server] 2022-11-03T05:48:30.916Z     raise e
[root.server] 2022-11-03T05:48:30.916Z   File "/content/venv/lib/python3.8/site-packages/lightning/app/utilities/proxies.py", line 319, in __call__
[root.server] 2022-11-03T05:48:30.916Z     self.run_once()
[root.server] 2022-11-03T05:48:30.916Z   File "/content/venv/lib/python3.8/site-packages/lightning/app/utilities/proxies.py", line 457, in run_once
[root.server] 2022-11-03T05:48:30.916Z     self.work.on_exception(e)
[root.server] 2022-11-03T05:48:30.916Z   File "/content/venv/lib/python3.8/site-packages/lightning/app/core/work.py", line 550, in on_exception
[root.server] 2022-11-03T05:48:30.916Z     raise exception
[root.server] 2022-11-03T05:48:30.916Z   File "/content/venv/lib/python3.8/site-packages/lightning/app/utilities/proxies.py", line 422, in run_once
[root.server] 2022-11-03T05:48:30.916Z     ret = work_run(*args, **kwargs)
[root.server] 2022-11-03T05:48:30.916Z   File "build_config.py", line 10, in run
[root.server] 2022-11-03T05:48:30.916Z     import flask
[root.server] 2022-11-03T05:48:30.916Z ModuleNotFoundError: No module named 'flask'
```

### Environment

```
Running on latest lightning with default CloudCompute
```

cc @tchaton @rohitgr7

**Comment by kaushikb11** [comment]
Workaround fix for it

```python
import lightning as L

class CustomBuildConfig(L.BuildConfig):

    def build_commands(self):
        return ["python -m pip install flask"]


class SampleWork(L.LightningWork):
    def __init__(self):
        cloud_build_config = CustomBuildConfig()
        super().__init__(cloud_build_config=cloud_build_config)

    def run(self):
        import flask
        print("flask imported succesfully")


class Root(L.LightningFlow):
    def __init__(self):
        super().__init__()
        self.server = SampleWork()

    def run(self, *args, **kwargs) -> None:
        self.server.run()

app = L.LightningApp(Root())
```

**Comment by rohitgr7** [comment]
> Workaround fix is to do python -m pip install x to install modules

well, yes and no
if you are using an existing name, still won't work
