### ISSUE TITLE
`Drive.delete()` Doesn't Work in the Cloud

### ISSUE THREAD

**Issue by alecmerdler** [Lightning-AI/lightning#15539]
### Bug description

It appears that `Drive.delete()` does not actually delete the file from the Drive when running in the cloud. The app I am building stores user submitted audio/video files, and we need to [delete these files](https://github.com/Lightning-AI/LAI-Echo-App/blob/main/echo/components/fileserver.py#L164) when the user deletes some other objects from the database.

I've provided a minimal `app.py` that can be used below.

### How to reproduce the bug

```python
import pathlib
import os

from lightning import LightningApp, LightningFlow, LightningWork, CloudCompute
from lightning.app.storage import Drive


class Worker(LightningWork):
    def __init__(self, drive: Drive):
        super().__init__(cloud_compute=CloudCompute("cpu-small"))
        self._drive = drive

    def run(self):
        path = pathlib.Path("./testfile.txt")
        path.touch()

        self._drive.put(path.name)
        self._drive.delete(path.name)
        os.remove(path.name)

        try:
            self._drive.get(path=path.name)
            # Should not reach here
            raise Exception("File should not exist")
        except Exception as e:
            # Expected exception
            return


class Root(LightningFlow):
    def __init__(self):
        super().__init__()
        self._drive = Drive(id="lit://root", component_name="root")
        self.worker = Worker(drive=self._drive)

    def run(self):
        self.worker.run()
        self._exit()


app = LightningApp(Root())
```

### Error messages and logs

```
Traceback (most recent call last):
  File "/content/venv/lib/python3.8/site-packages/s3fs/core.py", line 111, in _error_wrapper
    return await func(*args, **kwargs)
  File "/content/venv/lib/python3.8/site-packages/aiobotocore/client.py", line 358, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (403) when calling the DeleteObjects operation: Forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/content/venv/bin/lightning-cloud-launcher", line 8, in <module>
    sys.exit(main())
  File "/content/venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/content/venv/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/content/venv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/content/venv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/content/venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/content/venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/content/venv/lib/python3.8/site-packages/lightning_launcher/cli/__main__.py", line 87, in run_work
    run_lightning_work(
  File "/content/venv/lib/python3.8/site-packages/lightning_launcher/utils.py", line 50, in wrapper
    res = func(*args, **kwargs)
  File "/content/venv/lib/python3.8/site-packages/lightning_launcher/utils.py", line 75, in wrapper
    res = func(*args, **kwargs)
  File "/content/venv/lib/python3.8/site-packages/lightning_launcher/launcher.py", line 161, in run_lightning_work
    WorkRunner(
  File "/content/venv/lib/python3.8/site-packages/lightning/app/utilities/proxies.py", line 336, in __call__
    raise e
  File "/content/venv/lib/python3.8/site-packages/lightning/app/utilities/proxies.py", line 319, in __call__
    self.run_once()
  File "/content/venv/lib/python3.8/site-packages/lightning/app/utilities/proxies.py", line 457, in run_once
    self.work.on_exception(e)
  File "/content/venv/lib/python3.8/site-packages/lightning/app/core/work.py", line 550, in on_exception
    raise exception
  File "/content/venv/lib/python3.8/site-packages/lightning/app/utilities/proxies.py", line 422, in run_once
    ret = work_run(*args, **kwargs)
  File "app.py", line 19, in run
    self._drive.delete(path.name)
  File "/content/venv/lib/python3.8/site-packages/lightning/app/storage/drive.py", line 212, in delete
    self.fs.rm(str(shared_path))
  File "/content/venv/lib/python3.8/site-packages/fsspec/asyn.py", line 111, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/content/venv/lib/python3.8/site-packages/fsspec/asyn.py", line 96, in sync
    raise return_result
  File "/content/venv/lib/python3.8/site-packages/fsspec/asyn.py", line 53, in _runner
    result[0] = await coro
  File "/content/venv/lib/python3.8/site-packages/s3fs/core.py", line 1804, in _rm
    await _run_coros_in_chunks(
  File "/content/venv/lib/python3.8/site-packages/fsspec/asyn.py", line 267, in _run_coros_in_chunks
    await asyncio.gather(*chunk, return_exceptions=return_exceptions),
  File "/usr/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/content/venv/lib/python3.8/site-packages/s3fs/core.py", line 1784, in _bulk_delete
    await self._call_s3("delete_objects", kwargs, Bucket=bucket, Delete=delete_keys)
  File "/content/venv/lib/python3.8/site-packages/s3fs/core.py", line 338, in _call_s3
    return await _error_wrapper(
  File "/content/venv/lib/python3.8/site-packages/s3fs/core.py", line 138, in _error_wrapper
    raise err
PermissionError: Forbidden
```

### Environment

```

#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow): `LightningApp`
#- PyTorch Lightning Version (e.g., 1.5.0): `1.8.0.post1`
#- Lightning App Version (e.g., 0.5.2): `1.8.0.post1`
#- PyTorch Version (e.g., 1.10): N/A
#- Python version (e.g., 3.9): 3.8
#- OS (e.g., Linux): Linux
#- CUDA/cuDNN version: N/A
#- GPU models and configuration: N/A
#- How you installed Lightning(`conda`, `pip`, source): `pip`
#- Running environment of LightningApp (e.g. local, cloud): Cloud

```

**Comment by alecmerdler** [comment]
@awaelchli @carmocca Any update on this issue?

**Comment by pietrolesci** [comment]
Hi there,
I am having the same problem. My app heavily relies on `Drive` to share audio files across Works. Due to privacy concerns, once the audio files are processed, I'd like to delete them from the `Drive` and at the moment this is not possible.
