### ISSUE TITLE
DDP Spawn breaks when worker_output is None

### ISSUE THREAD

**Issue by tchaton** [Lightning-AI/lightning#15556]
### Bug description

I will provide a reproducible script soon.

Right now, it seems changing this line https://github.com/Lightning-AI/lightning/blob/master/src/pytorch_lightning/strategies/launchers/multiprocessing.py#L119
prevents the problem.
```python
if trainer is None or worker_output is None:
    return worker_output
```

### How to reproduce the bug

```python
Process Process-3:
Traceback (most recent call last):
  File "/Users/thomas/.pyenv/versions/3.8.5/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/thomas/.pyenv/versions/3.8.5/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/thomas/Documents/GitHub/lightning/src/lightning/app/utilities/proxies.py", line 343, in __call__
    raise e
  File "/Users/thomas/Documents/GitHub/lightning/src/lightning/app/utilities/proxies.py", line 326, in __call__
    self.run_once()
  File "/Users/thomas/Documents/GitHub/lightning/src/lightning/app/utilities/proxies.py", line 467, in run_once
    self.work.on_exception(e)
  File "/Users/thomas/Documents/GitHub/lightning/src/lightning/app/core/work.py", line 558, in on_exception
    raise exception
  File "/Users/thomas/Documents/GitHub/lightning/src/lightning/app/utilities/proxies.py", line 432, in run_once
    ret = work_run(*args, **kwargs)
  File "/Users/thomas/Documents/GitHub/lightning/examples/app_multi_node/app_pl_work.py", line 32, in run
    trainer.fit(model)
  File "/Users/thomas/Documents/GitHub/lightning/.venv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 579, in fit
    call._call_and_handle_interrupt(
  File "/Users/thomas/Documents/GitHub/lightning/.venv/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 36, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/Users/thomas/Documents/GitHub/lightning/.venv/lib/python3.8/site-packages/pytorch_lightning/strategies/launchers/multiprocessing.py", line 122, in launch
    self._recover_results_in_main_process(worker_output, trainer)
  File "/Users/thomas/Documents/GitHub/lightning/.venv/lib/python3.8/site-packages/pytorch_lightning/strategies/launchers/multiprocessing.py", line 149, in _recover_results_in_main_process
    trainer.checkpoint_callback.best_model_path = str(worker_output.best_model_path)
AttributeError: 'NoneType' object has no attribute 'best_model_path'
```

### Error messages and logs

```

# Error messages and logs here please

```

### Environment

```

#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 1.10):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):

```

**Comment by tchaton** [comment]
@awaelchli @carmocca Any ideas ?

**Comment by awaelchli** [comment]
@tchaton The fix in the linked PR should unblock you. I will improve the existing test(s) to simulate the multi-node case here.

**Comment by carmocca** [comment]
This can be uncommented now: https://github.com/Lightning-AI/lightning/blob/36b953b64349b83e7165ed3da2792a5c8e9bc4b5/tests/tests_examples_app/public/test_multi_node.py#L51
