### ISSUE TITLE
__iter__ in IterDataPipe doesn't exit in a timely manner because the DataFetcher is not torn down after an evaluation run

### ISSUE THREAD

**Issue by nickguletskii** [Lightning-AI/lightning#15667]
### Bug description

The generator produced by my IterDataPipe never exits because Pytorch Lightning doesn't get rid of the DataLoader's iterator properly after running the evaluation loop. For me, this causes a deadlock, because the training and validation datasets share a single native resource which must be released by the evaluation loop before the training dataset can start producing entries.

This seems to be a problem with how EvaluationLoop and EvaluationEpochLoop manage the DataFetchers. Calling `teardown` before setting `self._data_fetcher` to null seems to fix this problem.

### How to reproduce the bug

```python
import multiprocessing
import time
from typing import List, Tuple

import torch
from torch.nn import Linear
from torch.utils.data import DataLoader, IterDataPipe

from lightning.pytorch import Trainer, LightningDataModule, LightningModule


class FinallyCallCountingIterDataPipe(IterDataPipe):
    def __init__(self, assert_counts: List[Tuple[int, "FinallyCallCountingIterDataPipe"]] = []):
        self.assert_counts = assert_counts
        self._len = 128
        self.lock = multiprocessing.Lock()
        self.finally_called_n_times = multiprocessing.Manager().Value("i", 0)

    def __iter__(self):
        time.sleep(0.5)  # A deadline for the previous iterators to be cleaned up. Could be replaced with
        # some clever synchronization logic, but then the test would hang on failure.
        for expected_count, dp in self.assert_counts:
            with dp.lock:
                # >= is needed here to pass the check on the second epoch
                assert dp.finally_called_n_times.value >= expected_count
        try:
            for i in range(self._len):
                yield i
        finally:
            with self.lock:
                self.finally_called_n_times.value += 1

    def __len__(self):
        return self._len


def test_evaluation_loop_disposes_of_iterator():
    val_data_pipe = FinallyCallCountingIterDataPipe()
    # When the train loop starts, we expect the iterator used by the sanity check to already be cleaned up
    train_data_pipe = FinallyCallCountingIterDataPipe([(4, val_data_pipe)])

    class TestModel(LightningModule):
        def __init__(self):
            super().__init__()
            self.layer = Linear(1, 1)

        def forward(self, *args, **kwargs):
            return self.layer(torch.zeros((1,)))

        def training_step(self, batch, batch_idx):
            return self.forward(batch)

        def validation_step(self, batch, batch_idx, dataloader_idx=0):
            return self.forward(batch)

        def configure_optimizers(self):
            return torch.optim.SGD(self.layer.parameters(), lr=0.1)

    class TestDataModule(LightningDataModule):
        def train_dataloader(self):
            return DataLoader(train_data_pipe, batch_size=4, num_workers=4)

        def val_dataloader(self):
            return DataLoader(val_data_pipe, batch_size=4, num_workers=4)

    model = TestModel()
    trainer = Trainer(max_epochs=2, accelerator="cpu", devices=1)
    data_module = TestDataModule()
    trainer.fit(model, datamodule=data_module)
    time.sleep(0.5)  # A deadline for the previous iterators to be cleaned up. Could be replaced with
    # some clever synchronization logic, but then the test would hang on failure.

    # 2 epochs, 4 processes => 8 disposed iterators
    assert train_data_pipe.finally_called_n_times.value == 8
    # 2 epochs, 4 processes + 1 sanity check => 12 disposed iterators
    assert val_data_pipe.finally_called_n_times.value == 12


test_evaluation_loop_disposes_of_iterator()
```

### Error messages and logs

```
============================= test session starts ==============================
collecting ... collected 1 item

Epoch 0:   0%|          | 0/64 [00:00<?, ?it/s] GPU available: False, used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs

  | Name  | Type   | Params
---------------------------------
0 | layer | Linear | 2     
---------------------------------
2         Trainable params
0         Non-trainable params
2         Total params
0.000     Total estimated model params size (MB)

tests/tests_pytorch/loops/test_evaluation_loop_iterator_cleanup.py:50 (test_evaluation_loop_disposes_of_iterator)
def test_evaluation_loop_disposes_of_iterator():
        val_data_pipe = FinallyCallCountingIterDataPipe()
        # When the train loop starts, we expect the iterator used by the sanity check to already be cleaned up
        train_data_pipe = FinallyCallCountingIterDataPipe([(4, val_data_pipe)])
    
        class TestModel(LightningModule):
            def __init__(self):
                super().__init__()
                self.layer = Linear(1, 1)
    
            def forward(self, *args, **kwargs):
                return self.layer(torch.zeros((1,)))
    
            def training_step(self, batch, batch_idx):
                return self.forward(batch)
    
            def validation_step(self, batch, batch_idx, dataloader_idx=0):
                return self.forward(batch)
    
            def configure_optimizers(self):
                return torch.optim.SGD(self.layer.parameters(), lr=0.1)
    
        class TestDataModule(LightningDataModule):
            def train_dataloader(self):
                return DataLoader(train_data_pipe, batch_size=4, num_workers=4)
    
            def val_dataloader(self):
                return DataLoader(val_data_pipe, batch_size=4, num_workers=4)
    
        model = TestModel()
        trainer = Trainer(max_epochs=2)
        data_module = TestDataModule()
>       trainer.fit(model, datamodule=data_module)

test_evaluation_loop_iterator_cleanup.py:83: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../../src/pytorch_lightning/trainer/trainer.py:582: in fit
    call._call_and_handle_interrupt(
../../../src/pytorch_lightning/trainer/call.py:38: in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
../../../src/pytorch_lightning/trainer/trainer.py:624: in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
../../../src/pytorch_lightning/trainer/trainer.py:1061: in _run
    results = self._run_stage()
../../../src/pytorch_lightning/trainer/trainer.py:1140: in _run_stage
    self._run_train()
../../../src/pytorch_lightning/trainer/trainer.py:1163: in _run_train
    self.fit_loop.run()
../../../src/pytorch_lightning/loops/loop.py:199: in run
    self.advance(*args, **kwargs)
../../../src/pytorch_lightning/loops/fit_loop.py:267: in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
../../../src/pytorch_lightning/loops/loop.py:199: in run
    self.advance(*args, **kwargs)
../../../src/pytorch_lightning/loops/epoch/training_epoch_loop.py:188: in advance
    batch = next(data_fetcher)
../../../src/pytorch_lightning/utilities/fetching.py:184: in __next__
    return self.fetching_function()
../../../src/pytorch_lightning/utilities/fetching.py:265: in fetching_function
    self._fetch_next_batch(self.dataloader_iter)
../../../src/pytorch_lightning/utilities/fetching.py:280: in _fetch_next_batch
    batch = next(iterator)
../../../src/pytorch_lightning/trainer/supporters.py:568: in __next__
    return self.request_next_batch(self.loader_iters)
../../../src/pytorch_lightning/trainer/supporters.py:580: in request_next_batch
    return apply_to_collection(loader_iters, Iterator, next)
SNIP/lib/python3.9/site-packages/lightning_utilities/core/apply_func.py:47: in apply_to_collection
    return function(data, *args, **kwargs)
SNIP/lib/python3.9/site-packages/torch/utils/data/dataloader.py:628: in __next__
    data = self._next_data()
SNIP/lib/python3.9/site-packages/torch/utils/data/dataloader.py:1333: in _next_data
    return self._process_data(data)
SNIP/lib/python3.9/site-packages/torch/utils/data/dataloader.py:1359: in _process_data
    data.reraise()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <torch._utils.ExceptionWrapper object at 0x7fe082d64040>

    def reraise(self):
        r"""Reraises the wrapped exception in the current thread"""
        # Format a message such as: "Caught ValueError in DataLoader worker
        # process 2. Original Traceback:", followed by the traceback.
        msg = "Caught {} {}.\nOriginal {}".format(
            self.exc_type.__name__, self.where, self.exc_msg
        )
        if self.exc_type == KeyError:
            # KeyError calls repr() on its argument (usually a dict key). This
            # makes stack traces unreadable. It will not be changed in Python
            # (https://bugs.python.org/issue2651), so we work around it.
            msg = KeyErrorMessage(msg)
        elif getattr(self.exc_type, "message", None):
            # Some exceptions have first argument as non-str but explicitly
            # have message field
            raise self.exc_type(message=msg)
        try:
            exception = self.exc_type(msg)
        except TypeError:
            # If the exception takes multiple arguments, don't try to
            # instantiate since we don't know how to
            raise RuntimeError(msg) from None
>       raise exception
E       AssertionError: Caught AssertionError in DataLoader worker process 0.
E       Original Traceback (most recent call last):
E         File "SNIP/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
E           data = fetcher.fetch(index)
E         File "SNIP/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 34, in fetch
E           data.append(next(self.dataset_iter))
E         File "SNIP/lib/python3.9/site-packages/torch/utils/data/datapipes/_hook_iterator.py", line 173, in wrap_generator
E           response = gen.send(None)
E         File "SNIP/lib/python3.9/site-packages/torch/utils/data/datapipes/datapipe.py", line 351, in __iter__
E           yield from self._datapipe
E         File "SNIP/lib/python3.9/site-packages/torch/utils/data/datapipes/_hook_iterator.py", line 173, in wrap_generator
E           response = gen.send(None)
E         File "/home/nick/workspaces/3rdparty/lightning/tests/tests_pytorch/loops/test_evaluation_loop_iterator_cleanup.py", line 39, in __iter__
E           assert dp.finally_called_n_times.value >= expected_count
E       AssertionError: assert 0 >= 4
E        +  where 0 = <ValueProxy object, typeid 'Value' at 0x7fdfe0691970>.value
E        +    where <ValueProxy object, typeid 'Value' at 0x7fdfe0691970> = FinallyCallCountingIterDataPipe.finally_called_n_times
E       This exception is thrown by __iter__ of FinallyCallCountingIterDataPipe(assert_counts=[(4, FinallyCallCountingIterDataPipe)])









======================== 1 failed, 5 warnings in 1.56s =========================

Process finished with exit code 1

```

### Environment

* CUDA:
	- GPU:               None
	- available:         False
	- version:           None
* Lightning:
	- lightning:         1.9.0.dev0
	- lightning-api-access: 0.0.1
	- lightning-cloud:   0.5.11
	- lightning-utilities: 0.3.0
	- pytorch-lightning: 1.8.1
	- torch:             1.13.0+cpu
	- torchaudio:        0.13.0+cpu
	- torchmetrics:      0.8.2
	- torchvision:       0.14.0+cpu
* Packages:
	- *snip*
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- ELF
	- processor:         x86_64
	- python:            3.9.13
	- version:           58-Ubuntu SMP

cc @justusschock @awaelchli

**Comment by carmocca** [comment]
> Calling teardown before setting self._data_fetcher to null seems to fix this problem.

Can you describe precisely what change are you proposing? We already call it this way:
https://github.com/Lightning-AI/lightning/blob/524608ce53b2598cabd87ac306177ef05c93aebd/src/lightning/pytorch/loops/fit_loop.py#L398-L400

**Comment by nickguletskii** [comment]
> > Calling teardown before setting self._data_fetcher to null seems to fix this problem.
> 
> Can you describe precisely what change are you proposing? We already call it this way:
> 
> https://github.com/Lightning-AI/lightning/blob/524608ce53b2598cabd87ac306177ef05c93aebd/src/lightning/pytorch/loops/fit_loop.py#L398-L400

I apologize for the delayed response. Unfortunately, I am no longer actively using pytorch-lightning, partially due to this specific issue.

However, if I recall correctly, the code that you've mentioned only gets called after the whole training process completes. If a data pipe used by the training data loader and a data pipe used by the validation data loader both need exclusive access to a resource (e.g. shared data behind a mutex), then the training process will hang because the data pipe's generator used by the validation loop is never released. A similar problem is demonstrated in the test case that I've provided with this issue and the accompanying pull request: the `finally` clause inside the previously used DataPipe doesn't get called before a new DataPipe is started.

The change I was proposing was to tear down the validation data fetcher after each validation epoch, thus releasing any resources held by the generator produced by the validation data pipe.

**Comment by awaelchli** [comment]
Closing this now, since torchdata stopped the development and we don't expect it to be resumed in the near future. But thanks for the investigation @nickguletskii! One related issue for tracking: #18289
