### ISSUE TITLE
__init__() got an unexpected keyword argument 'truncated_bptt_steps'

### ISSUE THREAD

**Issue by Logicino** [Lightning-AI/lightning#15707]
### Bug description

Hello, I'm trying to run this project:
https://github.com/ws-choi/Conditioned-Source-Separation-LaSAFT
and came into the bug
1. 
```
TypeError: Error instantiating 'pytorch_lightning.trainer.trainer.Trainer' : __init__() got an unexpected keyword argument 'truncated_bptt_steps'
```
I followed some solutions in the issues to degrade the pytorch lightning into version 1.4.0, and it get other problems:
2. 
```
python train.py trainer.gpus=1 dataset.batch_size=6 dataset.musdb_root=/home/data/musdb/
Traceback (most recent call last):
  File "train.py", line 4, in <module>
    from pytorch_lightning.utilities.distributed import rank_zero_info
  File "/home/usrname/anaconda3/envs/lasaft/lib/python3.8/site-packages/pytorch_lightning/__init__.py", line 20, in <module>
    from pytorch_lightning import metrics  # noqa: E402
  File "/home/usrname/anaconda3/envs/lasaft/lib/python3.8/site-packages/pytorch_lightning/metrics/__init__.py", line 15, in <module>
    from pytorch_lightning.metrics.classification import (  # noqa: F401
  File "/home/usrname/anaconda3/envs/lasaft/lib/python3.8/site-packages/pytorch_lightning/metrics/classification/__init__.py", line 14, in <module>
    from pytorch_lightning.metrics.classification.accuracy import Accuracy  # noqa: F401
  File "/home/usrname/anaconda3/envs/lasaft/lib/python3.8/site-packages/pytorch_lightning/metrics/classification/accuracy.py", line 18, in <module>
    from pytorch_lightning.metrics.utils import deprecated_metrics, void
  File "/home/usrname/anaconda3/envs/lasaft/lib/python3.8/site-packages/pytorch_lightning/metrics/utils.py", line 22, in <module>
    from torchmetrics.utilities.data import get_num_classes as _get_num_classes
ImportError: cannot import name 'get_num_classes' from 'torchmetrics.utilities.data' (/home/usrname/.local/lib/python3.8/site-packages/torchmetrics/utilities/data.py)
```

To solve this questions, I take solutions like 
https://github.com/cv-rits/MonoScene/issues/18
https://github.com/NVIDIA/DeepLearningExamples/issues/1113
which tells me to install pytorch lightning==1.5.10, and degrade the torchmetrics to 0.6.0, but after this it will come back to the problem 1. As I tried, all the version >= 1.5.0 would cause this problem.
What should I do? Thank you.

### Error messages and logs

```

# Error messages and logs here please

```

### Environment

```

#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 1.10):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):

```

**Comment by awaelchli** [comment]
@Logicino This project does not support the latest version of Lightning. The `truncated_bptt_steps` argument in Trainer was deprecated and removed a long time ago. Please raise the issue directly on the project's issues page. 

The [requirements file there](https://github.com/ws-choi/Conditioned-Source-Separation-LaSAFT/blob/main/requirements.txt) suggests that you can use pytorch-lightning 1.3.2 and torchmetrics 0.3.2
