### ISSUE TITLE
Version 1.8.1 of lightning missing redis dependency

### ISSUE THREAD

**Issue by marcosfelt** [Lightning-AI/lightning#15717]
### Bug description

Lightning 1.8.2 seems to be causing issues with redis not being installed. I think this might be one of the auxiliary lightning packages rather than the main one.

### Error messages and logs

```
[flow] 2022-11-18T01:25:34.259Z no setup.py
[flow] 2022-11-18T01:25:44.868Z + echo Done
[flow] 2022-11-18T01:25:44.868Z Done
[flow] 2022-11-18T01:25:44.888Z  * Starting OpenBSD Secure Shell server sshd
[flow] 2022-11-18T01:25:44.897Z    ...done.
[flow] 2022-11-18T01:25:50.663Z /content/venv/lib/python3.8/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 0.23ubuntu1 is an invalid version and will not be supported in a future release
[flow] 2022-11-18T01:25:50.663Z   warnings.warn(
[flow] 2022-11-18T01:25:50.665Z Traceback (most recent call last):
[flow] 2022-11-18T01:25:50.665Z     sys.exit(main())
[flow] 2022-11-18T01:25:50.665Z   File "/content/venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
[flow] 2022-11-18T01:25:50.665Z     return self.main(*args, **kwargs)
[flow] 2022-11-18T01:25:50.665Z   File "/content/venv/lib/python3.8/site-packages/click/core.py", line 1055, in main
[flow] 2022-11-18T01:25:50.665Z     rv = self.invoke(ctx)
[flow] 2022-11-18T01:25:50.665Z   File "/content/venv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
[flow] 2022-11-18T01:25:50.665Z     return _process_result(sub_ctx.command.invoke(sub_ctx))
[flow] 2022-11-18T01:25:50.665Z   File "/content/venv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
[flow] 2022-11-18T01:25:50.665Z     return _process_result(sub_ctx.command.invoke(sub_ctx))
[flow] 2022-11-18T01:25:50.665Z   File "/content/venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
[flow] 2022-11-18T01:25:50.665Z     return ctx.invoke(self.callback, **ctx.params)
[flow] 2022-11-18T01:25:50.665Z   File "/content/venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
[flow] 2022-11-18T01:25:50.665Z     return __callback(*args, **kwargs)
[flow] 2022-11-18T01:25:50.665Z   File "/content/venv/lib/python3.8/site-packages/lightning_launcher/cli/__main__.py", line 73, in run_flow
[flow] 2022-11-18T01:25:50.665Z     run_lightning_flow(file, queue_id=queue_id, base_url=base_url)
[flow] 2022-11-18T01:25:50.665Z   File "/content/venv/lib/python3.8/site-packages/lightning_launcher/utils.py", line 50, in wrapper
[flow] 2022-11-18T01:25:50.665Z     res = func(*args, **kwargs)
[flow] 2022-11-18T01:25:50.665Z   File "/content/venv/lib/python3.8/site-packages/lightning_launcher/utils.py", line 75, in wrapper
[flow] 2022-11-18T01:25:50.665Z     res = func(*args, **kwargs)
[flow] 2022-11-18T01:25:50.665Z   File "/content/venv/lib/python3.8/site-packages/lightning_launcher/launcher.py", line 211, in run_lightning_flow
[flow] 2022-11-18T01:25:50.665Z     wait_for_queues(queue_system)
[flow] 2022-11-18T01:25:50.665Z   File "/content/venv/lib/python3.8/site-packages/lightning_launcher/launcher.py", line 465, in wait_for_queues
[flow] 2022-11-18T01:25:50.665Z     while not queue_system.get_queue("healthz").is_running:
[flow] 2022-11-18T01:25:50.665Z   File "/content/venv/lib/python3.8/site-packages/lightning/app/core/queues.py", line 61, in get_queue
[flow] 2022-11-18T01:25:50.665Z     return RedisQueue(queue_name, default_timeout=REDIS_QUEUES_READ_DEFAULT_TIMEOUT)
[flow] 2022-11-18T01:25:50.665Z   File "/content/venv/lib/python3.8/site-packages/lightning/app/utilities/imports.py", line 32, in wrapper
[flow] 2022-11-18T01:25:50.665Z     raise ModuleNotFoundError(
[flow] 2022-11-18T01:25:50.665Z ModuleNotFoundError: Required dependencies not available. Please run: pip install 'redis'

```

**Comment by ethanwharris** [comment]
Hi @marcosfelt thanks for reporting this! This was a temporary issue that was addressed just after the release. Should now be working as expected 😃

**Comment by marcosfelt** [comment]
Thanks!
