### ISSUE TITLE
"TypeError: cannot pickle 'dict_keys' object" when GPU DDP training.

### ISSUE THREAD

**Issue by xiazhongyv** [Lightning-AI/lightning#15722]
### Bug description

 `TypeError: cannot pickle 'dict_keys' object` when GPU DDP training.

### Error messages and logs

```

Global seed set to 0
/home/xiazhongyu/anaconda3/envs/bev/lib/python3.8/site-packages/torch/functional.py:478: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2894.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/home/xiazhongyu/anaconda3/envs/bev/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py:446: LightningDeprecationWarning: Setting `Trainer(gpus=8)` is deprecated in v1.7 and will be removed in v2.0. Please use `Trainer(accelerator='gpu', devices=8)` instead.
  rank_zero_deprecation(
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Traceback (most recent call last):
  File "exps/bevfusion/bevfusion_L_transf_256x256_24e_2key.py", line 666, in <module>
    run_cli()
  File "exps/bevfusion/bevfusion_L_transf_256x256_24e_2key.py", line 645, in run_cli
    main(args)
  File "exps/bevfusion/bevfusion_L_transf_256x256_24e_2key.py", line 606, in main
    trainer.fit(model)
  File "/home/xiazhongyu/anaconda3/envs/bev/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 582, in fit
    call._call_and_handle_interrupt(
  File "/home/xiazhongyu/anaconda3/envs/bev/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 36, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/home/xiazhongyu/anaconda3/envs/bev/lib/python3.8/site-packages/pytorch_lightning/strategies/launchers/multiprocessing.py", line 113, in launch
    mp.start_processes(
  File "/home/xiazhongyu/anaconda3/envs/bev/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 189, in start_processes
    process.start()
  File "/home/xiazhongyu/anaconda3/envs/bev/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/xiazhongyu/anaconda3/envs/bev/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/home/xiazhongyu/anaconda3/envs/bev/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/xiazhongyu/anaconda3/envs/bev/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__    self._launch(process_obj)
  File "/home/xiazhongyu/anaconda3/envs/bev/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/home/xiazhongyu/anaconda3/envs/bev/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'dict_keys' object

```

### Environment

```

#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0): 1.8.2
#- Lightning App Version (e.g., 0.5.2): 
#- PyTorch Version (e.g., 1.10): 1.12
#- Python version (e.g., 3.9): 3.8
#- OS (e.g., Linux): Ubuntu 20.04.4 LTS
#- CUDA/cuDNN version: 11.6
#- GPU models and configuration: 8 GPU DDP
#- How you installed Lightning(`conda`, `pip`, source): pip
#- Running environment of LightningApp (e.g. local, cloud): local

```

cc @justusschock @awaelchli @akihironitta

**Comment by xiazhongyv** [comment]
In fact, with pytorch-lightning 1.6.0 I ran into this problem when saving the model by ModelCheckpoint callback. I upgraded to version 1.8.2, and now I get this error when training starts.
```
def main(args: Namespace) -> None:
    if args.seed is not None:
        pl.seed_everything(args.seed)

    model = BEVFusionLightningModel(**vars(args))
    trainer = pl.Trainer.from_argparse_args(args)
    if args.evaluate:
        trainer.test(model, ckpt_path=args.ckpt_path)
    else:
        trainer.fit(model)


def run_cli():
    parent_parser = ArgumentParser(add_help=False)
    parent_parser = pl.Trainer.add_argparse_args(parent_parser)
    parent_parser.add_argument('-e',
                               '--evaluate',
                               dest='evaluate',
                               action='store_true',
                               help='evaluate model on validation set')
    parent_parser.add_argument('-b', '--batch_size_per_device', type=int)
    parent_parser.add_argument('--seed',
                               type=int,
                               default=0,
                               help='seed for initializing training.')
    parent_parser.add_argument('--ckpt_path', type=str)
    parser = BEVFusionLightningModel.add_model_specific_args(parent_parser)
    parser.set_defaults(
        profiler='simple',
        deterministic=False,
        benchmark=False,
        max_epochs=10,
        accelerator='cuda',
        num_sanity_val_steps=0,
        gradient_clip_val=5,
        enable_checkpointing=True,
        precision=32,
        default_root_dir='./outputs/'+os.path.basename(__file__)[:-3])
    args = parser.parse_args()
    main(args)
```

**Comment by xiazhongyv** [comment]
#- PyTorch Lightning Version: 1.6.0
#- PyTorch Version (e.g., 1.10): 1.12
#- Python version (e.g., 3.9): 3.8
#- OS (e.g., Linux): Ubuntu 20.04.4 LTS
#- CUDA/cuDNN version: 11.6
#- GPU models and configuration: 8 GPU DDP
#- How you installed Lightning(`conda`, `pip`, source): pip
#- Running environment of LightningApp (e.g. local, cloud): local

When I set enable_checkpointing=True, but do not set callbacks, it works well.
When I set enable_checkpointing=True and set callbacks=[ModelCheckpoint()], error occurs.

**Comment by awaelchli** [comment]
When using ddp_spawn, all objects in your code/model need to be pickleable. 

You can set a breakpoint here:

  File "/home/xiazhongyu/anaconda3/envs/bev/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)

and inspect the object to find out.

**Comment by myc634** [comment]
Hi, I had met the same problem in mmdetedtion3d; how did you solve that?
