### ISSUE TITLE
`test_app_state_api[MultiProcessRuntime]` fails with `KeyError: 'flows'` on macOS in CI

### ISSUE THREAD

**Issue by akihironitta** [Lightning-AI/lightning#15936]
### Bug description

See title and log.

### Error messages and logs

```
Process ForkProcess-32:
Traceback (most recent call last):
  File "/Users/runner/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/runner/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/runner/work/lightning/lightning/src/lightning/app/utilities/proxies.py", line 419, in __call__
    raise e
  File "/Users/runner/work/lightning/lightning/src/lightning/app/utilities/proxies.py", line 402, in __call__
    self.run_once()
  File "/Users/runner/work/lightning/lightning/src/lightning/app/utilities/proxies.py", line 550, in run_once
    self.work.on_exception(e)
  File "/Users/runner/work/lightning/lightning/src/lightning/app/core/work.py", line 567, in on_exception
    raise exception
  File "/Users/runner/work/lightning/lightning/src/lightning/app/utilities/proxies.py", line 515, in run_once
    ret = self.run_executor_cls(self.work, work_run, self.delta_queue)(*args, **kwargs)
  File "/Users/runner/work/lightning/lightning/src/lightning/app/utilities/proxies.py", line 351, in __call__
    return self.work_run(*args, **kwargs)
  File "/Users/runner/work/lightning/lightning/tests/tests_app/core/test_lightning_api.py", line 53, in run
    assert state.var_a == 0
  File "/Users/runner/work/lightning/lightning/src/lightning/app/utilities/state.py", line 168, in __getattr__
    self._request_state()
  File "/Users/runner/work/lightning/lightning/src/lightning/app/utilities/state.py", line 161, in _request_state
    self._store_state(response.json())
  File "/Users/runner/work/lightning/lightning/src/lightning/app/utilities/state.py", line 127, in _store_state
    self._last_state = self._find_state_under_affiliation(_LAST_STATE, self._my_affiliation)
  File "/Users/runner/work/lightning/lightning/src/lightning/app/utilities/state.py", line 110, in _find_state_under_affiliation
    if name in children_state["flows"]:
KeyError: 'flows'
```

```
=========================== short test summary info ============================
FAILED tests_app/core/test_lightning_api.py::test_app_state_api[MultiProcessRuntime] - SystemExit: 1
===== 1 failed, 589 passed, 50 skipped, 2122 warnings in 451.32s (0:07:31) =====
Error: Process completed with exit code 1.
```

### Environment

https://github.com/Lightning-AI/lightning/actions/runs/3638338139/jobs/6140786615

cc @carmocca @akihironitta @borda

**Comment by Borda** [comment]
ok, I saw it a few times too, it is very random and not sure what is happening...
cc: @tchaton @ethanwharris @awaelchli

**Comment by tchaton** [comment]
This happens because the server takes some time to setup and the first response is empty. Race condition basically.

@ethanwharris is going to push a fix.

**Comment by ethanwharris** [comment]
Should now be fixed 😃
