### ISSUE TITLE
ImportError: cannot import name '_PATH' from 'pytorch_lightning.utilities.types'

### ISSUE THREAD

**Issue by tmcquaig** [Lightning-AI/lightning#16036]
### Bug description

(Dreambooth-SD) E:\Dreambooth-Stable-Diffusion>python main.py
Traceback (most recent call last):
  File "E:\Dreambooth-Stable-Diffusion\main.py", line 2, in <module>
    from ldm.modules.pruningckptio import PruningCheckpointIO
  File "E:\Dreambooth-Stable-Diffusion\ldm\modules\pruningckptio.py", line 4, in <module>
    from pytorch_lightning.utilities.types import _PATH
ImportError: cannot import name '_PATH' from 'pytorch_lightning.utilities.types' (C:\Users\tmcquaig\anaconda3\envs\Dreambooth-SD\lib\site-packages\pytorch_lightning\utilities\types.py)

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

(Dreambooth-SD) E:\Dreambooth-Stable-Diffusion>python C:\Users\tmcquaig\anaconda3\envs\Dreambooth-SD\Scripts\collect_env_details.py
* CUDA:
        - GPU:               None
        - available:         False
        - version:           None
* Lightning:
        - lightning-utilities: 0.4.2
        - pytorch-lightning: 1.8.4.post0
        - torch:             1.13.0
        - torchmetrics:      0.11.0
* Packages:
        - aiohttp:           3.8.3
        - aiosignal:         1.3.1
        - async-timeout:     4.0.2
        - attrs:             22.1.0
        - certifi:           2022.9.24
        - charset-normalizer: 2.1.1
        - colorama:          0.4.6
        - fire:              0.5.0
        - frozenlist:        1.3.3
        - fsspec:            2022.11.0
        - idna:              3.4
        - lightning-utilities: 0.4.2
        - multidict:         6.0.3
        - numpy:             1.23.5
        - packaging:         22.0
        - pip:               22.3.1
        - protobuf:          3.20.1
        - pytorch-lightning: 1.8.4.post0
        - pyyaml:            6.0
        - requests:          2.28.1
        - setuptools:        65.5.0
        - six:               1.16.0
        - tensorboardx:      2.5.1
        - termcolor:         2.1.1
        - torch:             1.13.0
        - torchmetrics:      0.11.0
        - tqdm:              4.64.1
        - typing-extensions: 4.4.0
        - urllib3:           1.26.13
        - wheel:             0.37.1
        - wincertstore:      0.2
        - yarl:              1.8.2
* System:
        - OS:                Windows
        - architecture:
                - 64bit
                - WindowsPE
        - processor:         AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD
        - python:            3.10.8
        - version:           10.0.22621

**Comment by tmcquaig** [comment]
moving to https://github.com/JoePenna/Dreambooth-Stable-Diffusion/issues/118
