### ISSUE TITLE
Launching any app on the cloud from CLI fails in master

### ISSUE THREAD

**Issue by akihironitta** [Lightning-AI/lightning#16065]
### Bug description

Currently users cannot run any apps from their CLI due to the error shown below.

This error seems to be caused by #16057.

### How to reproduce the bug

```python
$ gh repo clone Lightning-AI/lightning
$ cd lightning
$ pip install -e .
$ lightning run app examples/app_v0/app.py --cloud
...
Traceback (most recent call last):
  File "/home/aki/.pyenv/versions/3.9.15/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/aki/.pyenv/versions/3.9.15/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/aki/work/github.com/Lightning-AI/lightning/src/lightning/app/frontend/web.py", line 87, in _start_server
    uvicorn.run(app=fastapi_service, host=host, port=port, log_config=log_config, root_path=root_path)
  File "/home/aki/work/github.com/Lightning-AI/lightning/venv/lib/python3.9/site-packages/uvicorn/main.py", line 569, in run
    server.run()
  File "/home/aki/work/github.com/Lightning-AI/lightning/venv/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/home/aki/.pyenv/versions/3.9.15/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/aki/work/github.com/Lightning-AI/lightning/venv/lib/python3.9/site-packages/uvicorn/server.py", line 77, in serve
    await self.startup(sockets=sockets)
  File "/home/aki/work/github.com/Lightning-AI/lightning/venv/lib/python3.9/site-packages/uvicorn/server.py", line 151, in startup
    server = await loop.create_server(
  File "uvloop/loop.pyx", line 1743, in create_server
  File "uvloop/loop.pyx", line 905, in uvloop.loop.Loop._getaddrinfo
  File "/home/aki/.pyenv/versions/3.9.15/lib/python3.9/encodings/__init__.py", line 98, in search_function
    mod = __import__('encodings.' + modname, fromlist=_import_tail,
TypeError: _mock_import() got an unexpected keyword argument 'fromlist'
```

**Comment by carmocca** [comment]
I'll work on re-landing the PR. I will also need to find out why CI didnt catch this
