### ISSUE TITLE
Potential Mismatch Between Checkpoint Saving and Loading Behavior When Using DeepSpeed Stage 1

### ISSUE THREAD

**Issue by FarzanT** [Lightning-AI/lightning#16117]
### Bug description

I've used ZeRO Stage 1 on 4 GPUs, my checkpoint is sharded into multiple states. Here is the trainer call I used:
```python
    trainer = pl.Trainer(
        default_root_dir=root_dir,
        callbacks=[
            ModelCheckpoint(
                dirpath=root_dir,
                every_n_train_steps=10000//(args.batch_size * args.grad_acc * torch.cuda.device_count()),
                filename=model_name + "_{epoch}_{step}",
                save_last=True)
        ],
        accelerator="gpu",
        accumulate_grad_batches=args.grad_acc,
        strategy=DeepSpeedStrategy(
            stage=1,
            allgather_bucket_size=500000000,
            reduce_bucket_size=500000000,
            pin_memory=True,
            hysteresis=100,
            overlap_comm=True
        ) if args.deepspeed else None,
        devices=-1,
        num_nodes=1,
        precision=16 if args.half_precision else 32,
        max_epochs=args.epoch,
        check_val_every_n_epoch=args.valid_every,
        gradient_clip_val=5,
        plugins=[SLURMEnvironment(requeue_signal=signal.SIGHUP)]
    )

```
When I call `convert_zero_checkpoint_to_fp32_state_dict` on the checkpoint directory, I get the following:
```python
from pytorch_lightning.utilities.deepspeed import convert_zero_checkpoint_to_fp32_state_dict
convert_zero_checkpoint_to_fp32_state_dict(save_path, output_path)
Processing zero checkpoint '/Users/ftaj/Library/CloudStorage/OneDrive-UniversityofToronto/PycharmProjects/autopath/scTransformers/RegressionTransformer/checkpoints/last.ckpt/checkpoint'
Traceback (most recent call last):
  File "/Users/ftaj/opt/anaconda3/envs/autopath/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-16-1ecd0e27460d>", line 1, in <cell line: 1>
    convert_zero_checkpoint_to_fp32_state_dict(save_path, output_path)
  File "/Users/ftaj/opt/anaconda3/envs/autopath/lib/python3.9/site-packages/pytorch_lightning/utilities/deepspeed.py", line 81, in convert_zero_checkpoint_to_fp32_state_dict
    state_dict = get_fp32_state_dict_from_zero_checkpoint(checkpoint_dir, tag)
  File "/Users/ftaj/opt/anaconda3/envs/autopath/lib/python3.9/site-packages/deepspeed/utils/zero_to_fp32.py", line 406, in get_fp32_state_dict_from_zero_checkpoint
    return _get_fp32_state_dict_from_zero_checkpoint(ds_checkpoint_dir)
  File "/Users/ftaj/opt/anaconda3/envs/autopath/lib/python3.9/site-packages/deepspeed/utils/zero_to_fp32.py", line 164, in _get_fp32_state_dict_from_zero_checkpoint
    zero_stage, world_size, fp32_flat_groups = parse_optim_states(optim_files, ds_checkpoint_dir)
  File "/Users/ftaj/opt/anaconda3/envs/autopath/lib/python3.9/site-packages/deepspeed/utils/zero_to_fp32.py", line 131, in parse_optim_states
    raise ValueError(f"unknown zero stage {zero_stage}")
ValueError: unknown zero stage 1
```
These are the contents of my checkpoint directory:
```bash
-rw-r----- 1 ftaj lstein 6.5M Dec 19 01:54 mp_rank_00_model_states.pt
-rw-r----- 1 ftaj lstein 9.4M Dec 19 01:54 zero_pp_rank_0_mp_rank_00_optim_states.pt
-rw-r----- 1 ftaj lstein 9.4M Dec 19 01:54 zero_pp_rank_1_mp_rank_00_optim_states.pt
-rw-r----- 1 ftaj lstein 9.4M Dec 19 01:54 zero_pp_rank_2_mp_rank_00_optim_states.pt
-rw-r----- 1 ftaj lstein 9.4M Dec 19 01:54 zero_pp_rank_3_mp_rank_00_optim_states.pt
```
And when I try to load the `mp_rank_00_model_states.pt` file directly, I get this 
```python
model = RegressionTransformer.load_from_checkpoint(checkpoint_path+"/checkpoint/mp_rank_00_model_states.pt")
```

```python
Traceback (most recent call last):
  File "/Users/ftaj/opt/anaconda3/envs/autopath/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-12-87290d30a2b7>", line 1, in <cell line: 1>
    model = RegressionTransformer.load_from_checkpoint(checkpoint_path+"/checkpoint/mp_rank_00_model_states.pt")
  File "/Users/ftaj/opt/anaconda3/envs/autopath/lib/python3.9/site-packages/pytorch_lightning/core/saving.py", line 137, in load_from_checkpoint
    return _load_from_checkpoint(
  File "/Users/ftaj/opt/anaconda3/envs/autopath/lib/python3.9/site-packages/pytorch_lightning/core/saving.py", line 180, in _load_from_checkpoint
    return _load_state(cls, checkpoint, strict=strict, **kwargs)
  File "/Users/ftaj/opt/anaconda3/envs/autopath/lib/python3.9/site-packages/pytorch_lightning/core/saving.py", line 238, in _load_state
    keys = obj.load_state_dict(checkpoint["state_dict"], strict=strict)
KeyError: 'state_dict'
```
I tried looking into `mp_rank_00_model_states.pt` with `torch.load()`. The keys of the dict are as follows:
```python

dict_keys(['module', 'buffer_names', 'optimizer', 'param_shapes', 'lr_scheduler', 'sparse_tensor_module_names', 'skipped_steps', 'global_steps', 'global_samples', 'dp_world_size', 'mp_world_size', 'ds_config', 'ds_version', 'epoch', 'global_step', 'pytorch-lightning_version', 'loops', 'callbacks', 'lr_schedulers', 'hparams_name', 'hyper_parameters'])
```
It is mentioned in the Docs that Lightning uses DeepSpeed's implementation for saving the checkpoint, but loading the checkpoint still uses the Lightning Module's `on_load_checkpoint`:
https://github.com/Lightning-AI/lightning/blob/0abd6864082a456c07e03b80b0a60075b3f33efa/src/pytorch_lightning/core/saving.py#L236-L238

If DeepSpeed users have to modify their `on_load_checkpoint()` method in their `LightningModule`, please advise.
Note that I updated to 1.8.5 and I'm still having the same problem.

Thank you,
Farzan

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow): LightningModule/Trainer
#- PyTorch Lightning Version (e.g., 1.5.0): 1.8.4.post0
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 1.10): 1.12.1
#- Python version (e.g., 3.9): 3.8.13
#- OS (e.g., Linux): Linux, Red Hat Enterprise Linux
#- CUDA/cuDNN version: 11.4.4
#- GPU models and configuration: x4 V100, 1 Node, Slurm environment
#- How you installed Lightning(`conda`, `pip`, source): pip
#- Running environment of LightningApp (e.g. local, cloud): cluster
```

</details>

cc @awaelchli

**Comment by moonlightlane** [comment]
I have experienced exactly the same two errors as above when 1) trying to convert the deepspeed checkpoint to fp32 and 2) when trying to directly load the deepspeed model using the lightning module. Suggestions are much appreciated!

**Comment by lorr1** [comment]
I fixed it by adding this following to my Lightning Module.

```
def on_load_checkpoint(self, checkpoint: dict[str, Any]) -> None:
        """Fix the checkpoint loading issue for deepspeed."""
        if "state_dict" in checkpoint:
            return
        state_dict = checkpoint['module']
        state_dict = {k.partition('module.')[2]: state_dict[k] for k in state_dict.keys()}
        checkpoint['state_dict'] = state_dict
        return
```

**Comment by gg22mm** [comment]
Time to load utils op: 0.0010721683502197266 seconds
[3]
  0%|          | 0/833 [00:00<?, ?it/s]                                                                                                                                                                                                                                                                                  Using /root/.cache/torch_extensions/py38_cu117 as PyTorch extensions root...
No modifications detected for re-loaded extension module utils, skipping build step...
Loading extension module utils...
Time to load utils op: 0.0003685951232910156 seconds
[3]
  0%|          | 0/833 [00:01<?, ?it/s]                                                                                                                                                                                                                                                                                  
Traceback (most recent call last):
  File "/root/autodl-tmp/train_wll.py", line 162, in <module>
    trainer.run(m_cfg, train_dataset, None, tconf)
  File "/root/miniconda3/envs/mygpt/lib/python3.8/site-packages/lightning_fabric/fabric.py", line 628, in _run_impl
    return self._strategy.launcher.launch(run_method, *args, **kwargs)
  File "/root/miniconda3/envs/mygpt/lib/python3.8/site-packages/lightning_fabric/strategies/launchers/subprocess_script.py", line 90, in launch
    return function(*args, **kwargs)
  File "/root/miniconda3/envs/mygpt/lib/python3.8/site-packages/lightning_fabric/fabric.py", line 638, in _run_with_setup
    return run_function(*args, **kwargs)
  File "/root/autodl-tmp/src/trainer.py", line 177, in run
    run_epoch('train')
  File "/root/autodl-tmp/src/trainer.py", line 119, in run_epoch
    loss = model(x, y) # forward the model
  File "/root/miniconda3/envs/mygpt/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/mygpt/lib/python3.8/site-packages/lightning_fabric/wrappers.py", line 110, in forward
    output = self._forward_module(*args, **kwargs)
  File "/root/miniconda3/envs/mygpt/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/mygpt/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/mygpt/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1656, in forward
    loss = self.module(*inputs, **kwargs)
  File "/root/miniconda3/envs/mygpt/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/autodl-tmp/src/model.py", line 408, in forward
    x = self.head(x)
  File "/root/miniconda3/envs/mygpt/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/mygpt/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.30 GiB (GPU 1; 15.74 GiB total capacity; 14.23 GiB already allocated; 1.31 GiB free; 14.23 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
  0%|          | 0/1666 [00:01<?, ?it/s]                                                                                                                                                                                                                                                                                 
Traceback (most recent call last):
  File "train_wll.py", line 162, in <module>
    trainer.run(m_cfg, train_dataset, None, tconf)
  File "/root/miniconda3/envs/mygpt/lib/python3.8/site-packages/lightning_fabric/fabric.py", line 628, in _run_impl
    return self._strategy.launcher.launch(run_method, *args, **kwargs)
  File "/root/miniconda3/envs/mygpt/lib/python3.8/site-packages/lightning_fabric/strategies/launchers/subprocess_script.py", line 90, in launch
    return function(*args, **kwargs)
  File "/root/miniconda3/envs/mygpt/lib/python3.8/site-packages/lightning_fabric/fabric.py", line 638, in _run_with_setup
    return run_function(*args, **kwargs)
  File "/root/autodl-tmp/src/trainer.py", line 177, in run
    run_epoch('train')
  File "/root/autodl-tmp/src/trainer.py", line 119, in run_epoch
    loss = model(x, y) # forward the model
  File "/root/miniconda3/envs/mygpt/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/mygpt/lib/python3.8/site-packages/lightning_fabric/wrappers.py", line 110, in forward
    output = self._forward_module(*args, **kwargs)
  File "/root/miniconda3/envs/mygpt/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/mygpt/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/mygpt/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1656, in forward
    loss = self.module(*inputs, **kwargs)
  File "/root/miniconda3/envs/mygpt/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/autodl-tmp/src/model.py", line 408, in forward
    x = self.head(x)
  File "/root/miniconda3/envs/mygpt/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/mygpt/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.30 GiB (GPU 0; 15.74 GiB total capacity; 14.23 GiB already allocated; 812.69 MiB free; 14.23 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
 # trainer = Trainer(devices=NUM_GPUS, accelerator="gpu", precision='bf16') 
    # trainer = Trainer(strategy="deepspeed", devices=NUM_GPUS, accelerator="gpu", precision='bf16') #省显存方式：strategy="deepspeed" 
        
    strategy=DeepSpeedStrategy(
            stage=1,
            allgather_bucket_size=200000000,
            reduce_bucket_size=200000000,
            pin_memory=True,
            hysteresis=100,
            overlap_comm=True
        )   

    trainer = Trainer(strategy=strategy, devices=1, accelerator="gpu", precision='bf16')

**Comment by PicoCreator** [comment]
I have no idea if this works for all use cases of deepspeed 1 - but i found that for mine. The checkpoint format "is compatible" with deepspeed 2.

A simple search and replace for "== 2" to "<= 2" in the conversion script, allows it to work.

https://github.com/microsoft/DeepSpeed/pull/3936

If you are facing this issue, please do try and validate if it works for your use case. Cause until someone from deepspeed confirms that the format is the same - i have no idea if this is the right path.

**Comment by awaelchli** [comment]
Thanks @PicoCreator for sending the fix in the deepspeed repo! I reproduced the issue described here and can confirm your changes fixed it with the latest DeepSpeed version from master. 

My steps to reproduce using the following script:

```py
import torch
from torch.utils.data import DataLoader, Dataset

from lightning.pytorch import LightningModule, Trainer
from lightning.pytorch.callbacks import ModelCheckpoint
from lightning.pytorch.utilities.deepspeed import convert_zero_checkpoint_to_fp32_state_dict


class RandomDataset(Dataset):
    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len


class BoringModel(LightningModule):
    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)

    def forward(self, x):
        return self.layer(x)

    def training_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("train_loss", loss)
        return {"loss": loss}

    def validation_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("valid_loss", loss)

    def test_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("test_loss", loss)

    def configure_optimizers(self):
        return torch.optim.Adam(self.parameters())


def run():
    train_data = DataLoader(RandomDataset(32, 64), batch_size=2)
    val_data = DataLoader(RandomDataset(32, 64), batch_size=2)
    test_data = DataLoader(RandomDataset(32, 64), batch_size=2)

    model = BoringModel()
    trainer = Trainer(
        max_epochs=2, 
        accelerator="cuda",
        devices=2,
        strategy="deepspeed_stage_1",
        callbacks=ModelCheckpoint(dirpath="deepspeed_checkpoint")
    )
    trainer.fit(model, train_dataloaders=train_data, val_dataloaders=val_data)
    trainer.test(model, dataloaders=test_data)

    if trainer.global_rank == 0:
        convert_zero_checkpoint_to_fp32_state_dict(
            "deepspeed_checkpoint/epoch=1-step=32.ckpt", 
            "deepspeed_checkpoint/model.pt"
        )

    trainer.strategy.barrier()

    # verify we can load
    loaded_model = BoringModel.load_from_checkpoint("deepspeed_checkpoint/model.pt")
    # success!


if __name__ == "__main__":
    run()
```

1. Run the above with latest version of Lightning (2.0) and deepspeed <= 0.9.5. You will get this error:
	```
	Traceback (most recent call last):
	  File "/home/adrian/repositories/lightning/examples/pytorch/bug_report/bug_report_model.py", line 73, in <module>
	  File "/home/adrian/repositories/lightning/examples/pytorch/bug_report/bug_report_model.py", line 63, in run
	    convert_zero_checkpoint_to_fp32_state_dict(
	  File "/home/adrian/repositories/lightning/src/lightning/pytorch/utilities/deepspeed.py", line 79, in convert_zero_checkpoint_to_fp32_state_dict
	    state_dict = get_fp32_state_dict_from_zero_checkpoint(checkpoint_dir, tag)
	  File "/home/adrian/.conda/envs/lightning/lib/python3.10/site-packages/deepspeed/utils/zero_to_fp32.py", line 505, in get_fp32_state_dict_from_zero_checkpoint
	    return _get_fp32_state_dict_from_zero_checkpoint(ds_checkpoint_dir)
	  File "/home/adrian/.conda/envs/lightning/lib/python3.10/site-packages/deepspeed/utils/zero_to_fp32.py", line 201, in _get_fp32_state_dict_from_zero_checkpoint
	    zero_stage, world_size, fp32_flat_groups = parse_optim_states(optim_files, ds_checkpoint_dir)
	  File "/home/adrian/.conda/envs/lightning/lib/python3.10/site-packages/deepspeed/utils/zero_to_fp32.py", line 172, in parse_optim_states
	    raise ValueError(f"unknown zero stage {zero_stage}")
	ValueError: unknown zero stage 1
	```

2. `pip install git+https://github.com/microsoft/DeepSpeed.git@master` (https://github.com/microsoft/DeepSpeed/pull/3936)

3. Run again to see it succeed with the following logs:

	```
	Processing zero checkpoint 'deepspeed_checkpoint/epoch=1-step=32.ckpt/checkpoint'
	Detected checkpoint of type zero stage 1, world_size: 2
	Parsing checkpoint created by deepspeed==0.10.0+103884ae
	Reconstructed fp32 state dict with 2 params 66 elements
	Saving fp32 state dict to deepspeed_checkpoint/model.pt
	```

Thanks again @PicoCreator! Closing this issue.
