### ISSUE TITLE
CLI error with RichProgressBar

### ISSUE THREAD

**Issue by quancs** [Lightning-AI/lightning#16208]
### Bug description

ValueError: Expected "default" argument to be an instance of "RichProgressBarTheme" or its kwargs dict, given {'class_path': 'pytorch_lightning.callbacks.progress.rich_progress.RichProgressBarTheme'}

### How to reproduce the bug

```python
import os
from typing import Callable

import torch
from torch.utils.data import DataLoader, Dataset

from pytorch_lightning import LightningModule, Trainer, LightningDataModule
from pytorch_lightning.cli import LightningArgumentParser, LightningCLI
from pytorch_lightning.callbacks import RichProgressBar


class RandomDataset(Dataset):

    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len


class BoringModel(LightningModule):

    def __init__(self, x: int = 10, **mykwargs):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)

    def forward(self, x):
        return self.layer(x)

    def training_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("train_loss", loss)
        return {"loss": loss}

    def validation_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("valid_loss", loss)

    def test_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("test_loss", loss)

    def configure_optimizers(self):
        return torch.optim.SGD(self.layer.parameters(), lr=0.1)


class MyDataModule(LightningDataModule):

    def __init__(self, train_transforms=None, val_transforms=None, test_transforms=None, dims=None):
        super().__init__(train_transforms=train_transforms, val_transforms=val_transforms, test_transforms=test_transforms, dims=dims)

    def train_dataloader(self) -> DataLoader:
        return DataLoader(RandomDataset(32, 64), batch_size=2)

    def val_dataloader(self) -> DataLoader:
        return DataLoader(RandomDataset(32, 64), batch_size=2)

    def test_dataloader(self) -> DataLoader:
        return DataLoader(RandomDataset(32, 64), batch_size=2)


class MyCLI(LightningCLI):

    def add_arguments_to_parser(self, parser: LightningArgumentParser) -> None:
        # RichProgressBar
        parser.add_lightning_class_args(RichProgressBar, nested_key='progress_bar')


if __name__ == "__main__":
    MyCLI(BoringModel, MyDataModule, seed_everything_default=None, save_config_overwrite=True)
```

### Error messages and logs

```
/mnt/home/quancs/miniconda3/lib/python3.9/site-packages/pytorch_lightning/cli.py:358: LightningDeprecationWarning: Setting `LightningCLI.seed_everything_default` to `None` is deprecated in v1.7 and will be removed in v1.9. Set it to `False` instead.
  rank_zero_deprecation(
/mnt/home/quancs/miniconda3/lib/python3.9/site-packages/pytorch_lightning/cli.py:369: LightningDeprecationWarning: LightningCLI's 'save_config_overwrite' init parameter is deprecated from v1.8 and will be removed in v1.10. Use 'save_config_kwargs' instead.
  rank_zero_deprecation(
Traceback (most recent call last):
  File "/mnt/home/quancs/projects/NBSS_pmt/boring.py", line 75, in <module>
    MyCLI(BoringModel, MyDataModule, seed_everything_default=None, save_config_overwrite=True)
  File "/mnt/home/quancs/miniconda3/lib/python3.9/site-packages/pytorch_lightning/cli.py", line 343, in __init__
    self.setup_parser(run, main_kwargs, subparser_kwargs)
  File "/mnt/home/quancs/miniconda3/lib/python3.9/site-packages/pytorch_lightning/cli.py", line 403, in setup_parser
    self._add_subcommands(self.parser, **subparser_kwargs)
  File "/mnt/home/quancs/miniconda3/lib/python3.9/site-packages/pytorch_lightning/cli.py", line 480, in _add_subcommands
    subcommand_parser = self._prepare_subcommand_parser(trainer_class, subcommand, **subparser_kwargs)
  File "/mnt/home/quancs/miniconda3/lib/python3.9/site-packages/pytorch_lightning/cli.py", line 486, in _prepare_subcommand_parser
    self._add_arguments(parser)
  File "/mnt/home/quancs/miniconda3/lib/python3.9/site-packages/pytorch_lightning/cli.py", line 439, in _add_arguments
    self.add_arguments_to_parser(parser)
  File "/mnt/home/quancs/projects/NBSS_pmt/boring.py", line 71, in add_arguments_to_parser
    parser.add_lightning_class_args(RichProgressBar, nested_key='progress_bar')
  File "/mnt/home/quancs/miniconda3/lib/python3.9/site-packages/pytorch_lightning/cli.py", line 120, in add_lightning_class_args
    return self.add_class_arguments(
  File "/mnt/home/quancs/miniconda3/lib/python3.9/site-packages/jsonargparse/signatures.py", line 69, in add_class_arguments
    added_args = self._add_signature_arguments(
  File "/mnt/home/quancs/miniconda3/lib/python3.9/site-packages/jsonargparse/signatures.py", line 244, in _add_signature_arguments
    self._add_signature_parameter(
  File "/mnt/home/quancs/miniconda3/lib/python3.9/site-packages/jsonargparse/signatures.py", line 353, in _add_signature_parameter
    action = group.add_argument(*args, **kwargs)
  File "/mnt/home/quancs/miniconda3/lib/python3.9/site-packages/jsonargparse/core.py", line 110, in add_argument
    self.add_dataclass_arguments(theclass, nested_key, **kwargs)
  File "/mnt/home/quancs/miniconda3/lib/python3.9/site-packages/jsonargparse/signatures.py", line 402, in add_dataclass_arguments
    raise ValueError(f'Expected "default" argument to be an instance of "{theclass.__name__}" or its kwargs dict, given {default}')
ValueError: Expected "default" argument to be an instance of "RichProgressBarTheme" or its kwargs dict, given {'class_path': 'pytorch_lightning.callbacks.progress.rich_progress.RichProgressBarTheme'}
```

### Environment

<details>
  <summary>Current environment</summary>

```
* CUDA:
        - GPU:
                - NVIDIA A100-SXM4-40GB
                - NVIDIA A100-SXM4-40GB
                - NVIDIA A100-SXM4-40GB
                - NVIDIA A100-SXM4-40GB
                - NVIDIA A100-SXM4-40GB
                - NVIDIA A100-SXM4-40GB
                - NVIDIA A100-SXM4-40GB
                - NVIDIA A100-SXM4-40GB
        - available:         True
        - version:           11.6
* Lightning:
        - lightning-utilities: 0.5.0
        - pytorch-lightning: 1.8.6
        - pytorch-ranger:    0.1.1
        - torch:             1.12.1
        - torch-complex:     0.4.3
        - torch-optimizer:   0.3.0
        - torch-stoi:        0.1.2
        - torch-tb-profiler: 0.4.0
        - torchaudio:        0.12.1
        - torchdata:         0.4.1
        - torchmetrics:      0.9.2
        - torchvision:       0.13.1
* Packages:
        - absl-py:           1.2.0
        - aiohttp:           3.8.1
        - aiosignal:         1.2.0
        - antlr4-python3-runtime: 4.9.3
        - anyio:             3.6.2
        - appdirs:           1.4.4
        - argon2-cffi:       21.3.0
        - argon2-cffi-bindings: 21.2.0
        - asteroid:          0.5.1
        - asteroid-filterbanks: 0.4.0
        - asttokens:         2.1.0
        - async-timeout:     4.0.2
        - attrs:             21.4.0
        - audioread:         2.1.9
        - autopep8:          1.7.0
        - backcall:          0.2.0
        - beautifulsoup4:    4.11.1
        - black:             19.10b0
        - bleach:            5.0.1
        - blessings:         1.7
        - brotlipy:          0.7.0
        - cached-property:   1.5.2
        - cachetools:        5.2.0
        - certifi:           2022.6.15
        - cffi:              1.15.0
        - cfgv:              3.3.1
        - charset-normalizer: 2.0.4
        - click:             8.0.4
        - cmake:             3.24.1
        - commonmark:        0.9.1
        - conda:             4.13.0
        - conda-content-trust: 0+unknown
        - conda-package-handling: 1.7.3
        - cryptography:      36.0.0
        - cycler:            0.11.0
        - debugpy:           1.6.4
        - decorator:         5.1.1
        - defusedxml:        0.7.1
        - dill:              0.3.5.1
        - distlib:           0.3.5
        - docstring-parser:  0.15
        - einops:            0.4.1
        - entrypoints:       0.3
        - executing:         1.2.0
        - fastjsonschema:    2.16.2
        - filelock:          3.8.0
        - flake8:            3.7.9
        - fonttools:         4.34.4
        - frozenlist:        1.3.0
        - fsspec:            2022.5.0
        - future:            0.18.2
        - google-auth:       2.9.1
        - google-auth-oauthlib: 0.4.6
        - gpurir:            1.2.0
        - gpustat:           0.6.0
        - grpcio:            1.47.0
        - huggingface-hub:   0.8.1
        - hyperpyyaml:       1.0.1
        - identify:          2.5.3
        - idna:              3.3
        - imageio:           2.22.1
        - importlib-metadata: 4.12.0
        - ipykernel:         6.17.1
        - ipython:           8.7.0
        - ipython-genutils:  0.2.0
        - ipywidgets:        8.0.2
        - jedi:              0.18.2
        - jinja2:            3.1.2
        - joblib:            1.1.0
        - jsonargparse:      4.18.0
        - jsonschema:        4.17.1
        - julius:            0.2.6
        - jupyter:           1.0.0
        - jupyter-client:    7.4.7
        - jupyter-console:   6.4.4
        - jupyter-core:      5.1.0
        - jupyter-server:    1.23.3
        - jupyterlab-pygments: 0.2.2
        - jupyterlab-widgets: 3.0.3
        - kiwisolver:        1.4.4
        - librosa:           0.9.2
        - lightning-utilities: 0.5.0
        - line-profiler:     3.5.1
        - llvmlite:          0.38.1
        - markdown:          3.4.1
        - markupsafe:        2.1.1
        - matplotlib:        3.5.2
        - matplotlib-inline: 0.1.6
        - mccabe:            0.6.1
        - mir-eval:          0.7
        - mistune:           2.0.4
        - mkl-fft:           1.3.1
        - mkl-random:        1.2.2
        - mkl-service:       2.4.0
        - more-itertools:    8.14.0
        - multidict:         6.0.2
        - multiprocess:      0.70.13
        - mypy:              0.971
        - mypy-extensions:   0.4.3
        - nbclassic:         0.4.8
        - nbclient:          0.7.0
        - nbconvert:         7.2.5
        - nbformat:          5.7.0
        - nest-asyncio:      1.5.6
        - networkx:          2.8.7
        - nodeenv:           1.7.0
        - notebook:          6.5.2
        - notebook-shim:     0.2.2
        - numba:             0.55.2
        - numpy:             1.22.3
        - nvidia-ml-py3:     7.352.0
        - oauthlib:          3.2.0
        - olefile:           0.46
        - omegaconf:         2.2.2
        - opencv-python:     4.6.0.66
        - p-tqdm:            1.3.3
        - packaging:         21.3
        - pandas:            1.4.3
        - pandocfilters:     1.5.0
        - parso:             0.8.3
        - pathos:            0.2.9
        - pathspec:          0.9.0
        - pb-bss-eval:       0.0.2
        - pesq:              0.0.4
        - pexpect:           4.8.0
        - pickleshare:       0.7.5
        - pillow:            9.2.0
        - pip:               21.2.4
        - platformdirs:      2.5.2
        - pluggy:            0.13.1
        - pooch:             1.6.0
        - portalocker:       2.5.1
        - pox:               0.3.1
        - ppft:              1.7.6.5
        - pre-commit:        2.20.0
        - prometheus-client: 0.15.0
        - prompt-toolkit:    3.0.33
        - protobuf:          3.19.4
        - psutil:            5.9.1
        - ptflops:           0.6.9
        - ptyprocess:        0.7.0
        - pure-eval:         0.2.2
        - py:                1.11.0
        - pyasn1:            0.4.8
        - pyasn1-modules:    0.2.8
        - pyaudio:           0.2.11
        - pycodestyle:       2.9.1
        - pycosat:           0.6.3
        - pycparser:         2.21
        - pydeprecate:       0.3.2
        - pyflakes:          2.1.1
        - pygments:          2.12.0
        - pyopenssl:         21.0.0
        - pyparsing:         3.0.9
        - pyqt5:             5.15.7
        - pyqt5-qt5:         5.15.2
        - pyqt5-sip:         12.11.0
        - pyrsistent:        0.19.2
        - pysocks:           1.7.1
        - pystoi:            0.3.3
        - pytest:            5.4.1
        - python-dateutil:   2.8.2
        - pytorch-lightning: 1.8.6
        - pytorch-ranger:    0.1.1
        - pytz:              2022.1
        - pywavelets:        1.4.1
        - pyyaml:            6.0
        - pyzmq:             24.0.1
        - qtconsole:         5.4.0
        - qtpy:              2.3.0
        - regex:             2022.8.17
        - requests:          2.27.1
        - requests-oauthlib: 1.3.1
        - resampy:           0.3.1
        - rich:              12.5.1
        - rsa:               4.9
        - ruamel-yaml-conda: 0.15.100
        - ruamel.yaml:       0.17.21
        - ruamel.yaml.clib:  0.2.6
        - scikit-image:      0.19.3
        - scikit-learn:      1.1.1
        - scipy:             1.8.1
        - screeninfo:        0.8
        - seaborn:           0.11.2
        - send2trash:        1.8.0
        - sentencepiece:     0.1.97
        - setuptools:        58.0.4
        - six:               1.16.0
        - sniffio:           1.3.0
        - sounddevice:       0.4.4
        - soundfile:         0.10.3.post1
        - soupsieve:         2.3.2.post1
        - speechbrain:       0.5.12
        - stack-data:        0.6.2
        - tensorboard:       2.10.0
        - tensorboard-data-server: 0.6.1
        - tensorboard-plugin-wit: 1.8.1
        - tensorboardx:      2.5.1
        - terminado:         0.17.0
        - thop:              0.1.1.post2209071413
        - threadpoolctl:     3.1.0
        - tifffile:          2022.8.12
        - tinycss2:          1.2.1
        - toml:              0.10.2
        - tomli:             2.0.1
        - torch:             1.12.1
        - torch-complex:     0.4.3
        - torch-optimizer:   0.3.0
        - torch-stoi:        0.1.2
        - torch-tb-profiler: 0.4.0
        - torchaudio:        0.12.1
        - torchdata:         0.4.1
        - torchmetrics:      0.9.2
        - torchvision:       0.13.1
        - tornado:           6.2
        - tqdm:              4.62.3
        - traitlets:         5.5.0
        - typed-ast:         1.5.4
        - types-pyyaml:      6.0.11
        - typing-extensions: 4.3.0
        - urllib3:           1.26.7
        - validators:        0.20.0
        - virtualenv:        20.16.3
        - wcwidth:           0.2.5
        - webencodings:      0.5.1
        - websocket-client:  1.4.2
        - werkzeug:          2.1.2
        - wheel:             0.37.1
        - widgetsnbextension: 4.0.3
        - yamllint:          1.23.0
        - yapf:              0.32.0
        - yarl:              1.7.2
        - zipp:              3.8.1
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.9.7
        - version:           #1 SMP Mon Oct 19 16:18:59 UTC 2020
```

</details>

cc @carmocca @mauvilsa

**Comment by mauvilsa** [comment]
I was unable to reproduce the issue. The code snippet does not seem to correspond to the reported pytorch-lightning version, since `LightningDataModule` in v1.8.6 does not accept any `__init__` parameters, and above there are `train_transforms, val_transforms, test_transforms, dims`. Even if I remove those parameters, the code runs without problem for `cli.py fit`. The description does not give any specific command that needs to be run to reproduce.

**Comment by quancs** [comment]
> I was unable to reproduce the issue. The code snippet does not seem to correspond to the reported pytorch-lightning version, since `LightningDataModule` in v1.8.6 does not accept any `__init__` parameters, and above there are `train_transforms, val_transforms, test_transforms, dims`. Even if I remove those parameters, the code runs without problem for `cli.py fit`. The description does not give any specific command that needs to be run to reproduce.

The problem only exists on jsonargparse 4.18.0. Other versions like jsonargparse 4.17.0 are OK.

**Comment by mauvilsa** [comment]
It does not fail with jsonargparse 4.19.0. So I guess whatever was the issue, it has already been fixed.
