### ISSUE TITLE
Bug with isolate_rng "Cannot re-initialize CUDA in forked subprocess"

### ISSUE THREAD

**Issue by sergeevii123** [Lightning-AI/lightning#16262]
### Bug description

I was using isolate_rng in pytorch dataset for some augmentations in pytorch lightning 1.7.1 but after update to latest 1.8.6 I experience error now.

```
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method

```

### How to reproduce the bug

```python
from torch.utils.data import DataLoader
import pytorch_lightning as pl
from torch.utils.data import Dataset
import torch
from torch import nn
import torch.nn.functional as F

class LitAutoEncoder(pl.LightningModule):
    def __init__(self):
        super().__init__()
        self.encoder = nn.Sequential(nn.Linear(28 * 28, 128), nn.ReLU(), nn.Linear(128, 3))
        self.decoder = nn.Sequential(nn.Linear(3, 128), nn.ReLU(), nn.Linear(128, 28 * 28))

    def forward(self, x):
        # in lightning, forward defines the prediction/inference actions
        embedding = self.encoder(x)
        return embedding

    def training_step(self, batch, batch_idx):
        # training_step defines the train loop. It is independent of forward
        x, y = batch
        x = x.view(x.size(0), -1)
        z = self.encoder(x)
        x_hat = self.decoder(z)
        loss = F.mse_loss(x_hat, x)
        self.log("train_loss", loss)
        return loss

    def configure_optimizers(self):
        optimizer = torch.optim.Adam(self.parameters(), lr=1e-3)
        return optimizer

class DummyDataset(Dataset):
    def __init__(self) -> None:
        super().__init__()
        
    def __getitem__(self,  index: int):
        with pl.utilities.seed.isolate_rng():
            return [torch.ones(28,28),torch.ones(28,28)] 
    
    def __len__(self):
        return 10

dataset = DummyDataset()

trainer = pl.Trainer(logger=None, accelerator='gpu')
trainer.fit(LitAutoEncoder(), DataLoader(dataset, num_workers=2))
```
if you remove num_workers=2 the bug will go away but I need multiple workers.

### Error messages and logs

```
Traceback (most recent call last):
  File "check_bug_in_pl.py", line 47, in <module>
    trainer.fit(LitAutoEncoder(), DataLoader(dataset, num_workers=2))
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 603, in fit
    call._call_and_handle_interrupt(
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 645, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 1098, in _run
    results = self._run_stage()
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 1177, in _run_stage
    self._run_train()
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 1200, in _run_train
    self.fit_loop.run()
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/loops/fit_loop.py", line 267, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 188, in advance
    batch = next(data_fetcher)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/utilities/fetching.py", line 184, in __next__
    return self.fetching_function()
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/utilities/fetching.py", line 265, in fetching_function
    self._fetch_next_batch(self.dataloader_iter)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/utilities/fetching.py", line 280, in _fetch_next_batch
    batch = next(iterator)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/supporters.py", line 568, in __next__
    return self.request_next_batch(self.loader_iters)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/supporters.py", line 580, in request_next_batch
    return apply_to_collection(loader_iters, Iterator, next)
  File "/home/jovyan/.local/lib/python3.8/site-packages/lightning_utilities/core/apply_func.py", line 47, in apply_to_collection
    return function(data, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.8/dist-packages/torch/_utils.py", line 457, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "check_bug_in_pl.py", line 38, in __getitem__
    with pl.utilities.seed.isolate_rng():
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/utilities/seed.py", line 42, in isolate_rng
    states = _collect_rng_states()
  File "/usr/local/lib/python3.8/dist-packages/lightning_lite/utilities/seed.py", line 112, in _collect_rng_states
    "torch.cuda": torch.cuda.get_rng_state_all(),
  File "/usr/local/lib/python3.8/dist-packages/torch/cuda/random.py", line 39, in get_rng_state_all
    results.append(get_rng_state(i))
  File "/usr/local/lib/python3.8/dist-packages/torch/cuda/random.py", line 22, in get_rng_state
    _lazy_init()
  File "/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py", line 206, in _lazy_init
    raise RuntimeError(
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method

Epoch 0:   0%|          | 0/10 [00:00<?, ?it/s]   
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0): 1.8.6
#- Lightning App Version (e.g., 0.5.2): 
#- PyTorch Version (e.g., 1.10): 1.11.0+cu102
#- Python version (e.g., 3.9):  3.8.10
#- OS (e.g., Linux): ubuntu
#- CUDA/cuDNN version: 10.2
#- GPU models and configuration: Tesla T4 
#- How you installed Lightning: pip
#- Running environment of LightningApp : local
```

</details>

cc @awaelchli

**Comment by sergeevii123** [comment]
Error with this code starts to appear after pytorch-lightning 1.8.0

**Comment by sergeevii123** [comment]
seems I've found what this is about 
```
 # torch.cuda rng_state is only included since v1.8.
    if "torch.cuda" in rng_state_dict:
        torch.cuda.set_rng_state_all(rng_state_dict["torch.cuda"])
```
The question is can we make isolate_rng with parameter to not include cuda? or it's better to write my own version locally?

**Comment by awaelchli** [comment]
@sergeevii123 Thanks for the reproducible code. Did you try wrapping the code with this guard?

```py
if __name__ == "__main__": 
    dataset = DummyDataset()
    trainer = pl.Trainer(logger=None, accelerator='gpu')
    trainer.fit(LitAutoEncoder(), DataLoader(dataset, num_workers=2))
```

I will take a closer look otherwise.

**Comment by sergeevii123** [comment]
> @sergeevii123 Thanks for the reproducible code. Did you try wrapping the code with this guard?
> 
> ```python
> if __name__ == "__main__": 
>     dataset = DummyDataset()
>     trainer = pl.Trainer(logger=None, accelerator='gpu')
>     trainer.fit(LitAutoEncoder(), DataLoader(dataset, num_workers=2))
> ```
> 
> I will take a closer look otherwise.

Tried but result is same. It works if you remove collecting cuda state from `_collect_rng_states` function

**Comment by awaelchli** [comment]
Adding an argument to exclude the cuda seed would be possible, but let me first check what the root cause is and whether we can fix it properly.

**Comment by awaelchli** [comment]
@sergeevii123 I cannot reproduce this with the pytorch version 1.11.0 and PL version 1.8.6 like you have reported. This is weird, I can't explain how you get this error. 

Somehow you get your processes being created with the fork start method. Is there anything special about your environment? Are you running this in a notebook? I'm not sure what I'm doing different.

**Comment by sergeevii123** [comment]
> @sergeevii123 I cannot reproduce this with the pytorch version 1.11.0 and PL version 1.8.6 like you have reported. This is weird, I can't explain how you get this error.
> 
> Somehow you get your processes being created with the fork start method. Is there anything special about your environment? Are you running this in a notebook? I'm not sure what I'm doing different.

Interesting, I'm running this in dev-contaier(docker image) on the kubeflow as a python script. Maybe it's somehow changes the start method because some of the docker settings or environment settings🤔
 How can I log the start method in my script?

**Comment by awaelchli** [comment]
Hey @sergeevii123 sorry for the late answer. You can check the start method like this:

```py
import torch.multiprocessing as mp
print(mp.get_start_method())
```

**Comment by sergeevii123** [comment]
> Hey @sergeevii123 sorry for the late answer. You can check the start method like this:
> 
> ```python
> import torch.multiprocessing as mp
> print(mp.get_start_method())
> ```

@awaelchli 
here is the method`starting method fork`

the code that I've used
```
from torch.utils.data import DataLoader
import pytorch_lightning as pl
from torch.utils.data import Dataset
import torch
from torch import nn
import torch.nn.functional as F

import torch.multiprocessing as mp


class LitAutoEncoder(pl.LightningModule):
    def __init__(self):
        super().__init__()
        self.encoder = nn.Sequential(nn.Linear(28 * 28, 128), nn.ReLU(), nn.Linear(128, 3))
        self.decoder = nn.Sequential(nn.Linear(3, 128), nn.ReLU(), nn.Linear(128, 28 * 28))

    def forward(self, x):
        # in lightning, forward defines the prediction/inference actions
        embedding = self.encoder(x)
        return embedding

    def training_step(self, batch, batch_idx):
        # training_step defines the train loop. It is independent of forward
        x, y = batch
        x = x.view(x.size(0), -1)
        z = self.encoder(x)
        x_hat = self.decoder(z)
        loss = F.mse_loss(x_hat, x)
        self.log("train_loss", loss)
        return loss

    def configure_optimizers(self):
        optimizer = torch.optim.Adam(self.parameters(), lr=1e-3)
        return optimizer

class DummyDataset(Dataset):
    def __init__(self) -> None:
        super().__init__()
        
    def __getitem__(self,  index: int):
        with pl.utilities.seed.isolate_rng():
            return [torch.ones(28,28),torch.ones(28,28)] 
    
    def __len__(self):
        return 10
        
if __name__ == "__main__": 
    print("starting method", mp.get_start_method())
    dataset = DummyDataset()
    trainer = pl.Trainer(logger=None, accelerator='gpu')
    trainer.fit(LitAutoEncoder(), DataLoader(dataset, num_workers=2))
```
Error with `RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method` persists

**Comment by sergeevii123** [comment]
Maybe this starting method could be checked in the `isolate_rng` so it will not result in the error

**Comment by awaelchli** [comment]
@sergeevii123 I think it would be fine to add an argument to the function `include_cuda=True|False`. 

One could detect the start method yes, but that alone doesn't tell us whether we are running the function in a forked process or the main one, which I don't know how to detect like that.  So, if it's between the two, I would prefer the optional argument.

**Comment by jamesgunnfiveai** [comment]
Hi folks, just hit this same issue in lightning 1.9.0, but via a different path. I'm using fault tolerant training on a map-style dataset, using the "ddp" strategy. The worker loop ends up calling `state_dict` on `CaptureMapDataset` which makes a call to `_collect_rng_states()` and ends up triggering the same code path as stated above, leading to the same crash.

```
Original Traceback (most recent call last):
  File ".../torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File ".../torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File ".../pytorch_lightning/utilities/auto_restart.py", line 418, in _capture_metadata_collate
    metadata = dataset.state_dict()
  File ".../pytorch_lightning/utilities/auto_restart.py", line 275, in state_dict
    return {self.worker_id: {"rng_states": _collect_rng_states()}}
  File ".../lightning_fabric/utilities/seed.py", line 111, in _collect_rng_states
    "torch.cuda": torch.cuda.get_rng_state_all(),
  File ".../torch/cuda/random.py", line 39, in get_rng_state_all
    results.append(get_rng_state(i))
  File ".../torch/cuda/random.py", line 22, in get_rng_state
    _lazy_init()
  File ".../torch/cuda/__init__.py", line 207, in _lazy_init
    raise RuntimeError(
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method
```

Would you prefer a new bug for this one, or is there already sufficient info on this ticket to propose a way of solving this?

**Comment by awaelchli** [comment]
@jamesgunnfiveai Yes, in the `CaptureMapDataset.state_dict`, we should call the function `_collect_rng_states` with `include_cuda=True` only on systems that don't use fork as the default (macos and windows) for dataloader processes, and on Linux we should call `include_cuda=False`. That's my guess. A PR for this would be welcome :)

**Comment by jamesgunnfiveai** [comment]
@awaelchli - I can certainly take a look, though I'm not familiar at all with these lower level cuda calls. Do you think it would be more robust to instead check whether we're _in_ a forked process (and then set `include_cuda=False`) rather than just checking the system default? It's perfectly reasonable to collect the cuda rng states if we're using num_workers=0 for example, even on Linux.
I could modify `state_dict` to look something like this instead, which should handle all cases?
```
def state_dict(self) -> Dict[int, Dict[str, Any]]:
    return {self.worker_id: {"rng_states": _collect_rng_states(include_cuda=torch.cuda.is_initialized())}}
```
If you think this is ok, I'll raise a PR. The only concern I would still have with this is that nothing will collect the cuda random state for num_workers>0 on linux, because no worker has access to initialised CUDA. But that could be discussed on the PR.

**Comment by awaelchli** [comment]
Sounds good. Unfortunately, with a quick research I couldn't find a good way to check whether we are in a forked process. 
`torch.cuda.is_initialized()` could be a way around, but technically no what we want. 

> The only concern I would still have with this is that nothing will collect the cuda random state for num_workers>0 on linux, because no worker has access to initialised CUDA. But that could be discussed on the PR.

Unfortunately I have no better idea.

**Comment by jamesgunnfiveai** [comment]
> Unfortunately I have no better idea.
Nor do I! I'll get a PR sorted.
