### ISSUE TITLE
Compile your model to ONNX

### ISSUE THREAD

**Issue by celsofranssa** [Lightning-AI/lightning#16368]
### Bug description

During `to_onnx` for the second time, it re-generates just a tiny ONNX file that does not correspond to the model (as generated for the first time). 

Do I miss something?

### How to reproduce the bug

```python
filepath = "model.onnx"
input_sample = torch.randn((1, 64))
model.to_onnx(filepath, input_sample, export_params=True)
```

### Error messages and logs

``` python
2023-01-15 15:27:25.744120495 [E:onnxruntime:, inference_session.cc:1500 operator()] Exception during initialization: /onnxruntime_src/onnxruntime/core/framework/session_state_utils.cc:200 onnxruntime::common::Status onnxruntime::session_state_utils::SaveInitializedTensors(const onnxruntime::Env&, const std::__cxx11::basic_string<char>&, const onnxruntime::GraphViewer&, const AllocatorPtr&, const onnxruntime::OrtValueNameIdxMap&, const std::vector<int>&, onnxruntime::ITensorAllocator&, const SaveTensorFunction&, const onnxruntime::logging::Logger&, const onnxruntime::DataTransferManager&, const onnxruntime::ExecutionPlanBase&, const onnxruntime::SessionOptions&, const MemoryProfileFunction&) ort_value_name_idx_map.MaxIdx() > -1 was false. OrtValue indexes should have been populated.

Traceback (most recent call last):
  File "/mnt/ark/projects/TeCBenchAPI/main.py", line 61, in <module>
    ort_session = onnxruntime.InferenceSession("resource/onnx/model.onnx")
  File "/mnt/ark/projects/TeCBenchAPI/venv/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 347, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/mnt/ark/projects/TeCBenchAPI/venv/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 395, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: /onnxruntime_src/onnxruntime/core/framework/session_state_utils.cc:200 onnxruntime::common::Status onnxruntime::session_state_utils::SaveInitializedTensors(const onnxruntime::Env&, const std::__cxx11::basic_string<char>&, const onnxruntime::GraphViewer&, const AllocatorPtr&, const onnxruntime::OrtValueNameIdxMap&, const std::vector<int>&, onnxruntime::ITensorAllocator&, const SaveTensorFunction&, const onnxruntime::logging::Logger&, const onnxruntime::DataTransferManager&, const onnxruntime::ExecutionPlanBase&, const onnxruntime::SessionOptions&, const MemoryProfileFunction&) ort_value_name_idx_map.MaxIdx() > -1 was false. OrtValue indexes should have been populated.


Process finished with exit code 1
```

### Environment

<details>
  <summary>Current environment</summary>

```
* CUDA:
	- GPU:
		- NVIDIA GeForce RTX 3090 Ti
	- available:         True
	- version:           11.7
* Lightning:
	- pytorch-lightning: 1.6.5
	- pytorch-metric-learning: 1.5.2
	- torch:             1.13.1+cu117
	- torchaudio:        0.13.1+cu117
	- torchmetrics:      0.9.3
	- torchvision:       0.14.1+cu117
* Packages:
	- absl-py:           1.3.0
	- aiohttp:           3.8.3
	- aiosignal:         1.3.1
	- antlr4-python3-runtime: 4.9.3
	- async-timeout:     4.0.2
	- attrs:             22.1.0
	- cachetools:        5.2.0
	- certifi:           2022.9.24
	- charset-normalizer: 2.1.1
	- contourpy:         1.0.6
	- cycler:            0.11.0
	- filelock:          3.8.0
	- fonttools:         4.38.0
	- frozenlist:        1.3.3
	- fsspec:            2022.11.0
	- google-auth:       2.14.1
	- google-auth-oauthlib: 0.4.6
	- grpcio:            1.50.0
	- huggingface-hub:   0.11.0
	- hydra-core:        1.2.0
	- idna:              3.4
	- joblib:            1.2.0
	- kiwisolver:        1.4.4
	- markdown:          3.4.1
	- markupsafe:        2.1.1
	- matplotlib:        3.6.2
	- multidict:         6.0.2
	- nmslib:            2.1.1
	- numpy:             1.22.4
	- nvidia-cublas-cu11: 11.10.3.66
	- nvidia-cuda-nvrtc-cu11: 11.7.99
	- nvidia-cuda-runtime-cu11: 11.7.99
	- nvidia-cudnn-cu11: 8.5.0.96
	- oauthlib:          3.2.2
	- omegaconf:         2.2.3
	- opentsne:          0.6.2
	- packaging:         21.3
	- pandas:            1.5.2
	- pillow:            9.3.0
	- pip:               22.0.2
	- protobuf:          3.20.1
	- psutil:            5.9.4
	- pyasn1:            0.4.8
	- pyasn1-modules:    0.2.8
	- pybind11:          2.6.1
	- pydeprecate:       0.3.2
	- pyparsing:         3.0.9
	- python-dateutil:   2.8.2
	- pytorch-lightning: 1.6.5
	- pytorch-metric-learning: 1.5.2
	- pytz:              2022.6
	- pyyaml:            6.0
	- regex:             2022.10.31
	- requests:          2.28.1
	- requests-oauthlib: 1.3.1
	- rsa:               4.9
	- scikit-learn:      1.1.3
	- scipy:             1.9.3
	- seaborn:           0.12.1
	- setuptools:        59.6.0
	- six:               1.16.0
	- tensorboard:       2.11.0
	- tensorboard-data-server: 0.6.1
	- tensorboard-plugin-wit: 1.8.1
	- threadpoolctl:     3.1.0
	- tokenizers:        0.12.1
	- torch:             1.13.1+cu117
	- torchaudio:        0.13.1+cu117
	- torchmetrics:      0.9.3
	- torchvision:       0.14.1+cu117
	- tqdm:              4.64.1
	- transformers:      4.20.1
	- typing-extensions: 4.4.0
	- urllib3:           1.26.13
	- werkzeug:          2.2.2
	- wheel:             0.37.1
	- yarl:              1.8.1
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- ELF
	- processor:         x86_64
	- python:            3.10.6
	- version:           #63-Ubuntu SMP Thu Nov 24 13:43:17 UTC 2022


```

</details>

**Comment by celsofranssa** [comment]
It may have occurred due to an error in the model forward method.
