### ISSUE TITLE
FSDP and activation checkpointing leading to an error

### ISSUE THREAD

**Issue by w2ex** [Lightning-AI/lightning#16435]
### Bug description

Training a model with strategy `fsdp` using activation checkpointing worked fine up until 1.7.7. It stopped working from 1.8.0. 
This occurs using (`fairscale.nn.checkpoint_wrapper` or `torch.distributed.algorithms._checkpoint.checkpoint_wrapper.checkpoint_wrapper` ) and `fsdp` .
Using activation checkpointing with `DDPStrategy(find_unused_parameters=False)` works fine. Similarly, using FSDP without activation checkpointing is ok.

### How to reproduce the bug

```python
import os
from torch import optim, nn, utils, Tensor
from torchvision.datasets import MNIST
from torchvision.transforms import ToTensor
import pytorch_lightning as pl
from torch.distributed.algorithms._checkpoint.checkpoint_wrapper import checkpoint_wrapper
#from fairscale.nn import checkpoint_wrapper
from pytorch_lightning.strategies import DDPStrategy

# define any number of nn.Modules (or use your current ones)
encoder = nn.Sequential(nn.Linear(28 * 28, 64), nn.ReLU(), checkpoint_wrapper(nn.Linear(64, 64)), nn.ReLU(), nn.Linear(64, 3))
decoder = nn.Sequential(nn.Linear(3, 64), nn.ReLU(), checkpoint_wrapper(nn.Linear(64, 64)), nn.ReLU(), nn.Linear(64, 28*28))

# define the LightningModule
class LitAutoEncoder(pl.LightningModule):
    def __init__(self, encoder, decoder):
        super().__init__()
        self.encoder = encoder
        self.decoder = decoder

    def training_step(self, batch, batch_idx):
        # training_step defines the train loop.
        # it is independent of forward
        x, y = batch
        x = x.view(x.size(0), -1)
        z = self.encoder(x)
        x_hat = self.decoder(z)
        loss = nn.functional.mse_loss(x_hat, x)
        # Logging to TensorBoard (if installed) by default
        self.log("train_loss", loss)
        return loss

    def configure_optimizers(self):
        optimizer = optim.Adam(self.trainer.model.parameters(), lr=1e-3)
        return optimizer


# init the autoencoder
autoencoder = LitAutoEncoder(encoder, decoder)

dataset = MNIST(os.getcwd(), download=True, transform=ToTensor())
train_loader = utils.data.DataLoader(dataset)

trainer = pl.Trainer(limit_train_batches=100, max_epochs=1, accelerator='gpu', strategy='fsdp')#DDPStrategy(find_unused_parameters=False))
trainer.fit(model=autoencoder, train_dataloaders=train_loader)
```

### Error messages and logs

```
Traceback (most recent call last):
  File "dummy.py", line 45, in <module>
    trainer.fit(model=autoencoder, train_dataloaders=train_loader)
  File "./venv2/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 579, in fit
    call._call_and_handle_interrupt(  
  File "./venv2/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 36, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "./venv2/lib/python3.8/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 90, in launch
    return function(*args, **kwargs)  
  File "./venv2/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 621, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "./venv2/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1058, in _run
    results = self._run_stage()
  File "./venv2/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1137, in _run_stage
    self._run_train()
  File "./venv2/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1160, in _run_train
    self.fit_loop.run()
  File "./venv2/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "./venv2/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 267, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "./venv2/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "./venv2/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 214, in advance
    batch_output = self.batch_loop.run(kwargs)
  File "./venv2/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "./venv2/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 88, in advance
    outputs = self.optimizer_loop.run(optimizers, kwargs)
  File "./venv2/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "./venv2/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 200, in advance
    result = self._run_optimization(kwargs, self._optimizers[self.optim_progress.optimizer_position])
  File "./venv2/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 247, in _run_optimization
    self._optimizer_step(optimizer, opt_idx, kwargs.get("batch_idx", 0), closure)
  File "./venv2/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 357, in _optimizer_step
    self.trainer._call_lightning_module_hook(
  File "./venv2/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1302, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "./venv2/lib/python3.8/site-packages/pytorch_lightning/core/module.py", line 1661, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "./venv2/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py", line 169, in step
    step_output = self._strategy.optimizer_step(self._optimizer, self._optimizer_idx, closure, **kwargs)
  File "./venv2/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 234, in optimizer_step
    return self.precision_plugin.optimizer_step(
  File "./venv2/lib/python3.8/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 121, in optimizer_step
    return optimizer.step(closure=closure, **kwargs)
  File "./venv2/lib/python3.8/site-packages/torch/optim/optimizer.py", line 140, in wrapper
    out = func(*args, **kwargs)
  File "./venv2/lib/python3.8/site-packages/torch/optim/optimizer.py", line 23, in _use_grad
    ret = func(self, *args, **kwargs) 
  File "./venv2/lib/python3.8/site-packages/torch/optim/adam.py", line 183, in step
    loss = closure()
  File "./venv2/lib/python3.8/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 107, in _wrap_closure
      closure_result = closure()
  File "./venv2/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 147, in __call__
    self._result = self.closure(*args, **kwargs)
  File "./venv2/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 142, in closure
    self._backward_fn(step_output.closure_loss)
  File "./venv2/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 303, in backward_fn
    self.trainer._call_strategy_hook("backward", loss, optimizer, opt_idx)
  File "./venv2/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1440, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "./venv2/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 207, in backward
    self.precision_plugin.backward(closure_loss, self.lightning_module, optimizer, optimizer_idx, *args, **kwargs)
  File "./venv2/lib/python3.8/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 69, in backward
    model.backward(tensor, optimizer, optimizer_idx, *args, **kwargs)
  File "./venv2/lib/python3.8/site-packages/pytorch_lightning/core/module.py", line 1406, in backward
    loss.backward(*args, **kwargs)
  File "./venv2/lib/python3.8/site-packages/torch/_tensor.py", line 488, in backward
    torch.autograd.backward(
  File "./venv2/lib/python3.8/site-packages/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: setStorage: sizes [64, 3], strides [3, 1], storage offset 54595, and itemsize 4 requiring a storage size of 219148 are out of bounds for storage of size 0
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow): Trainer, LightningModule
#- PyTorch Lightning Version (e.g., 1.5.0): 1.8.0
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 1.10): 1.13.1+cu117
#- Python version (e.g., 3.9): 3.9
#- OS (e.g., Linux): Linux
#- CUDA/cuDNN version: 11.7
#- GPU models and configuration: NVidia GeForce RTX 3080
#- How you installed Lightning(`conda`, `pip`, source): pip
#- Running environment of LightningApp (e.g. local, cloud): local
```

</details>

### More info

I built this dummy model to debug a similar error I have on a bigger project. I cannot display the whole code here, but the error I get is `The tensor has a non-zero number of elements, but its data is not allocated yet. Caffe2 uses a lazy allocation, so you will need to call mutable_data() or raw_mutable_data() to actually allocate memory.`, and it occurs on the exact same conditions as the error described above (pytorch-lightning >= 1.8.0, activation checkpointing + FSDP)

cc @awaelchli @carmocca

**Comment by w2ex** [comment]
Ok, so I find how to make it work in 1.8+
Manually configuring the model sharding solves the issue :
```
from torch.distributed.fsdp.wrap import wrap, always_wrap_policy

class LitAutoEncoder(pl.LightningModule):
    [...]

    def configure_sharded_model(self):
        self.encoder = wrap(self.encoder, auto_wrap_policy=always_wrap_policy)
        self.decoder = wrap(self.decoder, auto_wrap_policy=always_wrap_policy)

```

I think the FSDP auto wrapping no longer wraps properly the checkpointing wrappers (which is a regression compared to 1.7), and manually calling the FSDP wrapper solves this. It would be nice not having to configure manually the sharding for simple models.

**Comment by w2ex** [comment]
It appears the solution I described above works with `fsdp` up until 1.8.6. It however does not work with `fsdp_native` :
`RuntimeError: shape '[4160]' is invalid for input of size 2080`

From 1.9.0, it stops working for `fsdp` too :
`ValueError: The optimizer does not seem to reference any FSDP parameters. HINT: Make sure to create the optimizer after setting up the model by referencing 'self.trainer.model.parameters()' in the 'configure_optimizers()' hook.`

**Comment by awaelchli** [comment]
@w2ex With FSDP, activation checkpointing has to be enabled in a different way. In Lightning, that's an argument to the strategy:

```py
# (lightning 2.0+)
from lightning.pytorch.strategies import FSDPStrategy

modules = [TransformerBlock]
trainer = Trainer(strategy=FSDPStrategy(activation_checkpointing=modules))
```
Here, TransformerBlock is just an example, representing the class of the layer(s) that should checkpoint their activations.
