### ISSUE TITLE
pytorch_lightning compatibility with pytorch that supports CUDA capability sm_86 

### ISSUE THREAD

**Issue by coffeedrunkpanda** [Lightning-AI/lightning#16515]
### Bug description

I was trying to run my pytorch_lightning training and it did not work because there was some incompatibility with my current
Hardware (RTX 3060 with CUDA capability sm_86) and the pytorch package. Then I've tried to update the package to 
pytorch==1.13.0 which is compatible with sm_86. But then I had another issue, pytorch lightning is not compatible with the pytorch package. I tried to update pytorch_lightning to the last version (1.9.0).
I currently have installed  CUDA 12.0 and the cuda toolkit package was updated when I installed pytorch_lightning==1.9.0.

Traceback:

```
>>> import torch
>>> torch.cuda.get_arch_list()
['sm_37', 'sm_50', 'sm_60', 'sm_70', 'sm_75', 'sm_80', 'sm_86']
>>> 
>>> 
>>> import pytorch_lightning as pl
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/horovod/torch/mpi_ops.py", line 33, in <module>
    from horovod.torch import mpi_lib_v2 as mpi_lib
ImportError: /usr/local/lib/python3.9/dist-packages/horovod/torch/mpi_lib_v2.cpython-39-x86_64-linux-gnu.so: undefined symbol: _Z13__THCudaCheck9cudaErrorPKci

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/__init__.py", line 35, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/callbacks/__init__.py", line 28, in <module>
    from pytorch_lightning.callbacks.pruning import ModelPruning
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/callbacks/pruning.py", line 31, in <module>
    from pytorch_lightning.core.module import LightningModule
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/core/__init__.py", line 16, in <module>
    from pytorch_lightning.core.module import LightningModule
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/core/module.py", line 50, in <module>
    from pytorch_lightning.trainer.connectors.logger_connector.fx_validator import _FxValidator
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/trainer/__init__.py", line 17, in <module>
    from pytorch_lightning.trainer.trainer import Trainer
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/trainer/trainer.py", line 57, in <module>
    from pytorch_lightning.loops import PredictionLoop, TrainingEpochLoop
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/loops/__init__.py", line 15, in <module>
    from pytorch_lightning.loops.batch import TrainingBatchLoop  # noqa: F401
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/loops/batch/__init__.py", line 15, in <module>
    from pytorch_lightning.loops.batch.training_batch_loop import TrainingBatchLoop  # noqa: F401
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 20, in <module>
    from pytorch_lightning.loops.optimization.manual_loop import _OUTPUTS_TYPE as _MANUAL_LOOP_OUTPUTS_TYPE
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/loops/optimization/__init__.py", line 15, in <module>
    from pytorch_lightning.loops.optimization.manual_loop import ManualOptimization  # noqa: F401
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/loops/optimization/manual_loop.py", line 23, in <module>
    from pytorch_lightning.loops.utilities import _build_training_step_kwargs, _extract_hiddens
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/loops/utilities.py", line 29, in <module>
    from pytorch_lightning.strategies.parallel import ParallelStrategy
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/strategies/__init__.py", line 24, in <module>
    from pytorch_lightning.strategies.horovod import HorovodStrategy  # noqa: F401
  File "/usr/local/lib/python3.9/dist-packages/pytorch_lightning/strategies/horovod.py", line 35, in <module>
    _HOROVOD_AVAILABLE = module_available("horovod.torch")
  File "/usr/local/lib/python3.9/dist-packages/lightning_utilities/core/imports.py", line 56, in module_available
    importlib.import_module(module_path)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.9/dist-packages/horovod/torch/__init__.py", line 35, in <module>
    from horovod.torch import elastic
  File "/usr/local/lib/python3.9/dist-packages/horovod/torch/elastic/__init__.py", line 17, in <module>
    from horovod.torch.mpi_ops import init, shutdown
  File "/usr/local/lib/python3.9/dist-packages/horovod/torch/mpi_ops.py", line 35, in <module>
    check_installed_version('pytorch', torch.__version__, e)
  File "/usr/local/lib/python3.9/dist-packages/horovod/common/util.py", line 260, in check_installed_version
    raise HorovodVersionMismatchError(name, version, installed_version) from exception
horovod.common.exceptions.HorovodVersionMismatchError: Framework pytorch installed with version 1.9.1+cu102 but found version 1.13.1+cu117.
             This can result in unexpected behavior including runtime errors.
             Reinstall Horovod using `pip install --no-cache-dir` to build with the new version.

```
Then, I tried to reinstall the Horovod as it was asked in the error message throught:

```
pip install --no-cache-dir horovod
```
then

```
pip install --no-cache-dir horovod[pytorch]
```
```
pip install --no-cache-dir horovod[pytorch_lightning]
```
And nothing worked.

Is there a pytorch_lightning package compatible with pytorch that supports  CUDA capability sm_86 ? 

### How to reproduce the bug

```python
My environment is the docker container which can be obtained through


docker pull annevalvezan/ml_dockers:ml-base-docker-0.0.1
```

then run the container 

```
docker run --name container --userns=host --ipc=host -it --gpus all annevalvezan/ml_dockers:ml-base-docker-0.0.1
```

After running the container

I have executed:

```
pip install pytorch_lightning==1.9.0
```

Enter python and import pytorch_lightning, which will generate the traceback.
```


### Error messages and logs

```
# Error messages and logs here please
```


### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 1.10):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>


### More info

_No response_

cc @awaelchli

**Comment by coffeedrunkpanda** [comment]
I don't really need `horovod`, it was just pre-installed. Your solution worked, thank you so much.

**Comment by awaelchli** [comment]
Great. That's what I thought. This is good news because we deprecated horovod from Lightning Trainer. In the next version of Lightning, it won't attempt to import horovod even if you have it installed in the environment, and so this problem would be solved for all users.
