### ISSUE TITLE
optimizer tensor size mismatch when resuming from ckpt with different number of workers using fsdp

### ISSUE THREAD

**Issue by leoleoasd** [Lightning-AI/lightning#16815]
### Bug description

I'm using `fsdp` distributed training, and I noticed when I resume training from a ckpt with a different number of workers, the optimize step will fail

### Error messages and logs

RuntimeError: The size of tensor a (56124554) must match the size of tensor b (14031139) at non-singleton dimension 0

The checkpoint is trained with a node with 6 cards. Then when resuming with 4 nodes (a total of 24 cards), it gives this error.

**Note that 56124554 / 4 = 14031138.5 ~= 14031139**

<details>
  <summary>Full Traceback</summary>
```
Traceback (most recent call last):
  File "/opt/code-fetcher/yuxlu-test.git/yuxlu-test/src/yuxlutest/main.py", line 168, in <module>
    main()
  File "/home/jobuser/build/yuxlu-test/environments/development-venv/lib/python3.10/site-packages/linkedin/clix/_clix.py", line 659, in decorated
    f.callback.invoke_listeners(e)
  File "/home/jobuser/build/yuxlu-test/environments/development-venv/lib/python3.10/site-packages/linkedin/clix/_clix.py", line 230, in invoke_listeners
    raise value
  File "/home/jobuser/build/yuxlu-test/environments/development-venv/lib/python3.10/site-packages/linkedin/clix/_clix.py", line 656, in decorated
    return f(*args, **kwargs)
  File "/home/jobuser/build/yuxlu-test/environments/development-venv/lib/python3.10/site-packages/linkedin/clix/ext/zipapp.py", line 41, in __call__
    super().__call__(*args, **kwargs)
  File "/home/jobuser/build/yuxlu-test/environments/development-venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/jobuser/build/yuxlu-test/environments/development-venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/jobuser/build/yuxlu-test/environments/development-venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jobuser/build/yuxlu-test/environments/development-venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/jobuser/build/yuxlu-test/environments/development-venv/lib/python3.10/site-packages/linkedin/clix/_clix.py", line 212, in __call__
    self.invoke_listeners(e)
  File "/home/jobuser/build/yuxlu-test/environments/development-venv/lib/python3.10/site-packages/linkedin/clix/_clix.py", line 230, in invoke_listeners
    raise value
  File "/home/jobuser/build/yuxlu-test/environments/development-venv/lib/python3.10/site-packages/linkedin/clix/_clix.py", line 206, in __call__
    return self.callback(self, *args, **kwargs)
  File "/home/jobuser/build/yuxlu-test/environments/development-venv/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/opt/code-fetcher/yuxlu-test.git/yuxlu-test/src/yuxlutest/main.py", line 152, in main
    trainer.fit(mnist_model, datamodule=datamodule, ckpt_path=ckpt_path)
  File "/home/jobuser/build/yuxlu-test/environments/development-venv/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 603, in fit
    call._call_and_handle_interrupt(
  File "/home/jobuser/build/yuxlu-test/environments/development-venv/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/jobuser/build/yuxlu-test/environments/development-venv/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 645, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/home/jobuser/build/yuxlu-test/environments/development-venv/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1098, in _run
    results = self._run_stage()
  File "/home/jobuser/build/yuxlu-test/environments/development-venv/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1177, in _run_stage
    self._run_train()
  File "/home/jobuser/build/yuxlu-test/environments/development-venv/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1200, in _run_train
    self.fit_loop.run()
  File "/home/jobuser/build/yuxlu-test/environments/development-venv/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/jobuser/build/yuxlu-test/environments/development-venv/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 267, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "/home/jobuser/build/yuxlu-test/environments/development-venv/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/jobuser/build/yuxlu-test/environments/development-venv/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 214, in advance
    batch_output = self.batch_loop.run(kwargs)
  File "/home/jobuser/build/yuxlu-test/environments/development-venv/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/jobuser/build/yuxlu-test/environments/development-venv/lib/python3.10/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 88, in advance
    outputs = self.optimizer_loop.run(optimizers, kwargs)
  File "/home/jobuser/build/yuxlu-test/environments/development-venv/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/jobuser/build/yuxlu-test/environments/development-venv/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 200, in advance
    result = self._run_optimization(kwargs, self._optimizers[self.optim_progress.optimizer_position])
  File "/home/jobuser/build/yuxlu-test/environments/development-venv/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 247, in _run_optimization
    self._optimizer_step(optimizer, opt_idx, kwargs.get("batch_idx", 0), closure)
  File "/home/jobuser/build/yuxlu-test/environments/development-venv/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 357, in _optimizer_step
    self.trainer._call_lightning_module_hook(
  File "/home/jobuser/build/yuxlu-test/environments/development-venv/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1342, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/home/jobuser/build/yuxlu-test/environments/development-venv/lib/python3.10/site-packages/pytorch_lightning/core/module.py", line 1661, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/home/jobuser/build/yuxlu-test/environments/development-venv/lib/python3.10/site-packages/pytorch_lightning/core/optimizer.py", line 169, in step
    step_output = self._strategy.optimizer_step(self._optimizer, self._optimizer_idx, closure, **kwargs)
  File "/home/jobuser/build/yuxlu-test/environments/development-venv/lib/python3.10/site-packages/pytorch_lightning/strategies/ddp.py", line 281, in optimizer_step
    optimizer_output = super().optimizer_step(optimizer, opt_idx, closure, model, **kwargs)
  File "/home/jobuser/build/yuxlu-test/environments/development-venv/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 234, in optimizer_step
    return self.precision_plugin.optimizer_step(
  File "/home/jobuser/build/yuxlu-test/environments/development-venv/lib/python3.10/site-packages/pytorch_lightning/plugins/precision/native_amp.py", line 98, in optimizer_step
    step_output = self.scaler.step(optimizer, **kwargs)
  File "/home/jobuser/build/yuxlu-test/environments/development-venv/lib/python3.10/site-packages/fairscale/optim/grad_scaler.py", line 317, in step
    retval = self._maybe_opt_step(optimizer, optimizer_state, *args, **kwargs)  # type: ignore
  File "/home/jobuser/build/yuxlu-test/environments/development-venv/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 285, in _maybe_opt_step
    retval = optimizer.step(*args, **kwargs)
  File "/home/jobuser/build/yuxlu-test/environments/development-venv/lib/python3.10/site-packages/torch/optim/lr_scheduler.py", line 65, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/jobuser/build/yuxlu-test/environments/development-venv/lib/python3.10/site-packages/torch/optim/optimizer.py", line 113, in wrapper
    return func(*args, **kwargs)
  File "/home/jobuser/build/yuxlu-test/environments/development-venv/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/jobuser/build/yuxlu-test/environments/development-venv/lib/python3.10/site-packages/torch/optim/adam.py", line 157, in step
    adam(params_with_grad,
  File "/home/jobuser/build/yuxlu-test/environments/development-venv/lib/python3.10/site-packages/torch/optim/adam.py", line 213, in adam
    func(params,
  File "/home/jobuser/build/yuxlu-test/environments/development-venv/lib/python3.10/site-packages/torch/optim/adam.py", line 262, in _single_tensor_adam
    exp_avg.mul_(beta1).add_(grad, alpha=1 - beta1)
RuntimeError: The size of tensor a (56124554) must match the size of tensor b (14031139) at non-singleton dimension 0
```
</details>

### Environment

<details>
  <summary>Current environment</summary>

trainer argument:
```python
  trainer = pl.Trainer(
      default_root_dir=config["root_dir"],
      accelerator="gpu",
      devices=torch.cuda.device_count()
      if torch.cuda.is_available()
      else None,  # limiting got iPython runs
      max_epochs=config["max_epochs"],
      logger=TensorBoardLogger(
        save_dir=config["root_dir"],
        name="",
        version=run_name,  # current time
        default_hp_metric=True,
        max_queue=200,
    ),
      log_every_n_steps=1,
      strategy=strategy, # DDPFullyShardedStrategy
      num_nodes=int(os.getenv("WORLD_SIZE", "1")) // torch.cuda.device_count(),
      callbacks=[ModelCheckpoint(
        dirpath=config["root_dir"] + "/" + run_name + "/checkpoints",
        save_top_k=-1,  # We have plenty of disks. Save all.
        mode="max",
        monitor="val/loss",
        filename="epoch={epoch}-step={step}-val_loss={val/loss:.5f}",
        every_n_train_steps=100,
        auto_insert_metric_name=False,
        save_last=True,
    )],
      precision=16,
      accumulate_grad_batches=config["accumulate_grad_batches"],
      val_check_interval=500,
      max_steps=config["max_steps"],
  )

```

```
#- Running environment of LightningApp (e.g. local, cloud): cloud

other information:
* CUDA:
	- GPU:
		- Tesla V100-PCIE-32GB
		- Tesla V100-PCIE-32GB
		- Tesla V100-PCIE-32GB
		- Tesla V100-PCIE-32GB
		- Tesla V100-PCIE-32GB
		- Tesla V100-PCIE-32GB
	- available:         True
	- version:           10.2
* Lightning:
	- lightning-utilities: 0.5.0
	- lion-pytorch:      0.0.6
	- pytorch-lightning: 1.8.6
	- torch:             1.12.1
	- torchmetrics:      0.7.2
* Packages:
	- absl-py:           0.15.0
	- accept-types:      0.4.1
	- acl-python-api:    15.0.0
	- aiodns:            2.0.0
	- aiohttp:           3.8.1
	- aiosignal:         1.2.0
	- ansicolors:        1.1.8
	- anyio:             2.2.0
	- apipkg:            1.5
	- appdirs:           1.4.4
	- appnope:           0.1.3
	- argon2-cffi:       20.1.0
	- async-generator:   1.10
	- async-timeout:     4.0.1
	- asynctest:         0.13.0
	- atomicwrites:      1.4.0
	- atpublic:          1.0
	- attrs:             21.4.0
	- avro-json-serializer: 0.5
	- avro-python3:      1.8.2
	- azure-common:      1.1.23
	- azure-core:        1.11.0
	- azure-identity:    1.4.0
	- azure-keyvault-secrets: 4.0.0
	- babel:             2.9.1
	- backcall:          0.2.0
	- backoff:           1.3.1
	- backports.entry-points-selectable: 1.0.4
	- bleach:            3.2.1
	- cachecontrol:      0.12.11
	- cached-property:   1.5.1
	- cachetools:        5.2.0
	- cachy:             0.3.0
	- certifi:           2022.6.15
	- cffi:              1.15.0
	- charset-normalizer: 2.1.0
	- cleo:              0.8.1
	- click:             8.1.3
	- clikit:            0.6.2
	- colorama:          0.4.3
	- construct:         2.8.11
	- contextvars:       2.4
	- coverage:          6.3.2
	- crashtest:         0.3.1
	- cryptography:      2.9.2
	- cython:            0.29.32
	- datasets:          2.5.1
	- decorator:         4.4.2
	- defusedxml:        0.6.0
	- deprecation:       2.0.7
	- dill:              0.3.5.1
	- diskcache:         5.3.0
	- distgradle:        2.1.6
	- distlib:           0.3.1
	- dnspython:         2.1.0.1
	- docutils:          0.17.1
	- entrypoints:       0.3.0.2
	- execnet:           1.7.1
	- fairscale:         0.4.13
	- filelock:          3.8.0
	- flake8:            4.0.1.1
	- flake8-annotations-complexity: 0.0.6.2
	- flake8-bugbear:    20.1.4
	- flake8-builtins:   1.4.2
	- flake8-pie:        0.5.0.1
	- flit:              1.3.0.1
	- flit-core:         3.7.1
	- flufl.lock:        5.0.1
	- frozenlist:        1.2.0
	- fsspec:            2022.11.0
	- gitdb:             4.0.9
	- gitpython:         3.1.27
	- google-auth:       2.10.0
	- google-auth-oauthlib: 0.4.6
	- googleapis-common-protos: 1.54.0
	- grpcio:            1.47.0
	- halo:              0.0.30
	- html5lib:          1.0.1
	- huggingface-hub:   0.10.1
	- idna:              3.3
	- idna-ssl:          1.1.0
	- immutables:        0.9
	- importlib-metadata: 4.12.0
	- importlib-resources: 5.1.2
	- iniconfig:         1.1.1
	- intreehooks:       1.0
	- ipykernel:         5.5.3
	- ipython:           7.19.0
	- ipython-genutils:  0.2.0
	- isodate:           0.6.0
	- jedi:              0.18.0
	- jeepney:           0.4.3.2
	- jinja2:            3.0.3
	- json5:             0.9.5
	- jsonschema:        3.2.0
	- jupyter-client:    6.1.12
	- jupyter-core:      4.7.1
	- jupyter-packaging: 0.9.2
	- jupyter-server:    1.6.1
	- jupyterlab:        3.2.9
	- jupyterlab-pygments: 0.1.2
	- jupyterlab-server: 2.4.0
	- keyring:           21.4.0
	- kms-python-api:    3.1.13
	- ldap3:             2.9.1
	- lightning-utilities: 0.5.0
	- lion-pytorch:      0.0.6
	- log-symbols:       0.0.14
	- lxml:              4.8.0
	- markdown:          3.4.1
	- markupsafe:        2.1.1
	- mccabe:            0.7.0
	- mistune:           0.8.4
	- more-itertools:    8.0.2
	- msal:              1.15.0
	- msal-extensions:   0.2.2
	- msgpack:           1.0.4
	- msrest:            0.6.10
	- multidict:         5.2.0
	- multiprocess:      0.70.11.1
	- mypy:              0.812
	- mypy-extensions:   0.4.3
	- nbclassic:         0.2.7
	- nbclient:          0.5.0
	- nbconvert:         6.0.7
	- nbformat:          5.1.3
	- nest-asyncio:      1.4.0
	- netifaces:         0.10.9
	- notebook:          6.3.0
	- numpy:             1.23.0
	- oauthlib:          3.1.0
	- oldest-supported-numpy: 2022.1.30
	- packaging:         21.3
	- pandas:            1.3.5
	- pandocfilters:     1.4.2
	- parsimonious:      0.8.1
	- parso:             0.8.1
	- pastel:            0.2.1
	- pbkdf2:            1.3
	- pbr:               5.6.0
	- pexpect:           4.8.0
	- pickleshare:       0.7.5
	- pip:               21.3.1
	- pkginfo:           1.6.1
	- pluggy:            1.0.0
	- poetry:            1.1.4.1
	- poetry-core:       1.0.8
	- portalocker:       1.7.1
	- prometheus-client: 0.10.1
	- prompt-toolkit:    3.0.14
	- protobuf:          3.19.4
	- psutil:            5.9.0
	- ptyprocess:        0.7.0
	- py:                1.11.0
	- pyarrow:           8.0.0
	- pyasn1:            0.4.8
	- pyasn1-modules:    0.2.8
	- pycares:           3.0.0
	- pycodestyle:       2.8.0
	- pycparser:         2.20
	- pydeprecate:       0.3.1
	- pyflakes:          2.4.0
	- pygments:          2.10.0
	- pyjwt:             1.7.1
	- pylev:             1.3.0
	- pyopenssl:         19.1.0
	- pyparsing:         3.0.6
	- pyrsistent:        0.14.11
	- pytest:            7.1.2
	- pytest-cov:        3.0.0.1
	- pytest-datadir:    1.3.1
	- pytest-forked:     1.1.3
	- pytest-html:       3.1.1
	- pytest-metadata:   1.11.0
	- pytest-runner:     5.3.1
	- pytest-xdist:      2.5.0
	- python-dateutil:   2.8.2
	- python-seco-range: 9.1.3
	- pytoml:            0.1.21
	- pytorch-lightning: 1.8.6
	- pytz:              2021.3
	- pyyaml:            6.0
	- pyzmq:             22.0.3
	- regex:             2022.7.25
	- requests:          2.28.1
	- requests-oauthlib: 1.3.0
	- requests-toolbelt: 0.9.1
	- responses:         0.18.0
	- retry:             0.9.2.1
	- rsa:               4.9
	- secretstorage:     3.1.2.1
	- send2trash:        1.5.0
	- setuptools:        59.6.0
	- setuptools-git:    1.2
	- setuptools-scm:    6.4.2
	- setuptools-scm-git-archive: 1.1
	- shellingham:       1.3.1
	- simplejson:        3.17.2
	- six:               1.16.0
	- smmap:             5.0.0
	- sniffio:           1.2.0
	- spinners:          0.0.24
	- statsd:            3.3.0
	- tblib:             1.4.0
	- tbvaccine:         0.3.1
	- tensorboard:       2.10.0
	- tensorboard-data-server: 0.6.1
	- tensorboard-plugin-wit: 1.8.1
	- tensorboardx:      2.2
	- termcolor:         1.1.0
	- terminado:         0.9.4
	- testpath:          0.4.4
	- tokenizers:        0.11.6
	- toml:              0.10.2
	- tomli:             2.0.1
	- tomlkit:           0.7.2
	- tools-events-api:  6.0.10
	- torch:             1.12.1
	- torchmetrics:      0.7.2
	- tornado:           6.1
	- tqdm:              4.64.1
	- traitlets:         5.0.5
	- transformers:      4.23.1
	- types-futures:     3.3.1
	- types-protobuf:    3.18.3
	- typing-extensions: 4.4.0
	- urllib3:           1.26.9
	- virtualenv:        20.1.0
	- wcwidth:           0.2.5
	- weaver-grpc-python-api: 0.0.2
	- weaver-python-api: 4.0.0
	- webencodings:      0.5.1
	- werkzeug:          2.2.2
	- wheel:             0.37.0
	- xxhash:            3.0.0
	- yarl:              1.7.2
	- zipp:              3.8.0
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- ELF
	- processor:         x86_64
	- python:            3.10.2
	- version:           #1 SMP Wed Apr 27 20:34:34 UTC 2022
```

</details>

### More info

This problem makes elastic training impossible since `torchrun` will restart all workers when a new worker joins, and all of them will fail on this tensor size mismatch.

cc @awaelchli @tchaton @justusschock

**Comment by leoleoasd** [comment]
Is there any way to clear optimizer state when resuming? I tried the following code, and it isn't working:
```
def on_load_checkpoint(self, checkpoint):
    from lightning_lite.utilities.optimizer import _optimizers_to_device
    self.trainer.strategy.setup_optimizers(self.trainer)
    _optimizers_to_device(self.trainer.strategy.optimizers, self.trainer.strategy.root_device)
```

It seems that `configure_optimizers` are called twice, once in `on_load_checkpoint` and once later, which loads the optimizer state.

**Comment by leng-yue** [comment]
I also met the same error. Is there any update?

**Comment by leoleoasd** [comment]
My current solution is to use a custom strategy:
```
    class MyDDPFullyShardedNativeStrategy(DDPFullyShardedNativeStrategy):
        @property
        def lightning_restore_optimizer(self) -> bool:
            """Override to disable Lightning restoring optimizers/schedulers.

            This is useful for plugins which manage restoring optimizers/schedulers.
            """
            return False
```

I'm not an expert at this, and I don't know why the optimizer's state isn't shared across nodes. It seems that the shape of optimizer's state is related to the number of nodes (so each node have a separate state? I don't know.).

**Comment by leng-yue** [comment]
Appreciate!

**Comment by leng-yue** [comment]
After debugging for a while, I believe there is an issue with the checkpoint saving process that results in an incorrect optimization status size in FSDP checkpoints. Seems like lightning had customized `save_checkpoint` and `load_checkpoint` only in fabric (#17526): https://github.com/Lightning-AI/lightning/blob/00909ba3ffbba92e21d84cc013ec0f148c459ff9/src/lightning/fabric/strategies/fsdp.py#L322 

Should we also implement it in PyTorch lightning?

**Comment by leoleoasd** [comment]
Sadly pytorch's `FileSystemWriter` don't support fsspec paths. Since FSDP is mainly used inside big clusters, I assume supporting remote filesystem is kinda important for it?

**Comment by leng-yue** [comment]
As a workaround, I mount NFS to my servers...
