### ISSUE TITLE
FSDP + inference_mode fails with PyTorch 2.0 

### ISSUE THREAD

**Issue by carmocca** [Lightning-AI/lightning#16908]
### Bug description

```python
../../src/pytorch_lightning/trainer/connectors/checkpoint_connector.py:278: in restore_model
    trainer.strategy.load_model_state_dict(self._loaded_checkpoint)
../../src/pytorch_lightning/strategies/strategy.py:351: in load_model_state_dict
    self.lightning_module.load_state_dict(checkpoint["state_dict"])
/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py:2027: in load_state_dict
    load(self, state_dict)
/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py:2015: in load
    load(child, child_state_dict, child_prefix)
/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py:2015: in load
    load(child, child_state_dict, child_prefix)
/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py:2009: in load
    module._load_from_state_dict(
/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py:1909: in _load_from_state_dict
    hook(state_dict, prefix, local_metadata, strict, missing_keys, unexpected_keys, error_msgs)
/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py:69: in __call__
    return self.hook(module, *args, **kwargs)
/usr/local/lib/python3.9/dist-packages/torch/utils/_contextlib.py:115: in decorate_context
    return func(*args, **kwargs)
/usr/local/lib/python3.9/dist-packages/torch/distributed/fsdp/_state_dict_utils.py:700: in _pre_load_state_dict_hook
    _pre_load_state_dict_hook_fn[fsdp_state._state_dict_type](
/usr/local/lib/python3.9/dist-packages/torch/distributed/fsdp/_state_dict_utils.py:332: in _full_pre_load_state_dict_hook
    _enter_unshard_params_ctx(module, fsdp_state, writeback=True)
/usr/local/lib/python3.9/dist-packages/torch/distributed/fsdp/_state_dict_utils.py:109: in _enter_unshard_params_ctx
    fsdp_state._unshard_params_ctx[module].__enter__()
/usr/lib/python3.9/contextlib.py:119: in __enter__
    return next(self.gen)
/usr/local/lib/python3.9/dist-packages/torch/distributed/fsdp/_unshard_param_utils.py:224: in _unshard_fsdp_state_params
    stack.enter_context(_unflatten_as_params(state, module))
/usr/lib/python3.9/contextlib.py:448: in enter_context
    result = _cm_type.__enter__(cm)
/usr/lib/python3.9/contextlib.py:119: in __enter__
    return next(self.gen)
/usr/local/lib/python3.9/dist-packages/torch/distributed/fsdp/_unshard_param_utils.py:116: in _unflatten_as_params
    with handles[0].unflatten_as_params():
/usr/lib/python3.9/contextlib.py:119: in __enter__
    return next(self.gen)
/usr/local/lib/python3.9/dist-packages/torch/distributed/fsdp/flat_param.py:1540: in unflatten_as_params
    self._use_unsharded_views(as_params=True)
/usr/local/lib/python3.9/dist-packages/torch/distributed/fsdp/flat_param.py:1405: in _use_unsharded_views
    module.register_parameter(param_name, nn.Parameter(view))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

cls = <class 'torch.nn.parameter.Parameter'>
data = tensor([[-0.0358, -0.0199,  0.1170,  ...,  0.1346,  0.0104,  0.1507],
        [-0.0653, -0.0155,  0.0075,  ..., -0.111...0925,  0.1059,  0.0031],
        [ 0.0626,  0.0617, -0.1541,  ..., -0.0366,  0.0817, -0.0724]],
       device='cuda:0')
requires_grad = True

    def __new__(cls, data=None, requires_grad=True):
        if data is None:
            data = torch.empty(0)
        if type(data) is torch.Tensor or type(data) is Parameter:
            # For ease of BC maintenance, keep this path for standard Tensor.
            # Eventually (tm), we should change the behavior for standard Tensor to match.
>           return torch.Tensor._make_subclass(cls, data, requires_grad)
E           RuntimeError: Setting requires_grad=True on inference tensor outside InferenceMode is not allowed.

/usr/local/lib/python3.9/dist-packages/torch/nn/parameter.py:36: RuntimeError
```

https://dev.azure.com/Lightning-AI/lightning/_build/results?buildId=140547&view=logs&j=5b0799f7-725e-5b16-9b83-c0a5a25d03f0&t=447f4a64-1b89-5215-644b-382bd30b3565&l=3708

### How to reproduce the bug

```python
Remove:

https://github.com/Lightning-AI/lightning/blob/b4e29e0c8f2b039d977110569b66cd5e244a8b45/tests/tests_pytorch/strategies/test_fsdp.py#L250
```

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

Master with PyTorch 2.0

**Comment by carmocca** [comment]
This needs to be reproduced with just PyTorch so they take a look. If this is not fixed before the 2.0 release, we should update our `Trainer(inference_mode)` logic to account for this bug

**Comment by awaelchli** [comment]
Here is the torch-only repro:

```py
import os

import torch.cuda
import torch.nn as nn
import torch.distributed as dist
import torch.multiprocessing as mp
from torch.distributed.fsdp import FullyShardedDataParallel


def work(rank):
    os.environ["MASTER_ADDR"] = "127.0.0.1"
    os.environ["MASTER_PORT"] = "1234"
    dist.init_process_group("nccl", world_size=2, rank=rank)

    torch.cuda.set_device(rank)
    device = torch.device("cuda", rank)

    model = nn.Linear(100, 50).to(device)
    model = FullyShardedDataParallel(model)

    with torch.inference_mode():
        model(torch.rand(2, 100))

    torch.save(model.state_dict(), "fsdp_model.pt")

    with torch.inference_mode():
        model.load_state_dict(torch.load("fsdp_model.pt"))
        model(torch.rand(2, 100))


def run():
    mp.spawn(work, nprocs=2)


if __name__ == "__main__":
    run()


```

Error:

```
Traceback (most recent call last):
  File "/home/adrian/anaconda3/envs/lightning/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/adrian/repositories/lightning/repro.py", line 25, in work
    torch.save(model.state_dict(), "fsdp_model.pt")
  File "/home/adrian/anaconda3/envs/lightning/lib/python3.9/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 2402, in state_dict
    with summon_ctx:
  File "/home/adrian/anaconda3/envs/lightning/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/adrian/anaconda3/envs/lightning/lib/python3.9/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 3002, in _summon_full_params
    stack.enter_context(self._fsdp_wrapped_module.unflatten_as_params())
  File "/home/adrian/anaconda3/envs/lightning/lib/python3.9/contextlib.py", line 448, in enter_context
    result = _cm_type.__enter__(cm)
  File "/home/adrian/anaconda3/envs/lightning/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/adrian/anaconda3/envs/lightning/lib/python3.9/site-packages/torch/distributed/fsdp/flatten_params_wrapper.py", line 144, in unflatten_as_params
    with self._flat_param_handle.unflatten_as_params():
  File "/home/adrian/anaconda3/envs/lightning/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/adrian/anaconda3/envs/lightning/lib/python3.9/site-packages/torch/distributed/fsdp/flat_param.py", line 1019, in unflatten_as_params
    self._unflatten(as_params=True)
  File "/home/adrian/anaconda3/envs/lightning/lib/python3.9/site-packages/torch/distributed/fsdp/flat_param.py", line 990, in _unflatten
    module.register_parameter(param_name, nn.Parameter(view))
  File "/home/adrian/anaconda3/envs/lightning/lib/python3.9/site-packages/torch/nn/parameter.py", line 36, in __new__
    return torch.Tensor._make_subclass(cls, data, requires_grad)
RuntimeError: Setting requires_grad=True on inference tensor outside InferenceMode is not allowed.
```

**Comment by awaelchli** [comment]
@carmocca FYI, this is not just with PyTorch 2.0. This also failed on 1.13.1.
