### ISSUE TITLE
Let TorchCollective work with default `torch.distributed` process group

### ISSUE THREAD

**Issue by belerico** [Lightning-AI/lightning#16922]
### Description & Motivation

Right now TorchCollective cannot own the default, i.e. the `None` one, torch.distributed process group. In fact, suppose that i want to instantiate a custom distributed training using only TorchCollective:
```python
import os

import torch
from lightning.fabric.plugins.collectives import TorchCollective


def fn(collective):
    t = torch.ones(1)
    collective.all_reduce(t)


def init_process(rank: int, world_size: int):
    os.environ["MASTER_ADDR"] = "localhost"
    os.environ["MASTER_PORT"] = "29400"
    world_collective = TorchCollective()
    world_collective.setup(backend="gloo", init_method="tcp://localhost:29400", rank=rank, world_size=world_size)
    fn(world_collective)


if __name__ == "__main__":
    world_size = 4
    torch.multiprocessing.spawn(
        init_process,
        args=(world_size,),
        nprocs=world_size,
        join=True,
        daemon=False,
        start_method="spawn",
    )
```
This results in the following error:
```python
Traceback (most recent call last):
  File "/home/belerico/Desktop/orobix/ppo-fabric/test.py", line 23, in <module>
    torch.multiprocessing.spawn(
  File "/home/belerico/miniconda3/envs/lightning-ai/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/belerico/miniconda3/envs/lightning-ai/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/home/belerico/miniconda3/envs/lightning-ai/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/belerico/miniconda3/envs/lightning-ai/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/belerico/Desktop/orobix/ppo-fabric/test.py", line 18, in init_process
    fn(world_collective)
  File "/home/belerico/Desktop/orobix/ppo-fabric/test.py", line 9, in fn
    collective.all_reduce(t)
  File "/home/belerico/miniconda3/envs/lightning-ai/lib/python3.9/site-packages/lightning/fabric/plugins/collectives/torch_collective.py", line 43, in all_reduce
    dist.all_reduce(tensor, op=op, group=self.group)
  File "/home/belerico/miniconda3/envs/lightning-ai/lib/python3.9/site-packages/lightning/fabric/plugins/collectives/collective.py", line 35, in group
    raise RuntimeError(
RuntimeError: `TorchCollective` does not own a group. HINT: try `collective.create_group().group`
```
that's becuse the `self.group` property defined in [here](https://github.com/Lightning-AI/lightning/blob/master/src/lightning/fabric/plugins/collectives/collective.py#L33) raises an error if `self._group` is None.  

To circumvent this error one can do the following:
```python

def init_process(rank: int, world_size: int):
    """Initialize the distributed environment."""
    os.environ["MASTER_ADDR"] = "localhost"
    os.environ["MASTER_PORT"] = "29400"
    dist.init_process_group(backend="gloo", init_method="tcp://localhost:29400", rank=rank, world_size=world_size)
    world_collective = TorchCollective()
    world_collective.create_group(ranks=list(range(world_size)))
    fn(world_collective)
```
which creates first the process group with the standard torch.distributed package and then creates a new one with all the ranks participating.  

The proposal is to let TorchCollective work with the default process group of the torch.distributed by simply removing the check over the None state  in the `self._group` property, removing then the needs to create another group with all the ranks participating to it.

cc @borda @awaelchli @carmocca @justusschock

**Comment by carmocca** [comment]
I like the proposal.

But instead of removing the check, I would override the `group` property in `TorchCollective` to try to default to the world:


```python
class TorchCollective(Collective):
    @property
    def group(self):
        if self._group is None:
            # None if not initialized
            self._group = group.WORLD
        return super().group
```

Let me know what you think!

Note that the implementation of the collectives is not finished and might not be reliable or might change unexpectedly. It's great that you are finding uses for it already though

**Comment by belerico** [comment]
Hi @carmocca, i didn't think about that but it's perfect! If you want i can open a PR with the change

**Comment by carmocca** [comment]
Sure, go ahead

**Comment by belerico** [comment]
Hi @carmocca, after a bit of working on the issue some doubts have come up that i want to discuss before opening the PR.  

1. With the suggested change now multiple collectives can operate on the WORLD group: is this intended? An alternative can be one in which only one collective (namely the first one calling the `setup` method) can own the WORLD group, with all the other collectives working on new groups
2. If i have intended this correctly, the `teardown` method was supposed to be possibly called once for every collective, destroying the collective group and the WORLD one if managed by `TorchCollective`. Now, something like the following raises `RuntimeError: Invalid process group specified`:

      ```python
      import os
      
      import torch
      from lightning.fabric.plugins.collectives import TorchCollective
      
      
      def init_process(rank: int, world_size: int):
          os.environ["MASTER_ADDR"] = "localhost"
          os.environ["MASTER_PORT"] = "29400"
          collective1 = TorchCollective()
          collective2 = TorchCollective()
          collective1.setup(backend="gloo", rank=rank, world_size=world_size)
          collective2.setup()
          collective2.create_group()
          collective1.teardown()
          collective2.teardown()
      
      
      if __name__ == "__main__":
          world_size = 4
          torch.multiprocessing.spawn(
              init_process,
              args=(world_size,),
              nprocs=world_size,
              join=True,
              daemon=False,
              start_method="spawn",
          )
      ```
      which is expected, since after `collective1.teardown()` has destroyed the WORLD group the `collective2.group` has leaked: it is not None but it is no more inside the `torch.distributed_c10d._pg_map`. A quick fix is to check inside the `TorchCollective.teardown` method if `self.group in torch.distributed_c10d._pg_map` and calling `super().teardown()` if that is true, setting `self._group = None` otherwise

**Comment by carmocca** [comment]
1. Our intention was that each collective would own a group, but I don't think we can or should enforce that the groups are distinct across collectives. So I would say it's intended.


2. That looks good to me. Here's what I would implement

```diff
diff --git a/src/lightning/fabric/plugins/collectives/torch_collective.py b/src/lightning/fabric/plugins/collectives/torch_collective.py
index 4159735d6..357b3019b 100644
--- a/src/lightning/fabric/plugins/collectives/torch_collective.py
+++ b/src/lightning/fabric/plugins/collectives/torch_collective.py
@@ -134,18 +134,30 @@ class TorchCollective(Collective):
             os.environ.pop("MASTER_PORT", None)
         return self
 
+    @property
+    def group(self):
+        if self._group is None:
+            # None if not initialized
+            from torch.distributed import group
+            self._group = group.WORLD
+        return super().group
+
     def teardown(self) -> Self:  # type: ignore[valid-type]
-        non_group_member = self.group == dist.GroupMember.NON_GROUP_MEMBER
+        group_member = self.group != dist.GroupMember.NON_GROUP_MEMBER
         super().teardown()  # will destroy its own group
         # try to destroy the default group. this should only be done by a group member to avoid race conditions,
         # and only if the class is managing it
-        if not non_group_member and TorchCollective.manages_default_group:
-            default_group = dist.GroupMember.WORLD
-            if default_group is not None:  # not destroyed already
-                group_map = dist.distributed_c10d._pg_map
-                if len(group_map) == 1 and default_group in group_map:  # only the default group is left
-                    self.destroy_group(default_group)
-                    TorchCollective.manages_default_group = False
+        if (
+            group_member
+            and TorchCollective.manages_default_group
+            and (default_group := dist.GroupMember.WORLD) is not None  # not destroyed already
+            and len(dist.distributed_c10d._pg_map) == 1  # only the default group is left
+        ):
+            self.destroy_group(default_group)
+            TorchCollective.manages_default_group = False
+        elif TorchCollective.manages_default_group and dist.GroupMember.WORLD is None:  # destroyed already
+            # reset this flag in case a collective destroyed the group already
+            TorchCollective.manages_default_group = False
         return self
 
     @classmethod
@@ -168,7 +180,8 @@ class TorchCollective(Collective):
     def destroy_group(cls, group: CollectibleGroup) -> None:
         # can be called by all processes in the default group, group will be `object()` if they are not part of the
         # current group
-        dist.destroy_process_group(group)  # type: ignore[arg-type]
+        if group in dist.distributed_c10d._pg_map:
+            dist.destroy_process_group(group)  # type: ignore[arg-type]
 
     @classmethod
     def _convert_to_native_op(cls, op: Union[str, ReduceOp, RedOpType]) -> Union[ReduceOp, RedOpType]:
```

**Comment by awaelchli** [comment]
I think this is totally fine, and I see use cases for this. A collective object sharing the same group as another is totally fine in my opinion. And for teardown, I think it is fine too. We just make it so that it is a no-op if the group has already been destroyed :) What do you think?

**Comment by carmocca** [comment]
Yes. That's also what I propose with my diff above
