### ISSUE TITLE
Incompatibility with MLFlow 1.30

### ISSUE THREAD

**Issue by whrichd** [Lightning-AI/lightning#17084]
### Bug description

This is just to let you guys know that there's an incompatibility bug with MLFlow 1.30.

PL creates runs through [this line](https://github.com/Lightning-AI/lightning/blob/caa3329b79965f7712e49bd9f8933f7a4686c49b/src/pytorch_lightning/loggers/mlflow.py#L195) without specifying the run_name, which will make MLFlow generate a random run_name [here](https://github.com/mlflow/mlflow/blob/d975b5a19c8b04db97ba446cce91eb876f8ee60e/mlflow/store/tracking/file_store.py#L607) and then this will be added to the tags [here](https://github.com/mlflow/mlflow/blob/d975b5a19c8b04db97ba446cce91eb876f8ee60e/mlflow/store/tracking/file_store.py#L632). But if a run_name has already been passed through PL with the tags, this will create a duplication error.

This is fixed in MLFlow 2.0. So could you perhaps change the version requirement, or add run_name to the create_run line in src/pytorch_lightning/loggers/mlflow.py? Or if someone can investigate further it would be great too. Thanks!

### How to reproduce the bug

```python
- start an experiment with run_name specified in the config, and log with MLFlow.
```

### Error messages and logs

```
Traceback (most recent call last):
  File "run_finetune.py", line 104, in main
    logger.log_hyperparams({'trainer': OmegaConf.to_object(cfg.trainer)})
  File "***/lib/python3.8/site-packages/lightning_utilities/core/rank_zero.py", line 27, in wrapped_fn
    return fn(*args, **kwargs)
  File "***/lib/python3.8/site-packages/pytorch_lightning/loggers/mlflow.py", line 231, in log_hyperparams
    self.experiment.log_param(self.run_id, k, v)
  File "***/lib/python3.8/site-packages/pytorch_lightning/loggers/logger.py", line 53, in experiment
    return get_experiment() or DummyExperiment()
  File "***/lib/python3.8/site-packages/lightning_utilities/core/rank_zero.py", line 27, in wrapped_fn
    return fn(*args, **kwargs)
  File "***/lib/python3.8/site-packages/pytorch_lightning/loggers/logger.py", line 51, in get_experiment
    return fn(self)
  File "***/lib/python3.8/site-packages/pytorch_lightning/loggers/mlflow.py", line 195, in experiment
    run = self._mlflow_client.create_run(experiment_id=self._experiment_id, tags=resolve_tags(self.tags))
  File "***/lib/python3.8/site-packages/mlflow/tracking/client.py", line 270, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
  File "***/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 108, in create_run
    return self.store.create_run(
  File "***/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py", line 204, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "***/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py", line 57, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "***/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 280, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "***/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 206, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: BAD_REQUEST: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "tag_pk"
DETAIL:  Key (key, run_uuid)=(mlflow.runName, 8****) already exists.

[SQL: INSERT INTO tags (key, value, run_uuid) VALUES (%(key)s, %(value)s, %(run_uuid)s)]
[parameters: (****{'key': 'mlflow.runName', 'value': 'finetune_trial', 'run_uuid': '8****'}, {'key': 'mlflow.runName', 'value': 'bouncy-squid-39', 'run_uuid': '8****'})]

```

### Environment

<details>
  <summary>Current environment</summary>

```
PyTorch Lightning 1.8.6
MLFlow 1.30.0
```

</details>

**Comment by awaelchli** [comment]
Hey @whrichd 

Since you have mlflow installed and a code that can reproduce this, would you mind determining in which version of MLflow between 1.30.0 and 2.0 this was solved? We would could then set the minimum supported version to that. Your help would very much be appreciated here!

**Comment by whrichd** [comment]
Hi @awaelchli the next version after 1.30.0 is 2.0.0. And the latter works while the former doesn't. Another detail is that it only throws the error if the backend for MLFlow tracking is an SQLite database. It works if I'm tracking with the local filesystem.

**Comment by awaelchli** [comment]
Okay @whrichd. But in this case, I think we shouldn't do anything on the Lightning side. People using the local filesystem should not be required to run the latest version. I would say it is up to the user to decide here. Lightning should only care if the problem is in the `lightning.pytorch.loggers.MLFlowLogger` code. 

Not a strong opinion here as a non-mlflow user. If you have any suggestions what can be done on our side, let me know.

**Comment by whrichd** [comment]
Ok! I'll let you know if we can fix it easily with our setup
