### ISSUE TITLE
Lightning 2.0 - `ImportError: cannot import name 'Schema' from 'pydantic'`

### ISSUE THREAD

**Issue by thesofakillers** [Lightning-AI/lightning#17106]
### Bug description

When importing lightning with the new 2.0 release, I get the following error

```
ImportError: cannot import name 'Schema' from 'pydantic'
```

### How to reproduce the bug

```python
import lightning
```

### Error messages and logs

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/thesofakillers/miniconda3/envs/thesis/lib/python3.10/site-packages/lightning/__init__.py", line 18, in <module>
    from lightning.app import storage  # noqa: E402
  File "/Users/thesofakillers/miniconda3/envs/thesis/lib/python3.10/site-packages/lightning/app/__init__.py", line 24, in <module>
    from lightning.app import components  # noqa: E402, F401
  File "/Users/thesofakillers/miniconda3/envs/thesis/lib/python3.10/site-packages/lightning/app/components/__init__.py", line 1, in <module>
    from lightning.app.components.database.client import DatabaseClient
  File "/Users/thesofakillers/miniconda3/envs/thesis/lib/python3.10/site-packages/lightning/app/components/database/__init__.py", line 1, in <module>
    from lightning.app.components.database.client import DatabaseClient
  File "/Users/thesofakillers/miniconda3/envs/thesis/lib/python3.10/site-packages/lightning/app/components/database/client.py", line 22, in <module>
    from lightning.app.components.database.utilities import _GeneralModel
  File "/Users/thesofakillers/miniconda3/envs/thesis/lib/python3.10/site-packages/lightning/app/components/database/utilities.py", line 20, in <module>
    from fastapi import Response, status
  File "/Users/thesofakillers/miniconda3/envs/thesis/lib/python3.10/site-packages/fastapi/__init__.py", line 5, in <module>
    from .applications import FastAPI
  File "/Users/thesofakillers/miniconda3/envs/thesis/lib/python3.10/site-packages/fastapi/applications.py", line 3, in <module>
    from fastapi import routing
  File "/Users/thesofakillers/miniconda3/envs/thesis/lib/python3.10/site-packages/fastapi/routing.py", line 6, in <module>
    from fastapi import params
  File "/Users/thesofakillers/miniconda3/envs/thesis/lib/python3.10/site-packages/fastapi/params.py", line 4, in <module>
    from pydantic import Schema
ImportError: cannot import name 'Schema' from 'pydantic' (/Users/thesofakillers/miniconda3/envs/thesis/lib/python3.10/site-packages/pydantic/__init__.cpython-310-darwin.so)
```

### Environment

**<details>
  <summary>Current environment</summary>

```
* CUDA:
	- GPU:               None
	- available:         False
	- version:           None
* Lightning:
	- lightning:         2.0.0
	- lightning-cloud:   0.5.31
	- lightning-utilities: 0.8.0
	- pytorch-lightning: 2.0.0
	- torch:             2.0.0
	- torchmetrics:      0.11.4
* Packages:
	- accelerate:        0.17.1
	- aiofiles:          22.1.0
	- aiohttp:           3.8.4
	- aiosignal:         1.3.1
	- aiosqlite:         0.18.0
	- aniso8601:         9.0.1
	- anyio:             3.6.2
	- appnope:           0.1.3
	- argon2-cffi:       21.3.0
	- argon2-cffi-bindings: 21.2.0
	- arrow:             1.2.3
	- asttokens:         2.2.1
	- async-timeout:     4.0.2
	- attrs:             22.2.0
	- babel:             2.12.1
	- backcall:          0.2.0
	- beautifulsoup4:    4.11.2
	- black:             23.1.0
	- bleach:            6.0.0
	- blessed:           1.20.0
	- certifi:           2022.12.7
	- cffi:              1.15.1
	- charset-normalizer: 3.1.0
	- click:             8.1.3
	- comm:              0.1.2
	- contourpy:         1.0.7
	- croniter:          1.3.8
	- cycler:            0.11.0
	- dateutils:         0.6.12
	- debugpy:           1.6.6
	- decorator:         5.1.1
	- deepdiff:          6.2.3
	- defusedxml:        0.7.1
	- diffusers:         0.14.0
	- dnspython:         2.3.0
	- email-validator:   1.3.1
	- executing:         1.2.0
	- fastapi:           0.1.17
	- fastjsonschema:    2.16.3
	- filelock:          3.10.0
	- fonttools:         4.39.1
	- fqdn:              1.5.1
	- frozenlist:        1.3.3
	- fsspec:            2023.3.0
	- graphene:          3.2.2
	- graphql-core:      3.2.3
	- graphql-relay:     3.2.0
	- h11:               0.14.0
	- huggingface-hub:   0.13.2
	- idna:              3.4
	- importlib-metadata: 6.0.0
	- inquirer:          3.1.3
	- ipykernel:         6.21.3
	- ipython:           8.11.0
	- ipython-genutils:  0.2.0
	- isoduration:       20.11.0
	- itsdangerous:      2.1.2
	- jedi:              0.18.2
	- jinja2:            3.1.2
	- json5:             0.9.11
	- jsonpointer:       2.3
	- jsonschema:        4.17.3
	- jupyter-client:    8.0.3
	- jupyter-core:      5.2.0
	- jupyter-events:    0.6.3
	- jupyter-server:    2.4.0
	- jupyter-server-fileid: 0.8.0
	- jupyter-server-terminals: 0.4.4
	- jupyter-server-ydoc: 0.6.1
	- jupyter-ydoc:      0.2.3
	- jupyterlab:        3.6.1
	- jupyterlab-code-formatter: 1.5.3
	- jupyterlab-pygments: 0.2.2
	- jupyterlab-server: 2.20.0
	- kiwisolver:        1.4.4
	- lightning:         2.0.0
	- lightning-cloud:   0.5.31
	- lightning-utilities: 0.8.0
	- markdown-it-py:    2.2.0
	- markupsafe:        2.1.2
	- matplotlib:        3.7.1
	- matplotlib-inline: 0.1.6
	- mdurl:             0.1.2
	- mistune:           2.0.5
	- mpmath:            1.3.0
	- multidict:         6.0.4
	- mypy-extensions:   1.0.0
	- nbclassic:         0.5.3
	- nbclient:          0.7.2
	- nbconvert:         7.2.10
	- nbformat:          5.7.3
	- nest-asyncio:      1.5.6
	- networkx:          3.0
	- notebook:          6.5.3
	- notebook-shim:     0.2.2
	- numpy:             1.24.2
	- ordered-set:       4.1.0
	- orjson:            3.8.7
	- packaging:         23.0
	- pandocfilters:     1.5.0
	- parso:             0.8.3
	- pathspec:          0.11.1
	- pexpect:           4.8.0
	- pickleshare:       0.7.5
	- pillow:            9.4.0
	- pip:               23.0.1
	- platformdirs:      3.1.1
	- prometheus-client: 0.16.0
	- prompt-toolkit:    3.0.38
	- psutil:            5.9.4
	- ptyprocess:        0.7.0
	- pure-eval:         0.2.2
	- pycparser:         2.21
	- pydantic:          1.10.6
	- pygments:          2.14.0
	- pyjwt:             2.6.0
	- pyparsing:         3.0.9
	- pyrsistent:        0.19.3
	- python-dateutil:   2.8.2
	- python-editor:     1.0.4
	- python-json-logger: 2.0.7
	- python-multipart:  0.0.6
	- pytorch-lightning: 2.0.0
	- pytz:              2022.7.1
	- pyyaml:            6.0
	- pyzmq:             25.0.1
	- readchar:          4.0.4
	- regex:             2022.10.31
	- requests:          2.28.2
	- rfc3339-validator: 0.1.4
	- rfc3986-validator: 0.1.1
	- rich:              13.3.2
	- safetensors:       0.3.0
	- send2trash:        1.8.0
	- setuptools:        67.6.0
	- setuptools-scm:    7.1.0
	- six:               1.16.0
	- sniffio:           1.3.0
	- soupsieve:         2.4
	- stack-data:        0.6.2
	- starlette:         0.26.1
	- starsessions:      1.3.0
	- sympy:             1.11.1
	- terminado:         0.17.1
	- tinycss2:          1.2.1
	- tomli:             2.0.1
	- torch:             2.0.0
	- torchmetrics:      0.11.4
	- tornado:           6.2
	- tqdm:              4.65.0
	- traitlets:         5.9.0
	- typing-extensions: 4.5.0
	- ujson:             5.7.0
	- uri-template:      1.2.0
	- urllib3:           1.26.15
	- uvicorn:           0.21.1
	- wcwidth:           0.2.6
	- webcolors:         1.12
	- webencodings:      0.5.1
	- websocket-client:  1.5.1
	- websockets:        10.4
	- wheel:             0.37.1
	- y-py:              0.5.9
	- yarl:              1.8.2
	- ypy-websocket:     0.8.2
	- zipp:              3.15.0
* System:
	- OS:                Darwin
	- architecture:
		- 64bit
		- 
	- processor:         i386
	- python:            3.10.9
	- version:           Darwin Kernel Version 19.6.0: Tue Jun 21 21:18:39 PDT 2022; root:xnu-6153.141.66~1/RELEASE_X86_64

```

</details>**

### More info

Seems like I can't import lightning with the 2.0 release. Complains about not being able to import Schema from pydantic. Only other trace I could fine in the issues page here: https://github.com/Lightning-AI/lightning/pull/14333#issuecomment-1221558023

cc @tchaton

**Comment by shivammehta25** [comment]
This looks like a Pydantic issue, a temp fix will be to downgrade pydantic using `pip install 'pydantic<1.8.0'`.

**Comment by carmocca** [comment]
https://github.com/Lightning-AI/lightning/blob/e9937476a2c54f764e786a97f00f0f4baff74919/requirements/app/base.txt#L19 should probably be updated. Maybe it also requires the "strict" marker cc @Borda

**Comment by thesofakillers** [comment]
@shivammehta25 Unfortunately downgrading pydantic seems to produce a new error:

```
>>> import lightning
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/thesofakillers/miniconda3/envs/thesis/lib/python3.10/site-packages/lightning/__init__.py", line 18, in <module>
    from lightning.app import storage  # noqa: E402
  File "/Users/thesofakillers/miniconda3/envs/thesis/lib/python3.10/site-packages/lightning/app/__init__.py", line 24, in <module>
    from lightning.app import components  # noqa: E402, F401
  File "/Users/thesofakillers/miniconda3/envs/thesis/lib/python3.10/site-packages/lightning/app/components/__init__.py", line 1, in <module>
    from lightning.app.components.database.client import DatabaseClient
  File "/Users/thesofakillers/miniconda3/envs/thesis/lib/python3.10/site-packages/lightning/app/components/database/__init__.py", line 1, in <module>
    from lightning.app.components.database.client import DatabaseClient
  File "/Users/thesofakillers/miniconda3/envs/thesis/lib/python3.10/site-packages/lightning/app/components/database/client.py", line 22, in <module>
    from lightning.app.components.database.utilities import _GeneralModel
  File "/Users/thesofakillers/miniconda3/envs/thesis/lib/python3.10/site-packages/lightning/app/components/database/utilities.py", line 20, in <module>
    from fastapi import Response, status
  File "/Users/thesofakillers/miniconda3/envs/thesis/lib/python3.10/site-packages/fastapi/__init__.py", line 5, in <module>
    from .applications import FastAPI
  File "/Users/thesofakillers/miniconda3/envs/thesis/lib/python3.10/site-packages/fastapi/applications.py", line 3, in <module>
    from fastapi import routing
  File "/Users/thesofakillers/miniconda3/envs/thesis/lib/python3.10/site-packages/fastapi/routing.py", line 6, in <module>
    from fastapi import params
  File "/Users/thesofakillers/miniconda3/envs/thesis/lib/python3.10/site-packages/fastapi/params.py", line 14, in <module>
    class Param(Schema):
TypeError: function() argument 'code' must be code, not str
```

**Comment by Borda** [comment]
@thesofakillers could you share a full trace or more details about your env to reproduce?

**Comment by jhoffe** [comment]
I am not the one who created the issue, but I have the exact same issue, and my environment is the following:

<details><summary>Conda env export</summary>
<p>

```
# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
_libgcc_mutex=0.1=conda_forge
_openmp_mutex=4.5=2_kmp_llvm
aiofiles=23.1.0=pypi_0
aiohttp=3.7.4.post0=pypi_0
alabaster=0.7.13=pypi_0
aniso8601=9.0.1=pypi_0
antlr4-python3-runtime=4.9.3=pypi_0
anyio=3.6.2=pypi_0
appdirs=1.4.4=pypi_0
arrow=1.2.3=pypi_0
async-timeout=3.0.1=pypi_0
attrs=22.2.0=pyh71513ae_0
babel=2.11.0=pypi_0
bcrypt=4.0.1=pypi_0
beautifulsoup4=4.11.2=pypi_0
black=23.1.0=pypi_0
bleach=6.0.0=pypi_0
blessed=1.20.0=pypi_0
brotlipy=0.7.0=py311hd4cff14_1005
bsc-metadata-archeology=1.0.0=pypi_0
bzip2=1.0.8=h7b6447c_0
ca-certificates=2022.12.7=ha878542_0
cachecontrol=0.12.11=pyhd8ed1ab_1
certifi=2022.12.7=pyhd8ed1ab_0
cffi=1.15.1=py311h409f033_3
cfgv=3.3.1=pypi_0
chardet=4.0.0=pypi_0
charset-normalizer=3.0.1=pypi_0
cleo=2.0.1=pyhd8ed1ab_0
click=8.1.3=pypi_0
click-log=0.4.0=pypi_0
cmake=3.26.0=pypi_0
colorama=0.4.6=pyhd8ed1ab_0
contourpy=1.0.7=pypi_0
coverage=7.1.0=pypi_0
crashtest=0.4.1=pyhd8ed1ab_0
croniter=1.3.8=pypi_0
cryptography=39.0.1=pypi_0
cycler=0.11.0=pypi_0
dateutils=0.6.12=pypi_0
dbus=1.13.6=he372182_0
deepdiff=6.2.3=pypi_0
deprecated=1.2.13=pypi_0
distlib=0.3.6=pyhd8ed1ab_0
dnspython=2.3.0=pypi_0
docker-pycreds=0.4.0=pypi_0
docutils=0.19=pypi_0
dotty-dict=1.3.1=pypi_0
dtuhpc=2.1.1=pypi_0
dulwich=0.21.3=py311h2582759_0
email-validator=1.3.1=pypi_0
expat=2.5.0=h27087fc_0
fabric=2.7.1=pypi_0
fastapi=0.1.17=pypi_0
filelock=3.9.0=pypi_0
flake8=6.0.0=pypi_0
fonttools=4.38.0=pypi_0
fsspec=2023.1.0=pypi_0
gitdb=4.0.10=pypi_0
gitpython=3.1.30=pypi_0
glib=2.69.1=he621ea3_2
graphene=3.2.2=pypi_0
graphql-core=3.2.3=pypi_0
graphql-relay=3.2.0=pypi_0
h11=0.14.0=pypi_0
html5lib=1.1=pyh9f0ad1d_0
hydra-core=1.3.1=pypi_0
identify=2.5.18=pypi_0
idna=3.4=pyhd8ed1ab_0
imagesize=1.4.1=pypi_0
importlib-metadata=6.0.0=pyha770c72_0
importlib_metadata=6.0.0=hd8ed1ab_0
importlib_resources=5.12.0=pyhd8ed1ab_0
inquirer=3.1.3=pypi_0
invoke=1.7.3=pypi_0
isort=5.12.0=pypi_0
itsdangerous=2.1.2=pypi_0
jaraco.classes=3.2.3=pyhd8ed1ab_0
jeepney=0.8.0=pyhd8ed1ab_0
jinja2=3.1.2=pypi_0
joblib=1.2.0=pypi_0
jsonschema=4.17.3=pyhd8ed1ab_0
keyring=23.13.1=py311h38be061_0
kiwisolver=1.4.4=pypi_0
ld_impl_linux-64=2.38=h1181459_1
libblas=3.9.0=16_linux64_openblas
libcblas=3.9.0=16_linux64_openblas
libffi=3.4.2=h6a678d5_6
libgcc-ng=12.2.0=h65d4601_19
libgfortran-ng=12.2.0=h69a702a_19
libgfortran5=12.2.0=h337968e_19
liblapack=3.9.0=16_linux64_openblas
libopenblas=0.3.21=pthreads_h78a6416_3
libstdcxx-ng=12.2.0=h46fd767_19
libuuid=1.41.5=h5eee18b_0
lightning=2.0.0=pypi_0
lightning-cloud=0.5.31=pypi_0
lightning-utilities=0.8.0=pypi_0
lit=15.0.7=pypi_0
llvm-openmp=14.0.6=h9e868ea_0
lockfile=0.12.2=py_1
markdown-it-py=2.1.0=pypi_0
markupsafe=2.1.2=pypi_0
matplotlib=3.6.3=pypi_0
mccabe=0.7.0=pypi_0
mdurl=0.1.2=pypi_0
more-itertools=9.0.0=pypi_0
mpmath=1.3.0=pypi_0
msgpack-python=1.0.5=py311ha3edf6b_0
multidict=6.0.4=pypi_0
mypy-extensions=1.0.0=pypi_0
ncurses=6.4=h6a678d5_0
networkx=3.0=pypi_0
nodeenv=1.7.0=pypi_0
numpy=1.24.2=py311h8e6699e_0
nvidia-cublas-cu11=11.10.3.66=pypi_0
nvidia-cuda-cupti-cu11=11.7.101=pypi_0
nvidia-cuda-nvrtc-cu11=11.7.99=pypi_0
nvidia-cuda-runtime-cu11=11.7.99=pypi_0
nvidia-cudnn-cu11=8.5.0.96=pypi_0
nvidia-cufft-cu11=10.9.0.58=pypi_0
nvidia-curand-cu11=10.2.10.91=pypi_0
nvidia-cusolver-cu11=11.4.0.1=pypi_0
nvidia-cusparse-cu11=11.7.4.91=pypi_0
nvidia-nccl-cu11=2.14.3=pypi_0
nvidia-nvtx-cu11=11.7.91=pypi_0
omegaconf=2.3.0=pypi_0
openssl=1.1.1t=h0b41bf4_0
ordered-set=4.1.0=pypi_0
orjson=3.8.7=pypi_0
packaging=23.0=pyhd8ed1ab_0
pandas=1.5.3=pypi_0
paramiko=3.0.0=pypi_0
pathlib2=2.3.7.post1=pypi_0
pathspec=0.11.0=pypi_0
pathtools=0.1.2=pypi_0
pcre=8.45=h9c3ff4c_0
pexpect=4.8.0=pyh1a96a4e_2
pillow=9.4.0=pypi_0
pip=22.3.1=py311h06a4308_0
pkginfo=1.9.6=pyhd8ed1ab_0
pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
platformdirs=3.0.0=pypi_0
poetry=1.4.0=linux_pyhd8ed1ab_0
poetry-core=1.5.1=pyhd8ed1ab_0
poetry-plugin-export=1.3.0=pyhd8ed1ab_0
pre-commit=3.1.0=pypi_0
protobuf=4.21.12=pypi_0
psutil=5.9.4=pypi_0
ptyprocess=0.7.0=pyhd3deb0d_0
pyarrow=11.0.0=pypi_0
pycodestyle=2.10.0=pypi_0
pycparser=2.21=pyhd8ed1ab_0
pydantic=1.10.6=pypi_0
pyflakes=3.0.1=pypi_0
pygithub=1.57=pypi_0
pygments=2.14.0=pypi_0
pyjwt=2.6.0=pypi_0
pynacl=1.5.0=pypi_0
pyopenssl=23.0.0=pyhd8ed1ab_0
pyparsing=3.0.9=pypi_0
pyproject_hooks=1.0.0=pyhd8ed1ab_0
pyrsistent=0.19.3=py311h2582759_0
pysocks=1.7.1=pyha2e5f31_6
python=3.11.0=h7a1cb2a_3
python-build=0.10.0=pyhd8ed1ab_0
python-dateutil=2.8.2=pypi_0
python-dotenv=0.21.1=pypi_0
python-editor=1.0.4=pypi_0
python-gitlab=3.13.0=pypi_0
python-installer=0.6.0=pyhd8ed1ab_0
python-multipart=0.0.6=pypi_0
python-semantic-release=7.33.1=pypi_0
python_abi=3.11=2_cp311
pytorch-lightning=1.9.1=pypi_0
pytz=2022.7.1=pypi_0
pyyaml=6.0=pypi_0
rapidfuzz=2.13.7=py311hcafe171_0
readchar=4.0.4=pypi_0
readline=8.2=h5eee18b_0
readme-renderer=37.3=pypi_0
requests=2.28.2=pyhd8ed1ab_0
requests-toolbelt=0.10.1=pyhd8ed1ab_0
rfc3986=2.0.0=pypi_0
rich=13.3.1=pypi_0
scikit-learn=1.2.1=pypi_0
scipy=1.9.3=pypi_0
seaborn=0.12.2=pypi_0
secretstorage=3.3.3=py311h38be061_1
semver=2.13.0=pypi_0
sentry-sdk=1.15.0=pypi_0
setproctitle=1.3.2=pypi_0
setuptools=67.2.0=pypi_0
shellingham=1.5.1=pyhd8ed1ab_0
six=1.16.0=pyh6c4a22f_0
smmap=5.0.0=pypi_0
sniffio=1.3.0=pypi_0
snowballstemmer=2.2.0=pypi_0
soupsieve=2.4=pypi_0
sphinx=6.1.3=pypi_0
sphinxcontrib-applehelp=1.0.4=pypi_0
sphinxcontrib-devhelp=1.0.2=pypi_0
sphinxcontrib-htmlhelp=2.0.1=pypi_0
sphinxcontrib-jsmath=1.0.1=pypi_0
sphinxcontrib-qthelp=1.0.3=pypi_0
sphinxcontrib-serializinghtml=1.1.5=pypi_0
sqlite=3.41.1=h5eee18b_0
starlette=0.26.1=pypi_0
starsessions=1.3.0=pypi_0
sympy=1.11.1=pypi_0
threadpoolctl=3.1.0=pypi_0
tk=8.6.12=h1ccaba5_0
tomli=2.0.1=pyhd8ed1ab_0
tomlkit=0.11.6=pyha770c72_0
torch=2.0.0=pypi_0
torchmetrics=0.11.4=pypi_0
torchvision=0.15.1=pypi_0
tqdm=4.64.1=pypi_0
traitlets=5.9.0=pypi_0
triton=2.0.0=pypi_0
trove-classifiers=2023.3.9=pyhd8ed1ab_0
twine=3.8.0=pypi_0
typing=3.10.0.0=pyhd8ed1ab_0
typing-extensions=4.4.0=pypi_0
tzdata=2022g=h04d1e81_0
ujson=5.7.0=pypi_0
urllib3=1.26.14=pypi_0
uvicorn=0.21.1=pypi_0
virtualenv=20.19.0=pypi_0
wandb=0.13.10=pypi_0
wcwidth=0.2.6=pypi_0
webencodings=0.5.1=py_1
websocket-client=1.5.1=pypi_0
websockets=10.4=pypi_0
wheel=0.38.4=pypi_0
wrapt=1.14.1=pypi_0
xz=5.2.10=h5eee18b_1
yarl=1.8.2=pypi_0
zipp=3.13.0=pypi_0
zlib=1.2.13=h5eee18b_0
```

</p>
</details> 

<details><summary>Conda env info</summary>
<p>

```

     active environment : bsc3
    active env location : /home/xxx/miniconda3/envs/bsc3
            shell level : 4
       user config file : /home/xxx/.condarc
 populated config files : 
          conda version : 23.1.0
    conda-build version : not installed
         python version : 3.10.8.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=11.6=0
                          __glibc=2.35=0
                          __linux=6.0.12=0
                          __unix=0=0
       base environment : /home/xxx/miniconda3  (writable)
      conda av data dir : /home/xxx/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/xxx/miniconda3/pkgs
                          /home/xxx/.conda/pkgs
       envs directories : /home/xxx/miniconda3/envs
                          /home/xxx/.conda/envs
               platform : linux-64
             user-agent : conda/23.1.0 requests/2.28.1 CPython/3.10.8 Linux/6.0.12-76060006-generic pop/22.04 glibc/2.35
                UID:GID : 1000:1000
             netrc file : /home/xxx/.netrc
           offline mode : False
```

</p>
</details>

**Comment by thesofakillers** [comment]
@Borda thats the full trace after trying to run import lightning. My environment details are shared in my first comment at the beginning of this issue thread. Lmk if you’re missing anything.

**Comment by Borda** [comment]
> @Borda thats the full trace after trying to run import lightning. My environment details are shared in my first comment at the beginning of this issue thread. Lmk if you’re missing anything.

I see you are using Mac, is it M1?
also are you installed on pip or conda env?

**Comment by thesofakillers** [comment]
It is not an M1 Mac. I installed using pip in a conda environment.

**Comment by tautrimas** [comment]
I have solved an error by installing higher version of `fastapi` eg >=0.80. 

My `poetry` resolver decided to use an old version of fastapi, but adding a requirement to `pyproject.toml` helped.

**Comment by thesofakillers** [comment]
@tautrimas' solution also worked for me.

**Comment by Queuecumber** [comment]
I'm still getting this error after pinning `fastapi = "0.88"` in my pyproject.yaml, can someone post the exact version of fastapi that worked for them?

**Comment by thesofakillers** [comment]
fwiw i didn' manually pin it in pyproject.yaml. I did `poetry add fastapi=">=0.80". It installed version 0.88.0. Maybe you need to run `poetry install` and/or `poetry lock` still.

**Comment by Queuecumber** [comment]
yeah I did the same, let me take a closer look, I'm using this as part of a docker setup so theres a few more moving parts and one of them might not be playing nice. Thanks for letting me know that 0.88 is what is working for you though that helps rule out one part of it

**Comment by Borda** [comment]
> can someone post the exact version of fastapi that worked for them?

looking at CI and the last master commit passed with `fastapi==0.86`
https://github.com/Lightning-AI/lightning/actions/runs/4448838992/jobs/7812197055

**Comment by carmocca** [comment]
I just installed Lightning in a clean environment and got

```python
ImportError while loading conftest '/home/carlos/lightning/tests/tests_pytorch/conftest.py'.
../conftest.py:25: in <module>
    import lightning.fabric
../../../src/lightning/__init__.py:18: in <module>
    from lightning.app import storage  # noqa: E402
../../../src/lightning/app/__init__.py:24: in <module>
    from lightning.app import components  # noqa: E402, F401
../../../src/lightning/app/components/__init__.py:15: in <module>
    from lightning.app.components.serve.serve import ModelInferenceAPI
../../../src/lightning/app/components/serve/serve.py:35: in <module>
    fastapi_service = FastAPI()
../../../../venv/lib/python3.8/site-packages/fastapi/applications.py:146: in __init__
    self.middleware_stack: ASGIApp = self.build_middleware_stack()
../../../../venv/lib/python3.8/site-packages/fastapi/applications.py:152: in build_middleware_stack
    debug = self.debug
E   AttributeError: 'FastAPI' object has no attribute 'debug'
```

Pulling out Lightning

```bash
$ python -c "import fastapi; fastapi.FastAPI()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/carlos/venv/lib/python3.8/site-packages/fastapi/applications.py", line 146, in __init__
    self.middleware_stack: ASGIApp = self.build_middleware_stack()
  File "/home/carlos/venv/lib/python3.8/site-packages/fastapi/applications.py", line 152, in build_middleware_stack
    debug = self.debug
AttributeError: 'FastAPI' object has no attribute 'debug'
$ pip list | grep -E 'starlette|fastapi|pydantic'
fastapi                 0.88.0       
pydantic                1.10.7       
starlette               0.26.1      
```

Uninstalling these 3 and re-installing fixed it:

```bash
$ pip uninstall -y starlette fastapi pydantic
$ pip install starlette fastapi pydantic
Successfully installed fastapi-0.95.0 pydantic-1.10.7 starlette-0.26.1
```

But this points that our requirements specify an invalid combination of these 3 dependencies.

**Comment by svnv-svsv-jm** [comment]
Hello
I also had the same issue and @tautrimas' solution also worked for me: `poetry add fastapi=">=0.80"`.

In my `pyproject.toml`:

```toml
[tool.poetry.dependencies]
python = ">=3.10,<3.12"
kivy = "^2.1.0"
kivy-ios = "^2023.1.29"
kivymd = "^1.1.1"
buildozer = "^1.5.0"
transformers = {extras = ["torch"], version = "^4.25.1"}
lightning = "^2.0.1"
fastapi = ">=0.80"
loguru = "^0.6.0"
pyrootutils = "^1.0.4"
ipykernel = "^6.20.1"
pillow = "^9.4.0"
cython = "^0.29.34"
python-for-android = "^2023.2.10"
types-requests = "^2.28.11.17"
```

**Comment by carmocca** [comment]
https://github.com/Lightning-AI/lightning/issues/17106#issuecomment-1480344283 is not fied yet. Re-opening

**Comment by alexandervaneck-paige** [comment]
I believe this is still impacting for `lightning<2.0`.

```
$ pip freeze | grep -e lightning= -e fastapi= -e pydantic=
fastapi==0.1.17
lightning==1.9.5
pydantic==2.6.1
```

```
$ python -c "import lightning.pytorch"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/aicompute/env/lib/python3.10/site-packages/lightning/__init__.py", line 32, in <module>
    from lightning.app import storage  # noqa: E402
  File "/home/aicompute/env/lib/python3.10/site-packages/lightning/app/__init__.py", line 25, in <module>
    from lightning.app import components  # noqa: E402, F401
  File "/home/aicompute/env/lib/python3.10/site-packages/lightning/app/components/__init__.py", line 1, in <module>
    from lightning.app.components.database.client import DatabaseClient
  File "/home/aicompute/env/lib/python3.10/site-packages/lightning/app/components/database/__init__.py", line 1, in <module>
    from lightning.app.components.database.client import DatabaseClient
  File "/home/aicompute/env/lib/python3.10/site-packages/lightning/app/components/database/client.py", line 22, in <module>
    from lightning.app.components.database.utilities import _GeneralModel
  File "/home/aicompute/env/lib/python3.10/site-packages/lightning/app/components/database/utilities.py", line 20, in <module>
    from fastapi import Response, status
  File "/home/aicompute/env/lib/python3.10/site-packages/fastapi/__init__.py", line 5, in <module>
    from .applications import FastAPI
  File "/home/aicompute/env/lib/python3.10/site-packages/fastapi/applications.py", line 3, in <module>
    from fastapi import routing
  File "/home/aicompute/env/lib/python3.10/site-packages/fastapi/routing.py", line 6, in <module>
    from fastapi import params
  File "/home/aicompute/env/lib/python3.10/site-packages/fastapi/params.py", line 4, in <module>
    from pydantic import Schema
ImportError: cannot import name 'Schema' from 'pydantic' (/home/aicompute/env/lib/python3.10/site-packages/pydantic/__init__.py)
```

Thank you for fixing this with 2.0.x @Borda 🙇 

Is 1.x still supported and if so how should this be solved?

**Comment by Borda** [comment]
> Is 1.x still supported and if so how should this be solved?

we moved quite a lot and it was not easy to bring CI to live allowing us release, #18537

**Comment by alexandervaneck-paige** [comment]
That's a shame! Thank you for the quick reply 🙇 

I'll look into upgrading to lighting 2.0 then!
