### ISSUE TITLE
Error suggests setting `LightningCLI(save_config_overwrite=True)` however such a parameter does not exist

### ISSUE THREAD

**Issue by bwconrad** [Lightning-AI/lightning#17115]
### Bug description

When the `SaveConfigCallback` raises an error to avoid overwriting a previous config file, the following message is given:
```
RuntimeError: SaveConfigCallback expected output/config.yaml to NOT exist. Aborting to avoid overwriting results of a previous run. You can delete the previous config 
file, set `LightningCLI(save_config_callback=None)` to disable config saving, or set `LightningCLI(save_config_overwrite=True)` to overwrite the config file.
``` 

The message suggests setting `LightningCLI(save_config_overwrite=True)` however this parameter does not exist anymore and should instead suggest setting `LightningCLI(save_config_kwargs={"overwrite": True})`.

### How to reproduce the bug

```python
`main.py`


import torch
from pytorch_lightning import LightningDataModule, LightningModule
from pytorch_lightning.cli import LightningCLI
from torch.utils.data import DataLoader, Dataset


class RandomDataset(Dataset):
    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len


class MyDataModule(LightningDataModule):
    def train_dataloader(self) -> DataLoader:
        return DataLoader(RandomDataset(32, 64), batch_size=2)

    def val_dataloader(self) -> DataLoader:
        return DataLoader(RandomDataset(32, 64), batch_size=2)

    def test_dataloader(self) -> DataLoader:
        return DataLoader(RandomDataset(32, 64), batch_size=2)


class BoringModel(LightningModule):
    def __init__(self, dim: int = 32):
        super().__init__()
        self.layer = torch.nn.Linear(dim, 2)

    def forward(self, x):
        return self.layer(x)

    def training_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("train_loss", loss)
        return {"loss": loss}

    def configure_optimizers(self):
        return torch.optim.SGD(self.layer.parameters(), lr=0.1)

cli = LightningCLI(BoringModel, MyDataModule)


Run this twice to get the `RuntimeError`: `python main.py fit --trainer.max_steps 10 --trainer.logger CSVLogger --trainer.logger.init_args.save_dir output`

Changing the line to the suggested `cli = LightningCLI(BoringModel, MyDataModule, save_config_overwrite=True)` does not work since `save_config_overwrite` does not exist.
  
Changing the line to `cli = LightningCLI(BoringModel, MyDataModule, save_config_kwargs={"overwrite": True})` does correctly solve the error.
```

### Error messages and logs

```
Traceback (most recent call last):
  File "/home/lightning/code/main.py", line 48, in <module>
    cli = LightningCLI(BoringModel, MyDataModule)
  File "/home/lightning/lib/python3.10/site-packages/pytorch_lightning/cli.py", line 353, in __init__
    self._run_subcommand(self.subcommand)
  File "/home/lightning/lib/python3.10/site-packages/pytorch_lightning/cli.py", line 642, in _run_subcommand
    fn(**fn_kwargs)
  File "/home/lightning/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 520, in fit
    call._call_and_handle_interrupt(
  File "/home/lightning/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/lightning/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 559, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/lightning/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 896, in _run
    call._call_setup_hook(self)  # allow user to setup lightning_module in accelerator environment
  File "/home/lightning/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 82, in _call_setup_hook
    _call_callback_hooks(trainer, "setup", stage=fn)
  File "/home/lightning/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 190, in _call_callback_hooks
    fn(trainer, trainer.lightning_module, *args, **kwargs)
  File "/home/lightning/lib/python3.10/site-packages/pytorch_lightning/cli.py", line 242, in setup
    raise RuntimeError(
RuntimeError: SaveConfigCallback expected output/config.yaml to NOT exist. Aborting to avoid overwriting results of a previous run. You can delete the previous config 
file, set `LightningCLI(save_config_callback=None)` to disable config saving, or set `LightningCLI(save_config_overwrite=True)` to overwrite the config file.
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow): LightningCLI
#- PyTorch Lightning Version (e.g., 1.5.0): 2.0.0
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0): 2.0.0
#- Python version (e.g., 3.9): 3.10
#- OS (e.g., Linux): Linux
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source): pip
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

**Comment by MyGitHub-G** [comment]
Thanks for your work. i use your suggestion，but cant resolve the problem.
my LightningCLI:

LightningCLI(
        my_model_class,               
        my_datamodule_class,   
        save_config_kwargs={"overwrite": True},
    )

![image](https://github.com/user-attachments/assets/93f66619-5617-4494-be01-8b44d972ea7e)
