### ISSUE TITLE
2.0.0 cannot resume 1.9.3 checkpoint

### ISSUE THREAD

**Issue by thefiddler** [Lightning-AI/lightning#17120]
### Bug description

UPDATE: the issue appears to be happening when trying to load an eager weights file into a compiled model (`torch.compile`).

While it would be great if lightning supported that, that is not a lightning bug - I am going to close this.

----

I have been training a network using lightning 1.9.3. Upon upgrading to 2.0.0, the saved checkpoints fail to load with "missing key" and "unexpected key" errors. Based on the log, this affects every weight of the model - maybe an issue in the checkpoint upgrade procedure?
- missing key: `model._orig_mod.<name>.weight`
- unexpected key: `model.<name>.weight`

### How to reproduce the bug

Train 1 epoch with lightning 1.9.3 using checkpointing. Upgrade to 2.0.0 and attempt to resume that checkpoint.

### Error messages and logs

```
Restoring states from the checkpoint path at lightning_logs/version_39/checkpoints/epoch=16372-step=311087.ckpt
Lightning automatically upgraded your loaded checkpoint from v1.9.4 to v2.0.0. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file lightning_logs/version_39/checkpoints/epoch=16372-step=311087.ckpt`
Traceback (most recent call last):
  File "irun.py", line 215, in <module>
    main()
  File "irun.py", line 200, in main
    IRun(args)
  File "irun.py", line 188, in __init__
    super().__init__(self.model, self.data, trainer_class=DefaultTrainer)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/cli.py", line 353, in __init__
    self._run_subcommand(self.subcommand)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/cli.py", line 642, in _run_subcommand
    fn(**fn_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 520, in fit
    call._call_and_handle_interrupt(
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 559, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 901, in _run
    self._checkpoint_connector._restore_modules_and_callbacks(ckpt_path)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 396, in _restore_modules_and_callbacks
    self.restore_model()
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 278, in restore_model
    trainer.strategy.load_model_state_dict(self._loaded_checkpoint)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/strategies/strategy.py", line 351, in load_model_state_dict
    self.lightning_module.load_state_dict(checkpoint["state_dict"])
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Model:
        Missing key(s) in state_dict: "model._orig_mod.input_conv.weight", ...
        Unexpected key(s) in state_dict: "model.input_conv.weight", ...
```

### Environment

<details>
  <summary>Current environment</summary>

```
- Lightning Component: Trainer, LightningModule, LightningCLI
- PyTorch Lightning Version: 2.0.0
- PyTorch Version (e.g., 2.0): 2.1.0.dev20230316+cu118
- Python version (e.g., 3.9): 3.8.10
- OS (e.g., Linux): Nvidia PyTorch docker image 23.02
- CUDA/cuDNN version: 11.8
- GPU models and configuration: unet-style
- How you installed Lightning(`conda`, `pip`, source): pip
```

</details>

### More info

Restoring in lightning 1.9.3 with pytorch 2.1.0-pre works fine. Upgrading to lightning 2.0.0 makes loading fail.

Training loop is using bf16. Setting bf16 or bf16-mixed makes no difference.

I need to use pytorch nightly because of a bugfix for bf16 interpolation.

**Comment by jeremyadamsfisher** [comment]
For future devs: I ran into this issue because I was trying to restore a model that had been compiled (with the `torch.compile` api) with weights from a run where the model was NOT compiled.

The OP might have had this issue because the training script running checked whether the `.compile()` api was available and automatically done so.

For me, I fixed this by moving the compilation step after resuming from the checkpoint.
