### ISSUE TITLE
`LightningModule.log` failed to reach fixed point while using `torch.compile`

### ISSUE THREAD

**Issue by fmocking** [Lightning-AI/lightning#17140]
### Bug description

Hello,

I'm having issues when I'm trying to log anything from Lightning module. I'm using DDP, tried with single GPU problem still persists. I've tried to set logger to `None` to make sure its not caused by specific logger. 

I'm surprised that this is not a common issue. I'm getting this error with very basic setup. 

### How to reproduce the bug

```python
def __step(self, input_data, split='train', dataloader_idx=0):  
    out = self(input_data)  
  
    self.log(f"loss/{split}", out["loss"], on_step=True, on_epoch=True)  
    return {  
        "loss": out["loss"]  
    }  
  
def training_step(self, batch, batch_idx, dataloader_idx=0):  
    return self.__step(batch, 'train', dataloader_idx=dataloader_idx)  
  
def validation_step(self, batch, batch_idx, dataloader_idx=0):  
    return self.__step(batch, 'val', dataloader_idx=dataloader_idx)  
  
def test_step(self, batch, batch_idx, dataloader_idx=0):  
    return self.__step(batch, 'test', dataloader_idx=dataloader_idx)  
```

### Error messages and logs

```
 [2023-03-19 07:13:17,833] torch._dynamo.symbolic_convert: [INFO] Step 1: torchdynamo start tracing apply_to_collection
Traceback (most recent call last):
  File "/model.py.py", line 352, in <module>
    main()
  File "/model.py.py", line 313, in main
    trainer.fit(model, dm, ckpt_path=args.ds_checkpoint_path)
  File "python/site-packages/pytorch_lightning/trainer/trainer.py", line 520, in fit
    call._call_and_handle_interrupt(
  File "python/site-packages/pytorch_lightning/trainer/call.py", line 42, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "python/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 92, in launch
    return function(*args, **kwargs)
  File "python/site-packages/pytorch_lightning/trainer/trainer.py", line 559, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "python/site-packages/pytorch_lightning/trainer/trainer.py", line 935, in _run
    results = self._run_stage()
  File "python/site-packages/pytorch_lightning/trainer/trainer.py", line 976, in _run_stage
    self._run_sanity_check()
  File "python/site-packages/pytorch_lightning/trainer/trainer.py", line 1005, in _run_sanity_check
    val_loop.run()
  File "python/site-packages/pytorch_lightning/loops/utilities.py", line 174, in _decorator
    return loop_run(self, *args, **kwargs)
  File "python/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 115, in run
    self._evaluation_step(batch, batch_idx, dataloader_idx)
  File "python/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 375, in _evaluation_step
    output = call._call_strategy_hook(trainer, hook_name, *step_kwargs.values())
  File "python/site-packages/pytorch_lightning/trainer/call.py", line 288, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "python/site-packages/pytorch_lightning/strategies/ddp.py", line 337, in validation_step
    return self.model(*args, **kwargs)
  File "python/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "python/site-packages/torch/nn/parallel/distributed.py", line 1156, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "python/site-packages/torch/nn/parallel/distributed.py", line 1110, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])  # type: ignore[index]
  File "python/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "python/site-packages/pytorch_lightning/overrides/base.py", line 102, in forward
    return self._forward_module.validation_step(*inputs, **kwargs)
  File "python/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
 File "model.py", line 259, in <graph break in validation_step>
    self.log(f"loss/val", out["loss"], on_step=True, on_epoch=True)
  File "python/site-packages/pytorch_lightning/core/module.py", line 403, in log
    apply_to_collection(value, dict, self.__check_not_nested, name)
  File "python/site-packages/torch/_dynamo/eval_frame.py", line 334, in catch_errors
    return hijacked_callback(frame, cache_size, hooks)
  File "python/site-packages/torch/_dynamo/convert_frame.py", line 404, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "python/site-packages/torch/_dynamo/convert_frame.py", line 104, in _fn
    return fn(*args, **kwargs)
  File "python/site-packages/torch/_dynamo/convert_frame.py", line 262, in _convert_frame_assert
    return _compile(
  File "python/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "python/site-packages/torch/_dynamo/convert_frame.py", line 324, in _compile
    out_code = transform_code_object(code, transform)
  File "python/site-packages/torch/_dynamo/bytecode_transformation.py", line 445, in transform_code_object
    transformations(instructions, code_options)
  File "python/site-packages/torch/_dynamo/convert_frame.py", line 311, in transform
    tracer.run()
  File "python/site-packages/torch/_dynamo/symbolic_convert.py", line 1726, in run
    super().run()
  File "python/site-packages/torch/_dynamo/symbolic_convert.py", line 576, in run
    and self.step()
  File "python/site-packages/torch/_dynamo/symbolic_convert.py", line 540, in step
    getattr(self, inst.opname)(inst)
  File "python/site-packages/torch/_dynamo/symbolic_convert.py", line 378, in wrapper
    resume_call_insts = self.create_call_resume_at(self.next_instruction)
  File "python/site-packages/torch/_dynamo/symbolic_convert.py", line 1755, in create_call_resume_at
    new_code: types.CodeType = ContinueExecutionCache.lookup(
  File "python/site-packages/torch/_dynamo/resume_execution.py", line 154, in lookup
    cls.cache[code][key] = cls.generate(code, lineno, *key)
  File "python/site-packages/torch/_dynamo/resume_execution.py", line 233, in generate
    new_code = transform_code_object(code, update)
  File "python/site-packages/torch/_dynamo/bytecode_transformation.py", line 446, in transform_code_object
    return clean_and_assemble_instructions(instructions, keys, code_options)[1]
  File "python/site-packages/torch/_dynamo/bytecode_transformation.py", line 470, in clean_and_assemble_instructions
    code_options["co_stacksize"] = stacksize_analysis(instructions)
  File "python/site-packages/torch/_dynamo/bytecode_analysis.py", line 184, in stacksize_analysis
    assert fixed_point.value, "failed to reach fixed point"
AssertionError: failed to reach fixed point

from user code:
   File "python/site-packages/lightning_utilities/core/apply_func.py", line 94, in apply_to_collection
    if is_dataclass_instance(data):

Set torch._dynamo.config.verbose=True for more information
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow): LightningModule
#- PyTorch Lightning Version (e.g., 1.5.0): 2.0.0
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0): 2.0
#- Python version (e.g., 3.9): 3.8
#- OS (e.g., Linux): Linux
#- CUDA/cuDNN version: 11.7
#- GPU models and configuration: V100 16GB
#- How you installed Lightning(`conda`, `pip`, source): Conda (Also tested with pip)
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

**Comment by weicao1990** [comment]
same issue

**Comment by kayvane1** [comment]
Same issue, HuggingFace model compiles with torch.compile() but the model in my `pl.LightningModule` gives me the same error as above.

**Comment by mayeroa** [comment]
Same issue as #17177 .

**Comment by fmocking** [comment]
@Borda @mayeroa I'm not sure why this issue is closed, and tagged as duplicate. The referenced issue #17177  is created after this one (4 days later).

**Comment by Borda** [comment]
> @Borda @mayeroa I'm not sure why this issue is closed, and tagged as duplicate. The referenced issue #17177 is the duplicate since created after this one (4 days later).

As the other one includes much more conversion, it is better to preserve it (apology for missing this explanation earlier)
