### ISSUE TITLE
pytorch 2.0 Torch Compiled model error at test_step

### ISSUE THREAD

**Issue by AryoBithealth** [Lightning-AI/lightning#17175]
### Bug description

Error torch._dynamo.exc.BackendCompilerFailed: debug_wrapper raised RuntimeError: Inference tensors do not track version counter.

Error only happened during test step

version
```
lightning==2.0.0
torch==2.0.0+cu117
```
the code is inspired by post from: [https://lightning.ai/pages/blog/training-compiled-pytorch-2.0-with-pytorch-lightning/](https://lightning.ai/pages/blog/training-compiled-pytorch-2.0-with-pytorch-lightning/)
but changing the structure into datamodule and adding test in the trainer

in code below, if
```python
self.model = torch.compile(
            create_model("resnet18", num_classes=10)
        )
```
is using non compiled model
```python
self.model =  create_model("resnet18", num_classes=10)
```
will not having this error

### How to reproduce the bug

```python
# Full Code:
import torch
import lightning as L
import torchmetrics
import torch.nn as nn
import torchvision
import torchvision.transforms as transforms
from timm import create_model


class CIFAR10DataModule(L.LightningDataModule):
    
    def __init__(self, batch_size = 32) -> None:
        super().__init__()
        self.transform = transforms.Compose(
            [transforms.ToTensor(), transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))]
        )

        self.batch_size = batch_size

        self.train_set = torchvision.datasets.CIFAR10(
            root="~/data", train=True, download=True, transform=self.transform
        )
        self.test_set = torchvision.datasets.CIFAR10(
            root="~/data", train=False, download=True, transform=self.transform
        )
        
    def train_dataloader(self):
        return torch.utils.data.DataLoader(
            self.train_set, batch_size=self.batch_size, shuffle=True, num_workers=4
        )
        
    def test_dataloader(self):
        return torch.utils.data.DataLoader(
            self.test_set, batch_size=self.batch_size, shuffle=False, num_workers=4
        )



class LitModel(L.LightningModule):
    def __init__(self):
        super().__init__()
        self.model = torch.compile(
            create_model("resnet18", num_classes=10)
        )
        self.criterion = nn.CrossEntropyLoss()
        self.accuracy_score = torchmetrics.Accuracy(
            task="multiclass", num_classes=10
        )

    def forward(self, x):
        return self.model(x)

    def common_step(self, x, y, stage):
        logits = self.model(x)
        loss = self.criterion(logits, y)
        acc = self.accuracy_score(logits, y)
        self.log(
            f"{stage}_loss", loss, on_epoch=True, prog_bar=True, logger=True
        )
        self.log(
            f"{stage}_acc", acc, on_epoch=True, prog_bar=True, logger=True
        )
        return loss, acc

    def training_step(self, batch, batch_idx):
        x, y = batch
        loss, acc = self.common_step(x, y, "train")
        return loss

    def test_step(self, batch, batch_idx):
        x, y = batch
        loss, acc = self.common_step(x, y, "test")
        return {"test_loss": loss, "test_acc": acc}

    def configure_optimizers(self):
        return torch.optim.Adam(self.model.parameters(), lr=0.001)


def main():
    datamodule = CIFAR10DataModule()
    model = LitModel()
    trainer = L.Trainer(
        max_epochs=3,
        devices="auto",
    )
    trainer.fit(model, datamodule=datamodule)
    test_result = trainer.test(ckpt_path="best", datamodule=datamodule)
    print(test_result)

if __name__ == "__main__":
    main()
```

### Error messages and logs

```
# Error messages and logs here please

(venv) (base) ?  appadmin@gcp-rpamr-01  ~/development-model-retrain git:(update-torch) ? python test_torch20.py 
Files already downloaded and verified
Files already downloaded and verified
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name           | Type               | Params
------------------------------------------------------
0 | model          | OptimizedModule    | 11.2 M
1 | criterion      | CrossEntropyLoss   | 0     
2 | accuracy_score | MulticlassAccuracy | 0     
------------------------------------------------------
11.2 M    Trainable params
0         Non-trainable params
11.2 M    Total params
44.727    Total estimated model params size (MB)
Epoch 2: 100%|█| 1563/1563 [00:31<00:00, 49.39it/s, v_num=1, train_loss_step=0.539, train_acc_step=0.812, train_loss_epo`Trainer.fit` stopped: `max_epochs=3` reached.
Epoch 2: 100%|█| 1563/1563 [00:32<00:00, 48.78it/s, v_num=1, train_loss_step=0.539, train_acc_step=0.812, train_loss_epo
Restoring states from the checkpoint path at /home/appadmin/development-model-retrain/lightning_logs/version_1/checkpoints/epoch=2-step=4689.ckpt
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
Loaded model weights from the checkpoint at /home/appadmin/development-model-retrain/lightning_logs/version_1/checkpoints/epoch=2-step=4689.ckpt
Testing DataLoader 0:   0%|                                                                     | 0/313 [00:00<?, ?it/s]Failed to collect metadata on function, produced code may be suboptimal.  Known situations this can occur are inference mode only compilation involving resize_ or prims (!schema.hasAnyAliasInfo() INTERNAL ASSERT FAILED); if your situation looks different please file a bug to PyTorch.
Traceback (most recent call last):
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 1674, in aot_wrapper_dedupe
    fw_metadata, _out = run_functionalized_fw_and_collect_metadata(
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 606, in inner
    flat_f_outs = f(*flat_f_args)
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 2776, in functional_call
    out = Interpreter(mod).run(*args[params_len:], **kwargs)
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/torch/fx/interpreter.py", line 136, in run
    self.env[node] = self.run_node(node)
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/torch/fx/interpreter.py", line 177, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/torch/fx/interpreter.py", line 294, in call_module
    return submod(*args, **kwargs)
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/torch/_inductor/overrides.py", line 38, in __torch_function__
    return func(*args, **kwargs)
RuntimeError: Inference tensors do not track version counter.

While executing %self_fc : [#users=1] = call_module[target=self_fc](args = (%self_global_pool_flatten,), kwargs = {})
Original traceback:
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/timm/models/resnet.py", line 727, in forward_head
    return x if pre_logits else self.fc(x)
 |   File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/timm/models/resnet.py", line 731, in forward
    x = self.forward_head(x)

Traceback (most recent call last):
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/torch/_dynamo/output_graph.py", line 670, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.fake_example_inputs())
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/torch/_dynamo/debug_utils.py", line 1055, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/torch/__init__.py", line 1390, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/torch/_inductor/compile_fx.py", line 455, in compile_fx
    return aot_autograd(
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/torch/_dynamo/backends/common.py", line 48, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 2805, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 2498, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config)
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 1802, in aot_wrapper_dedupe
    compiled_fn = compiler_fn(wrapped_flat_fn, deduped_flat_args, aot_config)
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 1278, in aot_dispatch_base
    _fw_metadata, _out = run_functionalized_fw_and_collect_metadata(
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 606, in inner
    flat_f_outs = f(*flat_f_args)
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 1800, in wrapped_flat_fn
    return flat_fn(*add_dupe_args(args))
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 2776, in functional_call
    out = Interpreter(mod).run(*args[params_len:], **kwargs)
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/torch/fx/interpreter.py", line 136, in run
    self.env[node] = self.run_node(node)
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/torch/fx/interpreter.py", line 177, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/torch/fx/interpreter.py", line 294, in call_module
    return submod(*args, **kwargs)
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/torch/_inductor/overrides.py", line 38, in __torch_function__
    return func(*args, **kwargs)
RuntimeError: Inference tensors do not track version counter.

While executing %self_fc : [#users=1] = call_module[target=self_fc](args = (%self_global_pool_flatten,), kwargs = {})
Original traceback:
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/timm/models/resnet.py", line 727, in forward_head
    return x if pre_logits else self.fc(x)
 |   File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/timm/models/resnet.py", line 731, in forward
    x = self.forward_head(x)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/appadmin/development-model-retrain/test_torch20.py", line 94, in <module>
    main()
  File "/home/appadmin/development-model-retrain/test_torch20.py", line 90, in main
    test_result = trainer.test(ckpt_path="best", datamodule=datamodule)
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 706, in test
    return call._call_and_handle_interrupt(
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/lightning/pytorch/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 749, in _test_impl
    results = self._run(model, ckpt_path=ckpt_path)
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 935, in _run
    results = self._run_stage()
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 971, in _run_stage
    return self._evaluation_loop.run()
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/lightning/pytorch/loops/utilities.py", line 174, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 115, in run
    self._evaluation_step(batch, batch_idx, dataloader_idx)
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 375, in _evaluation_step
    output = call._call_strategy_hook(trainer, hook_name, *step_kwargs.values())
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/lightning/pytorch/trainer/call.py", line 288, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/lightning/pytorch/strategies/strategy.py", line 387, in test_step
    return self.model.test_step(*args, **kwargs)
  File "/home/appadmin/development-model-retrain/test_torch20.py", line 75, in test_step
    loss, acc = self.common_step(x, y, "test")
  File "/home/appadmin/development-model-retrain/test_torch20.py", line 57, in common_step
    logits = self.model(x)
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 82, in forward
    return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 337, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 404, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 104, in _fn
    return fn(*args, **kwargs)
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 262, in _convert_frame_assert
    return _compile(
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 324, in _compile
    out_code = transform_code_object(code, transform)
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/torch/_dynamo/bytecode_transformation.py", line 445, in transform_code_object
    transformations(instructions, code_options)
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 311, in transform
    tracer.run()
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 1726, in run
    super().run()
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 576, in run
    and self.step()
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 540, in step
    getattr(self, inst.opname)(inst)
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 1792, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/torch/_dynamo/output_graph.py", line 517, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/torch/_dynamo/output_graph.py", line 588, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/torch/_dynamo/output_graph.py", line 675, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e) from e
torch._dynamo.exc.BackendCompilerFailed: debug_wrapper raised RuntimeError: Inference tensors do not track version counter.

While executing %self_fc : [#users=1] = call_module[target=self_fc](args = (%self_global_pool_flatten,), kwargs = {})
Original traceback:
  File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/timm/models/resnet.py", line 727, in forward_head
    return x if pre_logits else self.fc(x)
 |   File "/home/appadmin/development-model-retrain/venv/lib/python3.9/site-packages/timm/models/resnet.py", line 731, in forward
    x = self.forward_head(x)



You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True

Testing DataLoader 0:   0%|          | 0/313 [00:01<?, ?it/s]                                                           
(venv) (base) ?  appadmin@gcp-rpamr-01  ~/development-model-retrain git:(update-torch) ? 

```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow): LightningModule, LightningDataModule
#- PyTorch Lightning Version (e.g., 1.5.0): 2.0.0
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0): 2.0.0+cu117
#- Python version (e.g., 3.9): 3.9
#- OS (e.g., Linux): Ubuntu 22.04.2 LTS x86_64
#- CUDA/cuDNN version: 11.7
#- GPU models and configuration: NVIDIA Tesla T4
#- How you installed Lightning(`conda`, `pip`, source): pip
#- Running environment of LightningApp (e.g. local, cloud): Google Compute Engine
```

</details>

**Comment by hynky1999** [comment]
This seems to be problem on pytorch side https://github.com/pytorch/pytorch/issues/93042#issuecomment-1410954858
One way to temporary fix it would be to change

```_no_grad_context(loop_run: Callable) -> Callable:``` in lightning.pytorch.loops.utlities

to

```
def _no_grad_context(loop_run: Callable) -> Callable:
    def _decorator(self: _Loop, *args: Any, **kwargs: Any) -> Any:
        if not isinstance(self, _Loop):
            raise TypeError(f"`{type(self).__name__}` needs to be a Loop.")
        if not hasattr(self, "inference_mode"):
            raise TypeError(f"`{type(self).__name__}.inference_mode` needs to be defined")
        context_manager: Type[ContextManager]
        if dist.is_available() and dist.is_initialized() and dist.get_backend() == "gloo":
            # gloo backend does not work properly.
            # https://github.com/Lightning-AI/lightning/pull/12715/files#r854569110
            # TODO: explore why and possibly open an issue in PyTorch repository
            context_manager = torch.no_grad
        elif isinstance(self.trainer.accelerator, TPUAccelerator):
            context_manager = torch.no_grad
        elif _TORCH_GREATER_EQUAL_1_13 and isinstance(self.trainer.strategy, FSDPStrategy):
            # https://github.com/pytorch/pytorch/issues/95957
            context_manager = torch.no_grad
        elif self.inference_mode:
            #CHANGE HERE inference mode to no_grad, which creates version counters
             context_manager = torch.no_grad
        else:
            context_manager = torch.no_grad
        with context_manager():
            return loop_run(self, *args, **kwargs)

    return _decorator
 ```

**Comment by carmocca** [comment]
Opened #17215 to fix this issue. As a workaround, you can do `Trainer(inference_mode=False)`
