### ISSUE TITLE
pytorch 2.0 compile forward with `torch.no_grad()` make `error: file too short`

### ISSUE THREAD

**Issue by DogeWatch** [Lightning-AI/lightning#17196]
### Bug description

```python
model = torch.compile(model)
for data in datas:
    with torch.no_grad():
        result = model(data)
```
with the iteration of datas, the log of torch._inductor.compile_fx: torchinductor compiling FORWARDS graph xxx, xxx number continuous increase and do not stop. finally got an error `torch._dynamo.exc.BackendCompilerFailed: debug_wrapper raised OSError: /tmp/torchinductor_root/vo/cvooqhqmrnrzwasedi5rgeoxxzyph7alhza2qpb3zz3g3hxdbpzb.so: file too short`

### Error messages and logs

```
Traceback (most recent call last):
  File "forward.py", line 143, in <module>
    main(args.model_path, args.local_rank, args.hdfs_path, args.use_venus, args.output_path, args.batch_size, args.rank, args.world_size, args.mode)
  File "forward.py", line 108, in main
    embeddings = server.forward(token)
  File "/cfs/share/common/torch_2.0_test/bai/server.py", line 139, in forward
    embeddings = self.model(x={'input_ids': inp, 'attention_mask': attention_mask}).x_embed
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 82, in forward
    return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "/cfs/share/common/torch_2.0_test/bai/bai.py", line 72, in forward
    x_embed, y_embed = self.embed(x, padding), self.embed(y, padding) if y is not None else None
  File "/cfs/share/common/torch_2.0_test/bai/bai.py", line 64, in embed
    hidden_states = self.inner_model(**input, return_dict=True).last_hidden_state
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/transformers/models/opt/modeling_opt.py", line 786, in forward
    decoder_outputs = self.decoder(
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/transformers/models/opt/modeling_opt.py", line 641, in forward
    attention_mask = self._prepare_decoder_attention_mask(
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/transformers/models/opt/modeling_opt.py", line 538, in _prepare_decoder_attention_mask
    combined_attention_mask = _make_causal_mask(
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 337, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 404, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 104, in _fn
    return fn(*args, **kwargs)
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 262, in _convert_frame_assert
    return _compile(
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 324, in _compile
    out_code = transform_code_object(code, transform)
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/torch/_dynamo/bytecode_transformation.py", line 445, in transform_code_object
    transformations(instructions, code_options)
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 311, in transform
    tracer.run()
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1726, in run
    super().run()
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 576, in run
    and self.step()
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 540, in step
    getattr(self, inst.opname)(inst)
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1792, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/torch/_dynamo/output_graph.py", line 517, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/torch/_dynamo/output_graph.py", line 588, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/data/miniconda3/envs/env-3.8.8/lib/python3.8/site-packages/torch/_dynamo/output_graph.py", line 675, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e) from e
torch._dynamo.exc.BackendCompilerFailed: debug_wrapper raised OSError: /tmp/torchinductor_root/vo/cvooqhqmrnrzwasedi5rgeoxxzyph7alhza2qpb3zz3g3hxdbpzb.so: file too short
```

### Environment

* CUDA:
        - GPU:
                - Tesla V100-SXM2-32GB
        - available:         True
        - version:           11.7
* Lightning:
        - torch:             2.0.0+cu117
        - torchdata:         0.6.0
        - torchstat:         0.0.7
        - torchsummary:      1.5.1
        - torchtext:         0.15.1+cpu
        - torchvision:       0.15.1+rocm5.4.2
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.8.8

cc @carmocca

**Comment by Borda** [comment]
This seems rather like some Torch issue. Are you using proper packages, can you check with our sample model?

**Comment by Borda** [comment]
This seems rather like some Torch issue. Are you using proper packages, can you check with our sample model?

**Comment by carmocca** [comment]
Hi @DogeWatch. As the comment above says, this doesn't look like a PyTorch Lightning issue specifically.

Could you provide a fully-contained reproducible snippet? That would be helpful in finding what the issue is

**Comment by awaelchli** [comment]
It is unrelated to Lightning. Here is the issue on the PyTorch GitHub: https://github.com/pytorch/pytorch/issues/102539
Seems to be a race condition leading to a corrupted file. Workaround is to manually delete the file mentioned in the error message.
