### ISSUE TITLE
AttributeError: module '`pytorch_lightning.utilities.enums`' has no attribute '`_FaultTolerantMode`'

### ISSUE THREAD

**Issue by lingyun-hifibio** [Lightning-AI/lightning#17260]
### Bug description

The issue occurred when loading the previous checkpoint with `ckpt_path` (`trainer.fit(model, train_dataloaders=data_module.train_dataloader(), val_dataloaders=data_module.val_dataloader(),  ckpt_path=load_path)`) to training a model.     
pytorch==2.0.0   
lightning=2.0.0

### How to reproduce the bug

```python
data_module = DataInterface(args)
model = ModelInterface(args)
trainer = L.Trainer()
trainer.fit(model, train_dataloaders=data_module.train_dataloader(), val_dataloaders=data_module.val_dataloader(), ckpt_path=load_path)
```

### Error messages and logs

```
Traceback (most recent call last):
  File "/home/lchen/workspace/AbPrecision/src/main.py", line 349, in <module>
    main(args)
  File "/home/lchen/workspace/AbPrecision/src/main.py", line 281, in main
    trainer.fit(model, train_dataloaders=data_module.train_dataloader(), val_dataloaders=data_module.val_dataloader(),
  File "/home/lchen/miniconda3/envs/py3.10-torch2.0/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 520, in fit
    call._call_and_handle_interrupt(
  File "/home/lchen/miniconda3/envs/py3.10-torch2.0/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/lchen/miniconda3/envs/py3.10-torch2.0/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 559, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/lchen/miniconda3/envs/py3.10-torch2.0/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 901, in _run
    self._checkpoint_connector._restore_modules_and_callbacks(ckpt_path)
  File "/home/lchen/miniconda3/envs/py3.10-torch2.0/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/checkpoint_connector.py", line 395, in _restore_modules_and_callbacks
    self.resume_start(checkpoint_path)
  File "/home/lchen/miniconda3/envs/py3.10-torch2.0/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/checkpoint_connector.py", line 82, in resume_start
    loaded_checkpoint = self.trainer.strategy.load_checkpoint(checkpoint_path)
  File "/home/lchen/miniconda3/envs/py3.10-torch2.0/lib/python3.10/site-packages/lightning/pytorch/strategies/strategy.py", line 347, in load_checkpoint
    return self.checkpoint_io.load_checkpoint(checkpoint_path)
  File "/home/lchen/miniconda3/envs/py3.10-torch2.0/lib/python3.10/site-packages/lightning/fabric/plugins/io/torch_io.py", line 89, in load_checkpoint
    return pl_load(path, map_location=map_location)
  File "/home/lchen/miniconda3/envs/py3.10-torch2.0/lib/python3.10/site-packages/lightning/fabric/utilities/cloud_io.py", line 51, in _load
    return torch.load(f, map_location=map_location)  # type: ignore[arg-type]
  File "/home/lchen/miniconda3/envs/py3.10-torch2.0/lib/python3.10/site-packages/torch/serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/lchen/miniconda3/envs/py3.10-torch2.0/lib/python3.10/site-packages/torch/serialization.py", line 1172, in _load
    result = unpickler.load()
  File "/home/lchen/miniconda3/envs/py3.10-torch2.0/lib/python3.10/pickle.py", line 1213, in load
    dispatch[key[0]](self)
  File "/home/lchen/miniconda3/envs/py3.10-torch2.0/lib/python3.10/pickle.py", line 1529, in load_global
    klass = self.find_class(module, name)
  File "/home/lchen/miniconda3/envs/py3.10-torch2.0/lib/python3.10/site-packages/torch/serialization.py", line 1165, in find_class
    return super().find_class(mod_name, name)
  File "/home/lchen/miniconda3/envs/py3.10-torch2.0/lib/python3.10/site-packages/pytorch_lightning/_graveyard/legacy_import_unpickler.py", line 24, in find_class
    return super().find_class(new_module, name)
  File "/home/lchen/miniconda3/envs/py3.10-torch2.0/lib/python3.10/pickle.py", line 1584, in find_class
    return getattr(sys.modules[module], name)
AttributeError: module 'pytorch_lightning.utilities.enums' has no attribute '_FaultTolerantMode'
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
- PyTorch Lightning Version (2.0.0):
- PyTorch Version (2.0.0):
- Python version (3.10):
- OS (Ubuntu22.04):
- CUDA/cuDNN version: cuda11.7
- GPU: RTX4090
- How you installed Lightning(``pip`)
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

**Comment by Borda** [comment]
Correct, this private/protected attribute was removed in 2.0.0

**Comment by philippjh** [comment]
For me, this error occured during loading an older model, which has been trained with earlier version of both `torch` and `pytorch-lightning` (pre 2.0 releases).

**Comment by YaduKini** [comment]
I have the same issue. has anyone found a fix for this?. Any help would be greatly appreciated. Thanks.

**Comment by awaelchli** [comment]
@philippjh or @YaduKini Would you be so kind to send me the checkpoint file that you're trying to load, so I can inspect it and validate a fix? Thanks
