### ISSUE TITLE
Cannot configure a forced custom callback with no arguments in Lightning CLI

### ISSUE THREAD

**Issue by martinwhl** [Lightning-AI/lightning#17263]
### Bug description

I created a custom callback with no argument in its `__init__()` function, and tried to configure it as a forced callback in Lightning CLI. However, I found that the argument namespace cannot be successfully created when there is no argument in the custom callback and the program throws an error.

### How to reproduce the bug

```python
import torch
import torch.nn as nn
import lightning as L
from torch.utils.data import Dataset, DataLoader
from lightning.pytorch.callbacks import Callback, RichModelSummary
from lightning.pytorch.cli import LightningCLI


class DummyCallback(Callback):
    def __init__(self):
        print("Just a dummy callback with no arguments")

    def on_fit_start(self, trainer, pl_module):
        print("Fit starts")


class DummyCallbackWithAnArg(Callback):
    def __init__(self, arg=None):
        print("Just a dummy callback with an argument")

    def on_fit_start(self, trainer, pl_module):
        print("Fit starts")


class CustomLightningCLI(LightningCLI):
    def add_arguments_to_parser(self, parser):
        parser.add_lightning_class_args(
            RichModelSummary, "callbacks.rich_model_summary"
        )
        # a custom callback with no argument throws an error
        parser.add_lightning_class_args(
            DummyCallback, "callbacks.dummy_callback"
        )
        # ok
        parser.add_lightning_class_args(
            DummyCallbackWithAnArg, "callbacks.dummy_callback_with_an_arg"
        )


class DummyModule(L.LightningModule):
    def __init__(self):
        super().__init__()
        self.layer = nn.Linear(32, 2)

    def forward(self, x):
        return self.layer(x)

    def training_step(self, batch):
        return torch.sum(self(batch[0]) - batch[1])

    def configure_optimizers(self):
        return torch.optim.Adam(self.parameters(), lr=1e-3)


class DummyDataset(Dataset):
    def __init__(self):
        super().__init__()

    def __getitem__(self, idx):
        return torch.randn(32), torch.randn(2)

    def __len__(self):
        return 128


class DummyDataModule(L.LightningDataModule):
    def __init__(self):
        super().__init__()

    def train_dataloader(self):
        return DataLoader(DummyDataset(), batch_size=16)


cli = CustomLightningCLI(DummyModule, DummyDataModule, trainer_defaults={"max_epochs": 1})
```

### Error messages and logs

```
Traceback (most recent call last):
  File "C:\Users\aster\.conda\envs\torch\lib\site-packages\jsonargparse\signatures.py", line 529, in group_instantiate_class
    value, parent, key = cfg.get_value_and_parent(group.dest)
  File "C:\Users\aster\.conda\envs\torch\lib\site-packages\jsonargparse\namespace.py", line 318, in get_value_and_parent
    leaf_key, parent_ns, _ = self._parse_required_key(key)
  File "C:\Users\aster\.conda\envs\torch\lib\site-packages\jsonargparse\namespace.py", line 166, in _parse_required_key
    raise KeyError(f'Key "{key}" not found in namespace.')
KeyError: 'Key "callbacks.dummy_callback" not found in namespace.'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\aster\.conda\envs\torch\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\aster\.conda\envs\torch\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\aster\.vscode\extensions\ms-python.python-2023.4.1\pythonFiles\lib\python\debugpy\__main__.py", line 39, in <module>
    cli.main()
  File "c:\Users\aster\.vscode\extensions\ms-python.python-2023.4.1\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\Users\aster\.vscode\extensions\ms-python.python-2023.4.1\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "c:\Users\aster\.vscode\extensions\ms-python.python-2023.4.1\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "c:\Users\aster\.vscode\extensions\ms-python.python-2023.4.1\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "c:\Users\aster\.vscode\extensions\ms-python.python-2023.4.1\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "test.py", line 73, in <module>
    cli = CustomLightningCLI(DummyModule, DummyDataModule, trainer_defaults={"max_epochs": 1})
  File "C:\Users\aster\.conda\envs\torch\lib\site-packages\lightning\pytorch\cli.py", line 350, in __init__
    self.instantiate_classes()
  File "C:\Users\aster\.conda\envs\torch\lib\site-packages\lightning\pytorch\cli.py", line 499, in instantiate_classes
    self.config_init = self.parser.instantiate_classes(self.config)
  File "C:\Users\aster\.conda\envs\torch\lib\site-packages\jsonargparse\deprecated.py", line 131, in patched_instantiate_classes
    cfg = self._unpatched_instantiate_classes(cfg, **kwargs)
  File "C:\Users\aster\.conda\envs\torch\lib\site-packages\jsonargparse\core.py", line 1144, in instantiate_classes
    cfg[subcommand] = subparser.instantiate_classes(cfg[subcommand], instantiate_groups=instantiate_groups)
  File "C:\Users\aster\.conda\envs\torch\lib\site-packages\jsonargparse\deprecated.py", line 131, in patched_instantiate_classes
    cfg = self._unpatched_instantiate_classes(cfg, **kwargs)
  File "C:\Users\aster\.conda\envs\torch\lib\site-packages\jsonargparse\core.py", line 1138, in instantiate_classes
    component.instantiate_class(component, cfg)
  File "C:\Users\aster\.conda\envs\torch\lib\site-packages\jsonargparse\signatures.py", line 534, in group_instantiate_class
    assert '.' not in key
AssertionError
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0): 2.0.0
#- Lightning App Version (e.g., 0.5.2): N/A
#- PyTorch Version (e.g., 2.0): 2.0
#- Python version (e.g., 3.9): 3.9
#- OS (e.g., Linux): Windows
#- CUDA/cuDNN version: N/A
#- GPU models and configuration: N/A
#- How you installed Lightning(`conda`, `pip`, source): pip
#- Running environment of LightningApp (e.g. local, cloud): N/A
```

</details>

cc @carmocca @mauvilsa

**Comment by mauvilsa** [comment]
@martinwhl thank you for reporting. This is a bug in jsonargparse and has been fixed in https://github.com/omni-us/jsonargparse/commit/9e526d9d187fd6516b047b61fa7c7318c1b3bc8c. Once you update to jsonargparse 4.21.0 the problem should be solved.
