### ISSUE TITLE
Problems with reload the model weights only ( `pl.LightningModule.load_from_checkpoint` method）

### ISSUE THREAD

**Issue by YiandLi** [Lightning-AI/lightning#17356]
### Environment

  <summary>Current environment</summary>

```
 PyTorch Lightning Version -- '1.6.0'

```

1. My `pl.LightningModule ` model class is :
```
class LitAutoEncoder(pl.LightningModule):
    def __init__(self, encoder, hyper_parameters, handshaking_tagger, tag_size):
        super().__init__()
        # self.train_epoch_end_dict = []
        self.hyper_parameters = hyper_parameters
        self.rel_extractor = TPLinkerPlusBert(encoder,
                                              tag_size,
                                              hyper_parameters["shaking_type"],
                                              hyper_parameters["inner_enc_type"],
                                              hyper_parameters["tok_pair_sample_rate"]
                                              )
        self.metrics = MetricsCalculator(handshaking_tagger)
        self.loss_func = lambda y_pred, y_true: self.metrics.loss_func(y_pred, y_true, ghm=hyper_parameters["ghm"])
        self.best_valid_f1 = -float('inf')
    
    def training_step(self, batch_train_data, batch_idx):  # TODO 定义 train 过程
        # training_step defines the train loop.

....
```

2. When training, I use a `ModelCheckpoint` like this :
```
checkpoint_callback = ModelCheckpoint(monitor="avg_valid_f1", mode='max', save_top_k=1,
                                          save_weights_only=True
                                          )
```
3. Then the trainer is:
```
 trainer = pl.Trainer(callbacks=[checkpoint_callback, earlystoop_callback],
                         max_epochs=hyper_parameters["epochs"],
                         check_val_every_n_epoch=1,
                         # devices=1,
                         accelerator="gpu",
                         num_sanity_val_steps=0,  
                         logger=False,
                         enable_progress_bar=False
                         
                         )
```

4. After train, I have the checkpoint: `epoch=1-step=1760.ckpt`

5. Then I want to reload this model to inference, then I use the code but there is a bug:
```
>>> LitAutoEncoder.load_from_checkpoint('epoch=1-step=1760.ckpt')


Traceback (most recent call last):
  File "/Users/liuyilin/Library/Python/3.8/lib/python/site-packages/IPython/core/interactiveshell.py", line 3460, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-14-24eab9a4b6fe>", line 1, in <module>
    LitAutoEncoder.load_from_checkpoint('epoch=1-step=1760.ckpt')
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pytorch_lightning/core/saving.py", line 161, in load_from_checkpoint
    model = cls._load_model_state(checkpoint, strict=strict, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pytorch_lightning/core/saving.py", line 203, in _load_model_state
    model = cls(**_cls_kwargs)
TypeError: __init__() missing 4 required positional arguments: 'encoder', 'hyper_parameters', 'handshaking_tagger', and 'tag_size'
```

Then I try to 1stly initialize the model, then load form the ckpt file :
```
 autoencoder = LitAutoEncoder(encoder, hyper_parameters, handshaking_tagger, tag_size)
 autoencoder.load_from_checkpoint(checkpoint_path="checkpoints/epoch=1-step=1760.ckpt" )
```
but there is also a  Traceback:
```
TypeError: __init__() missing 4 required positional arguments: 'encoder', 'hyper_parameters', 'handshaking_tagger', and 'tag_size'
```

Finally I use:
```
    autoencoder = LitAutoEncoder(encoder, hyper_parameters, handshaking_tagger, tag_size)
    autoencoder.load_from_checkpoint(checkpoint_path="checkpoints/epoch=1-step=1760.ckpt",
                                     encoder=encoder,
                                     hyper_parameters=hyper_parameters,
                                     handshaking_tagger=handshaking_tagger,
                                     tag_size=tag_size)
```

and there is no bug, but the weight does not change and more 。。。。

And I use torch.load to see the content in this ckpt, I saw: 
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/72687714/231663940-76ebeaf7-a57c-4997-af41-d6b32f584cf4.png">

# Question:
But then  I have some questions:
1.  There are some other keys saved in this ckpt as well. Though it is ok, but Can I just save the model weight?
2. In the last process of reloading, I firstly initialize the model, then I use the object's method to reload the weight, but why do I still need to pass 4 required positional arguments: 'encoder', 'hyper_parameters', 'handshaking_tagger', and 'tag_size' ?
what is the order of it? In the [official demo](https://pytorch-lightning.readthedocs.io/en/1.6.1/common/checkpointing.html#checkpoint-loading)  , I do not need to pass them ., and these arguments will cover the ckpt weight, making the reload process meaningless.

### Error messages and logs

```
# Error messages and logs here please
```

**Comment by YiandLi** [comment]
Plus,

After setting  the  `save_weights_only=True`  for `ModelCheckpoint` ， why there are still training information in the checkpoint ???

**Comment by ryan597** [comment]
I think if you set in the `__init__` of your lightning model 
`self.save_hyperparameters()` you won't have to pass the params in when using `load_from_checkpoint`. `load_from_checkpoint` is a class method and you should use it as 
```python
model = ModelClass.load_from_checkpoint()` 

# not this
model = ModelClass()
model.load_from_checkpoint()

# But you could technically do this
model = ModelClass()
model = model.load_from_checkpoint()
```

**Comment by ryan597** [comment]
@YiandLi  Please see my first comment about the use of `load_from_checkpoint`. **You must assign the result to the model**
```python
model = ModelClass.load_from_checkpoint(path)
```

**Comment by ryan597** [comment]
So here is my quick test of the save_weights_only so that you can clearly see the differences between them.

<details><summary>Test Code (click to expand)</summary>
<p>

```python
import torch
import torch.nn as nn
import lightning.pytorch as pl
from lightning.pytorch.callbacks import ModelCheckpoint
from lightning.pytorch.demos.boring_classes import BoringModel

def test(arg):
  pl.seed_everything(1)
  checkpoint_callback = ModelCheckpoint(dirpath="checkpoints", 
                                        filename="boring",
                                        save_top_k=1,
                                        save_weights_only=arg)
  
  model = BoringModel()
  trainer = pl.Trainer(
      max_epochs=2,
      enable_model_summary=False,
      callbacks=[checkpoint_callback],
      accelerator="cuda",
  )
  trainer.fit(model)

test(True)
test(False)
```

Print and save the checkpoints to text files and you can get the diff by calling
```
diff -y -W150 checkpoints/1.txt checkpoints/2.txt
```

</p>
</details> 

<details><summary>Side-by-side difference between checkpoints (click to expand)</summary>
<p>

```
{'epoch': 1,                                                                    {'epoch': 1,
 'global_step': 128,                                                             'global_step': 128,
 'pytorch-lightning_version': '2.1.0dev',                                        'pytorch-lightning_version': '2.1.0dev',
 'state_dict': OrderedDict([('layer.weight',                                     'state_dict': OrderedDict([('layer.weight',
               tensor([[  9.3906, -11.6244,  21.3764, -11.5400,  13.21                         tensor([[  9.3906, -11.6244,  21.3764, -11.5400,  13.21
                         -1.7392,   9.9740,  17.2204,  10.8727,   0.59                                   -1.7392,   9.9740,  17.2204,  10.8727,   0.59
                        -12.2681,  18.3618,   0.2323, -19.5311,  -4.47                                  -12.2681,  18.3618,   0.2323, -19.5311,  -4.47
                         12.9603,  -6.5036,  -2.3473,   2.2381,  11.86                                   12.9603,  -6.5036,  -2.3473,   2.2381,  11.86
                         -5.6686,  -7.8706,  -3.2110,   9.4399],                                         -5.6686,  -7.8706,  -3.2110,   9.4399],
                       [  1.9284,   2.2786,   2.6716,  -8.1540,   4.27                                 [  1.9284,   2.2786,   2.6716,  -8.1540,   4.27
                          0.7786,  -2.8545,  -0.0840,  -2.4027,  -0.22                                    0.7786,  -2.8545,  -0.0840,  -2.4027,  -0.22
                         -3.6521,  -4.8529,   5.7222,   0.9696,   1.57                                   -3.6521,  -4.8529,   5.7222,   0.9696,   1.57
                          2.8144,   2.5263,  -2.8940,  -5.7262,  -1.84                                    2.8144,   2.5263,  -2.8940,  -5.7262,  -1.84
                         -3.9150,   3.2220,   4.4131,   3.6003]], devi                                   -3.9150,   3.2220,   4.4131,   3.6003]], devi
              ('layer.bias', tensor([0.0750, 2.1158], device='cuda:0')                        ('layer.bias', tensor([0.0750, 2.1158], device='cuda:0')
 'loops': {'fit_loop': {'state_dict': {},                                        'loops': {'fit_loop': {'state_dict': {},
   'epoch_loop.state_dict': {'_batches_that_stepped': 128},                        'epoch_loop.state_dict': {'_batches_that_stepped': 128},
   'epoch_loop.batch_progress': {'total': {'ready': 128,                           'epoch_loop.batch_progress': {'total': {'ready': 128,
     'completed': 128,                                                               'completed': 128,
     'started': 128,                                                                 'started': 128,
     'processed': 128},                                                              'processed': 128},
    'current': {'ready': 64, 'completed': 64, 'started': 64, 'processe              'current': {'ready': 64, 'completed': 64, 'started': 64, 'processe
    'is_last_batch': True},                                                         'is_last_batch': True},
   'epoch_loop.scheduler_progress': {'total': {'ready': 2, 'completed'             'epoch_loop.scheduler_progress': {'total': {'ready': 2, 'completed'
    'current': {'ready': 1, 'completed': 1}},                                       'current': {'ready': 1, 'completed': 1}},
   'epoch_loop.automatic_optimization.state_dict': {},                             'epoch_loop.automatic_optimization.state_dict': {},
   'epoch_loop.automatic_optimization.optim_progress': {'optimizer': {             'epoch_loop.automatic_optimization.optim_progress': {'optimizer': {
       'completed': 128},                                                              'completed': 128},
      'current': {'ready': 64, 'completed': 64}},                                     'current': {'ready': 64, 'completed': 64}},
     'zero_grad': {'total': {'ready': 128, 'completed': 128, 'started'               'zero_grad': {'total': {'ready': 128, 'completed': 128, 'started'
      'current': {'ready': 64, 'completed': 64, 'started': 64}}}},                    'current': {'ready': 64, 'completed': 64, 'started': 64}}}},
   'epoch_loop.manual_optimization.state_dict': {},                                'epoch_loop.manual_optimization.state_dict': {},
   'epoch_loop.manual_optimization.optim_step_progress': {'total': {'r             'epoch_loop.manual_optimization.optim_step_progress': {'total': {'r
     'completed': 0},                                                                'completed': 0},
    'current': {'ready': 0, 'completed': 0}},                                       'current': {'ready': 0, 'completed': 0}},
   'epoch_loop.val_loop.state_dict': {},                                           'epoch_loop.val_loop.state_dict': {},
   'epoch_loop.val_loop.batch_progress': {'total': {'ready': 64,                   'epoch_loop.val_loop.batch_progress': {'total': {'ready': 64,
     'completed': 64,                                                                'completed': 64,
     'started': 64,                                                                  'started': 64,
     'processed': 64},                                                               'processed': 64},
    'current': {'ready': 64, 'completed': 64, 'started': 64, 'processe              'current': {'ready': 64, 'completed': 64, 'started': 64, 'processe
    'is_last_batch': True},                                                         'is_last_batch': True},
   'epoch_progress': {'total': {'ready': 2,                                        'epoch_progress': {'total': {'ready': 2,
     'completed': 1,                                                                 'completed': 1,
     'started': 2,                                                                   'started': 2,
     'processed': 2},                                                                'processed': 2},
    'current': {'ready': 2, 'completed': 1, 'started': 2, 'processed':              'current': {'ready': 2, 'completed': 1, 'started': 2, 'processed':
  'validate_loop': {'state_dict': {},                                             'validate_loop': {'state_dict': {},
   'batch_progress': {'total': {'ready': 0,                                        'batch_progress': {'total': {'ready': 0,
     'completed': 0,                                                                 'completed': 0,
     'started': 0,                                                                   'started': 0,
     'processed': 0},                                                                'processed': 0},
    'current': {'ready': 0, 'completed': 0, 'started': 0, 'processed':              'current': {'ready': 0, 'completed': 0, 'started': 0, 'processed':
    'is_last_batch': False}},                                                       'is_last_batch': False}},
  'test_loop': {'state_dict': {},                                                 'test_loop': {'state_dict': {},
   'batch_progress': {'total': {'ready': 0,                                        'batch_progress': {'total': {'ready': 0,
     'completed': 0,                                                                 'completed': 0,
     'started': 0,                                                                   'started': 0,
     'processed': 0},                                                                'processed': 0},
    'current': {'ready': 0, 'completed': 0, 'started': 0, 'processed':              'current': {'ready': 0, 'completed': 0, 'started': 0, 'processed':
    'is_last_batch': False}},                                                       'is_last_batch': False}},
  'predict_loop': {'state_dict': {},                                              'predict_loop': {'state_dict': {},
   'batch_progress': {'total': {'ready': 0,                                        'batch_progress': {'total': {'ready': 0,
     'completed': 0,                                                                 'completed': 0,
     'started': 0,                                                                   'started': 0,
     'processed': 0},                                                                'processed': 0},
    'current': {'ready': 0, 'completed': 0, 'started': 0, 'processed':    \         'current': {'ready': 0, 'completed': 0, 'started': 0, 'processed':
                                                                          >      'callbacks': {"ModelCheckpoint{'monitor': None, 'mode': 'min', 'every
                                                                          >        'best_model_score': None,
                                                                          >        'best_model_path': '/home/ryan/Documents/codes/thunder-lightning/ch
                                                                          >        'current_score': None,
                                                                          >        'dirpath': '/home/ryan/Documents/codes/thunder-lightning/checkpoint
                                                                          >        'best_k_models': {},
                                                                          >        'kth_best_model_path': '',
                                                                          >        'kth_value': tensor(inf),
                                                                          >        'last_model_path': ''}},
                                                                          >      'optimizer_states': [{'state': {0: {'momentum_buffer': None},
                                                                          >         1: {'momentum_buffer': None}},
                                                                          >        'param_groups': [{'lr': 0.0010000000000000002,
                                                                          >          'momentum': 0,
                                                                          >          'dampening': 0,
                                                                          >          'weight_decay': 0,
                                                                          >          'nesterov': False,
                                                                          >          'maximize': False,
                                                                          >          'foreach': None,
                                                                          >          'differentiable': False,
                                                                          >          'initial_lr': 0.1,
                                                                          >          'params': [0, 1]}]}],
                                                                          >      'lr_schedulers': [{'step_size': 1,
                                                                          >        'gamma': 0.1,
                                                                          >        'base_lrs': [0.1],
                                                                          >        'last_epoch': 2,
                                                                          >        'verbose': False,
                                                                          >        '_step_count': 3,
                                                                          >        '_get_lr_called_within_step': False,
                                                                          >        '_last_lr': [0.0010000000000000002]}]}
```

</p>
</details> 

So yes it isn't just the models `state_dict`, and the argument `save_weights_only` to `ModelCheckpoint` is named rather misleading as it is. It wouldn't really be a checkpoint without this extra information, but the user is explicit about only saving the weights and the documentation also clearly states that it's only the weights.

I would propose also changing the file extension though if it is simply the state_dict.

**Comment by YiandLi** [comment]
Thank u for your explanation, I am clear about it now.
