### ISSUE TITLE
Instantiating CLI with custom args and run=False doesn't work with existing config file

### ISSUE THREAD

**Issue by fernandocamargoai** [Lightning-AI/lightning#17447]
### Bug description

I trained a model normally, invoking `python -m src.trainer fit -c config.yaml`. Then a `config.yaml` with all the parameters was saved, containing `ckpt_path: null`. In another script, I wanted to use the `CLI` to instantiate the model, data and load the checkpoint. I tried the following:

```python
cli = LightningCLI(
    FutureShotLightningModule,
    FutureShotDataModule,
    args=[
        "test",
        "-c",
        config_path,
        "--ckpt_path",
        checkpoint_path,
    ],
    run=False,
)
```

Which gave me this error:

```
error: Unrecognized arguments: test --ckpt_path experiments/group_687ed479bae1c3f3940ff7c23f7dd9e9_7_100_42/group_687ed479bae1c3f3940ff7c23f7dd9e9_7_100_42_experiment_1/model.ckpt
```

I tried removing the subcommand `test` and the `--ckpt_path`, but then it failed with:

```
error: 'Configuration check failed :: No action for destination key "ckpt_path" to check its value.'
```

In this case, it's because the file contains `ckpt_path: null`, as I said before. If I manually remove the `ckpt_path` from the file, I get:

```
Traceback (most recent call last):
  File "/home/fernando/phd_workspace/future-shot/src/future_shot/few_shot.py", line 196, in <module>
    CLI([fit, test])
  File "/home/fernando/phd_workspace/future-shot/venv/lib/python3.9/site-packages/jsonargparse/cli.py", line 104, in CLI
    return _run_component(component, cfg_init.get(subcommand))
  File "/home/fernando/phd_workspace/future-shot/venv/lib/python3.9/site-packages/jsonargparse/cli.py", line 138, in _run_component
    return component(**cfg)
  File "/home/fernando/phd_workspace/future-shot/src/future_shot/few_shot.py", line 188, in test
    _evaluate_few_shot(FewShotSplit(
  File "/home/fernando/phd_workspace/future-shot/src/future_shot/few_shot.py", line 84, in _evaluate_few_shot
    cli = FutureShotLightningCLI(
  File "/home/fernando/phd_workspace/future-shot/venv/lib/python3.9/site-packages/pytorch_lightning/cli.py", line 349, in __init__
    self.before_instantiate_classes()
  File "/home/fernando/phd_workspace/future-shot/src/future_shot/trainer.py", line 19, in before_instantiate_classes
    subcommand = self.config["subcommand"]
  File "/home/fernando/phd_workspace/future-shot/venv/lib/python3.9/site-packages/jsonargparse/namespace.py", line 205, in __getitem__
    leaf_key, parent_ns, _ = self._parse_required_key(key)
  File "/home/fernando/phd_workspace/future-shot/venv/lib/python3.9/site-packages/jsonargparse/namespace.py", line 166, in _parse_required_key
    raise KeyError(f'Key "{key}" not found in namespace.')
KeyError: 'Key "subcommand" not found in namespace.'

Process finished with exit code 1
```

How am I supposed to use the CLI for this use case? 

### What version are you seeing the problem on?

2.0+

### Environment

<details>
  <summary>Current environment</summary>

* CUDA:
        - GPU:
                - NVIDIA GeForce RTX 3050 Ti Laptop GPU
        - available:         True
        - version:           11.7
* Lightning:
        - lightning-utilities: 0.7.1
        - pytorch-lightning: 2.0.0
        - torch:             2.0.0
        - torchmetrics:      0.11.3
        - torchvision:       0.15.1
* Packages:
        - aiohttp:           3.8.4
        - aiosignal:         1.3.1
        - antlr4-python3-runtime: 4.9.3
        - appdirs:           1.4.4
        - async-timeout:     4.0.2
        - attrs:             22.2.0
        - certifi:           2022.12.7
        - charset-normalizer: 3.0.1
        - click:             8.1.3
        - cmake:             3.26.0
        - datasets:          2.10.1
        - dill:              0.3.6
        - docker-pycreds:    0.4.0
        - docstring-parser:  0.15
        - evaluate:          0.4.0
        - filelock:          3.9.0
        - frozenlist:        1.3.3
        - fsspec:            2023.1.0
        - future-shot:       0.0.1
        - gitdb:             4.0.10
        - gitpython:         3.1.31
        - huggingface-hub:   0.12.1
        - idna:              3.4
        - importlib-resources: 5.12.0
        - jinja2:            3.1.2
        - joblib:            1.2.0
        - jsonargparse:      4.20.0
        - lightning-utilities: 0.7.1
        - lit:               15.0.7
        - markupsafe:        2.1.2
        - mpmath:            1.3.0
        - multidict:         6.0.4
        - multiprocess:      0.70.14
        - networkx:          3.0
        - nltk:              3.8.1
        - numpy:             1.24.2
        - nvidia-cublas-cu11: 11.10.3.66
        - nvidia-cuda-cupti-cu11: 11.7.101
        - nvidia-cuda-nvrtc-cu11: 11.7.99
        - nvidia-cuda-runtime-cu11: 11.7.99
        - nvidia-cudnn-cu11: 8.5.0.96
        - nvidia-cufft-cu11: 10.9.0.58
        - nvidia-curand-cu11: 10.2.10.91
        - nvidia-cusolver-cu11: 11.4.0.1
        - nvidia-cusparse-cu11: 11.7.4.91
        - nvidia-nccl-cu11:  2.14.3
        - nvidia-nvtx-cu11:  11.7.91
        - omegaconf:         2.3.0
        - packaging:         23.0
        - pandas:            1.5.3
        - pathtools:         0.1.2
        - pillow:            9.4.0
        - pip:               23.0
        - protobuf:          4.22.1
        - psutil:            5.9.4
        - pyarrow:           11.0.0
        - python-dateutil:   2.8.2
        - pytorch-lightning: 2.0.0
        - pytz:              2022.7.1
        - pyyaml:            6.0
        - regex:             2022.10.31
        - requests:          2.28.2
        - responses:         0.18.0
        - scikit-learn:      1.2.2
        - scipy:             1.10.1
        - sentence-transformers: 2.2.2
        - sentencepiece:     0.1.97
        - sentry-sdk:        1.17.0
        - setproctitle:      1.3.2
        - setuptools:        67.1.0
        - six:               1.16.0
        - smmap:             5.0.0
        - sympy:             1.11.1
        - threadpoolctl:     3.1.0
        - tokenizers:        0.13.2
        - torch:             2.0.0
        - torchmetrics:      0.11.3
        - torchvision:       0.15.1
        - tqdm:              4.65.0
        - transformers:      4.27.1
        - triton:            2.0.0
        - typeshed-client:   2.2.0
        - typing-extensions: 4.5.0
        - urllib3:           1.26.14
        - wandb:             0.14.0
        - wheel:             0.38.4
        - xxhash:            3.2.0
        - yarl:              1.8.2
        - zipp:              3.15.0
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         
        - python:            3.9.12
        - version:           #1 SMP PREEMPT Wed Apr 5 09:58:14 UTC 2023

</details>

**Comment by fernandocamargoai** [comment]
I found the following workaround:

```python
config = yaml.load(open(config_path, "r"), Loader=yaml.FullLoader)
cli = LightningCLI(
    FutureShotLightningModule,
    FutureShotDataModule,
    args={
        key: value
        for key, value in config.items()
        if key in ("model", "data", "seed_everything")
    },
    run=False,
)
```

**Comment by mauvilsa** [comment]
@fernandocamargoai this is not a bug. The purpose of the automatically saved config is reproducibility. That is, if used with the **same** CLI then the result is reproduced (leaving aside other reasons why it might not give the exact same result). Using a saved config in a different CLI is not expected to work because that CLI can have different settings. Your workaround is fine, though this depends on the case. A more general solution that I have though of for this kind of use cases is https://github.com/Lightning-AI/lightning/issues/15427#issuecomment-1298869338.

**Comment by awaelchli** [comment]
Closing as working as intended, and #15427 is there to potentially fill the gap in form of a feature. Thanks for raising this @fernandocamargoai
