### ISSUE TITLE
Learning rate scheduler is invalid

### ISSUE THREAD

**Issue by tungts1101** [Lightning-AI/lightning#17476]
### Bug description

I am following the tutorial to reproduce the result of SimCLR (https://uvadlc-notebooks.readthedocs.io/en/latest/tutorial_notebooks/tutorial17/SimCLR.html) and I get the error notifying that the learning rate schedular is invalid.

```
Traceback (most recent call last):
  File "/home/ellen/ContrastiveLearning/train.py", line 61, in <module>
    simclr_model = train_simclr(hidden_dim=128, lr=args["learning_rate"],
  File "/home/ellen/ContrastiveLearning/train.py", line 56, in train_simclr
    trainer.fit(model, train_loader, val_loader)
  File "/home/ellen/anaconda3/envs/cl/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 553, in fit
    self._run(model)
  File "/home/ellen/anaconda3/envs/cl/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 874, in _run
    self.accelerator.setup(self, model)  # note: this sets up self.lightning_module
  File "/home/ellen/anaconda3/envs/cl/lib/python3.9/site-packages/pytorch_lightning/accelerators/gpu.py", line 42, in setup
    return super().setup(trainer, model)
  File "/home/ellen/anaconda3/envs/cl/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 88, in setup
    self.setup_optimizers(trainer)
  File "/home/ellen/anaconda3/envs/cl/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 330, in setup_optimizers
    optimizers, lr_schedulers, optimizer_frequencies = self.training_type_plugin.init_optimizers(
  File "/home/ellen/anaconda3/envs/cl/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 223, in init_optimizers
    return trainer.init_optimizers(model)
  File "/home/ellen/anaconda3/envs/cl/lib/python3.9/site-packages/pytorch_lightning/trainer/optimizers.py", line 99, in init_optimizers
    lr_schedulers = self.configure_schedulers(lr_schedulers, monitor, is_manual_optimization)
  File "/home/ellen/anaconda3/envs/cl/lib/python3.9/site-packages/pytorch_lightning/trainer/optimizers.py", line 176, in configure_schedulers
    raise ValueError(f'The provided lr scheduler "{scheduler}" is invalid')
ValueError: The provided lr scheduler "<torch.optim.lr_scheduler.ExponentialLR object at 0x7fda400bdee0>" is invalid
```

### What version are you seeing the problem on?

1.9.x

### How to reproduce the bug
Here is the code to configure the optimizer and learning rate schedular
```
def configure_optimizers(self):
        optimizer = optim.AdamW(self.parameters(),
                                lr=self.hparams.lr,
                                weight_decay=self.hparams.weight_decay)
        lr_scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer,
                                                            T_max=self.hparams.max_epochs)
        return [optimizer], [lr_scheduler]
```

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

cc @borda

**Comment by awaelchli** [comment]
@tungts1101 Could you please share the code that you ran producing this error? The error message you posted does not match the code snippet.

**Comment by kvnptl** [comment]
> I am facing the same error on `torch 2.0.1` for the learning rate scheduler `StepLR`

Downgrading to `torch==1.13.1 torchvision==0.14.1` worked for me

**Comment by awaelchli** [comment]
@kvnptl here is a code example that works with torch 2.0 and the StepLR scheduler. Could you please modify it to produce the error you are seeing? I can't reproduce what you are saying.

```py

import torch
from torch.utils.data import DataLoader, Dataset

from lightning.pytorch import LightningModule, Trainer


class RandomDataset(Dataset):
    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len


class BoringModel(LightningModule):
    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)

    def forward(self, x):
        return self.layer(x)

    def training_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("train_loss", loss)
        return {"loss": loss}

    def configure_optimizers(self):
        optimizer = torch.optim.SGD(self.layer.parameters(), lr=0.1)
        scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=1)
        return [optimizer], [scheduler]


def run():
    train_data = DataLoader(RandomDataset(32, 64), batch_size=2)
    model = BoringModel()
    trainer = Trainer(max_epochs=2)
    trainer.fit(model, train_dataloaders=train_data)


if __name__ == "__main__":
    run()

```

**Comment by arunraja-hub** [comment]
@awaelchli Here is an example that causes the same error: https://github.com/THUNLP-MT/PS-VAE/blob/0dfcbd25b91e1127e556cb3c273260a41a1c3f35/src/pl_models/ps_vae_model.py#L126

This is the output after I run `collect_env`:
```
Collecting environment information...
.../lib/python3.9/site-packages/torch/cuda/__init__.py:173: UserWarning: 
NVIDIA H100 PCIe with CUDA capability sm_90 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 sm_80 sm_86 compute_37.
If you want to use the NVIDIA H100 PCIe GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
PyTorch version: 2.0.1
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: CentOS Linux release 8.1.1911 (Core)  (x86_64)
GCC version: (GCC) 8.3.1 20190507 (Red Hat 8.3.1-4)
Clang version: Could not collect
CMake version: version 3.11.4
Libc version: glibc-2.28

Python version: 3.9.17 (main, Jul  5 2023, 20:41:20)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-4.18.0-147.8.1.el8_2.arc.x86_64-x86_64-with-glibc2.28
Is CUDA available: True
CUDA runtime version: 11.7.64
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA H100 PCIe
GPU 1: NVIDIA H100 PCIe
GPU 2: NVIDIA H100 PCIe
GPU 3: NVIDIA H100 PCIe

Nvidia driver version: 525.116.04
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              48
On-line CPU(s) list: 0-47
Thread(s) per core:  1
Core(s) per socket:  24
Socket(s):           2
NUMA node(s):        2
Vendor ID:           GenuineIntel
CPU family:          6
Model:               106
Model name:          Intel(R) Xeon(R) Gold 6342 CPU @ 2.80GHz
Stepping:            6
CPU MHz:             800.421
BogoMIPS:            5600.00
Virtualization:      VT-x
L1d cache:           48K
L1i cache:           32K
L2 cache:            1280K
L3 cache:            36864K
NUMA node0 CPU(s):   0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46
NUMA node1 CPU(s):   1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local wbnoinvd dtherm ida arat pln pts avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq rdpid md_clear pconfig flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.24.3
[pip3] pytorch-lightning==1.5.7
[pip3] torch==2.0.1
[pip3] torch-geometric==2.3.1
[pip3] torchaudio==0.8.1
[pip3] torchmetrics==0.9.3
[pip3] torchvision==0.15.2
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.3.1              h9edb442_10    conda-forge
[conda] cudatoolkit-dev           11.7.0               h1de0b5d_6    conda-forge
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py39h7e14d7c_0    conda-forge
[conda] mkl_fft                   1.3.1            py39h0c7bc48_1    conda-forge
[conda] mkl_random                1.2.2            py39hde0f152_0    conda-forge
[conda] numpy                     1.26.0                   pypi_0    pypi
[conda] numpy-base                1.24.3           py39h31eccc5_0  
[conda] pyg                       2.3.1           py39_torch_2.0.0_cu117    pyg
[conda] pytorch                   2.0.1           py3.9_cuda11.7_cudnn8.5.0_0    pytorch
[conda] pytorch-cuda              11.7                 h778d358_5    pytorch
[conda] pytorch-lightning         1.5.7                    pypi_0    pypi
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                0.8.1                    pypi_0    pypi
[conda] torchmetrics              0.9.3                    pypi_0    pypi
[conda] torchtriton               2.0.0                      py39    pytorch
[conda] torchvision               0.9.1+cu101              pypi_0    pypi
```

**Comment by UESTCSober** [comment]
> > I am facing the same error on `torch 2.0.1` for the learning rate scheduler `StepLR`
> 
> Downgrading to `torch==1.13.1 torchvision==0.14.1` worked for me

It works for me, thank you very much!

**Comment by CQ981001** [comment]
> > I am facing the same error on `torch 2.0.1` for the learning rate scheduler `StepLR`
> 
> Downgrading to `torch==1.13.1 torchvision==0.14.1` worked for me

It works for me! Thanks

**Comment by ZhanzhouFeng** [comment]
For the torch > 2.0.1, you should set it to :
`lr_scheduler == {'scheduler': ExponentialLR(gen_opt, 0.99), 'interval': 'step'} `

**Comment by HuangMJJJJJ** [comment]
For earlier versions of torch and pytorch-lightning, learning rate schedulers inherit from `optim.lr_scheduler._LRScheduler`. In the latest torch, they inherit from `optim.lr_scheduler.LRScheduler`. In the older versions of pytorch-lightning, the learning rate scheduler is checked using `isinstance(scheduler, optim.lr_scheduler._LRScheduler)`, which results in the inability to recognize the learning rate schedulers of the newer version of torch.

**Comment by Saumya-Gupta-26** [comment]
> lr_scheduler == {'scheduler': ExponentialLR(gen_opt, 0.99), 'interval': 'step'}

This worked for me. Thanks a lot!

**Comment by Skybluewater** [comment]
I am facing this error too with `torch2.3.1` with `pytorch_lightning 1.5.10`
Then I upgraded `pytorch_lightning` to `2.4.0` and it returned me another new error 

> 'Trainer' has no attribute 'add_argparse_args'

Finally I downgraded it to 1.9.0 and it works
