### ISSUE TITLE
Gradients in valid/test step not allowed

### ISSUE THREAD

**Issue by stases** [Lightning-AI/lightning#17653]
### Bug description

Hi everyone,

I am using PL to train a Graph Neural Network on the MD17 dataset. The input to the model is a graph, and the output is a scalar (energy). The forces on the atoms (nodes) are calculated as the gradient of the energy wrt. positions of nodes. The problem is that in the validation/test step, it is not possible to calculate forces, as PL doesn't allow me to set gradients to True on inference tensor.

I took a working code from a colleague, but it also didn't work for me. I am currently using the latest PL version, and this issue persisted until I downgraded all the way up to 1.6.0, and only then did the issue go away. I will provide you with the class I am using, but without the dataset and other models, it is not easy to reproduce the error. Hopefully, this will be enough.

Thank you for your help!

### What version are you seeing the problem on?

v1.7, v1.8, v1.9, v2.0

### How to reproduce the bug

```python
class MD17Model(pl.LightningModule):
# init ...

    def forward(self, graph):
        graph.x = graph.x.float()
        energy, force = self.pred_energy_and_force(graph)
        return energy, force

    @torch.enable_grad()
    def pred_energy_and_force(self, graph):
        graph.pos = torch.autograd.Variable(graph.pos, requires_grad=True)
        pred_energy = self.model(graph)
        sign = -1.0
        pred_force = (
            sign
            * torch.autograd.grad(
                pred_energy,
                graph.pos,
                grad_outputs=torch.ones_like(pred_energy),
                create_graph=True,
                retain_graph=True,
            )[0]
        )
        return pred_energy.squeeze(-1), pred_force

    @torch.inference_mode(False)
    def validation_step(self, graph, batch_idx):
        energy, force = self(graph)

    @torch.inference_mode(False)
    def test_step(self, graph, batch_idx):
        energy, force = self(graph)

```

### Error messages and logs

```
Traceback (most recent call last):
  File "/home/tin/Documents/Github/FractalMessagePassing/lightning_train.py", line 200, in <module>
    trainer.test(lightning_model)
  File "/home/tin/anaconda3/envs/AudioSeparation/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 868, in test
    return self._call_and_handle_interrupt(self._test_impl, model, dataloaders, ckpt_path, verbose, datamodule)
  File "/home/tin/anaconda3/envs/AudioSeparation/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 654, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/tin/anaconda3/envs/AudioSeparation/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 915, in _test_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/tin/anaconda3/envs/AudioSeparation/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1166, in _run
    results = self._run_stage()
  File "/home/tin/anaconda3/envs/AudioSeparation/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1249, in _run_stage
    return self._run_evaluate()
  File "/home/tin/anaconda3/envs/AudioSeparation/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1294, in _run_evaluate
    eval_loop_results = self._evaluation_loop.run()
  File "/home/tin/anaconda3/envs/AudioSeparation/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/home/tin/anaconda3/envs/AudioSeparation/lib/python3.10/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 155, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/home/tin/anaconda3/envs/AudioSeparation/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/home/tin/anaconda3/envs/AudioSeparation/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 143, in advance
    output = self._evaluation_step(**kwargs)
  File "/home/tin/anaconda3/envs/AudioSeparation/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 240, in _evaluation_step
    output = self.trainer._call_strategy_hook(hook_name, *kwargs.values())
  File "/home/tin/anaconda3/envs/AudioSeparation/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1703, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/tin/anaconda3/envs/AudioSeparation/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 379, in test_step
    return self.model.test_step(*args, **kwargs)
  File "/home/tin/anaconda3/envs/AudioSeparation/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/tin/Documents/Github/FractalMessagePassing/trainers/train_md17_lightning.py", line 132, in test_step
    energy, force = self(graph)
  File "/home/tin/anaconda3/envs/AudioSeparation/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tin/Documents/Github/FractalMessagePassing/trainers/train_md17_lightning.py", line 84, in forward
    energy, force = self.pred_energy_and_force(graph)
  File "/home/tin/anaconda3/envs/AudioSeparation/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/tin/Documents/Github/FractalMessagePassing/trainers/train_md17_lightning.py", line 89, in pred_energy_and_force
    graph.pos = torch.autograd.Variable(graph.pos, requires_grad=True)
RuntimeError: Setting requires_grad=True on inference tensor outside InferenceMode is not allowed.
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

**Comment by awaelchli** [comment]
Hey @stases 
Did you also try setting `Trainer(inferece_mode=False)`?

**Comment by awaelchli** [comment]
I'm confident that settings `inference_mode=False` will resolve your issue, but if not let me know and we can look into it further.
