### ISSUE TITLE
PTL 2.0 and num_workers > 0 breaks dataloading after a number of epochs

### ISSUE THREAD

**Issue by exnx** [Lightning-AI/lightning#17729]
### Bug description

I recently switched my PTL and PT to 2.0, but have a dataloading / multiprocessing bug after 7+ epochs.  When I switch back to PTL 1.8 and PT 1.13, the issue goes away.

Specifically, in my dataloader, it occurs if the num_workers >= 1.  I am testing with just a single gpu.  Some other quirks:

- If I lower the batch size, it works ok, but I need the larger batch size (which works in PTL 1.8).
- The problem goes away if num_workers=0, but it's 30% slower
- It happens when I launch a kubernetes cluster pod, but when running the same settings in an interactive shell, it doesn't occur.  The exact same command (as far as I can tell) is run in both instances.

Other context:
I am loading DNA sequences from a large file.

I would really appreciate any tips or advice if anyone also has seen something like this!  Thanks.

### What version are you seeing the problem on?

v2.0

### Error messages and logs

``` 
File "/home/miniconda3/envs/safari2/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1132, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/miniconda3/envs/safari2/lib/python3.8/queue.py", line 179, in get
    self.not_empty.wait(remaining)
  File "/home/miniconda3/envs/safari2/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
  File "/home/miniconda3/envs/safari2/lib/python3.8/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 1092) is killed by signal: Aborted.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "train.py", line 726, in main
    train(config)
  File "train.py", line 707, in train
    trainer.fit(model)
  File "/home/miniconda3/envs/safari2/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 520, in fit
    call._call_and_handle_interrupt(
  File "/home/miniconda3/envs/safari2/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/miniconda3/envs/safari2/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 559, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/miniconda3/envs/safari2/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 935, in _run
    results = self._run_stage()
  File "/home/miniconda3/envs/safari2/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 978, in _run_stage
    self.fit_loop.run()
  File "/home/miniconda3/envs/safari2/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 201, in run
    self.advance()
  File "/home/miniconda3/envs/safari2/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 354, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/home/miniconda3/envs/safari2/lib/python3.8/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 134, in run
    self.on_advance_end()
  File "/home/miniconda3/envs/safari2/lib/python3.8/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 248, in on_advance_end
    self.val_loop.run()
  File "/home/miniconda3/envs/safari2/lib/python3.8/site-packages/pytorch_lightning/loops/utilities.py", line 177, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/home/miniconda3/envs/safari2/lib/python3.8/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 108, in run
    batch, batch_idx, dataloader_idx = next(data_fetcher)
  File "/home/miniconda3/envs/safari2/lib/python3.8/site-packages/pytorch_lightning/loops/fetchers.py", line 136, in __next__
    self._fetch_next_batch(self.dataloader_iter)
  File "/home/miniconda3/envs/safari2/lib/python3.8/site-packages/pytorch_lightning/loops/fetchers.py", line 150, in _fetch_next_batch
    batch = next(iterator)
  File "/home/miniconda3/envs/safari2/lib/python3.8/site-packages/pytorch_lightning/utilities/combined_loader.py", line 276, in __next__
    out = next(self._iterator)
  File "/home/miniconda3/envs/safari2/lib/python3.8/site-packages/pytorch_lightning/utilities/combined_loader.py", line 122, in __next__
    out = next(self.iterators[self._iterator_idx])
  File "/home/miniconda3/envs/safari2/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/home/miniconda3/envs/safari2/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1328, in _next_data
    idx, data = self._get_data()
  File "/home/miniconda3/envs/safari2/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1284, in _get_data
    success, data = self._try_get_data()
  File "/home/miniconda3/envs/safari2/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1145, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 1092) exited unexpectedly
Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):  2.0
#- Lightning App Version (e.g., 0.5.2):  ?
#- PyTorch Version (e.g., 2.0):  1.13
#- Python version (e.g., 3.9):  3.8
#- OS (e.g., Linux):  linux
#- CUDA/cuDNN version:  11.7
#- GPU models and configuration:  a100
#- How you installed Lightning(`conda`, `pip`, source):  conda
#- Running environment of LightningApp (e.g. local, cloud):  cloud
```

</details>

**Comment by YuLiu-LY** [comment]
Hi, I have the same problem as you. Have you solved this problem?

**Comment by exnx** [comment]
check out this commit, it fixed it for me.  https://github.com/HazyResearch/hyena-dna/commit/c619f186cee05707e94f9c4e5931416e3fdc8777
