### ISSUE TITLE
ModuleNotFoundError: No module named 'pytorch_lightning.core.lightning'

### ISSUE THREAD

**Issue by monajalal** [Lightning-AI/lightning#17734]
### Bug description

How should I fix this bug?
```
(zephyr) mona@ard-gpu-01:~/zephyr/python/zephyr$ python test.py     --model_name pn2     --dataset_root ./data/ycb/matches_data_test/     --dataset_name ycbv     --dataset HSVD_diff_uv_norm     --no_valid_proj --no_valid_depth     --loss_cutoff log     --exp_name final     --resume_path ./ckpts/final_ycbv.ckpt
Traceback (most recent call last):
  File "/home/mona/zephyr/python/zephyr/test.py", line 9, in <module>
    from zephyr.models import getModel
  File "/home/mona/zephyr/python/zephyr/models/__init__.py", line 9, in <module>
    from .linear import MLP, LogReg
  File "/home/mona/zephyr/python/zephyr/models/linear.py", line 6, in <module>
    from .base import BaseModel
  File "/home/mona/zephyr/python/zephyr/models/base.py", line 6, in <module>
    from pytorch_lightning.core.lightning import LightningModule
ModuleNotFoundError: No module named 'pytorch_lightning.core.lightning'

```

```
(zephyr) mona@ard-gpu-01:~/zephyr/python/zephyr$ python
Python 3.9.16 (main, Mar  8 2023, 14:00:05) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pytorch_lightning
>>> pytorch_lightning.__version__
'2.0.2'
```

I have
```
$ uname -a
Linux ard-gpu-01 5.19.0-42-generic #43~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Apr 21 16:51:08 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
LSB Version:	core-11.1.0ubuntu4-noarch:security-11.1.0ubuntu4-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy

$ nvidia-smi
Wed May 31 13:58:18 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3080 L...    On | 00000000:01:00.0 Off |                  N/A |
| N/A   52C    P8               16W /  90W|    540MiB / 16384MiB |     15%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      2674      G   /usr/lib/xorg/Xorg                          251MiB |
|    0   N/A  N/A      3178      G   ...libexec/gnome-remote-desktop-daemon        3MiB |
|    0   N/A  N/A     81156      G   blender                                     283MiB |
+---------------------------------------------------------------------------------------+

$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Jun__8_16:49:14_PDT_2022
Cuda compilation tools, release 11.7, V11.7.99
Build cuda_11.7.r11.7/compiler.31442593_0

```

### What version are you seeing the problem on?

v2.0

### How to reproduce the bug

```python
check above
```

### Error messages and logs

```
# Error messages and logs here please
```
check above

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

```
(zephyr) mona@ard-gpu-01:~/zephyr/python/zephyr$ python collect_env_details.py
<details>
  <summary>Current environment</summary>

* CUDA:
	- GPU:
		- NVIDIA GeForce RTX 3080 Laptop GPU
	- available:         True
	- version:           11.7
* Lightning:
	- lightning:         2.0.2
	- lightning-cloud:   0.5.36
	- lightning-utilities: 0.8.0
	- pytorch-lightning: 2.0.2
	- torch:             1.13.0+cu117
	- torchmetrics:      0.11.4
	- torchtext:         0.14.0
	- torchvision:       0.14.0+cu117
* Packages:
	- aiohttp:           3.8.4
	- aiosignal:         1.3.1
	- anyio:             3.7.0
	- appdirs:           1.4.4
	- arrow:             1.2.3
	- astropy:           5.3
	- async-timeout:     4.0.2
	- attrs:             23.1.0
	- beautifulsoup4:    4.12.2
	- blessed:           1.20.0
	- certifi:           2023.5.7
	- charset-normalizer: 3.1.0
	- click:             8.1.3
	- cloudpickle:       2.2.1
	- contourpy:         1.0.7
	- croniter:          1.3.15
	- cycler:            0.11.0
	- dask:              2023.5.1
	- dateutils:         0.6.12
	- deepdiff:          6.3.0
	- exceptiongroup:    1.1.1
	- fastapi:           0.88.0
	- fonttools:         4.39.4
	- freetype-py:       2.4.0
	- frozenlist:        1.3.3
	- fsspec:            2023.5.0
	- h11:               0.14.0
	- idna:              3.4
	- imageio:           2.30.0
	- importlib-metadata: 6.6.0
	- importlib-resources: 5.12.0
	- inquirer:          3.1.3
	- itsdangerous:      2.1.2
	- jinja2:            3.1.2
	- kiwisolver:        1.4.4
	- lazy-loader:       0.2
	- lightning:         2.0.2
	- lightning-cloud:   0.5.36
	- lightning-utilities: 0.8.0
	- locket:            1.0.0
	- mako:              1.2.4
	- markdown-it-py:    2.2.0
	- markupsafe:        2.1.2
	- matplotlib:        3.7.1
	- mdurl:             0.1.2
	- multidict:         6.0.4
	- mvtec-halcon:      23050.0.0
	- networkx:          3.1
	- numpy:             1.22.3
	- ordered-set:       4.1.0
	- packaging:         23.1
	- partd:             1.4.0
	- pillow:            9.5.0
	- pip:               23.0.1
	- platformdirs:      3.5.1
	- plyfile:           0.9
	- pooch:             1.7.0
	- psutil:            5.9.5
	- pyamg:             5.0.0
	- pybind11:          2.9.2
	- pybind11-global:   2.10.4
	- pycuda:            2022.2.2
	- pydantic:          1.10.8
	- pyerfa:            2.0.0.3
	- pyglet:            2.0.7
	- pygments:          2.15.1
	- pyjwt:             2.7.0
	- pyopengl:          3.1.0
	- pyparsing:         3.0.9
	- pyrender:          0.1.45
	- python-dateutil:   2.8.2
	- python-editor:     1.0.4
	- python-multipart:  0.0.6
	- pytools:           2022.1.14
	- pytorch-lightning: 2.0.2
	- pytz:              2023.3
	- pywavelets:        1.4.1
	- pyyaml:            6.0
	- readchar:          4.0.5
	- requests:          2.31.0
	- rich:              13.4.1
	- scikit-image:      0.20.0
	- scipy:             1.9.1
	- setuptools:        67.8.0
	- simpleitk:         2.2.1
	- six:               1.16.0
	- sniffio:           1.3.0
	- soupsieve:         2.4.1
	- starlette:         0.22.0
	- starsessions:      1.3.0
	- tifffile:          2023.4.12
	- toolz:             0.12.0
	- torch:             1.13.0+cu117
	- torchmetrics:      0.11.4
	- torchtext:         0.14.0
	- torchvision:       0.14.0+cu117
	- tqdm:              4.65.0
	- traitlets:         5.9.0
	- trimesh:           3.21.7
	- typing-extensions: 4.6.2
	- urllib3:           2.0.2
	- uvicorn:           0.22.0
	- wcwidth:           0.2.6
	- websocket-client:  1.5.2
	- websockets:        11.0.3
	- wheel:             0.38.4
	- yarl:              1.9.2
	- zephyr:            0.1.dev0
	- zipp:              3.15.0
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- ELF
	- processor:         x86_64
	- python:            3.9.16
	- release:           5.19.0-42-generic
	- version:           #43~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Apr 21 16:51:08 UTC 2

</details>
```
</details>

### More info

check above

**Comment by monajalal** [comment]
downgraded to this version and it's fixed

```
(zephyr) mona@ard-gpu-01:~/zephyr$ python
Python 3.9.16 (main, Mar  8 2023, 14:00:05) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pytorch_lightning
>>> pytorch_lightning.__version__
'0.7.6'
```
