### ISSUE TITLE
Cannot import pytorch_lightning module: 'torch' has no attribute 'autocast'

### ISSUE THREAD

**Issue by SaulAryehKohn** [Lightning-AI/lightning#17741]
### Bug description

I'm on `torch=='1.9.0+cu111'`, `torchvision=='0.10.0+cu111'` and attempting to use `pytorch-lightning==2.0.2` with Python 3.8.10.

When I attempt to import the module, I get this error:
```
Python 3.8.10 (default, Mar 13 2023, 10:26:41) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pytorch_lightning
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/saul/Documents/Github/ai-model-zoo/ml/.venv/lib/python3.8/site-packages/pytorch_lightning/__init__.py", line 25, in <module>
    from lightning_fabric.utilities.seed import seed_everything  # noqa: E402
  File "/home/saul/Documents/Github/ai-model-zoo/ml/.venv/lib/python3.8/site-packages/lightning_fabric/__init__.py", line 29, in <module>
    from lightning_fabric.fabric import Fabric  # noqa: E402
  File "/home/saul/Documents/Github/ai-model-zoo/ml/.venv/lib/python3.8/site-packages/lightning_fabric/fabric.py", line 32, in <module>
    from lightning_fabric.plugins import Precision  # avoid circular imports: # isort: split
  File "/home/saul/Documents/Github/ai-model-zoo/ml/.venv/lib/python3.8/site-packages/lightning_fabric/plugins/__init__.py", line 18, in <module>
    from lightning_fabric.plugins.precision.amp import MixedPrecision
  File "/home/saul/Documents/Github/ai-model-zoo/ml/.venv/lib/python3.8/site-packages/lightning_fabric/plugins/precision/__init__.py", line 14, in <module>
    from lightning_fabric.plugins.precision.amp import MixedPrecision
  File "/home/saul/Documents/Github/ai-model-zoo/ml/.venv/lib/python3.8/site-packages/lightning_fabric/plugins/precision/amp.py", line 29, in <module>
    class MixedPrecision(Precision):
  File "/home/saul/Documents/Github/ai-model-zoo/ml/.venv/lib/python3.8/site-packages/lightning_fabric/plugins/precision/amp.py", line 96, in MixedPrecision
    def _autocast_context_manager(self) -> torch.autocast:
AttributeError: module 'torch' has no attribute 'autocast'
```

I can't find any substantial reporting of this bug online (for any python module that uses torch!).

### What version are you seeing the problem on?

v2.0

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow): n/a
#- PyTorch Lightning Version (e.g., 1.5.0): 2.0.2
#- Lightning App Version (e.g., 0.5.2): n/a
#- PyTorch Version (e.g., 2.0):1.9.1+cu111
#- Python version (e.g., 3.9): 3.8
#- OS (e.g., Linux): Linux Ubuntu
#- CUDA/cuDNN version: 12.0
#- GPU models and configuration: NVIDIA RTX A6000
#- How you installed Lightning(`conda`, `pip`, source): poetry
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

**Comment by leng-yue** [comment]
According to the [requirements](https://github.com/Lightning-AI/lightning/blob/master/requirements/pytorch/base.txt), the latest version of Lightning only supports `torch >=1.11.0, <=2.0.0`. However, it's worth noting that `torch.autocast` was introduced in torch version [1.10.0](https://pytorch.org/docs/1.10/amp.html?highlight=torch%20autocast#torch.autocast), which was released in October 2021.

**Comment by awaelchli** [comment]
That's correct @leng-yue. @SaulAryehKohn Could you please try again by upgrading torch?

**Comment by SaulAryehKohn** [comment]
Updating to `torch 1.10.0` was the fix! And I can go higher to a supported version of torch for Lightning. Thanks!
