### ISSUE TITLE
Custom batch sampler leads to an error

### ISSUE THREAD

**Issue by vadim0x60** [Lightning-AI/lightning#17793]
### Bug description

I am using a custom batch sampler with variable batch sizes. Lightning tries to read `batch_sampler.batch_size` parameter and fails

### What version are you seeing the problem on?

v2.0

### How to reproduce the bug

```python
class BatchSamplerForPaddingHaters(Sampler):
    def __init__(self, lengths, sampler):
        self.sampler = sampler
        self.lengths = lengths
        self.batch_sizes = []

        cur_len = lengths[0]
        cur_bs = 0
        for l in lengths:
            if l != cur_len:
                self.batch_sizes.append(cur_bs)
                cur_bs = 0
            cur_bs += 1
            cur_len = l

    def __iter__(self):
        sampler_iter = iter(self.sampler)
        for bs in self.batch_sizes:
            yield [next(sampler_iter) for _ in range(bs)]

    def __len__(self):
        return len(self.batch_sizes)

class MyDataModule(L.LightningDataModule):
    def train_dataloader(self):
        train_sampler = BatchSamplerForPaddingHaters(self.train_data.lengths, 
                                                          SequentialSampler(self.train_data))
        return DataLoader(self.train_data, num_workers=12, 
                          prefetch_factor=256, batch_sampler=train_sampler)

    def val_dataloader(self):
        test_sampler = BatchSamplerForPaddingHaters(self.test_data.lengths,
                                                         SequentialSampler(self.test_data))
        return DataLoader(self.test_data, num_workers=2, 
                          prefetch_factor=16, batch_sampler=test_sampler)

trainer_opts = {
        'accelerator': 'gpu',
        'log_every_n_steps': 1,
        'gradient_clip_val': GRAD_CLIP_VAL,
        'logger': loggers.WandbLogger(project='icat', log_model=True),
        'callbacks': [callbacks.ModelCheckpoint(monitor='val_loss',mode='min')],
        'devices': 2,
        'num_nodes': 1,
        'strategy': 'ddp'
    }

  trainer = L.Trainer(**trainer_opts)
  trainer.fit(model, data)
```

### Error messages and logs

```
Traceback (most recent call last):
  File "/home/mcs001/20194474/code/mimicseq/learn.py", line 93, in <module>
    train_icat()
  File "/home/mcs001/20194474/.local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/mcs001/20194474/.local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/mcs001/20194474/.local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mcs001/20194474/.local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/cm/shared/apps/Anaconda/2022.10/pth3.9/lib/python3.9/site-packages/tenacity/__init__.py", line 324, in wrapped_f
    return self(f, *args, **kw)
  File "/cm/shared/apps/Anaconda/2022.10/pth3.9/lib/python3.9/site-packages/tenacity/__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "/cm/shared/apps/Anaconda/2022.10/pth3.9/lib/python3.9/site-packages/tenacity/__init__.py", line 349, in iter
    return fut.result()
  File "/cm/shared/apps/Anaconda/2022.10/pth3.9/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/cm/shared/apps/Anaconda/2022.10/pth3.9/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/cm/shared/apps/Anaconda/2022.10/pth3.9/lib/python3.9/site-packages/tenacity/__init__.py", line 407, in __call__
    result = fn(*args, **kwargs)
  File "/home/mcs001/20194474/code/mimicseq/learn.py", line 88, in train_icat
    trainer.fit(model, data)
  File "/home/mcs001/20194474/.local/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 531, in fit
    call._call_and_handle_interrupt(
  File "/home/mcs001/20194474/.local/lib/python3.9/site-packages/lightning/pytorch/trainer/call.py", line 41, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/home/mcs001/20194474/.local/lib/python3.9/site-packages/lightning/pytorch/strategies/launchers/subprocess_script.py", line 91, in launch
    return function(*args, **kwargs)
  File "/home/mcs001/20194474/.local/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 570, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/mcs001/20194474/.local/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 975, in _run
    results = self._run_stage()
  File "/home/mcs001/20194474/.local/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 1016, in _run_stage
    self._run_sanity_check()
  File "/home/mcs001/20194474/.local/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 1045, in _run_sanity_check
    val_loop.run()
  File "/home/mcs001/20194474/.local/lib/python3.9/site-packages/lightning/pytorch/loops/utilities.py", line 177, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/home/mcs001/20194474/.local/lib/python3.9/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 98, in run
    self.setup_data()
  File "/home/mcs001/20194474/.local/lib/python3.9/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 169, in setup_data
    dl = _process_dataloader(trainer, dl)
  File "/home/mcs001/20194474/.local/lib/python3.9/site-packages/lightning/pytorch/trainer/connectors/data_connector.py", line 489, in _process_dataloader
    dataloader = trainer._data_connector._prepare_dataloader(dataloader, shuffle=is_shuffled, mode=stage)
  File "/home/mcs001/20194474/.local/lib/python3.9/site-packages/lightning/pytorch/trainer/connectors/data_connector.py", line 200, in _prepare_dataloader
    return _update_dataloader(dataloader, sampler, mode=mode)
  File "/home/mcs001/20194474/.local/lib/python3.9/site-packages/lightning/pytorch/utilities/data.py", line 132, in _update_dataloader
    dl_args, dl_kwargs = _get_dataloader_init_args_and_kwargs(dataloader, sampler, mode)
  File "/home/mcs001/20194474/.local/lib/python3.9/site-packages/lightning/pytorch/utilities/data.py", line 192, in _get_dataloader_init_args_and_kwargs
    dl_kwargs.update(_dataloader_init_kwargs_resolve_sampler(dataloader, sampler, mode, disallow_batch_sampler))
  File "/home/mcs001/20194474/.local/lib/python3.9/site-packages/lightning/pytorch/utilities/data.py", line 296, in _dataloader_init_kwargs_resolve_sampler
    batch_size=batch_sampler.batch_size,
AttributeError: 'BatchSamplerForPaddingHaters' object has no attribute 'batch_size'
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow): Trainer, LightiningDataModule
#- PyTorch Lightning Version (e.g., 1.5.0): 2.0.3
#- Lightning App Version (e.g., 0.5.2):2.0.3
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9): 3.9
#- OS (e.g., Linux):  Linux-3.10.0-1160.83.1.el7.x86_64-x86_64-with-glibc2.17
#- CUDA/cuDNN version: 11.8.0
#- GPU models and configuration: 2 Tesla V100-PCIE-16GB
#- How you installed Lightning(`conda`, `pip`, source): pip
#- Running environment of LightningApp (e.g. local, cloud): slurm cluster
```

</details>

**Comment by ZeguanXiao** [comment]
Similar issue in 1.8.4 when I try to use a custom batch sampler in `predict_dataloader()`.

**Comment by vadim0x60** [comment]
I am afraid I don't understand the source code of lightning well enough to fix it myself at this point.
The model is `torch.TransformerEncoder`
Given that @ZeguanXiao ran into the same, this is not a user-specific issue.

**Comment by ManoBharathi93** [comment]
@vadim0x60 can you share the full code that you implemented  ?

**Comment by ManoBharathi93** [comment]
Found it! .. You didn't inherit from base class to `MyDataModule` class. You missed constructor which requires `train_data`, `test_data`, and `batch_size` arguments.

I have trained on LSTM it's work fine for me using batch sampler.
```import torch
import torch.nn.functional as F
from torch.utils.data import Dataset, Sampler, SequentialSampler, DataLoader
from typing import List, Tuple
import pytorch_lightning as L
from pytorch_lightning import loggers, callbacks

GRAD_CLIP_VAL = 1.0

class MyDataset(Dataset):
    def __init__(self, data: List[Tuple[List[int], int]]):
        self.data = data

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        x, y = self.data[idx]
        return torch.LongTensor(x), torch.LongTensor([y])

class BatchSamplerForPaddingHaters(Sampler):
    def __init__(self, lengths, sampler):
        self.sampler = sampler
        self.lengths = lengths
        self.batch_sizes = []

        cur_len = lengths[0]
        cur_bs = 0
        for l in lengths:
            if l != cur_len:
                self.batch_sizes.append(cur_bs)
                cur_bs = 0
            cur_bs += 1
            cur_len = l

    def __iter__(self):
        sampler_iter = iter(self.sampler)
        for bs in self.batch_sizes:
            yield [next(sampler_iter) for _ in range(bs)]

    def __len__(self):
        return len(self.batch_sizes)

class MyDataModule(L.LightningDataModule):
    def __init__(self, train_data, test_data, batch_size=32):
        super().__init__()
        self.train_data = train_data
        self.test_data = test_data
        self.batch_size = batch_size

    def prepare_data(self):
        pass

    def setup(self, stage=None):
        pass

    def train_dataloader(self):
        train_sampler = BatchSamplerForPaddingHaters(self.train_data.lengths, 
                                                          SequentialSampler(self.train_data))
        return DataLoader(self.train_data, num_workers=12, 
                          prefetch_factor=256, batch_sampler=train_sampler)

    def val_dataloader(self):
        test_sampler = BatchSamplerForPaddingHaters(self.test_data.lengths,
                                                         SequentialSampler(self.test_data))
        return DataLoader(self.test_data, num_workers=2, 
                          prefetch_factor=16, batch_sampler=test_sampler)


class MyModel(L.LightningModule):
    def __init__(self, vocab_size: int, embedding_dim: int, hidden_dim: int, num_classes: int):
        super().__init__()
        self.embeddings = torch.nn.Embedding(vocab_size, embedding_dim)
        self.lstm = torch.nn.LSTM(embedding_dim, hidden_dim, num_layers=2, batch_first=True)
        self.fc = torch.nn.Linear(hidden_dim, num_classes)

    def forward(self, inputs):
        x = self.embeddings(inputs)
        lstm_out, _ = self.lstm(x)
        out = self.fc(lstm_out[:, -1, :])
        return out

    def training_step(self, batch, batch_idx):
        x, y = batch
        logits = self.forward(x)
        loss = F.cross_entropy(logits, y.squeeze())
        self.log('train_loss', loss)
        return loss

    def validation_step(self, batch, batch_idx):
        x, y = batch
        logits = self.forward(x)
        loss = F.cross_entropy(logits, y.squeeze())
        self.log('val_loss', loss)
        preds = torch.argmax(logits, dim=1)
        acc = torch.sum(preds == y.squeeze()).float() / y.size(0)
        self.log('val_acc', acc)
        return {'val_loss': loss, 'val_acc': acc}

    def configure_optimizers(self):
        optimizer = torch.optim.Adam(self.parameters())
        return optimizer

train_data = MyDataset([(list(range(i)), i % 3) for i in range(1, 1001)])
test_data = MyDataset([(list(range(i)), i % 3) for i in range(1001, 2001)])

data = MyDataModule(train_data, test_data)
model = MyModel(vocab_size=1000, embedding_dim=32, hidden_dim=64, num_classes=3)

trainer_opts = {
        'accelerator': 'gpu',
        'log_every_n_steps': 1,
        'gradient_clip_val': GRAD_CLIP_VAL,
        'logger': loggers.WandbLogger(project='icat', log_model=True),
        'callbacks': [callbacks.ModelCheckpoint(monitor='val_loss',mode='min')],
        'devices': 2,
        'num_nodes': 1,
        'distributed_backend': 'ddp'
    }

trainer = L.Trainer(**trainer_opts)
trainer.fit(model, data)
```
It works fine..

**Comment by ManoBharathi93** [comment]
@vadim0x60 
Correct way of Implementing `MyDataModule` : 
```
class MyDataModule(L.LightningDataModule):
def __init__(self, train_data, test_data, batch_size=32):
        super().__init__()
        self.train_data = train_data
        self.test_data = test_data
        self.batch_size = batch_size
    def train_dataloader(self):
        train_sampler = BatchSamplerForPaddingHaters(self.train_data.lengths, 
                                                          SequentialSampler(self.train_data))
        return DataLoader(self.train_data, num_workers=12, 
                          prefetch_factor=256, batch_sampler=train_sampler)

    def val_dataloader(self):
        test_sampler = BatchSamplerForPaddingHaters(self.test_data.lengths,
                                                         SequentialSampler(self.test_data))
        return DataLoader(self.test_data, num_workers=2, 
                          prefetch_factor=16, batch_sampler=test_sampler)
```
If it fixes your problem kindly close this issue ! 
Thank you

**Comment by vadim0x60** [comment]
I do inherit from `LightningDataModule`. And I actually have `super().__init__()` in my code (though not in the simplifiedsnippet I posted here), it doesn't help. I cannot include `batch_size` in the constructor, because my custom batch sampler has a variable batch size.

**Comment by alealv** [comment]
Facing the same issue. I also have a dynamic batch size 😟

**Comment by awaelchli** [comment]
Hi everyone. If you set `Trainer(use_distributed_sampler=False)` you shouldn't get this attribute error, please give it a try. I've opened a PR with better error messaging that explains to the user what is happening and how they can make it work. With a custom batch sampler, you are taking away control from the Trainer and will have to handle distributed sampling correctly within your sampler (that's why the explicit `use_distributed_sampler=False` is necessary).

**Comment by cataclysmus** [comment]
Hi, I am not sure that the problem was fixed. I still have this issue with `use_distributed_sampler=False`. I looked at code of `_prepare_dataloader` in `data_connector.py` and found that `requires_distributed_sampler` does not turn off `_update_dataloader` in case of prediction

```       if (
            self._requires_distributed_sampler(dataloader)  # sets the distributed sampler
            or mode == RunningStage.PREDICTING  # to track indices for the predictions
            or is_ipu
        ):
            sampler = self._resolve_sampler(dataloader, shuffle=shuffle, mode=mode)
            return _update_dataloader(dataloader, sampler, mode=mode)
```

**Comment by cr-assafbendavid** [comment]
Hi,
I have also encountered this issue when using `Trainer.predict`.

@cataclysmus, have you managed to find a workaround?
@awaelchli, can this issue please be reopened, or should I open a new issue specifically for the case of using `predict`?

**Comment by cataclysmus** [comment]
@cr-assafbendavid  I decided not to touch the lightning code. Instead I replace my dataloader with the standard one from torch, fortunately, my task allows me to it for a predict method.
