### ISSUE TITLE
import pytorch_lightning as pl

### ISSUE THREAD

**Issue by lhwjsj** [Lightning-AI/lightning#17850]
### Bug description

I did pip install pytorch-lightning in Ubuntu
when i try 'import pytorch_lightning as pl'

'''
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/miniconda3/lib/python3.7/site-packages/pytorch_lightning/__init__.py", line 35, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/opt/miniconda3/lib/python3.7/site-packages/pytorch_lightning/callbacks/__init__.py", line 28, in <module>
    from pytorch_lightning.callbacks.pruning import ModelPruning
  File "/opt/miniconda3/lib/python3.7/site-packages/pytorch_lightning/callbacks/pruning.py", line 31, in <module>
    from pytorch_lightning.core.module import LightningModule
  File "/opt/miniconda3/lib/python3.7/site-packages/pytorch_lightning/core/__init__.py", line 16, in <module>
    from pytorch_lightning.core.module import LightningModule
  File "/opt/miniconda3/lib/python3.7/site-packages/pytorch_lightning/core/module.py", line 52, in <module>
    from pytorch_lightning.loggers import Logger
  File "/opt/miniconda3/lib/python3.7/site-packages/pytorch_lightning/loggers/__init__.py", line 22, in <module>
    from pytorch_lightning.loggers.wandb import WandbLogger  # noqa: F401
  File "/opt/miniconda3/lib/python3.7/site-packages/pytorch_lightning/loggers/wandb.py", line 37, in <module>
    from wandb.sdk.lib import RunDisabled
ImportError: cannot import name 'RunDisabled' from 'wandb.sdk.lib' (/opt/miniconda3/lib/python3.7/site-packages/wandb/sdk/lib/__init__.py)

'''
what happened?

### What version are you seeing the problem on?

v1.9

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

**Comment by awaelchli** [comment]
Hi @lhwjsj 
Which version of wandb is installed here? If it is too old, try to upgrade it: `pip install -U wandb`

**Comment by lhwjsj** [comment]
> Hi @lhwjsj Which version of wandb is installed here? If it is too old, try to upgrade it: `pip install -U wandb`

wandb is 0.10.12

**Comment by lhwjsj** [comment]
I upgrade wandb, then it works
