### ISSUE TITLE
DeepSpeed `ipg_index` issue in Fabric

### ISSUE THREAD

**Issue by rasbt** [Lightning-AI/lightning#17856]
### Bug description

Fabric fails with recent deepspeed versions (whereas it works fine with DDP); I tried both deepspeed 0.9.3 and 0.9.4.

### What version are you seeing the problem on?

master

### How to reproduce the bug

```python
See the code files attached
```

### Error messages and logs

```
ime to load utils op: 0.0003647804260253906 seconds
Using /home/sebastian/.cache/torch_extensions/py39_cu118 as PyTorch extensions root...
No modifications detected for re-loaded extension module utils, skipping build step...
Loading extension module utils...
Time to load utils op: 0.000324249267578125 seconds
Using /home/sebastian/.cache/torch_extensions/py39_cu118 as PyTorch extensions root...
No modifications detected for re-loaded extension module utils, skipping build step...
Loading extension module utils...
Time to load utils op: 0.0006425380706787109 seconds
/home/sebastian/miniforge3/envs/lit-llama/lib/python3.9/site-packages/torch/optim/optimizer.py:242: UserWarning: 'has_cuda' is deprecated, please use 'torch.backends.cuda.is_built()'
  if not is_compiling() and torch.has_cuda and torch.cuda.is_available():
Using /home/sebastian/.cache/torch_extensions/py39_cu118 as PyTorch extensions root...
No modifications detected for re-loaded extension module utils, skipping build step...
Loading extension module utils...
Time to load utils op: 0.0004565715789794922 seconds
Traceback (most recent call last):
  File "/home/sebastian/Developer/cvpr2023/06_fabric-vit-mixed-deepspeed.py", line 107, in <module>
    train(
  File "/home/sebastian/Developer/cvpr2023/06_fabric-vit-mixed-deepspeed.py", line 30, in train
    loss.backward()
  File "/home/sebastian/miniforge3/envs/lit-llama/lib/python3.9/site-packages/torch/_tensor.py", line 491, in backward
    torch.autograd.backward(
  File "/home/sebastian/miniforge3/envs/lit-llama/lib/python3.9/site-packages/torch/autograd/__init__.py", line 204, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/sebastian/miniforge3/envs/lit-llama/lib/python3.9/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 810, in reduce_partition_and_remove_grads
    self.reduce_ready_partitions_and_remove_grads(param, i)
  File "/home/sebastian/miniforge3/envs/lit-llama/lib/python3.9/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 1258, in reduce_ready_partitions_and_remove_grads
    self.reduce_independent_p_g_buckets_and_remove_grads(param, i)
  File "/home/sebastian/miniforge3/envs/lit-llama/lib/python3.9/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 853, in reduce_independent_p_g_buckets_and_remove_grads
    new_grad_tensor = self.ipg_buffer[self.ipg_index].narrow(0, self.elements_in_ipg_bucket, param.numel())
AttributeError: 'DeepSpeedZeroOptimizer' object has no attribute 'ipg_index'
Traceback (most recent call last):
  File "/home/sebastian/Developer/cvpr2023/06_fabric-vit-mixed-deepspeed.py", line 107, in <module>
    train(
  File "/home/sebastian/Developer/cvpr2023/06_fabric-vit-mixed-deepspeed.py", line 30, in train
    loss.backward()
  File "/home/sebastian/miniforge3/envs/lit-llama/lib/python3.9/site-packages/torch/_tensor.py", line 491, in backward
    torch.autograd.backward(
  File "/home/sebastian/miniforge3/envs/lit-llama/lib/python3.9/site-packages/torch/autograd/__init__.py", line 204, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/sebastian/miniforge3/envs/lit-llama/lib/python3.9/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 810, in reduce_partition_and_remove_grads
    self.reduce_ready_partitions_and_remove_grads(param, i)
  File "/home/sebastian/miniforge3/envs/lit-llama/lib/python3.9/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 1258, in reduce_ready_partitions_and_remove_grads
    self.reduce_independent_p_g_buckets_and_remove_grads(param, i)
  File "/home/sebastian/miniforge3/envs/lit-llama/lib/python3.9/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 853, in reduce_independent_p_g_buckets_and_remove_grads
    new_grad_tensor = self.ipg_buffer[self.ipg_index].narrow(0, self.elements_in_ipg_bucket, param.numel())
AttributeError: 'DeepSpeedZeroOptimizer' object has no attribute 'ipg_index'
Traceback (most recent call last):
  File "/home/sebastian/Developer/cvpr2023/06_fabric-vit-mixed-deepspeed.py", line 107, in <module>
    train(
  File "/home/sebastian/Developer/cvpr2023/06_fabric-vit-mixed-deepspeed.py", line 30, in train
    loss.backward()
  File "/home/sebastian/miniforge3/envs/lit-llama/lib/python3.9/site-packages/torch/_tensor.py", line 491, in backward
    torch.autograd.backward(
  File "/home/sebastian/miniforge3/envs/lit-llama/lib/python3.9/site-packages/torch/autograd/__init__.py", line 204, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/sebastian/miniforge3/envs/lit-llama/lib/python3.9/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 810, in reduce_partition_and_remove_grads
    self.reduce_ready_partitions_and_remove_grads(param, i)
  File "/home/sebastian/miniforge3/envs/lit-llama/lib/python3.9/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 1258, in reduce_ready_partitions_and_remove_grads
    self.reduce_independent_p_g_buckets_and_remove_grads(param, i)
  File "/home/sebastian/miniforge3/envs/lit-llama/lib/python3.9/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 853, in reduce_independent_p_g_buckets_and_remove_grads
    new_grad_tensor = self.ipg_buffer[self.ipg_index].narrow(0, self.elements_in_ipg_bucket, param.numel())
AttributeError: 'DeepSpeedZeroOptimizer' object has no attribute 'ipg_index'
Traceback (most recent call last):
  File "/home/sebastian/Developer/cvpr2023/06_fabric-vit-mixed-deepspeed.py", line 107, in <module>
    train(
  File "/home/sebastian/Developer/cvpr2023/06_fabric-vit-mixed-deepspeed.py", line 30, in train
    loss.backward()
  File "/home/sebastian/miniforge3/envs/lit-llama/lib/python3.9/site-packages/torch/_tensor.py", line 491, in backward
    torch.autograd.backward(
  File "/home/sebastian/miniforge3/envs/lit-llama/lib/python3.9/site-packages/torch/autograd/__init__.py", line 204, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/sebastian/miniforge3/envs/lit-llama/lib/python3.9/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 810, in reduce_partition_and_remove_grads
    self.reduce_ready_partitions_and_remove_grads(param, i)
  File "/home/sebastian/miniforge3/envs/lit-llama/lib/python3.9/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 1258, in reduce_ready_partitions_and_remove_grads
    self.reduce_independent_p_g_buckets_and_remove_grads(param, i)
  File "/home/sebastian/miniforge3/envs/lit-llama/lib/python3.9/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 853, in reduce_independent_p_g_buckets_and_remove_grads
    new_grad_tensor = self.ipg_buffer[self.ipg_index].narrow(0, self.elements_in_ipg_bucket, param.numel())
AttributeError: 'DeepSpeedZeroOptimizer' object has no attribute 'ipg_index'
```

### Environment

<details>
  <summary>Current environment</summary>

```
        - asttokens:         2.2.1
        - async-timeout:     4.0.2
        - attrs:             22.2.0
        - babel:             2.12.1
        - backcall:          0.2.0
        - backports.functools-lru-cache: 1.6.4
        - beautifulsoup4:    4.12.2
        - bitsandbytes:      0.39.0
        - bleach:            6.0.0
        - blessed:           1.20.0
        - brotlipy:          0.7.0
        - certifi:           2022.12.7
        - cffi:              1.15.1
        - charset-normalizer: 3.1.0
        - click:             8.1.3
        - cmake:             3.26.3
        - colorama:          0.4.6
        - comm:              0.1.3
        - croniter:          1.3.14
        - cryptography:      40.0.2
        - datasets:          2.11.0
        - dateutils:         0.6.12
        - debugpy:           1.6.7
        - decorator:         5.1.1
        - deepdiff:          6.3.0
        - deepspeed:         0.9.4
        - defusedxml:        0.7.1
        - dill:              0.3.6
        - entrypoints:       0.4
        - exceptiongroup:    1.1.1
        - executing:         1.2.0
        - fastapi:           0.88.0
        - fastjsonschema:    2.16.3
        - filelock:          3.12.0
        - flit-core:         3.8.0
        - frozenlist:        1.3.3
        - fsspec:            2023.4.0
        - h11:               0.14.0
        - hjson:             3.1.0
        - huggingface-hub:   0.13.4
        - idna:              3.4
        - importlib-metadata: 6.6.0
        - importlib-resources: 5.12.0
        - iniconfig:         2.0.0
        - inquirer:          3.1.3
        - ipykernel:         6.22.0
        - ipython:           8.12.0
        - ipython-genutils:  0.2.0
        - ipywidgets:        8.0.6
        - itsdangerous:      2.1.2
        - jedi:              0.18.2
        - jinja2:            3.1.2
        - joblib:            1.2.0
        - json5:             0.9.5
        - jsonargparse:      4.21.0
        - jsonschema:        4.17.3
        - jupyter-client:    8.2.0
        - jupyter-core:      5.3.0
        - jupyter-events:    0.6.3
        - jupyter-server:    2.5.0
        - jupyter-server-terminals: 0.4.4
        - jupyterlab:        3.5.3
        - jupyterlab-pygments: 0.2.2
        - jupyterlab-server: 2.22.1
        - jupyterlab-widgets: 3.0.7
        - lightning:         2.1.0.dev0
        - lightning-cloud:   0.5.34
        - lightning-utilities: 0.8.0
        - lit:               16.0.1
        - markdown-it-py:    2.2.0
        - markupsafe:        2.1.2
        - matplotlib-inline: 0.1.6
        - mdurl:             0.1.2
        - mistune:           2.0.5
        - mpmath:            1.3.0
        - multidict:         6.0.4
        - multiprocess:      0.70.14
        - nbclassic:         0.5.5
        - nbclient:          0.7.3
        - nbconvert:         7.3.1
        - nbformat:          5.8.0
        - nest-asyncio:      1.5.6
        - networkx:          3.1
        - ninja:             1.11.1
        - notebook:          6.5.4
        - notebook-shim:     0.2.2
        - numpy:             1.24.2
        - nvidia-cublas-cu11: 11.10.3.66
        - nvidia-cuda-cupti-cu11: 11.7.101
        - nvidia-cuda-nvrtc-cu11: 11.7.99
        - nvidia-cuda-runtime-cu11: 11.7.99
        - nvidia-cudnn-cu11: 8.5.0.96
        - nvidia-cufft-cu11: 10.9.0.58
        - nvidia-curand-cu11: 10.2.10.91
        - nvidia-cusolver-cu11: 11.4.0.1
        - nvidia-cusparse-cu11: 11.7.4.91
        - nvidia-nccl-cu11:  2.14.3
        - nvidia-nvtx-cu11:  11.7.91
        - ordered-set:       4.1.0
        - packaging:         23.1
        - pandas:            2.0.0
        - pandocfilters:     1.5.0
        - parso:             0.8.3
        - pexpect:           4.8.0
        - pickleshare:       0.7.5
        - pillow:            9.3.0
        - pip:               23.1
        - pkgutil-resolve-name: 1.3.10
        - platformdirs:      3.2.0
        - pluggy:            1.0.0
        - prometheus-client: 0.16.0
        - prompt-toolkit:    3.0.38
        - psutil:            5.9.5
        - ptyprocess:        0.7.0
        - pure-eval:         0.2.2
        - py-cpuinfo:        9.0.0
        - pyarrow:           11.0.0
        - pycparser:         2.21
        - pydantic:          1.10.7
        - pygments:          2.15.1
        - pyjwt:             2.6.0
        - pyopenssl:         23.1.1
        - pyrsistent:        0.19.3
        - pysocks:           1.7.1
        - pytest:            7.3.1
        - python-dateutil:   2.8.2
        - python-editor:     1.0.4
        - python-json-logger: 2.0.7
        - python-multipart:  0.0.6
        - pytorch-lightning: 2.0.1.post0
        - pytorch-triton:    2.1.0+9820899b38
        - pytz:              2023.3
        - pyyaml:            6.0
        - pyzmq:             25.0.2
        - readchar:          4.0.5
        - regex:             2023.3.23
        - requests:          2.28.2
        - responses:         0.18.0
        - rfc3339-validator: 0.1.4
        - rfc3986-validator: 0.1.1
        - rich:              13.3.4
        - scikit-learn:      1.2.2
        - scipy:             1.10.1
        - send2trash:        1.8.0
        - sentencepiece:     0.1.98
        - setuptools:        67.7.1
        - six:               1.16.0
        - sniffio:           1.3.0
        - soupsieve:         2.3.2.post1
        - stack-data:        0.6.2
        - starlette:         0.22.0
        - starsessions:      1.3.0
        - sympy:             1.11.1
        - terminado:         0.17.1
        - threadpoolctl:     3.1.0
        - tinycss2:          1.2.1
        - tokenizers:        0.13.3
        - tomli:             2.0.1
        - torch:             2.1.0.dev20230612+cu118
        - torchaudio:        2.1.0.dev20230612+cu118
        - torchmetrics:      0.11.4
        - torchvision:       0.16.0.dev20230612+cu118
        - tornado:           6.3
        - tqdm:              4.65.0
        - traitlets:         5.9.0
        - transformers:      4.28.1
        - triton:            2.1.0
        - typing-extensions: 4.5.0
        - tzdata:            2023.3
        - urllib3:           1.26.15
        - uvicorn:           0.21.1
        - watermark:         2.3.1
        - wcwidth:           0.2.6
        - webencodings:      0.5.1
        - websocket-client:  1.5.1
        - websockets:        11.0.2
        - wheel:             0.40.0
        - widgetsnbextension: 4.0.7
        - xxhash:            3.2.0
        - yarl:              1.9.1
        - zipp:              3.15.0
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.9.16
        - release:           5.4.0-149-generic
        - version:           #166-Ubuntu SMP Tue Apr 18 16:51:45 UTC 2023

```

</details>

### More info

I attached 3 files to reproduce this.

- `requirements.txt` for the relevant package installation & info
- `local_utilities.py` are just some local utilities to load the dataset
- `05_fabric-vit-mixed-ddp.py` the code with DDP, which works fine
- `06_fabric-vit-mixed-deepspeed.py` the same code but switching DDP to DeepSpeed that causes the bug

[code.zip](https://github.com/Lightning-AI/lightning/files/11779519/code.zip)

cc @awaelchli @carmocca @justusschock

**Comment by awaelchli** [comment]
Thanks @rasbt for reporting this. I can reproduce using your code, thanks a lot!

I fixed it by replacing
```py
loss.backward()
```

with 

```py
fabric.backward(loss)
```
In Fabric, it is generally mandatory to convert this backward call precisely because of such strategies like DeepSpeed where the backward call is slightly different comparted to raw PyTorch semantics.

Let me know if that works for you too.

**Comment by rasbt** [comment]
Sorry for wasting your time @awaelchli , that was a pretty stupid bug & my fault! 

I guess the reason why I didn't look for it was that it actually worked with fsdp! Pretty lucky / unlucky coincidence, but I am glad that it's not an actual bug!

**Comment by npuichigo** [comment]
@rasbt I have same issue when training dcgan with fabric + deepspeed.
The official example works fine with deepspeed: https://github.com/microsoft/DeepSpeedExamples/blob/master/training/gan/gan_deepspeed_train.py

After adapting it to use fabric, the error is the same as above.
```
import torch
import torch.backends.cudnn as cudnn
import torch.nn as nn
import torch.utils.data
import torchvision.datasets as dset
import torchvision.transforms as transforms
import torchvision.utils as vutils
from torch.utils.tensorboard import SummaryWriter
from time import time

from lightning.fabric import Fabric
from gan_model import Generator, Discriminator, weights_init
from utils import get_argument_parser, set_seed, create_folder


def get_dataset(args):
    if torch.cuda.is_available() and not args.cuda:
        print("WARNING: You have a CUDA device, so you should probably run with --cuda")
    if args.dataroot is None and str(args.dataset).lower() != 'fake':
        raise ValueError("`dataroot` parameter is required for dataset \"%s\"" % args.dataset)
    if args.dataset in ['imagenet', 'folder', 'lfw']:
        # folder dataset
        dataset = dset.ImageFolder(root=args.dataroot,
                                transform=transforms.Compose([
                                    transforms.Resize(args.imageSize),
                                    transforms.CenterCrop(args.imageSize),
                                    transforms.ToTensor(),
                                    transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5)),
                                ]))
        nc=3
    elif args.dataset == 'lsun':
        classes = [ c + '_train' for c in args.classes.split(',')]
        dataset = dset.LSUN(root=args.dataroot, classes=classes,
                            transform=transforms.Compose([
                                transforms.Resize(args.imageSize),
                                transforms.CenterCrop(args.imageSize),
                                transforms.ToTensor(),
                                transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5)),
                            ]))
        nc=3
    elif args.dataset == 'cifar10':
        dataset = dset.CIFAR10(root=args.dataroot, download=True,
                            transform=transforms.Compose([
                                transforms.Resize(args.imageSize),
                                transforms.ToTensor(),
                                transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5)),
                            ]))
        nc=3
    elif args.dataset == 'mnist':
            dataset = dset.MNIST(root=args.dataroot, download=True,
                            transform=transforms.Compose([
                                transforms.Resize(args.imageSize),
                                transforms.ToTensor(),
                                transforms.Normalize((0.5,), (0.5,)),
                            ]))
            nc=1

    elif args.dataset == 'fake':
        dataset = dset.FakeData(image_size=(3, args.imageSize, args.imageSize),
                                transform=transforms.ToTensor())
        nc=3

    elif args.dataset == 'celeba':
        dataset = dset.ImageFolder(root=args.dataroot,
                           transform=transforms.Compose([
                               transforms.Resize(args.imageSize),
                               transforms.CenterCrop(args.imageSize),
                               transforms.ToTensor(),
                               transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5)),
                           ]))
        nc = 3

    assert dataset
    return dataset, nc

def train(args):
    writer = SummaryWriter(log_dir=args.tensorboard_path)
    create_folder(args.outf)
    set_seed(args.manualSeed)
    cudnn.benchmark = True
    dataset, nc = get_dataset(args)
    dataloader = torch.utils.data.DataLoader(dataset, batch_size=args.batchSize, shuffle=True, num_workers=int(args.workers))
    ngpu = 0
    nz = int(args.nz)
    ngf = int(args.ngf)
    ndf = int(args.ndf)

    netG = Generator(ngpu, ngf, nc, nz)
    netG.apply(weights_init)
    if args.netG != '':
        netG.load_state_dict(torch.load(args.netG))

    netD = Discriminator(ngpu, ndf, nc)
    netD.apply(weights_init)
    if args.netD != '':
        netD.load_state_dict(torch.load(args.netD))

    criterion = nn.BCELoss()

    real_label = 1
    fake_label = 0

    fabric = Fabric(accelerator="auto", devices=1, precision='16-mixed',
                    strategy="deepspeed_stage_1")
    fabric.launch()

    fixed_noise = torch.randn(args.batchSize, nz, 1, 1, device=fabric.device)

    # setup optimizer
    optimizerD = torch.optim.Adam(netD.parameters(), lr=args.lr, betas=(args.beta1, 0.999))
    optimizerG = torch.optim.Adam(netG.parameters(), lr=args.lr, betas=(args.beta1, 0.999))

    netD, optimizerD = fabric.setup(netD, optimizerD)
    netG, optimizerG = fabric.setup(netG, optimizerG)

    dataloader = fabric.setup_dataloaders(dataloader)

    torch.cuda.synchronize()
    start = time()
    for epoch in range(args.epochs):
        for i, data in enumerate(dataloader, 0):
            ############################
            # (1) Update D network: maximize log(D(x)) + log(1 - D(G(z)))
            ###########################
            # train with real
            netD.zero_grad()
            real = data[0]
            batch_size = real.size(0)
            label = torch.full((batch_size,), real_label, dtype=real.dtype, device=fabric.device)
            output = netD(real)
            errD_real = criterion(output, label)
            fabric.backward(errD_real, model=netD)
            D_x = output.mean().item()

            # train with fake
            noise = torch.randn(batch_size, nz, 1, 1, device=fabric.device)
            fake = netG(noise)
            label.fill_(fake_label)
            output = netD(fake.detach())
            errD_fake = criterion(output, label)
            fabric.backward(errD_fake, model=netD)
            D_G_z1 = output.mean().item()
            errD = errD_real + errD_fake
            optimizerD.step()

            ############################
            # (2) Update G network: maximize log(D(G(z)))
            ###########################
            netG.zero_grad()
            label.fill_(real_label)  # fake labels are real for generator cost
            output = netD(fake)
            errG = criterion(output, label)
            fabric.backward(errG, model=netG)
            D_G_z2 = output.mean().item()
            optimizerG.step()

            print('[%d/%d][%d/%d] Loss_D: %.4f Loss_G: %.4f D(x): %.4f D(G(z)): %.4f / %.4f'
                % (epoch, args.epochs, i, len(dataloader),
                    errD.item(), errG.item(), D_x, D_G_z1, D_G_z2))
            writer.add_scalar("Loss_D", errD.item(), epoch*len(dataloader)+i)
            writer.add_scalar("Loss_G", errG.item(), epoch*len(dataloader)+i)
            if i % 100 == 0:
                vutils.save_image(real,
                        '%s/real_samples.png' % args.outf,
                        normalize=True)
                fake = netG(fixed_noise)
                vutils.save_image(fake.detach(),
                        '%s/fake_samples_epoch_%03d.png' % (args.outf, epoch),
                        normalize=True)

        # do checkpointing
        #torch.save(netG.state_dict(), '%s/netG_epoch_%d.pth' % (args.outf, epoch))
        #torch.save(netD.state_dict(), '%s/netD_epoch_%d.pth' % (args.outf, epoch))
    torch.cuda.synchronize()
    stop = time()
    print(f"total wall clock time for {args.epochs} epochs is {stop-start} secs")

def main():
    parser = get_argument_parser()
    args = parser.parse_args()
    train(args)

if __name__ == "__main__":
    main()
```
