### ISSUE TITLE
Importing lightning implicitly sets multiproecssing context

### ISSUE THREAD

**Issue by function2-llx** [Lightning-AI/lightning#18115]
### Bug description

Importing lightning in the code will implicitly sets multiproecssing context, which disables the user to set multiprocessing start method manually with `torch.multiprocessing.set_start_method` (unless with `force=True`).

### What version are you seeing the problem on?

v2.0

### How to reproduce the bug

```python
import lightning
import torch
torch.multiprocessing.set_start_method('spawn')
```

### Error messages and logs

```
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    torch.multiprocessing.set_start_method('spawn')
  File ".../multiprocessing/context.py", line 247, in set_start_method
    raise RuntimeError('context has already been set')
RuntimeError: context has already been set
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- PyTorch Lightning Version (e.g., 1.5.0): 2.0.5
#- PyTorch Version (e.g., 2.0): 2.0.1
#- Python version (e.g., 3.9): 3.11.4
#- OS (e.g., Linux): Linux
#- How you installed Lightning(`conda`, `pip`, source): pip
```

</details>

### More info

This piece of code firstly implicitly sets the multiprocessing context.

https://github.com/Lightning-AI/lightning/blob/dab373de548b352a69c8ea7251937fb4663038dc/src/lightning/app/perf/pdb.py#L20-L25

**Comment by function2-llx** [comment]
A simple workaround will be importing torch before lightning and set the start method in advance. However, the same error will occur when using multi-device training after calling `fabric.launch`.

**Comment by awaelchli** [comment]
@function2-llx Thanks, you are right, the multiprocessing lock is causing the context to be set. It would be nice if we could avoid triggering this code path at the top import level, but I'm not sure what could be done to avoid it without removing the import 🤔

**Comment by function2-llx** [comment]
@awaelchli How about we just make that lock lazy initialized? E.g.:

```python
class _StdinLock:
    def __init__(self):
        self._lock = None

    def __enter__(self):
        if self._lock is None:
            self._lock = multiprocessing.Lock()

        return self._lock.__enter__()

    def __exit__(self, *args, **kwargs):
        return self._lock.__exit__(*args, **kwargs)

_stdin_lock = _StdinLock()
```

**Comment by awaelchli** [comment]
@function2-llx That's a good attempt, but unfortunately, it won't work. If the lock is created lazily after processes are already launched, the lock won't be shared, rendering it useless. The lock must be created before processes get created, so they can share it and use it. That's the main reason why I think there might be no solution unless we remove the code (or live with the fact that you need to force-set the start method).

**Comment by lebrice** [comment]
Hey @awaelchli , a researcher here at Mila is having some really weird behaviour with v2.0.4, importing `lightning` (without even using it), and with **num_workers=0** still slows down PyTorch dataloading significantly (in the order of going from 5 iterations/sec with no `import lightning` down to just 1.3 with).

**Comment by awaelchli** [comment]
Hi @lebrice 
This doesn't sound so good. If you could provide me with an example that demonstrates this, I can start digging in.

**Comment by lebrice** [comment]
This seems to be an unrelated issue (I might create a new one for it).

That issue is caused by `legacy_import_unpickler.py` that is setting `pickle.Unpickler = RedirectingUnpickler`.
For datasets that unpickle files, switching from the C unpickler to the Python unpickler creates a slowdown of `~4x`.

Here's minimal code to reproduce (minus of course the paths):
```
import inspect
import time

# import lightning
import torch
import tqdm
from torch.utils.data import Dataset


class SlowDataset(Dataset):
    def __init__(self):
        super().__init__()

    def __len__(self):
        return 1000

    def __getitem__(self, idx):
        fname = f"/tmp/data/ckpt.pt"
        file = torch.load(fname)
        return file


def main():
    train_dataset = SlowDataset()

    i = 0
    for data in tqdm.tqdm(train_dataset):
        i += 1
        if i > 1000:
            break


if __name__ == "__main__":
    main()
```

**Comment by awaelchli** [comment]
@function2-llx What was your use case for setting the start method manually? Are you working with custom dataloaders or other third-party libraries that require it? I'd like to understand if this has impact on performance and usability with other libraries. If you could share your use case, that would be helpful!

**Comment by function2-llx** [comment]
@awaelchli I'm trying to perform data transformation on GPU (it will me too slow on my CPU). Specifically, I load the data from disk, transfer it to GPU, and perform further transformation. This will not work for the default "fork" method, and my current workaround it to manually set the start method to "spawn" (https://github.com/pytorch/pytorch/issues/40403).
