### ISSUE TITLE
FileNotFoundError when using latest Lightning and Neptune versions

### ISSUE THREAD

**Issue by peymanrahi** [Lightning-AI/lightning#18229]
### Bug description

a FileNotFoundError when using lightning==2.0.6 and neptune==1.4.1. It happens after a few epochs (even if we limit each epoch to 10 samples).

### What version are you seeing the problem on?

v2.0

### Error messages and logs

```

Traceback (most recent call last):
  File "lab/projects/jersey_number_detection/train.py", line 111, in main
    trainer.fit(lightning_model, datamodule=data_module)
  File "/usr/local/lib/python3.8/dist-packages/lightning/pytorch/trainer/trainer.py", line 529, in fit
    call._call_and_handle_interrupt(
  File "/usr/local/lib/python3.8/dist-packages/lightning/pytorch/trainer/call.py", line 42, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/lightning/pytorch/trainer/trainer.py", line 568, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/usr/local/lib/python3.8/dist-packages/lightning/pytorch/trainer/trainer.py", line 973, in _run
    results = self._run_stage()
  File "/usr/local/lib/python3.8/dist-packages/lightning/pytorch/trainer/trainer.py", line 1016, in _run_stage
    self.fit_loop.run()
  File "/usr/local/lib/python3.8/dist-packages/lightning/pytorch/loops/fit_loop.py", line 202, in run
    self.on_advance_end()
  File "/usr/local/lib/python3.8/dist-packages/lightning/pytorch/loops/fit_loop.py", line 369, in on_advance_end
    call._call_callback_hooks(trainer, "on_train_epoch_end", monitoring_callbacks=True)
  File "/usr/local/lib/python3.8/dist-packages/lightning/pytorch/trainer/call.py", line 193, in _call_callback_hooks
    fn(trainer, trainer.lightning_module, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/lightning/pytorch/callbacks/model_checkpoint.py", line 303, in on_train_epoch_end
    self._save_topk_checkpoint(trainer, monitor_candidates)
  File "/usr/local/lib/python3.8/dist-packages/lightning/pytorch/callbacks/model_checkpoint.py", line 362, in _save_topk_checkpoint
    self._save_none_monitor_checkpoint(trainer, monitor_candidates)
  File "/usr/local/lib/python3.8/dist-packages/lightning/pytorch/callbacks/model_checkpoint.py", line 671, in _save_none_monitor_checkpoint
    self._save_checkpoint(trainer, filepath)
  File "/usr/local/lib/python3.8/dist-packages/lightning/pytorch/callbacks/model_checkpoint.py", line 372, in _save_checkpoint
    logger.after_save_checkpoint(proxy(self))
  File "/usr/local/lib/python3.8/dist-packages/lightning_utilities/core/rank_zero.py", line 32, in wrapped_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/lightning/pytorch/loggers/neptune.py", line 507, in after_save_checkpoint
    self.run[f"{checkpoints_namespace}/{model_name}"] = File.from_stream(fp)
  File "/usr/local/lib/python3.8/dist-packages/neptune/metadata_containers/metadata_container.py", line 86, in inner_fun
    return fun(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/neptune/metadata_containers/metadata_container.py", line 252, in __setitem__
    self.__getitem__(key).assign(value)
  File "/usr/local/lib/python3.8/dist-packages/neptune/handler.py", line 86, in inner_fun
    return fun(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/neptune/handler.py", line 211, in assign
    self._container.define(self._path, value)
  File "/usr/local/lib/python3.8/dist-packages/neptune/metadata_containers/metadata_container.py", line 440, in define
    attr.process_assignment(neptune_value, wait=wait)
  File "/usr/local/lib/python3.8/dist-packages/neptune/attributes/attribute.py", line 66, in process_assignment
    return self.assign(value, wait=wait)
  File "/usr/local/lib/python3.8/dist-packages/neptune/attributes/atoms/file.py", line 30, in assign
    operation = UploadFile.of_file(
  File "/usr/local/lib/python3.8/dist-packages/neptune/internal/operation.py", line 206, in of_file
    value._save(operation_storage.upload_path / tmp_file_name)
  File "/usr/local/lib/python3.8/dist-packages/neptune/types/atoms/file.py", line 87, in _save
    self._file_composite.save(path)
  File "/usr/local/lib/python3.8/dist-packages/neptune/internal/types/file_types.py", line 127, in func
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/neptune/internal/types/file_types.py", line 158, in save
    with open(path, "wb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/sunstone/.neptune/sync/run__3d7cc3a2-5ebb-47cb-8820-226edd303f41/exec-1691068691.477657-2023-08-03_13.18.11.477657/upload_path/model_checkpoints_epoch=0-step=1-1691069130.342012-2023-08-03_13.25.30.342012.bin'

```
### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

**Comment by awaelchli** [comment]
Thanks for reporting @peymanrahi 
The error looks exactly the same as in this issue: #18224
So I'm closing this one as a duplicate.
