### ISSUE TITLE
Fabric + FSDP + load_raw before setup edge case

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/lightning#18363]
### Bug description

A user in an offline discussion demonstrated a PyTorch FSDP key error when calling `fabric.load_raw` before `fabric.setup()` was called on an FSDP model. The key error happened in the `__exit__` of this context manager:

https://github.com/Lightning-AI/lightning/blob/fbdbe632c67b05158804b52f4345944781ca4f07/src/lightning/fabric/strategies/fsdp.py#L866

I need to reproduce this and provide a fix.
Note: code was also using `fabric.init_module(empty_weights=True)`

### What version are you seeing the problem on?

master

### How to reproduce the bug

```python
TODO, reproduce this with instructions provided by user (code is not public)
```

### Error messages and logs

TODO: reproduce the error message

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0): 2.1dev 
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0): torch 2.1 nightly from July
#- Python version (e.g., 3.9): 3.10
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source): pip
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

cc @carmocca @justusschock @awaelchli

**Comment by awaelchli** [comment]
```py
import lightning as L
import torch
from lightning.fabric.strategies import FSDPStrategy


fabric = L.Fabric(devices=2, strategy="fsdp", precision="bf16-true")
fabric.launch()

model = torch.nn.Linear(2, 2)
torch.save(model.state_dict(), "checkpoint.pt")

with fabric.init_module(empty_init=False):
    model = torch.nn.Linear(2, 2)

fabric.load_raw("checkpoint.pt", model)
```

```
Traceback (most recent call last):
  File "/home/adrian/repositories/lit-gpt/finetune/full.py", line 15, in <module>
    fabric.load_raw("checkpoint.pt", model)
  File "/home/adrian/repositories/lightning/src/lightning/fabric/fabric.py", line 791, in load_raw
    self._strategy.load_checkpoint(path=path, state=obj, strict=strict)
  File "/home/adrian/repositories/lightning/src/lightning/fabric/strategies/fsdp.py", line 532, in load_checkpoint
    _load_raw_module_state_from_path(path, module=state, world_size=self.world_size, strict=strict)
  File "/home/adrian/repositories/lightning/src/lightning/fabric/strategies/fsdp.py", line 864, in _load_raw_module_state_from_path
    _load_raw_module_state(state_dict=_lazy_load(path), module=module, world_size=world_size, strict=strict)
  File "/home/adrian/repositories/lightning/src/lightning/fabric/strategies/fsdp.py", line 870, in _load_raw_module_state
Traceback (most recent call last):
  File "/home/adrian/repositories/lit-gpt/finetune/full.py", line 15, in <module>
    with _get_full_state_dict_context(module, world_size=world_size, rank0_only=False):
    fabric.load_raw("checkpoint.pt", model)
  File "/home/adrian/.conda/envs/lit-gpt/lib/python3.10/contextlib.py", line 142, in __exit__
  File "/home/adrian/repositories/lightning/src/lightning/fabric/fabric.py", line 791, in load_raw
    next(self.gen)
  File "/home/adrian/.conda/envs/lit-gpt/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 826, in state_dict_type
    self._strategy.load_checkpoint(path=path, state=obj, strict=strict)
  File "/home/adrian/repositories/lightning/src/lightning/fabric/strategies/fsdp.py", line 532, in load_checkpoint
    FullyShardedDataParallel.set_state_dict_type(
  File "/home/adrian/.conda/envs/lit-gpt/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 693, in set_state_dict_type
    _load_raw_module_state_from_path(path, module=state, world_size=self.world_size, strict=strict)
  File "/home/adrian/repositories/lightning/src/lightning/fabric/strategies/fsdp.py", line 864, in _load_raw_module_state_from_path
    state_dict_config_type = _state_dict_type_to_config[state_dict_type]
KeyError: None
    _load_raw_module_state(state_dict=_lazy_load(path), module=module, world_size=world_size, strict=strict)
  File "/home/adrian/repositories/lightning/src/lightning/fabric/strategies/fsdp.py", line 870, in _load_raw_module_state
    with _get_full_state_dict_context(module, world_size=world_size, rank0_only=False):
  File "/home/adrian/.conda/envs/lit-gpt/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/home/adrian/.conda/envs/lit-gpt/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 826, in state_dict_type
    FullyShardedDataParallel.set_state_dict_type(
  File "/home/adrian/.conda/envs/lit-gpt/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 693, in set_state_dict_type
    state_dict_config_type = _state_dict_type_to_config[state_dict_type]
KeyError: None
```
