### ISSUE TITLE
MLFlow logger with remote tracking and log_model=True fails with 'file' is invalid for use with the proxy mlflow-artifact scheme

### ISSUE THREAD

**Issue by robmarkcole** [Lightning-AI/lightning#18393]
### Bug description

Use of the arg `log_model=True` with a remote server results in error:
```
mlflow.exceptions.MlflowException: The configured tracking uri scheme: 'file' is invalid for use with the proxy mlflow-artifact scheme. The allowed tracking schemes are: {'http', 'https'}
```

### What version are you seeing the problem on?

v2.0

### How to reproduce the bug

```python
mlf_logger = MLFlowLogger(tracking_uri=MLFLOW_TRACKING_URI, log_model=True)
cli = LightningCLI(
   MyModel, 
   MyDataModule,
   trainer_defaults={"logger": mlf_logger},
   save_config_callback=None,
)
```

### Error messages and logs

```
`Trainer.fit` stopped: `max_epochs=1` reached.
Epoch 0: 100%|█| 13/13 [01:16<00:00,  5.92s/it, v_num=9fc4, valid_per_image_iou=0.000, valid_
Traceback (most recent call last):
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 42, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 568, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 986, in _run
    call._call_teardown_hook(self)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 118, in _call_teardown_hook
    logger.finalize("success")
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning_utilities/core/rank_zero.py", line 27, in wrapped_fn
    return fn(*args, **kwargs)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/loggers/mlflow.py", line 287, in finalize
    self._scan_and_log_checkpoints(self._checkpoint_callback)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/loggers/mlflow.py", line 360, in _scan_and_log_checkpoints
    self.experiment.log_artifact(self._run_id, p, artifact_path)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/mlflow/tracking/client.py", line 1091, in log_artifact
    self._tracking_client.log_artifact(run_id, local_path, artifact_path)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/client.py", line 448, in log_artifact
    artifact_repo = self._get_artifact_repo(run_id)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/client.py", line 433, in _get_artifact_repo
    artifact_repo = get_artifact_repository(artifact_uri)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/mlflow/store/artifact/artifact_repository_registry.py", line 114, in get_artifact_repository
    return _artifact_repository_registry.get_artifact_repository(artifact_uri)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/mlflow/store/artifact/artifact_repository_registry.py", line 72, in get_artifact_repository
    return repository(artifact_uri)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/mlflow/store/artifact/mlflow_artifacts_repo.py", line 45, in __init__
    super().__init__(self.resolve_uri(artifact_uri, get_tracking_uri()))
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/mlflow/store/artifact/mlflow_artifacts_repo.py", line 59, in resolve_uri
    _validate_uri_scheme(track_parse.scheme)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/mlflow/store/artifact/mlflow_artifacts_repo.py", line 35, in _validate_uri_scheme
    raise MlflowException(
mlflow.exceptions.MlflowException: The configured tracking uri scheme: 'file' is invalid for use with the proxy mlflow-artifact scheme. The allowed tracking schemes are: {'http', 'https'}
```

### Environment

Lightning.ai CPU & GPU machines:

<details>
  <summary>Current environment</summary>

* CUDA:
        - GPU:               None
        - available:         False
        - version:           11.7
* Lightning:
        - efficientnet-pytorch: 0.7.1
        - lightning:         2.0.5
        - lightning-cloud:   0.5.37
        - lightning-utilities: 0.8.0
        - pytorch-lightning: 2.0.5
        - segmentation-models-pytorch: 0.3.3
        - torch:             2.0.1
        - torch-tb-profiler: 0.4.1
        - torchmetrics:      0.11.4
        - torchvision:       0.15.2
* Packages:
        - absl-py:           1.4.0
        - affine:            2.4.0
        - aiobotocore:       2.4.2
        - aiofiles:          22.1.0
        - aiohttp:           3.8.4
        - aioitertools:      0.11.0
        - aiosignal:         1.3.1
        - aiosqlite:         0.19.0
        - albumentations:    1.3.1
        - alembic:           1.11.2
        - anyio:             3.7.0
        - argon2-cffi:       21.3.0
        - argon2-cffi-bindings: 21.2.0
        - arrow:             1.2.3
        - asttokens:         2.2.1
        - async-timeout:     4.0.2
        - attrs:             23.1.0
        - babel:             2.12.1
        - backcall:          0.2.0
        - backoff:           2.2.1
        - beautifulsoup4:    4.12.2
        - bleach:            6.0.0
        - blessed:           1.20.0
        - blinker:           1.6.2
        - botocore:          1.27.59
        - cachetools:        5.3.1
        - certifi:           2023.5.7
        - cffi:              1.15.1
        - charset-normalizer: 3.1.0
        - click:             8.1.3
        - click-plugins:     1.1.1
        - cligj:             0.7.2
        - cloudpickle:       2.2.1
        - cmake:             3.26.3
        - comm:              0.1.3
        - contourpy:         1.1.0
        - croniter:          1.3.15
        - cycler:            0.11.0
        - databricks-cli:    0.17.7
        - dateutils:         0.6.12
        - debugpy:           1.6.7
        - decorator:         5.1.1
        - deepdiff:          6.3.0
        - defusedxml:        0.7.1
        - distlib:           0.3.6
        - docker:            6.1.2
        - docstring-parser:  0.15
        - efficientnet-pytorch: 0.7.1
        - entrypoints:       0.4
        - exceptiongroup:    1.1.1
        - executing:         1.2.0
        - fastapi:           0.100.0
        - fastjsonschema:    2.17.1
        - filelock:          3.12.0
        - flask:             2.3.2
        - fonttools:         4.42.0
        - fqdn:              1.5.1
        - frozenlist:        1.3.3
        - fsspec:            2022.11.0
        - gitdb:             4.0.10
        - gitpython:         3.1.32
        - google-auth:       2.19.0
        - google-auth-oauthlib: 1.0.0
        - greenlet:          2.0.2
        - grpcio:            1.54.2
        - gunicorn:          20.1.0
        - h11:               0.14.0
        - huggingface-hub:   0.16.4
        - idna:              3.4
        - imageio:           2.31.1
        - importlib-metadata: 6.8.0
        - importlib-resources: 6.0.1
        - inquirer:          3.1.3
        - ipykernel:         6.23.1
        - ipython:           8.13.2
        - ipython-genutils:  0.2.0
        - ipywidgets:        8.0.7
        - isoduration:       20.11.0
        - itsdangerous:      2.1.2
        - jedi:              0.18.2
        - jinja2:            3.1.2
        - jmespath:          1.0.1
        - joblib:            1.3.2
        - json5:             0.9.14
        - jsonargparse:      4.23.1
        - jsonpointer:       2.3
        - jsonschema:        4.17.3
        - jupyter-client:    8.2.0
        - jupyter-core:      5.3.0
        - jupyter-events:    0.6.3
        - jupyter-server:    2.6.0
        - jupyter-server-fileid: 0.9.0
        - jupyter-server-terminals: 0.4.4
        - jupyter-server-ydoc: 0.6.1
        - jupyter-ydoc:      0.2.4
        - jupyterlab:        3.6.1
        - jupyterlab-pygments: 0.2.2
        - jupyterlab-server: 2.22.1
        - jupyterlab-widgets: 3.0.8
        - kiwisolver:        1.4.4
        - lazy-loader:       0.3
        - lightning:         2.0.5
        - lightning-cloud:   0.5.37
        - lightning-utilities: 0.8.0
        - lit:               16.0.5
        - mako:              1.2.4
        - markdown:          3.4.3
        - markdown-it-py:    2.2.0
        - markupsafe:        2.1.2
        - matplotlib:        3.7.2
        - matplotlib-inline: 0.1.6
        - mdurl:             0.1.2
        - mistune:           2.0.5
        - mlflow:            2.5.0
        - mpmath:            1.3.0
        - multidict:         6.0.4
        - munch:             4.0.0
        - nbclassic:         1.0.0
        - nbclient:          0.8.0
        - nbconvert:         7.4.0
        - nbformat:          5.9.0
        - nest-asyncio:      1.5.6
        - networkx:          3.1
        - notebook:          6.5.4
        - notebook-shim:     0.2.3
        - numpy:             1.24.3
        - nvidia-cublas-cu11: 11.10.3.66
        - nvidia-cuda-cupti-cu11: 11.7.101
        - nvidia-cuda-nvrtc-cu11: 11.7.99
        - nvidia-cuda-runtime-cu11: 11.7.99
        - nvidia-cudnn-cu11: 8.5.0.96
        - nvidia-cufft-cu11: 10.9.0.58
        - nvidia-curand-cu11: 10.2.10.91
        - nvidia-cusolver-cu11: 11.4.0.1
        - nvidia-cusparse-cu11: 11.7.4.91
        - nvidia-ml-py:      12.535.77
        - nvidia-nccl-cu11:  2.14.3
        - nvidia-nvtx-cu11:  11.7.91
        - nvitop:            1.2.0
        - oauthlib:          3.2.2
        - opencv-python-headless: 4.8.0.76
        - ordered-set:       4.1.0
        - overrides:         7.3.1
        - packaging:         23.1
        - pandas:            2.0.3
        - pandocfilters:     1.5.0
        - parso:             0.8.3
        - pexpect:           4.8.0
        - pickleshare:       0.7.5
        - pillow:            9.5.0
        - pip:               23.1.2
        - platformdirs:      3.5.1
        - pretrainedmodels:  0.7.4
        - prometheus-client: 0.17.0
        - prompt-toolkit:    3.0.38
        - protobuf:          4.23.2
        - psutil:            5.9.5
        - ptyprocess:        0.7.0
        - pure-eval:         0.2.2
        - pyarrow:           12.0.1
        - pyasn1:            0.5.0
        - pyasn1-modules:    0.3.0
        - pycparser:         2.21
        - pydantic:          1.10.8
        - pygments:          2.15.1
        - pyjwt:             2.7.0
        - pyparsing:         3.0.9
        - pyrsistent:        0.19.3
        - python-dateutil:   2.8.2
        - python-editor:     1.0.4
        - python-json-logger: 2.0.7
        - python-multipart:  0.0.6
        - pytorch-lightning: 2.0.5
        - pytz:              2023.3
        - pywavelets:        1.4.1
        - pyyaml:            6.0
        - pyzmq:             25.1.0
        - qudida:            0.0.4
        - querystring-parser: 1.2.4
        - rasterio:          1.3.8
        - readchar:          4.0.5
        - redis:             4.5.5
        - requests:          2.31.0
        - requests-oauthlib: 1.3.1
        - rfc3339-validator: 0.1.4
        - rfc3986-validator: 0.1.1
        - rich:              13.4.1
        - rsa:               4.9
        - s3fs:              2022.11.0
        - safetensors:       0.3.2
        - scikit-image:      0.21.0
        - scikit-learn:      1.3.0
        - scipy:             1.11.1
        - segmentation-models-pytorch: 0.3.3
        - send2trash:        1.8.2
        - setuptools:        67.8.0
        - six:               1.16.0
        - smmap:             5.0.0
        - sniffio:           1.3.0
        - snuggs:            1.4.7
        - soupsieve:         2.4.1
        - sqlalchemy:        2.0.19
        - sqlparse:          0.4.4
        - stack-data:        0.6.2
        - starlette:         0.27.0
        - starsessions:      1.3.0
        - sympy:             1.12
        - tabulate:          0.9.0
        - tensorboard:       2.13.0
        - tensorboard-data-server: 0.7.0
        - termcolor:         2.3.0
        - terminado:         0.17.1
        - threadpoolctl:     3.2.0
        - tifffile:          2023.8.12
        - timm:              0.9.2
        - tinycss2:          1.2.1
        - tomli:             2.0.1
        - torch:             2.0.1
        - torch-tb-profiler: 0.4.1
        - torchmetrics:      0.11.4
        - torchvision:       0.15.2
        - tornado:           6.3.2
        - tqdm:              4.65.0
        - traitlets:         5.9.0
        - triton:            2.0.0
        - typeshed-client:   2.3.0
        - typing-extensions: 4.6.2
        - tzdata:            2023.3
        - uri-template:      1.2.0
        - urllib3:           1.26.16
        - uvicorn:           0.22.0
        - virtualenv:        20.23.0
        - wcwidth:           0.2.6
        - webcolors:         1.13
        - webencodings:      0.5.1
        - websocket-client:  1.5.2
        - websockets:        11.0.3
        - werkzeug:          2.3.4
        - wheel:             0.38.4
        - widgetsnbextension: 4.0.8
        - wrapt:             1.15.0
        - y-py:              0.5.9
        - yarl:              1.9.2
        - ypy-websocket:     0.8.2
        - zipp:              3.16.2
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.10.11
        - release:           5.15.0-1041-aws
        - version:           #46~20.04.1-Ubuntu SMP Wed Jul 19 15:40:00 UTC 2023

### More info

Without this arg, logs are generated on the MLflow server correctly, but no model artifacts are written

**Comment by robmarkcole** [comment]
A validated workaround, first call:
```
import mlflow
mlflow.set_tracking_uri(MLFLOW_TRACKING_URI)

...

mlf_logger = MLFlowLogger etc
```
