### ISSUE TITLE
FileNotFoundError: Checkpoint at saved/muti_benchmark_01/last-epoch.ckpt not found. Aborting training.

### ISSUE THREAD

**Issue by TalonX1** [Lightning-AI/lightning#18413]
### Bug description

I try to use ddp(2 gpu) for training, It seems that there was an issue with training initialization on the second GPU.The weight file should not have been loaded

### What version are you seeing the problem on?

v1.7

### Error messages and logs

```
Global seed set to 3211215663
Initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/2
Global seed set to 3211215663
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/2
[2023-08-28 15:53:07,509][torch.distributed.distributed_c10d][INFO] - Added key: store_based_barrier_key:1 to store for rank: 0
[2023-08-28 15:53:07,510][torch.distributed.distributed_c10d][INFO] - Added key: store_based_barrier_key:1 to store for rank: 1
[2023-08-28 15:53:07,511][torch.distributed.distributed_c10d][INFO] - Rank 1: Completed store-based barrier for key:store_based_barrier_key:1 with 2 nodes.
[2023-08-28 15:53:07,520][torch.distributed.distributed_c10d][INFO] - Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 2 nodes.
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 2 processes
----------------------------------------------------------------------------------------------------

Traceback (most recent call last):
  File "/data2/qhb/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/data2/qhb/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/hydra/_internal/utils.py", line 347, in <lambda>
    lambda: hydra.run(
  File "/data2/qhb/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 107, in run
    return run_job(
  File "/data2/qhb/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/hydra/core/utils.py", line 128, in run_job
    ret.return_value = task_function(task_cfg)
  File "/data2/qhb/mask3d/Mask3D-main_20230621/muti_gpu_debug_main_instance_segmentation.py", line 130, in main
    train(cfg)
  File "/data2/qhb/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/hydra/main.py", line 27, in decorated_main
    return task_function(cfg_passthrough)
  File "/data2/qhb/mask3d/Mask3D-main_20230621/muti_gpu_debug_main_instance_segmentation.py", line 111, in train
    runner.fit(model)
  File "/data2/qhb/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "/data2/qhb/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/data2/qhb/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 737, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/data2/qhb/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1112, in _run
    self._restore_modules_and_callbacks(ckpt_path)
  File "/data2/qhb/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1065, in _restore_modules_and_callbacks
    self._checkpoint_connector.resume_start(checkpoint_path)
  File "/data2/qhb/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 85, in resume_start
    self._loaded_checkpoint = self._load_and_validate_checkpoint(checkpoint_path)
  File "/data2/qhb/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 89, in _load_and_validate_checkpoint
    loaded_checkpoint = self.trainer.strategy.load_checkpoint(checkpoint_path)
  File "/data2/qhb/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 339, in load_checkpoint
    return self.checkpoint_io.load_checkpoint(checkpoint_path)
  File "/data2/qhb/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/pytorch_lightning/plugins/io/torch_plugin.py", line 83, in load_checkpoint
    raise FileNotFoundError(f"Checkpoint at {path} not found. Aborting training.")
FileNotFoundError: Checkpoint at saved/muti_benchmark_01/last-epoch.ckpt not found. Aborting training.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data2/qhb/mask3d/Mask3D-main_20230621/muti_gpu_debug_main_instance_segmentation.py", line 136, in <module>
    main()
  File "/data2/qhb/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/hydra/main.py", line 32, in decorated_main
    _run_hydra(
  File "/data2/qhb/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/hydra/_internal/utils.py", line 346, in _run_hydra
    run_and_report(
  File "/data2/qhb/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/hydra/_internal/utils.py", line 267, in run_and_report
    print_exception(etype=None, value=ex, tb=final_tb)  # type: ignore
TypeError: print_exception() got an unexpected keyword argument 'etype'
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):1.7.2
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):1.12.1+cu113
#- Python version (e.g., 3.9):3.10.9
#- OS (e.g., Linux):linux
#- CUDA/cuDNN version:11.3
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):pip
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

**Comment by PandaDalin** [comment]
Delete Mask3D/saved/xx  xx is project name
