### ISSUE TITLE
RuntimeError: Attempting CUDA graph capture of step() for an instance of AdamW

### ISSUE THREAD

**Issue by celsofranssa** [Lightning-AI/lightning#18501]
### Bug description

RuntimeError: Attempting CUDA graph capture of step() for an instance of AdamW but this instance was constructed with capturable=False.

### What version are you seeing the problem on?

v1.6

### How to reproduce the bug

```python
just using normal PL training step with the following configure_optimizers:

    def configure_optimizers(self):
        opt_1 = torch.optim.AdamW(self.encoder_1.parameters(), lr=self.hparams.lr, eps=1e-8)
        opt_2 = torch.optim.AdamW(self.encoder_2.parameters(), lr=self.hparams.lr, eps=1e-8)
        scheduler_1 = get_linear_schedule_with_warmup(opt_1, num_warmup_steps=0,
                                                         num_training_steps=self.num_training_steps)
        scheduler_2 = get_linear_schedule_with_warmup(opt_2, num_warmup_steps=0,
                                                         num_training_steps=self.num_training_steps)

        return (
            {"optimizer": opt_1, "lr_scheduler": scheduler_1, "frequency": 1},
            {"optimizer": opt_2, "lr_scheduler": scheduler_2, "frequency": 1},
        )
```

### Error messages and logs

```
Traceback (most recent call last):
  File "/home/celso/projects/UniXcoder/main.py", line 47, in <module>
    perform_tasks()
  File "/home/celso/projects/venvs/UniXcoder/lib/python3.10/site-packages/hydra/main.py", line 48, in decorated_main
    _run_hydra(
  File "/home/celso/projects/venvs/UniXcoder/lib/python3.10/site-packages/hydra/_internal/utils.py", line 377, in _run_hydra
    run_and_report(
  File "/home/celso/projects/venvs/UniXcoder/lib/python3.10/site-packages/hydra/_internal/utils.py", line 294, in run_and_report
    raise ex
  File "/home/celso/projects/venvs/UniXcoder/lib/python3.10/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/home/celso/projects/venvs/UniXcoder/lib/python3.10/site-packages/hydra/_internal/utils.py", line 378, in <lambda>
    lambda: hydra.run(
  File "/home/celso/projects/venvs/UniXcoder/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 111, in run
    _ = ret.return_value
  File "/home/celso/projects/venvs/UniXcoder/lib/python3.10/site-packages/hydra/core/utils.py", line 233, in return_value
    raise self._return_value
  File "/home/celso/projects/venvs/UniXcoder/lib/python3.10/site-packages/hydra/core/utils.py", line 160, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/celso/projects/UniXcoder/main.py", line 37, in perform_tasks
    fit(params)
  File "/home/celso/projects/UniXcoder/main.py", line 16, in fit
    helper.perform_fit()
  File "/home/celso/projects/UniXcoder/source/helper/xCoFormerFitHelper.py", line 45, in perform_fit
    trainer.fit(
  File "/home/celso/projects/venvs/UniXcoder/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 552, in fit
    self._run(model)
  File "/home/celso/projects/venvs/UniXcoder/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 922, in _run
    self._dispatch()
  File "/home/celso/projects/venvs/UniXcoder/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 990, in _dispatch
    self.accelerator.start_training(self)
  File "/home/celso/projects/venvs/UniXcoder/lib/python3.10/site-packages/pytorch_lightning/accelerators/accelerator.py", line 92, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/home/celso/projects/venvs/UniXcoder/lib/python3.10/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 161, in start_training
    self._results = trainer.run_stage()
  File "/home/celso/projects/venvs/UniXcoder/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1000, in run_stage
    return self._run_train()
  File "/home/celso/projects/venvs/UniXcoder/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1049, in _run_train
    self.fit_loop.run()
  File "/home/celso/projects/venvs/UniXcoder/lib/python3.10/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/home/celso/projects/venvs/UniXcoder/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 200, in advance
    epoch_output = self.epoch_loop.run(train_dataloader)
  File "/home/celso/projects/venvs/UniXcoder/lib/python3.10/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/home/celso/projects/venvs/UniXcoder/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 130, in advance
    batch_output = self.batch_loop.run(batch, self.iteration_count, self._dataloader_idx)
  File "/home/celso/projects/venvs/UniXcoder/lib/python3.10/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 100, in run
    super().run(batch, batch_idx, dataloader_idx)
  File "/home/celso/projects/venvs/UniXcoder/lib/python3.10/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/home/celso/projects/venvs/UniXcoder/lib/python3.10/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 147, in advance
    result = self._run_optimization(batch_idx, split_batch, opt_idx, optimizer)
  File "/home/celso/projects/venvs/UniXcoder/lib/python3.10/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 201, in _run_optimization
    self._optimizer_step(optimizer, opt_idx, batch_idx, closure)
  File "/home/celso/projects/venvs/UniXcoder/lib/python3.10/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 395, in _optimizer_step
    model_ref.optimizer_step(
  File "/home/celso/projects/venvs/UniXcoder/lib/python3.10/site-packages/pytorch_lightning/core/lightning.py", line 1616, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/home/celso/projects/venvs/UniXcoder/lib/python3.10/site-packages/pytorch_lightning/core/optimizer.py", line 206, in step
    self.__optimizer_step(closure=closure, profiler_name=profiler_name, **kwargs)
  File "/home/celso/projects/venvs/UniXcoder/lib/python3.10/site-packages/pytorch_lightning/core/optimizer.py", line 128, in __optimizer_step
    trainer.accelerator.optimizer_step(self._optimizer, self._optimizer_idx, lambda_closure=closure, **kwargs)
  File "/home/celso/projects/venvs/UniXcoder/lib/python3.10/site-packages/pytorch_lightning/accelerators/accelerator.py", line 296, in optimizer_step
    self.run_optimizer_step(optimizer, opt_idx, lambda_closure, **kwargs)
  File "/home/celso/projects/venvs/UniXcoder/lib/python3.10/site-packages/pytorch_lightning/accelerators/accelerator.py", line 303, in run_optimizer_step
    self.training_type_plugin.optimizer_step(optimizer, lambda_closure=lambda_closure, **kwargs)
  File "/home/celso/projects/venvs/UniXcoder/lib/python3.10/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 226, in optimizer_step
    optimizer.step(closure=lambda_closure, **kwargs)
  File "/home/celso/projects/venvs/UniXcoder/lib/python3.10/site-packages/torch/optim/lr_scheduler.py", line 68, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/celso/projects/venvs/UniXcoder/lib/python3.10/site-packages/torch/optim/optimizer.py", line 140, in wrapper
    out = func(*args, **kwargs)
  File "/home/celso/projects/venvs/UniXcoder/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/celso/projects/venvs/UniXcoder/lib/python3.10/site-packages/torch/optim/adamw.py", line 115, in step
    self._cuda_graph_capture_health_check()
  File "/home/celso/projects/venvs/UniXcoder/lib/python3.10/site-packages/torch/optim/optimizer.py", line 103, in _cuda_graph_capture_health_check
    raise RuntimeError("Attempting CUDA graph capture of step() for an instance of " +
RuntimeError: Attempting CUDA graph capture of step() for an instance of AdamW but this instance was constructed with capturable=False.
```

### Environment

<details>
  <summary>Current environment</summary>

* CUDA:
	- GPU:
		- NVIDIA GeForce RTX 4090
	- available:         True
	- version:           11.7
* Lightning:
	- lightning-utilities: 0.9.0
	- pytorch-lightning: 1.4.9
	- torch:             1.13.1+cu117
	- torchmetrics:      0.5.1
* Packages:
	- absl-py:           1.4.0
	- aiohttp:           3.8.5
	- aiosignal:         1.3.1
	- antlr4-python3-runtime: 4.8
	- async-timeout:     4.0.3
	- attrs:             23.1.0
	- cachetools:        5.3.1
	- certifi:           2023.7.22
	- charset-normalizer: 3.2.0
	- filelock:          3.12.3
	- frozenlist:        1.4.0
	- fsspec:            2023.6.0
	- future:            0.18.3
	- google-auth:       2.22.0
	- google-auth-oauthlib: 1.0.0
	- grpcio:            1.57.0
	- huggingface-hub:   0.16.4
	- hydra-core:        1.1.2
	- idna:              3.4
	- lightning-utilities: 0.9.0
	- markdown:          3.4.4
	- markupsafe:        2.1.3
	- multidict:         6.0.4
	- nmslib:            2.1.1
	- numpy:             1.22.4
	- nvidia-cuda-runtime-cu11: 11.7.99
	- oauthlib:          3.2.2
	- omegaconf:         2.1.2
	- packaging:         23.1
	- pandas:            1.1.5
	- pip:               22.0.2
	- protobuf:          4.24.2
	- psutil:            5.9.5
	- pyasn1:            0.5.0
	- pyasn1-modules:    0.3.0
	- pybind11:          2.6.1
	- pydeprecate:       0.3.1
	- python-dateutil:   2.8.2
	- pytorch-lightning: 1.4.9
	- pytz:              2023.3
	- pyyaml:            6.0.1
	- regex:             2023.8.8
	- requests:          2.31.0
	- requests-oauthlib: 1.3.1
	- rsa:               4.9
	- scipy:             1.11.2
	- sentencepiece:     0.1.99
	- setuptools:        59.6.0
	- six:               1.16.0
	- tensorboard:       2.14.0
	- tensorboard-data-server: 0.7.1
	- tokenizers:        0.12.1
	- torch:             1.13.1+cu117
	- torchmetrics:      0.5.1
	- tqdm:              4.62.3
	- transformers:      4.21.3
	- typing-extensions: 4.7.1
	- urllib3:           1.26.16
	- werkzeug:          2.3.7
	- wheel:             0.37.1
	- yarl:              1.9.2
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- ELF
	- processor:         x86_64
	- python:            3.10.12
	- release:           5.15.0-79-generic
	- version:           #86-Ubuntu SMP Mon Jul 10 16:07:21 UTC 2023

</details>

**Comment by awaelchli** [comment]
@celsofranssa Does the issue occur with recent versions of Lightning and PyTorch too? We no longer support 1.6 with bugfix patches.

**Comment by celsofranssa** [comment]
It was in an old release. Thank you.
