### ISSUE TITLE
Validation metrics not available when resuming training from checkpoint

### ISSUE THREAD

**Issue by TreeMage** [Lightning-AI/lightning#18595]
### Bug description

I am training a lot of models in a preemtible environment where training is often stopped unexpectedly due to other jobs with higher priority requesting the GPU the model is being trained on. In these cases, I deploy resume jobs which resume from the last model checkpoint as follows:
```
trainer = Trainer(...)
datamodule = MyPLDataModule(...)
checkpoint_path = ...
module = MyPLModule.load_from_checkpoint(checkpoint_path)
trainer.fit(module, datamodule=datamodule, ckpt_path=checkpoint_path)
```

In ~90% of cases, this works perfectly fine and training resumes as expected. However, in the remaining 10%, training crashes as soon as the EarlyStoppingCallback is invoked since the monitored metric is not available.
Note that I am using a modified version of the EarlyStoppingCallback that allows for a warm-up grace-period:
```
class EarlyStoppingWithWarmUp(EarlyStopping):
    def __init__(
        self,
        monitor: str,
        min_delta: float = 0.0,
        patience: int = 3,
        verbose: bool = False,
        mode: str = "min",
        strict: bool = True,
        check_finite: bool = True,
        stopping_threshold: Optional[float] = None,
        divergence_threshold: Optional[float] = None,
        check_on_train_epoch_end: Optional[bool] = None,
        log_rank_zero_only: bool = False,
        warmup_epochs: int = 0,
    ):
        super().__init__(
            monitor,
            min_delta,
            patience,
            verbose,
            mode,
            strict,
            check_finite,
            stopping_threshold,
            divergence_threshold,
            check_on_train_epoch_end,
            log_rank_zero_only,
        )
        self._warmup_epochs = warmup_epochs

    def _is_warmup_epoch(self, trainer: pl.Trainer) -> bool:
        return trainer.current_epoch < self._warmup_epochs

    def _should_skip_check_due_to_warmup(self, trainer: pl.Trainer) -> bool:
        return self._is_warmup_epoch(trainer)

    def on_train_epoch_end(
        self, trainer: pl.Trainer, pl_module: pl.LightningModule
    ) -> None:
        logs = trainer.callback_metrics
        if (
            trainer.fast_dev_run
            or not self._validate_condition_metric(  # disable early_stopping with fast_dev_run
                logs
            )
        ):  # short circuit if metric not present
            return
        if self.check_finite:
            # If the monitor is not finite, run the check anyway to stop training
            current = logs[self.monitor].squeeze()
            if not torch.isfinite(current):
                return super().on_train_epoch_end(trainer, pl_module)
        if self._should_skip_check_due_to_warmup(trainer):
            return
        return super().on_train_epoch_end(trainer, pl_module)

    def on_validation_end(
        self, trainer: pl.Trainer, pl_module: pl.LightningModule
    ) -> None:
        if self._should_skip_check_due_to_warmup(trainer):
            return
        return super().on_validation_end(trainer, pl_module)

```

Any insights would be appreciated!

### What version are you seeing the problem on?

v2.0

### Error messages and logs

```
Early stopping conditioned on metric `val_TimeSeriesMAE` which is not available. Pass in or modify your `EarlyStopping` callback to use any of the following: `train_loss`, `train_TimeSeriesMAE`, `train_TimeSeriesMAPE`, `train_TimeSeriesRMSE`, `train_TimeSeriesMSE`
Traceback (most recent call last):
  File "/app/pbim_models/cli/resume.py", line 199, in resume
    trainer.fit(
  File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 529, in fit
    call._call_and_handle_interrupt(
  File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 42, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 568, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 973, in _run
    results = self._run_stage()
  File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1016, in _run_stage
    self.fit_loop.run()
  File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 202, in run
    self.on_advance_end()
  File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 369, in on_advance_end
    call._call_callback_hooks(trainer, "on_train_epoch_end", monitoring_callbacks=True)
  File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 193, in _call_callback_hooks
    fn(trainer, trainer.lightning_module, *args, **kwargs)
  File "/app/models/util.py", line 110, in on_train_epoch_end
    or not self._validate_condition_metric(  # disable early_stopping with fast_dev_run
  File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/callbacks/early_stopping.py", line 146, in _validate_condition_metric
    raise RuntimeError(error_msg)
RuntimeError: Early stopping conditioned on metric `val_TimeSeriesMAE` which is not available. Pass in or modify your `EarlyStopping` callback to use any of the following: `train_loss`, `train_TimeSeriesMAE`, `train_TimeSeriesMAPE`, `train_TimeSeriesRMSE`, `train_TimeSeriesMSE`
```

### Environment

<details>
  <summary>Current environment</summary>
* Lightning:
   - lightning-utilities: 0.9.0
        - pytorch-lightning: 2.0.6
        - torch:             2.0.0
        - torch-cluster:     1.6.1
        - torchmetrics:      0.11.4
</details>

**Comment by john-zielke-snkeos** [comment]
Out of curiosity: Are you using a sampler or a fixed size dataset?

I think we are facing a similar issue stemming from the same problem. If we resume our training from an end of epoch callback, it does not start training from the next epoch immediately, but tries to run a validation loop before moving to the next epoch. And after that I'm assuming it also calls all callbacks with on_validation_epoch_end, which includes the EarlyStoppingCallback.
In your case the dataloader for validation probably returns no items, so the epoch ends without any metrics and then the callback fails. In our case, the DataPrefetcher loads a single example before realising it is past the end of the epoch. This example is then fed through the validation step and because of a sample size of 1 could either create a very high or very low value for the metric used for checkpointing. This will then cause the training to ignore the model improvements in the next epochs.

I think this is similar to what this PR https://github.com/Lightning-AI/lightning/pull/866 tried to fix, but maybe with the changes since then a regression was introduced. Or maybe it's by design that it does not continue directly with the next epoch, although I don't really see why that would be the case.
