### ISSUE TITLE
FSDP not working well with BatchNorm and 16-mixed precision

### ISSUE THREAD

**Issue by DLlearn** [Lightning-AI/lightning#18802]
### Bug description

i use fsdp strategy mixed precision 16 train the model 

### What version are you seeing the problem on?

v2.0

### How to reproduce the bug

```python
import time

import lightning as L
from lightning import Fabric

import torch
from torch.utils.data import random_split
import torch.nn.functional as F
import torchmetrics
import torchvision as tv


def train(num_epochs, model, optimizer, train_loader, val_loader, fabric):

    for epoch in range(num_epochs):
        train_acc = torchmetrics.Accuracy(task="multiclass", num_classes=10).to(fabric.device)

        model.train()
        for batch_idx, (features, targets) in enumerate(train_loader):
            model.train()
            
            ### FORWARD AND BACK PROP   
            logits = model(features)
            loss = F.cross_entropy(logits, targets)
            
            optimizer.zero_grad()
            fabric.backward(loss)

            ### UPDATE MODEL PARAMETERS
            optimizer.step()

            ### LOGGING
            if not batch_idx % 300:
                print(f"Epoch: {epoch+1:04d}/{num_epochs:04d} | Batch {batch_idx:04d}/{len(train_loader):04d} | Loss: {loss:.4f}")

            model.eval()
            with torch.no_grad():
                predicted_labels = torch.argmax(logits, 1)
                train_acc.update(predicted_labels, targets)

        ### MORE LOGGING
        model.eval()
        with torch.no_grad():
            val_acc = torchmetrics.Accuracy(task="multiclass", num_classes=10).to(fabric.device)

            for (features, targets) in val_loader:

                outputs = model(features)
                predicted_labels = torch.argmax(outputs, 1)
                val_acc.update(predicted_labels, targets)

            fabric.print(f"Epoch: {epoch+1:04d}/{num_epochs:04d} | Train acc.: {train_acc.compute()*100:.2f}% | Val acc.: {val_acc.compute()*100:.2f}%")
            train_acc.reset(), val_acc.reset()


if __name__ == "__main__":

    print("Torch CUDA available?", torch.cuda.is_available())
    #torch.set_float32_matmul_precision("medium")
    fabric = Fabric(accelerator="cuda",devices=[0,1,2,3],strategy="fsdp",precision="16-true")  #使用的是V100 只支持这个,精度容易损失
    fabric.launch()

    L.seed_everything(123)

    ##########################
    ### 1 Loading the Dataset
    ##########################
    train_transforms = tv.transforms.Compose([tv.transforms.Resize((64, 64)),
                                        #tv.transforms.RandomCrop((64, 64)),
                                        tv.transforms.ToTensor()])
    
    test_transforms = tv.transforms.Compose([tv.transforms.Resize((64, 64)),
                                        #transforms.CenterCrop((224, 224)),
                                        tv.transforms.ToTensor()])
    
    train_dataset = tv.datasets.CIFAR10(root='~/data',
                                    train=True,
                                    transform=train_transforms,
                                    download=True)


    train_fraction=0.9
    train_size = int(train_fraction * len(train_dataset))
    val_size = len(train_dataset) - train_size

    train_dataset, valid_dataset = random_split(train_dataset, [train_size, val_size])


    test_dataset = tv.datasets.CIFAR10(root='~/data',
                                    train=False,
                                    transform=test_transforms)
    batch_size=256
    num_workers=8
    

 

    train_loader = torch.utils.data.DataLoader(dataset=train_dataset,
                                batch_size=batch_size,
                                num_workers=num_workers,
                                drop_last=True,
                                shuffle=True)
    val_loader = torch.utils.data.DataLoader(dataset=valid_dataset,
                                batch_size=batch_size,
                                num_workers=num_workers,
                                shuffle=False)

    test_loader = torch.utils.data.DataLoader(dataset=test_dataset,
                                batch_size=batch_size,
                                num_workers=num_workers,
                                shuffle=False)
    train_loader,val_loader,test_loader = fabric.setup_dataloaders(train_loader,val_loader,test_loader)
    #########################################
    ### 2 Initializing the Model
    #########################################

    model = tv.models.resnet50()

    # replace output layer
    model.fc = torch.nn.Linear(in_features=2048,out_features=10)

    optimizer = torch.optim.Adam(model.parameters(), lr=5e-3) 
    model,optimizer = fabric.setup(model,optimizer)
    #########################################
    ### 3 training
    #########################################

    start = time.time()
    train(
        num_epochs=10,
        model=model,
        optimizer=optimizer,
        train_loader=train_loader,
        val_loader=val_loader,
        fabric=fabric
    )

    end = time.time()
    elapsed = end-start
    fabric.print(f"Time elapsed {elapsed/60:.2f} min")
    fabric.print(f"Memory used: {torch.cuda.max_memory_reserved() / 1e9:.02f} GB")

    #########################################
    ### 4 Evaluation
    #########################################
    
    with torch.no_grad():
        model.eval()
        test_acc = torchmetrics.Accuracy(task="multiclass", num_classes=10).to(fabric.device)

        for (features, targets) in test_loader:
            outputs = model(features)
            predicted_labels = torch.argmax(outputs, 1)
            test_acc.update(predicted_labels, targets)

    fabric.print(f"Test accuracy {test_acc.compute()*100:.2f}%")
```

### Error messages and logs

```
# Error messages and logs here please
Traceback (most recent call last):
  File "/home/tl/fabric/07_fabric_resnet50_mixed_fsdp.py", line 129, in <module>
    train(
  File "/home/tl/fabric/07_fabric_resnet50_mixed_fsdp.py", line 23, in train
    logits = model(features)
  File "/home/tl/anaconda3/envs/ptch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tl/anaconda3/envs/ptch/lib/python3.10/site-packages/lightning/fabric/wrappers.py", line 121, in forward
    output = self._forward_module(*args, **kwargs)
  File "/home/tl/anaconda3/envs/ptch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tl/anaconda3/envs/ptch/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 748, in forward
    output = self._fsdp_wrapped_module(*args, **kwargs)
  File "/home/tl/anaconda3/envs/ptch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tl/anaconda3/envs/ptch/lib/python3.10/site-packages/torchvision/models/resnet.py", line 285, in forward
    return self._forward_impl(x)
  File "/home/tl/anaconda3/envs/ptch/lib/python3.10/site-packages/torchvision/models/resnet.py", line 269, in _forward_impl
    x = self.bn1(x)
  File "/home/tl/anaconda3/envs/ptch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tl/anaconda3/envs/ptch/lib/python3.10/site-packages/torch/nn/modules/batchnorm.py", line 171, in forward
    return F.batch_norm(
  File "/home/tl/anaconda3/envs/ptch/lib/python3.10/site-packages/torch/nn/functional.py", line 2450, in batch_norm
    return torch.batch_norm(
RuntimeError: Expected tensor for argument #2 'weight' to have the same type as tensor for argument #4 'running_mean'; but type torch.cuda.FloatTensor does not equal torch.cuda.HalfTensor (while checking arguments for cudnn_batch_norm)
Traceback (most recent call last):
  File "/home/tl/fabric/07_fabric_resnet50_mixed_fsdp.py", line 129, in <module>
    train(
  File "/home/tl/fabric/07_fabric_resnet50_mixed_fsdp.py", line 23, in train
    logits = model(features)
  File "/home/tl/anaconda3/envs/ptch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tl/anaconda3/envs/ptch/lib/python3.10/site-packages/lightning/fabric/wrappers.py", line 121, in forward
    output = self._forward_module(*args, **kwargs)
  File "/home/tl/anaconda3/envs/ptch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tl/anaconda3/envs/ptch/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 748, in forward
    output = self._fsdp_wrapped_module(*args, **kwargs)
  File "/home/tl/anaconda3/envs/ptch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tl/anaconda3/envs/ptch/lib/python3.10/site-packages/torchvision/models/resnet.py", line 285, in forward
    return self._forward_impl(x)
  File "/home/tl/anaconda3/envs/ptch/lib/python3.10/site-packages/torchvision/models/resnet.py", line 269, in _forward_impl
    x = self.bn1(x)
  File "/home/tl/anaconda3/envs/ptch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tl/anaconda3/envs/ptch/lib/python3.10/site-packages/torch/nn/modules/batchnorm.py", line 171, in forward
    return F.batch_norm(
  File "/home/tl/anaconda3/envs/ptch/lib/python3.10/site-packages/torch/nn/functional.py", line 2450, in batch_norm
    return torch.batch_norm(
RuntimeError: Expected tensor for argument #2 'weight' to have the same type as tensor for argument #4 'running_mean'; but type torch.cuda.FloatTensor does not equal torch.cuda.HalfTensor (while checking arguments for cudnn_batch_norm)
Traceback (most recent call last):
  File "/home/tl/fabric/07_fabric_resnet50_mixed_fsdp.py", line 129, in <module>
Traceback (most recent call last):
  File "/home/tl/fabric/07_fabric_resnet50_mixed_fsdp.py", line 129, in <module>
    train(
  File "/home/tl/fabric/07_fabric_resnet50_mixed_fsdp.py", line 23, in train
    logits = model(features)
  File "/home/tl/anaconda3/envs/ptch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    train(
  File "/home/tl/fabric/07_fabric_resnet50_mixed_fsdp.py", line 23, in train
    logits = model(features)
  File "/home/tl/anaconda3/envs/ptch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tl/anaconda3/envs/ptch/lib/python3.10/site-packages/lightning/fabric/wrappers.py", line 121, in forward
    output = self._forward_module(*args, **kwargs)
  File "/home/tl/anaconda3/envs/ptch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tl/anaconda3/envs/ptch/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 748, in forward
    return forward_call(*args, **kwargs)
  File "/home/tl/anaconda3/envs/ptch/lib/python3.10/site-packages/lightning/fabric/wrappers.py", line 121, in forward
    output = self._fsdp_wrapped_module(*args, **kwargs)
  File "/home/tl/anaconda3/envs/ptch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    output = self._forward_module(*args, **kwargs)
  File "/home/tl/anaconda3/envs/ptch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tl/anaconda3/envs/ptch/lib/python3.10/site-packages/torchvision/models/resnet.py", line 285, in forward
    return self._forward_impl(x)
  File "/home/tl/anaconda3/envs/ptch/lib/python3.10/site-packages/torchvision/models/resnet.py", line 269, in _forward_impl
    x = self.bn1(x)
  File "/home/tl/anaconda3/envs/ptch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tl/anaconda3/envs/ptch/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 748, in forward
    return forward_call(*args, **kwargs)
    output = self._fsdp_wrapped_module(*args, **kwargs)
  File "/home/tl/anaconda3/envs/ptch/lib/python3.10/site-packages/torch/nn/modules/batchnorm.py", line 171, in forward
  File "/home/tl/anaconda3/envs/ptch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return F.batch_norm(
  File "/home/tl/anaconda3/envs/ptch/lib/python3.10/site-packages/torch/nn/functional.py", line 2450, in batch_norm
    return forward_call(*args, **kwargs)
  File "/home/tl/anaconda3/envs/ptch/lib/python3.10/site-packages/torchvision/models/resnet.py", line 285, in forward
    return torch.batch_norm(
RuntimeError: Expected tensor for argument #2 'weight' to have the same type as tensor for argument #4 'running_mean'; but type torch.cuda.FloatTensor does not equal torch.cuda.HalfTensor (while checking arguments for cudnn_batch_norm)
    return self._forward_impl(x)
  File "/home/tl/anaconda3/envs/ptch/lib/python3.10/site-packages/torchvision/models/resnet.py", line 269, in _forward_impl
    x = self.bn1(x)
  File "/home/tl/anaconda3/envs/ptch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tl/anaconda3/envs/ptch/lib/python3.10/site-packages/torch/nn/modules/batchnorm.py", line 171, in forward
    return F.batch_norm(
  File "/home/tl/anaconda3/envs/ptch/lib/python3.10/site-packages/torch/nn/functional.py", line 2450, in batch_norm
    return torch.batch_norm(
RuntimeError: Expected tensor for argument #2 'weight' to have the same type as tensor for argument #4 'running_mean'; but type torch.cuda.FloatTensor does not equal torch.cuda.HalfTensor (while checking arguments for cudnn_batch_norm)
```

### Environment

<details>
  <summary>Current environment</summary>

```
* CUDA:
        - GPU:
                - Tesla V100-PCIE-16GB-LS
                - Tesla V100-PCIE-16GB-LS
                - Tesla V100-PCIE-16GB-LS
                - Tesla V100-PCIE-16GB-LS
        - available:         True
        - version:           11.7
* Lightning:
        - lightning:         2.1.0
        - lightning-utilities: 0.9.0
        - pytorch-lightning: 2.1.0
        - torch:             2.0.1
        - torchaudio:        2.0.2
        - torcheval:         0.0.7
        - torchmetrics:      1.2.0
        - torchvision:       0.15.2
```

</details>

### More info

https://github.com/rasbt/cvpr2023#experiments-for-cvpr-2023-talk , I reference this link write code.

cc @awaelchli @carmocca

**Comment by awaelchli** [comment]
Hey @DLlearn 
The ResNet you are using there has a `nn.BatchNorm` layer which isn't well supported in FSDP for mixed precision. It's best to avoid wrapping the batch norm layers with FSDP if not necessary. You can find some scarce notes about it in PyTorch's docs: https://pytorch.org/docs/stable/fsdp.html

Is there a particular reason why you chose FSDP for this example? The resnet only has 25 million parameters, DDP would be much more appropriate here in my opinion.

**Comment by DLlearn** [comment]
> Hey @DLlearn The ResNet you are using there has a `nn.BatchNorm` layer which isn't well supported in FSDP for mixed precision. It's best to avoid wrapping the batch norm layers with FSDP if not necessary. You can find some scarce notes about it in PyTorch's docs: https://pytorch.org/docs/stable/fsdp.html
> 
> Is there a particular reason why you chose FSDP for this example? The resnet only has 25 million parameters, DDP would be much more appropriate here in my opinion.

Thank you. I random choice a model  just want to test the training piple line with different distributed startegy by using fabric.

**Comment by awaelchli** [comment]
Alright sounds good. I think I have a fix for this anyway in https://github.com/Lightning-AI/lightning/pull/18818, I just need to test it a bit more for my own understanding.
