### ISSUE TITLE
lightning run cli entry point stopped working after dropping app from top level

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/lightning#18815]
### Bug description

After #18386, the `lightning` cli entry point (e.g. lightning run model ...) exists but no longer works due to missing dependencies.

### What version are you seeing the problem on?

master

### How to reproduce the bug

```python
pip install lightning
lightning run --help
```

### Error messages and logs

```
Traceback (most recent call last):
  File "/Users/adrian/miniconda3/envs/lightning-fresh/bin/lightning", line 5, in <module>
    from lightning.app.cli.lightning_cli import main
  File "/Users/adrian/miniconda3/envs/lightning-fresh/lib/python3.11/site-packages/lightning/app/__init__.py", line 32, in <module>
    from lightning.app.core.app import LightningApp  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adrian/miniconda3/envs/lightning-fresh/lib/python3.11/site-packages/lightning/app/core/__init__.py", line 1, in <module>
    from lightning.app.core.app import LightningApp
  File "/Users/adrian/miniconda3/envs/lightning-fresh/lib/python3.11/site-packages/lightning/app/core/app.py", line 25, in <module>
    from deepdiff import DeepDiff, Delta
ModuleNotFoundError: No module named 'deepdiff'

```

### Environment

Lightning 2.1+ all platforms.

**Comment by shaibagon** [comment]
got it for 2.1.4
