### ISSUE TITLE
Misconfiguration error with self.log() called twice in training step

### ISSUE THREAD

**Issue by NumberChiffre** [Lightning-AI/lightning#18880]
### Bug description

I've just upgraded to using `torch==2.1.0` from `torch==2.0.1` and have been using `lightning==2.1.0` for the past week. I've just noticed a problem when I use `torch.compile` on the `LightningModule`. This error does not appear if I disable `torch.compile`:

```python
def training_step(
    self,
    batch: Tuple[float, np.ndarray, List[torch.Tensor]],
    batch_idx: int,
) -> torch.Tensor:
    id, _, (x, y, _) = batch
    y_hat = self(x)
    loss, _ = self.training_loss(input=y_hat, target=y, x=x)
    self.log("id", id, sync_dist=True)
    self.log(
        "train_loss",
        loss,
        prog_bar=True,
        sync_dist=True,
    )
    return loss
```

Which throws:
```shell
lightning.fabric.utilities.exceptions.MisconfigurationException: You called `self.log(train_loss, ...)` twice in `training_step` with different arguments. This is not allowed
```

### What version are you seeing the problem on?

v2.1

### Error messages and logs

```
Traceback (most recent call last):
  File "/home/app_user/app/src/utils/utils.py", line 71, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/home/app_user/app/src/pipelines/training/train.py", line 86, in train
    trainer.fit(
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/trainer/trainer.py", line 545, in fit
    call._call_and_handle_interrupt(
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/trainer/trainer.py", line 581, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/trainer/trainer.py", line 990, in _run
    results = self._run_stage()
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/trainer/trainer.py", line 1036, in _run_stage
    self.fit_loop.run()
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/loops/fit_loop.py", line 202, in run
    self.advance()
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/loops/fit_loop.py", line 359, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/loops/training_epoch_loop.py", line 136, in run
    self.advance(data_fetcher)
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/loops/training_epoch_loop.py", line 240, in advance
    batch_output = self.automatic_optimization.run(trainer.optimizers[0], batch_idx, kwargs)
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/loops/optimization/automatic.py", line 187, in run
    self._optimizer_step(batch_idx, closure)
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/loops/optimization/automatic.py", line 265, in _optimizer_step
    call._call_lightning_module_hook(
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/trainer/call.py", line 157, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/core/module.py", line 1282, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/core/optimizer.py", line 151, in step
    step_output = self._strategy.optimizer_step(self._optimizer, closure, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/strategies/strategy.py", line 230, in optimizer_step
    return self.precision_plugin.optimizer_step(optimizer, model=model, closure=closure, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/plugins/precision/precision_plugin.py", line 117, in optimizer_step
    return optimizer.step(closure=closure, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/optim/optimizer.py", line 76, in _use_grad
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/optim/adamw.py", line 161, in step
    loss = closure()
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/plugins/precision/precision_plugin.py", line 104, in _wrap_closure
    closure_result = closure()
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/loops/optimization/automatic.py", line 140, in __call__
    self._result = self.closure(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/loops/optimization/automatic.py", line 126, in closure
    step_output = self._step_fn()
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/loops/optimization/automatic.py", line 315, in _training_step
    training_step_output = call._call_strategy_hook(trainer, "training_step", *kwargs.values())
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/trainer/call.py", line 309, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/strategies/strategy.py", line 382, in training_step
    return self.lightning_module.training_step(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/eval_frame.py", line 328, in _fn
    return fn(*args, **kwargs)
  File "/home/app_user/app/src/models/lightningmodules/default.py", line 148, in training_step
    y_hat = self(x)
  File "/home/app_user/app/src/models/lightningmodules/default.py", line 149, in <resume in training_step>
    loss, _ = self.training_loss(input=y_hat, target=y, x=x)
  File "/home/app_user/app/src/models/lightningmodules/default.py", line 151, in <resume in training_step>
    self.log(
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/core/module.py", line 412, in log
    apply_to_collection(value, dict, self.__check_not_nested, name)
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/core/module.py", line 413, in <resume in log>
    apply_to_collection(
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/core/module.py", line 483, in <resume in log>
    and is_param_in_hook_signature(self.training_step, "dataloader_iter", explicit=True)
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/core/module.py", line 500, in <resume in log>
    results.log(
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/trainer/connectors/logger_connector/result.py", line 390, in log
    meta.sync = _Sync(_should=sync_dist, fn=sync_dist_fn, _group=sync_dist_group, rank_zero_only=rank_zero_only)
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/trainer/connectors/logger_connector/result.py", line 398, in <resume in log>
    raise MisconfigurationException(
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/trainer/connectors/logger_connector/result.py", line 398, in <resume in log>
    raise MisconfigurationException(
lightning.fabric.utilities.exceptions.MisconfigurationException: You called `self.log(train_loss, ...)` twice in `training_step` with different arguments. This is not allowed
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow): LightningModule
#- PyTorch Lightning Version (e.g., 1.5.0): 2.1.0
#- Lightning App Version (e.g., 0.5.2): 2.1.0
#- PyTorch Version (e.g., 2.0): 2.1.0
#- Python version (e.g., 3.9): 3.10.12
#- OS (e.g., Linux): Linux
#- CUDA/cuDNN version: 12.2
#- GPU models and configuration: Nvidia GeForce GTX 1660
#- How you installed Lightning(`conda`, `pip`, source): `poetry` within `Dockerfile`
#- Running environment of LightningApp (e.g. local, cloud): local



```

</details>

cc @carmocca

**Comment by haydn-jones** [comment]
l'm also encountering this issue on 2.0.9, 2.1.0, and master with torch 2.1.0.

**Comment by awaelchli** [comment]
See the response here for a workaround: #18835

**Comment by carmocca** [comment]
Closing as a duplicate

**Comment by carmocca** [comment]
Nothing soon: https://github.com/Lightning-AI/lightning/issues/18835#issuecomment-1786343481
