### ISSUE TITLE
Lightning CLI optimizer from command line for subset of model parameters

### ISSUE THREAD

**Issue by nilsleh** [Lightning-AI/lightning#19032]
### Description & Motivation

I was using hydra to configure my LightningModule, to specifically have control over the optimizer choice. Additionally, there would be a step to only use a subset of all model.parameters() for the optimizer.

I added a notebook what the optimizer setup in my lightning module looks like in a simplified version [here](https://colab.research.google.com/drive/1eGfJWGNDZE-ijGZKHICexJUIkJm9QXPB?usp=sharing).

However, when using the optimizer CLI argument, I understand that [here](https://github.com/Lightning-AI/lightning/blob/4789905880fa11b96e761e321a4ad97c40d007fd/src/lightning/pytorch/cli.py#L651) that procedure would be completely ignored and the specified optimizer is instantiated with *all* `self.model` parameters, and I don't have control over the subset anymore. 

### Pitch

Only optimizing a subset of your parameters is something that is commonly done in finetuning for example, but you loose control over that when you use LightningCLI since it just pulls in all available parameters in the LightningModule  as far as I understand. LightningCLI is great for reproducability and scaling experiments so I was hoping that this can be done, or that there is another configuration workaround. I would expect that someone would run into similar issues when trying to cli configure GAN training like shown in the [docs](https://lightning.ai/docs/pytorch/stable/common/lightning_module.html#configure-optimizers)

### Alternatives

Use a configuration scheme like hydra, which does not completely ignore the `configure_optimizer()` setup.

### Additional context

Edit:
In another issue I came across [this](https://lightning.ai/docs/pytorch/stable/cli/lightning_cli_advanced_3.html#multiple-optimizers-and-schedulers) which I was not aware of. The `auto_configure_optimizers` argument is missing from the parameters in the documentation.

cc @borda @carmocca @mauvilsa

**Comment by nilsleh** [comment]
I have the following `example.py`, where I am trying to do the same as the [docs exampe](https://lightning.ai/docs/pytorch/stable/cli/lightning_cli_advanced_3.html#multiple-optimizers-and-schedulers) but with a config file:

```python
from lightning import LightningModule, LightningDataModule
from lightning.pytorch.cli import LightningCLI, ArgsType
from lightning.pytorch.cli import OptimizerCallable

import os
import torch
from torch.utils.data import Dataset, DataLoader


from lightning.pytorch.cli import OptimizerCallable, LightningCLI

class RandomDataset(Dataset):
    def __init__(self, size=5, num_samples=10):
        self.len = num_samples
        self.data = torch.randn(num_samples, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len
    
class RandomDataModule(LightningDataModule):
    def __init__(self, size=5, num_samples=10, batch_size=2):
        super().__init__()
        self.size = size
        self.num_samples = num_samples
        self.batch_size = batch_size

    def setup(self, stage=None):
        self.train_dataset = RandomDataset(self.size, self.num_samples)
        self.val_dataset = RandomDataset(self.size, self.num_samples)
        self.test_dataset = RandomDataset(self.size, self.num_samples)

    def train_dataloader(self):
        return DataLoader(self.train_dataset, batch_size=self.batch_size)

    def val_dataloader(self):
        return DataLoader(self.val_dataset, batch_size=self.batch_size)

    def test_dataloader(self):
        return DataLoader(self.test_dataset, batch_size=self.batch_size)

class BoringModel(LightningModule):
    def __init__(self, optimizer: OptimizerCallable = torch.optim.Adam):
        super().__init__()

        self.model = torch.nn.Sequential(
            torch.nn.Linear(32, 32),
            torch.nn.Linear(32, 2)
        )
        self.optimizer = optimizer

    def forward(self, x):
        return self.model(x)

    def training_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("train_loss", loss)
        return {"loss": loss}

    def validation_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("valid_loss", loss)

    def test_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("test_loss", loss)

    def exclude_some_params(self):
        return self.model[0].parameters()

    def configure_optimizers(self):
        return self.optimizer(self.exclude_some_params())


def cli_main(args: ArgsType = None):
    LightningCLI(args=args, auto_configure_optimizers=False)

if __name__ == "__main__":
    cli_main(["fit", "--config", "test_config.yaml"])
```

And this `test_config.yaml` file:
```yaml
trainer: # pytorch lightning trainer arguments
  max_epochs: 2

model: # model input to trainer
  class_path: example.BoringModel
  init_args:
    optimizer:
      class_path: torch.optim.Adam
      init_args:
        lr: 0.003

data: # datamodule arguments
  class_path: example.RandomDataModule
```

However, running `example.py` yields:
```
Traceback (most recent call last):
  File "/home/testEnv/lib/python3.9/site-packages/jsonargparse/core.py", line 1043, in check_required
    val = cfg[reqkey]
  File "/home/testEnv/lib/python3.9/site-packages/jsonargparse/namespace.py", line 198, in __getitem__
    leaf_key, parent_ns, _ = self._parse_required_key(key)
  File "/home/testEnv/lib/python3.9/site-packages/jsonargparse/namespace.py", line 159, in _parse_required_key
    raise KeyError(f'Key "{key}" not found in namespace.')
KeyError: 'Key "params" not found in namespace.'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/testEnv/lib/python3.9/site-packages/jsonargparse/core.py", line 1082, in check_config
    check_required(cfg, self)
  File "/home/testEnv/lib/python3.9/site-packages/jsonargparse/core.py", line 1047, in check_required
    raise TypeError(f'Key "{prefix}{reqkey}" is required but not included in config object or its value is None.') from ex
TypeError: Key "params" is required but not included in config object or its value is None.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/test/example.py", line 81, in <module>
    cli_main(["fit", "--config", "test_config.yaml"])
  File "/home/test/example.py", line 78, in cli_main
    LightningCLI(args=args)
  File "/home/testEnv/lib/python3.9/site-packages/lightning/pytorch/cli.py", line 359, in __init__
    self._run_subcommand(self.subcommand)
  File "/home/testEnv/lib/python3.9/site-packages/lightning/pytorch/cli.py", line 650, in _run_subcommand
    fn(**fn_kwargs)
  File "/home/testEnv/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 532, in fit
    call._call_and_handle_interrupt(
  File "/home/testEnv/lib/python3.9/site-packages/lightning/pytorch/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/testEnv/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 571, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/testEnv/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 941, in _run
    call._call_setup_hook(self)  # allow user to setup lightning_module in accelerator environment
  File "/home/testEnv/lib/python3.9/site-packages/lightning/pytorch/trainer/call.py", line 86, in _call_setup_hook
    _call_callback_hooks(trainer, "setup", stage=fn)
  File "/home/testEnv/lib/python3.9/site-packages/lightning/pytorch/trainer/call.py", line 195, in _call_callback_hooks
    fn(trainer, trainer.lightning_module, *args, **kwargs)
  File "/home/testEnv/lib/python3.9/site-packages/lightning/pytorch/cli.py", line 260, in setup
    self.parser.save(
  File "/home/testEnv/lib/python3.9/site-packages/jsonargparse/deprecated.py", line 150, in patched_save
    return self._unpatched_save(cfg, *args, multifile=multifile, **kwargs)
  File "/home/testEnv/lib/python3.9/site-packages/jsonargparse/core.py", line 831, in save
    f.write(self.dump(cfg, **dump_kwargs))  # type: ignore
  File "/home/testEnv/lib/python3.9/site-packages/jsonargparse/deprecated.py", line 141, in patched_dump
    return self._unpatched_dump(cfg, *args, **kwargs)
  File "/home/testEnv/lib/python3.9/site-packages/jsonargparse/core.py", line 723, in dump
    self._dump_cleanup_actions(cfg, self._actions, dump_kwargs)
  File "/home/testEnv/lib/python3.9/site-packages/jsonargparse/core.py", line 753, in _dump_cleanup_actions
    value = action.serialize(value, dump_kwargs=dump_kwargs)
  File "/home/testEnv/lib/python3.9/site-packages/jsonargparse/typehints.py", line 382, in serialize
    return adapt_typehints(value, self._typehint, serialize=True, sub_add_kwargs=sub_add_kwargs)
  File "/home/testEnv/lib/python3.9/site-packages/jsonargparse/typehints.py", line 766, in adapt_typehints
    val = adapt_class_type(val, serialize, instantiate_classes, sub_add_kwargs, prev_val=prev_val)
  File "/home/testEnv/lib/python3.9/site-packages/jsonargparse/typehints.py", line 994, in adapt_class_type
    value['init_args'] = load_value(parser.dump(init_args, **dump_kwargs.get()))
  File "/home/testEnv/lib/python3.9/site-packages/jsonargparse/deprecated.py", line 141, in patched_dump
    return self._unpatched_dump(cfg, *args, **kwargs)
  File "/home/testEnv/lib/python3.9/site-packages/jsonargparse/core.py", line 723, in dump
    self._dump_cleanup_actions(cfg, self._actions, dump_kwargs)
  File "/home/testEnv/lib/python3.9/site-packages/jsonargparse/core.py", line 753, in _dump_cleanup_actions
    value = action.serialize(value, dump_kwargs=dump_kwargs)
  File "/home/testEnv/lib/python3.9/site-packages/jsonargparse/typehints.py", line 382, in serialize
    return adapt_typehints(value, self._typehint, serialize=True, sub_add_kwargs=sub_add_kwargs)
  File "/home/testEnv/lib/python3.9/site-packages/jsonargparse/typehints.py", line 710, in adapt_typehints
    val = adapt_class_type(val, True, False, sub_add_kwargs)
  File "/home/testEnv/lib/python3.9/site-packages/jsonargparse/typehints.py", line 994, in adapt_class_type
    value['init_args'] = load_value(parser.dump(init_args, **dump_kwargs.get()))
  File "/home/testEnv/lib/python3.9/site-packages/jsonargparse/deprecated.py", line 141, in patched_dump
    return self._unpatched_dump(cfg, *args, **kwargs)
  File "/home/testEnv/lib/python3.9/site-packages/jsonargparse/core.py", line 720, in dump
    self.check_config(cfg)
  File "/home/testEnv/lib/python3.9/site-packages/jsonargparse/core.py", line 1090, in check_config
    raise type(ex)(message) from ex
TypeError: Configuration check failed :: Key "params" is required but not included in config object or its value is None.
```
But I cannot add the parameters in the config file. Could you point out what I am configuring wrong?

**Comment by mauvilsa** [comment]
I haven't looked in depth, but I would say that the code and config look good. `params` should not be given by the CLI user since this is provided in `return self.optimizer(self.exclude_some_params())`.

I can have a deeper look maybe tomorrow. However, from the stack trace it is clear that you are using an old version of `jsonargparse`. Is there any particular reason for this? Otherwise I would advice that you install the latest version (4.27.0) and try again.

**Comment by nilsleh** [comment]
Updating jsonargparse to `4.27.0` actually fixes the error. Not sure why I had an older version. Thank you for the quick reply.
