### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'drop_last'

### ISSUE THREAD

**Issue by liziru** [Lightning-AI/lightning#19048]
### Bug description

I am training a gan model, but got the following error message, no related issues found in github:
### Error messages and logs
```
Traceback (most recent call last):
  File "/home/lee/Desktop/workspace2/project/tts/RVC/c/modules/train11.py", line 349, in <module>
    main(conf)
  File "/home/lee/Desktop/workspace2/project/tts/RVC/c/modules/train11.py", line 306, in main
    trainer.fit(system)
  File "/home/lee/Documents/software/anaconda3/envs/rvc-webui/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 768, in fit
    self._call_and_handle_interrupt(
  File "/home/lee/Documents/software/anaconda3/envs/rvc-webui/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 719, in _call_and_handle_interrupt
    return self.strategy.launcher.launch(trainer_fn, *args, trainer=self, **kwargs)
  File "/home/lee/Documents/software/anaconda3/envs/rvc-webui/lib/python3.9/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 93, in launch
    return function(*args, **kwargs)
  File "/home/lee/Documents/software/anaconda3/envs/rvc-webui/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 809, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/lee/Documents/software/anaconda3/envs/rvc-webui/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1234, in _run
    results = self._run_stage()
  File "/home/lee/Documents/software/anaconda3/envs/rvc-webui/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1321, in _run_stage
    return self._run_train()
  File "/home/lee/Documents/software/anaconda3/envs/rvc-webui/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1351, in _run_train
    self.fit_loop.run()
  File "/home/lee/Documents/software/anaconda3/envs/rvc-webui/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 199, in run
    self.on_run_start(*args, **kwargs)
  File "/home/lee/Documents/software/anaconda3/envs/rvc-webui/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py", line 208, in on_run_start
    self.trainer.reset_train_val_dataloaders(self.trainer.lightning_module)
  File "/home/lee/Documents/software/anaconda3/envs/rvc-webui/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1993, in reset_train_val_dataloaders
    self.reset_train_dataloader(model=model)
  File "/home/lee/Documents/software/anaconda3/envs/rvc-webui/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1860, in reset_train_dataloader
    self.train_dataloader = apply_to_collection(
  File "/home/lee/Documents/software/anaconda3/envs/rvc-webui/lib/python3.9/site-packages/pytorch_lightning/utilities/apply_func.py", line 99, in apply_to_collection
    return function(data, *args, **kwargs)
  File "/home/lee/Documents/software/anaconda3/envs/rvc-webui/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 300, in _prepare_dataloader
    dataloader = _update_dataloader(dataloader, sampler, mode=mode)
  File "/home/lee/Documents/software/anaconda3/envs/rvc-webui/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py", line 176, in _update_dataloader
    dl_kwargs = _get_dataloader_init_kwargs(dataloader, sampler, mode=mode)
  File "/home/lee/Documents/software/anaconda3/envs/rvc-webui/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py", line 230, in _get_dataloader_init_kwargs
    dl_kwargs.update(_dataloader_init_kwargs_resolve_sampler(dataloader, sampler, mode=mode))
  File "/home/lee/Documents/software/anaconda3/envs/rvc-webui/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py", line 286, in _dataloader_init_kwargs_resolve_sampler
    batch_sampler = type(batch_sampler)(
TypeError: __init__() got an unexpected keyword argument 'drop_last'

Process finished with exit code 1

```

### What version are you seeing the problem on?

v2.1

### How to reproduce the bug

run 'train.py'

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0): 1.6.3-2.1.0
#- Lightning App Version (e.g., 0.5.2): 
#- PyTorch Version (e.g., 2.0): 1.12.0+cu116
#- Python version (e.g., 3.9): 3.9.8
#- OS (e.g., Linux): ubuntu20.04
#- CUDA/cuDNN version: cu116
#- GPU models and configuration:1080ti
#- How you installed Lightning(`conda`, `pip`, source): pip
#- Running environment of LightningApp (e.g. local, cloud): local
```

Looking forward to the reply.

cc @justusschock @awaelchli

**Comment by awaelchli** [comment]
@liziru can you share the code for your batch sampler?

**Comment by awaelchli** [comment]
@liziru Looking at the error trace, it doesn't look like you are using Lightning 2.1 as reported. This must be pytorch-lightning 1.6.0 or older I think. We don't support that version anymore, so I suggest to upgrade because I'm pretty sure your issue is fixed.

**Comment by awaelchli** [comment]
Please let me know if you still see any trouble after upgrading. If you need to stay on that version of Lightning for whatever reason, then a workaround could be to subclass your batch sampler and add the missing drop_last argument to the `__init__` definition.

**Comment by liziru** [comment]
> Please let me know if you still see any trouble after upgrading. If you need to stay on that version of Lightning for whatever reason, then a workaround could be to subclass your batch sampler and add the missing drop_last argument to the `__init__` definition

Thanks for your reply. As you said, It will lead to a new error when I add a new batch sampler. I am sure that 'pytorch-lightning' version is 2.1.0 and pytorch is 2.1.0+cu118. This 'drop_last' error disappeared when adding the missing drop_last argument to the `__init__` definition, but I got the following new error: 
`Traceback (most recent call last):
  File "/home/lee/Desktop/workspace2/project/tts/RVC/c/training/train.py", line 308, in <module>
    main(conf, exp_dir, training_dir, bool(args.use_pretrain))
  File "/home/lee/Desktop/workspace2/project/tts/RVC/c/training/train.py", line 230, in main
    trainer.fit(system)
  File "/home/lee/Documents/software/anaconda3/envs/rvc-webuibkp/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 545, in fit
    call._call_and_handle_interrupt(
  File "/home/lee/Documents/software/anaconda3/envs/rvc-webuibkp/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/home/lee/Documents/software/anaconda3/envs/rvc-webuibkp/lib/python3.9/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 102, in launch
    return function(*args, **kwargs)
  File "/home/lee/Documents/software/anaconda3/envs/rvc-webuibkp/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 581, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/lee/Documents/software/anaconda3/envs/rvc-webuibkp/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 990, in _run
    results = self._run_stage()
  File "/home/lee/Documents/software/anaconda3/envs/rvc-webuibkp/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1036, in _run_stage
    self.fit_loop.run()
  File "/home/lee/Documents/software/anaconda3/envs/rvc-webuibkp/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py", line 194, in run
    self.setup_data()
  File "/home/lee/Documents/software/anaconda3/envs/rvc-webuibkp/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py", line 238, in setup_data
    dl = _process_dataloader(trainer, trainer_fn, stage, dl)
  File "/home/lee/Documents/software/anaconda3/envs/rvc-webuibkp/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 501, in _process_dataloader
    dataloader = trainer._data_connector._prepare_dataloader(dataloader, shuffle=is_shuffled, mode=stage)
  File "/home/lee/Documents/software/anaconda3/envs/rvc-webuibkp/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 207, in _prepare_dataloader
    return _update_dataloader(dataloader, sampler, mode=mode)
  File "/home/lee/Documents/software/anaconda3/envs/rvc-webuibkp/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py", line 133, in _update_dataloader
    dl_args, dl_kwargs = _get_dataloader_init_args_and_kwargs(dataloader, sampler, mode)
  File "/home/lee/Documents/software/anaconda3/envs/rvc-webuibkp/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py", line 192, in _get_dataloader_init_args_and_kwargs
    dl_kwargs.update(_dataloader_init_kwargs_resolve_sampler(dataloader, sampler, mode))
  File "/home/lee/Documents/software/anaconda3/envs/rvc-webuibkp/lib/python3.9/site-packages/pytorch_lightning/utilities/data.py", line 282, in _dataloader_init_kwargs_resolve_sampler
    batch_sampler = batch_sampler_cls(
TypeError: __init__() missing 1 required positional argument: 'boundaries'

Process finished with exit code 1
`
**Code:** 
`
class DistributedBucketSampler(torch.utils.data.distributed.DistributedSampler):
    """
    Maintain similar input lengths in a batch.
    Length groups are specified by boundaries.
    Ex) boundaries = [b1, b2, b3] -> any batch is included either {x | b1 < length(x) <=b2} or {x | b2 < length(x) <= b3}.

    It removes samples which are not included in the boundaries.
    Ex) boundaries = [b1, b2, b3] -> any x s.t. length(x) <= b1 or length(x) > b3 are discarded.
    """

    def __init__(
            self,
            dataset,
            batch_size,
            boundaries,
            num_replicas=None,
            rank=None,
            shuffle=True,
            drop_last=False,
            **kwargs
    ):
        super().__init__(dataset, num_replicas=num_replicas, rank=rank, shuffle=shuffle, drop_last=drop_last)

        self.lengths = dataset.lengths
        self.batch_size = batch_size
        self.boundaries = boundaries

        self.buckets, self.num_samples_per_bucket = self._create_buckets()
        self.total_size = sum(self.num_samples_per_bucket)
        self.num_samples = self.total_size // self.num_replicas

    def _create_buckets(self):
        buckets = [[] for _ in range(len(self.boundaries) - 1)]
        for i in range(len(self.lengths)):
            length = self.lengths[i]
            idx_bucket = self._bisect(length)
            if idx_bucket != -1:
                buckets[idx_bucket].append(i)

        for i in range(len(buckets) - 1, -1, -1):  #
            if len(buckets[i]) == 0:
                buckets.pop(i)
                self.boundaries.pop(i + 1)

        num_samples_per_bucket = []
        for i in range(len(buckets)):
            len_bucket = len(buckets[i])
            total_batch_size = self.num_replicas * self.batch_size
            rem = (
                          total_batch_size - (len_bucket % total_batch_size)
                  ) % total_batch_size
            num_samples_per_bucket.append(len_bucket + rem)
        return buckets, num_samples_per_bucket

    def __iter__(self):
        # deterministically shuffle based on epoch
        g = torch.Generator()
        g.manual_seed(self.epoch)
        print(33)

        indices = []
        if self.shuffle:
            for bucket in self.buckets:
                indices.append(torch.randperm(len(bucket), generator=g).tolist())
        else:
            for bucket in self.buckets:
                indices.append(list(range(len(bucket))))

        batches = []
        for i in range(len(self.buckets)):
            bucket = self.buckets[i]
            len_bucket = len(bucket)
            ids_bucket = indices[i]
            num_samples_bucket = self.num_samples_per_bucket[i]

            # add extra samples to make it evenly divisible
            rem = num_samples_bucket - len_bucket
            ids_bucket = (
                    ids_bucket
                    + ids_bucket * (rem // len_bucket)
                    + ids_bucket[: (rem % len_bucket)]
            )

            # subsample
            ids_bucket = ids_bucket[self.rank:: self.num_replicas]

            # batching
            for j in range(len(ids_bucket) // self.batch_size):
                batch = [
                    bucket[idx]
                    for idx in ids_bucket[
                               j * self.batch_size: (j + 1) * self.batch_size
                               ]
                ]
                batches.append(batch)

        if self.shuffle:
            batch_ids = torch.randperm(len(batches), generator=g).tolist()
            batches = [batches[i] for i in batch_ids]
        self.batches = batches

        assert len(self.batches) * self.batch_size == self.num_samples
        return iter(self.batches)

    def _bisect(self, x, lo=0, hi=None):
        if hi is None:
            hi = len(self.boundaries) - 1

        if hi > lo:
            mid = (hi + lo) // 2
            if self.boundaries[mid] < x and x <= self.boundaries[mid + 1]:
                return mid
            elif x <= self.boundaries[mid]:
                return self._bisect(x, lo, mid)
            else:
                return self._bisect(x, mid + 1, hi)
        else:
            return -1

    def __len__(self):
        return self.num_samples // self.batch_size
`
Looking forward to your reply.

**Comment by dalision** [comment]
@leospark  hi, I meet the same problem. Do you solved it?

**Comment by deependujha** [comment]
Hi @dalision, could you please share a minimal reproducible example on [Lightning Studio](https://lightning.ai/)?
It’ll help us reproduce and debug the issue more quickly.

Thanks,
Deependu
