### ISSUE TITLE
DDP spawn no longer works in Jupyter environment

### ISSUE THREAD

**Issue by Borda** [Lightning-AI/lightning#7550]
## 🐛 Bug

Running multi-GPU training does not update training progress bar, used in Grid Jupyterlab

## Please reproduce using the BoringModel

https://github.com/Borda/kaggle_plant-pathology/blob/main/notebooks/Plant-Pathology-with-Lightning.ipynb

### To Reproduce

just change 
```
    gpus=2
    accelerator="ddp_spawn"
    precision=16,
    accumulate_grad_batches=8,
    val_check_interval=0.25,
    progress_bar_refresh_rate=1,
    weights_summary='top',
```
when I check GPU utilization it is running correctly

### Expected behaviour

a properly updated progress bar

### Environment

**Note**: `Bugs with code` are solved faster ! `Colab Notebook` should be made `public` !

cc @tchaton @rohitgr7 @akihironitta @awaelchli

**Comment by tchaton** [comment]
Hey @Borda. I think this one is a `P0` as it is a very common usage.

**Comment by Borda** [comment]
@awaelchli just testing with v1.3.1 and seems like the training does not start at all :/

**Comment by awaelchli** [comment]
I did a quick test on Grid with this snippet:

```python
import torch.multiprocessing as mp


def foo(process_idx):
    print(process_idx)


if __name__ == "__main__":
    mp.spawn(foo, nprocs=2)  # should print 0 1
```

It crashes in Jupyter environment and works fine as a regular python program. 

```
---------------------------------------------------------------------------
ProcessExitedException                    Traceback (most recent call last)
<ipython-input-20-53d29309dc61> in <module>
      7 
      8 if __name__ == "__main__":
----> 9     mp.spawn(foo, nprocs=2)  # should print 0 1

~/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py in spawn(fn, args, nprocs, join, daemon, start_method)
    228                ' torch.multiprocessing.start_process(...)' % start_method)
    229         warnings.warn(msg)
--> 230     return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')

~/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py in start_processes(fn, args, nprocs, join, daemon, start_method)
    186 
    187     # Loop on join until it returns True or raises an exception.
--> 188     while not context.join():
    189         pass
    190 

~/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py in join(self, timeout)
    142                     error_index=error_index,
    143                     error_pid=failed_process.pid,
--> 144                     exit_code=exitcode
    145                 )
    146 

ProcessExitedException: process 1 terminated with exit code 1
```

So if this does not work in notebooks, then Lightning will also fail like this. Have you seen the same error?

**Comment by awaelchli** [comment]
I may have found something. This works in a Jupyter notebook

```python

import torch.multiprocessing as mp
import torch

def foo(process_idx):
    torch.rand(2, 2).cuda()
    print(process_idx)


if __name__ == "__main__":
    mp.start_processes(foo, nprocs=2, start_method="fork")  # should print 0 1
```

came to this idea when reading the PyTorch source code and reading this [remark](https://github.com/pytorch/pytorch/blob/db11619901e1bd941042af4c49c6e9da7b0d206d/torch/multiprocessing/spawn.py#L160): 

```
# mp.start_processes handles both start_method='spawn' and 'fork'. It's supposed to be a
# more generalized API than mp.spawn. Currently we only document mp.spawn as it's the
# CUDA compatible start_method. However, in environments like Ipython notebooks, 'fork'
# works better than 'spawn'. Every helper function we created for mp.spawn is indeed
# general enough, and backends like XLA can reuse them in Colab notebooks as well.
# Currently we only add this API first, we can consider adding it to documentation as
# needed in the future.
```

I will see if I can incorporate this into our spawn plugin and see what happens for cuda

**Comment by awaelchli** [comment]
We are blocked here. 

Summary: 
```python
# A)
# not working
# current usage in Lightning and recommended by PyTorch
torch.multiprocessing.spawn(..., start_method="spawn") 

# B)
# not supported by PyTorch, the start_method arg is being deprecated and has no impact, uses start_method=spawn anyway
torch.multiprocessing.spawn(..., start_method="fork") 

# C)
# works in the simple case that I showed in my comment above
# but incompatible with CUDA context, see the error below:
torch.multiprocessing.start_processes(..., start_method="fork") 
```
```
-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/adrian/anaconda3/envs/pl/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/adrian/repositories/pytorch-lightning/pytorch_lightning/plugins/training_type/ddp_spawn.py", line 195, in new_process
    self.model_to_device()
  File "/home/adrian/repositories/pytorch-lightning/pytorch_lightning/plugins/training_type/ddp_spawn.py", line 335, in model_to_device
    torch.cuda.set_device(self.root_device)
  File "/home/adrian/anaconda3/envs/pl/lib/python3.8/site-packages/torch/cuda/__init__.py", line 264, in set_device
    torch._C._cuda_setDevice(device)
  File "/home/adrian/anaconda3/envs/pl/lib/python3.8/site-packages/torch/cuda/__init__.py", line 162, in _lazy_init
    raise RuntimeError(
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method
```

C) is also used by the TPU spawn plugin, that's why it works in Google Colab.

I don't know what we can do at this point. Need to look into multiprocessing support in pytorch.

**Comment by Borda** [comment]
> I don't know what we can do at this point. Need to look into multiprocessing support in pytorch.

so you say we are in deadlock, A+B does not shoe progress but works, C fails to start for multi-GPU

**Comment by awaelchli** [comment]
Yes, A+B are not compatible with Jupyter and C) is compatible with Jupyter but not when we use cuda.

**Comment by twsl** [comment]
@awaelchli So it's currently not possible to run code on multiple GPUs with Pytorch Lightning inside a Jupyter notebook?

**Comment by awaelchli** [comment]
@twsl It is possible to do so with `accelerator="dp"`, but with "ddp_spawn" (default) it seems not.

**Comment by tchaton** [comment]
Hey @awaelchli,

Any updates there ?

**Comment by awaelchli** [comment]
Still blocked. PyTorch does not support fork anymore and spawn does not work in notebook cells.
